In [334]:
#tao duong dan file
from pathlib import Path
import pandas as pd

In [335]:
data_path=Path("../data/dataset_anonymization.csv")
print(data_path)
print(data_path.exists())

..\data\dataset_anonymization.csv
True

In [336]:
#doc file va luu file duoi ten data
data=pd.read_csv(
    data_path,
    #giup doc dc ki tu tieng vieton dinh hon

    encoding="utf-8"
)

In [337]:
#hien thi 5 dong dau tien cua file
data.head()

,tuoi,loai_cong_viec,trong_so_thong_ke,trinh_do_hoc_van,so_nam_hoc,tinh_trang_hon_nhan,nghe_nghiep,quan_he_gia_dinh,chung_toc,gioi_tinh,loi_nhuan_von,lo_von,gio_lam_moi_tuan,quoc_gia,thu_nhap
0,90,?,77053,Tot_nghiep_THPT,9,Goa,?,Khong_thuoc_gia_dinh,Da_trang,Nu,0,4356,40,Hoa_Ky,<=50K
1,82,Tu_nhan,132870,Tot_nghiep_THPT,9,Goa,Quan_ly_dieu_hanh,Khong_thuoc_gia_dinh,Da_trang,Nu,0,4356,18,Hoa_Ky,<=50K
2,66,?,186061,Hoc_mot_phan_dai_hoc,10,Goa,?,Doc_than,Da_den,Nu,0,4356,40,Hoa_Ky,<=50K
3,54,Tu_nhan,140359,Lop_7_8,4,Da_ly_hon,Van_hanh_may_moc,Doc_than,Da_trang,Nu,0,3900,40,Hoa_Ky,<=50K
4,41,Tu_nhan,264663,Hoc_mot_phan_dai_hoc,10,Ly_than,Chuyen_mon_dac_thu,Con_ruot,Da_trang,Nu,0,3900,40,Hoa_Ky,<=50K

In [338]:
#hien thi so dong so cot cua file
data.shape

(32561, 15)

In [339]:
#Hien thi ten tat ca cac cot
data.columns.tolist()

['tuoi',
 'loai_cong_viec',
 'trong_so_thong_ke',
 'trinh_do_hoc_van',
 'so_nam_hoc',
 'tinh_trang_hon_nhan',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'loi_nhuan_von',
 'lo_von',
 'gio_lam_moi_tuan',
 'quoc_gia',
 'thu_nhap']

In [340]:
#kiem tra kieu du lieu tung cot
data.dtypes

tuoi                    int64
loai_cong_viec         object
trong_so_thong_ke       int64
trinh_do_hoc_van       object
so_nam_hoc              int64
tinh_trang_hon_nhan    object
nghe_nghiep            object
quan_he_gia_dinh       object
chung_toc              object
gioi_tinh              object
loi_nhuan_von           int64
lo_von                  int64
gio_lam_moi_tuan        int64
quoc_gia               object
thu_nhap               object
dtype: object

In [341]:
#xem thong tin tong quan cau data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tuoi                 32561 non-null  int64
 1   loai_cong_viec       32561 non-null  object
 2   trong_so_thong_ke    32561 non-null  int64
 3   trinh_do_hoc_van     32561 non-null  object
 4   so_nam_hoc           32561 non-null  int64
 5   tinh_trang_hon_nhan  32561 non-null  object
 6   nghe_nghiep          32561 non-null  object
 7   quan_he_gia_dinh     32561 non-null  object
 8   chung_toc            32561 non-null  object
 9   gioi_tinh            32561 non-null  object
 10  loi_nhuan_von        32561 non-null  int64
 11  lo_von               32561 non-null  int64
 12  gio_lam_moi_tuan     32561 non-null  int64
 13  quoc_gia             32561 non-null  object
 14  thu_nhap             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

## Kiểm tra xem dấu ? xuất hiện ở nhũng đâu để xử lí

In [342]:
#Chon cac o co kieu du lieu object
object_columns= data.select_dtypes(include="object").columns
print(object_columns)

Index(['loai_cong_viec', 'trinh_do_hoc_van', 'tinh_trang_hon_nhan',
       'nghe_nghiep', 'quan_he_gia_dinh', 'chung_toc', 'gioi_tinh', 'quoc_gia',
       'thu_nhap'],
      dtype='object')

In [343]:
question_mark_counts=(
#lay cac du lieu dang object roi dem tong so ? xuat hien
    data[object_columns]=="?"
).sum()
question_mark_counts

loai_cong_viec         1836
trinh_do_hoc_van          0
tinh_trang_hon_nhan       0
nghe_nghiep            1843
quan_he_gia_dinh          0
chung_toc                 0
gioi_tinh                 0
quoc_gia                583
thu_nhap                  0
dtype: int64

In [344]:
#Hien ra cac cot cos dau ?
question_mark_counts[
    question_mark_counts>0
]

loai_cong_viec    1836
nghe_nghiep       1843
quoc_gia           583
dtype: int64

In [345]:
#Tao ra ban sao de sua khong anh huopng den du lieu goc
data_clean=data.copy()

In [346]:
#Chuyen cac du lieu bi ? thanh dang NA
data_clean=data_clean.replace(
    #Tim cac du lieu dang ? thay bang  NA
    "?",pd.NA
)

In [347]:
#Kiem tra lai
data_clean.isna().sum()

tuoi                      0
loai_cong_viec         1836
trong_so_thong_ke         0
trinh_do_hoc_van          0
so_nam_hoc                0
tinh_trang_hon_nhan       0
nghe_nghiep            1843
quan_he_gia_dinh          0
chung_toc                 0
gioi_tinh                 0
loi_nhuan_von             0
lo_von                    0
gio_lam_moi_tuan          0
quoc_gia                583
thu_nhap                  0
dtype: int64

In [348]:
#Hien thi cac gfia tri bi thieu
missing_counts=data_clean.isna().sum()
missing_counts[missing_counts>0]

loai_cong_viec    1836
nghe_nghiep       1843
quoc_gia           583
dtype: int64

Sau khi chuyen du lieu tu dang ? thanh pd.NA

Từ kết quả ta thấy dữ liệu bị thiếu ở cột Loai_cong_viec, nghe_nghiep, quoc_gia

In [349]:
#Tinh ti le phan tram du lieu con thieu
missing_percent=data_clean.isna().mean()*100
missing_percent[missing_percent>0]

loai_cong_viec    5.638647
nghe_nghiep       5.660146
quoc_gia          1.790486
dtype: float64

In [350]:
#lam tron ti le phan tram
missing_percent = data_clean.isna().mean() * 100
missing_percent = missing_percent[missing_percent > 0]

missing_percent.round(2)

loai_cong_viec    5.64
nghe_nghiep       5.66
quoc_gia          1.79
dtype: float64

Quá trình khảo sát chất lượng dữ liệu phát hiện ba thuộc tính có giá trị khuyết gồm loai_cong_viec, nghe_nghiep và quoc_gia, với tỷ lệ khuyết lần lượt khoảng 5.64%, 5.66% và 1.79%. Các giá trị khuyết ban đầu được biểu diễn bằng ký hiệu ? và được chuyển thành pd.NA để Pandas nhận diện chính xác.

In [351]:
#Kiem tra so dong bi trung
duplicate_cout=data_clean.duplicated().sum()
print("So dong bi trung: ",duplicate_cout)

So dong bi trung:  24

In [352]:
#xem tat ca cac dong bi trung
duplicate_rows=data_clean[
    data_clean.duplicated(keep=False)
]
duplicate_rows.head(20)

,tuoi,loai_cong_viec,trong_so_thong_ke,trinh_do_hoc_van,so_nam_hoc,tinh_trang_hon_nhan,nghe_nghiep,quan_he_gia_dinh,chung_toc,gioi_tinh,loi_nhuan_von,lo_von,gio_lam_moi_tuan,quoc_gia,thu_nhap
6227,90,Tu_nhan,52386,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Dich_vu_khac,Khong_thuoc_gia_dinh,Chau_A_Thai_Binh_Duong,Nam,0,0,35,Hoa_Ky,<=50K
7615,19,Tu_nhan,251579,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Dich_vu_khac,Con_ruot,Da_trang,Nam,0,0,14,Hoa_Ky,<=50K
7978,25,Tu_nhan,308144,Cu_nhan,13,Chua_ket_hon,Tho_thu_cong_sua_chua,Khong_thuoc_gia_dinh,Da_trang,Nam,0,0,40,Mexico,<=50K
8356,21,Tu_nhan,250051,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Chuyen_mon_dac_thu,Con_ruot,Da_trang,Nu,0,0,10,Hoa_Ky,<=50K
8453,25,Tu_nhan,308144,Cu_nhan,13,Chua_ket_hon,Tho_thu_cong_sua_chua,Khong_thuoc_gia_dinh,Da_trang,Nam,0,0,40,Mexico,<=50K
8500,38,Tu_nhan,207202,Tot_nghiep_THPT,9,Ket_hon_dan_su,Van_hanh_may_moc,Chong,Da_trang,Nam,0,0,48,Hoa_Ky,>50K
8645,90,Tu_nhan,52386,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Dich_vu_khac,Khong_thuoc_gia_dinh,Chau_A_Thai_Binh_Duong,Nam,0,0,35,Hoa_Ky,<=50K
9067,27,Tu_nhan,255582,Tot_nghiep_THPT,9,Chua_ket_hon,Van_hanh_may_moc,Khong_thuoc_gia_dinh,Da_trang,Nu,0,0,40,Hoa_Ky,<=50K
9269,20,Tu_nhan,107658,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Ho_tro_ky_thuat,Khong_thuoc_gia_dinh,Da_trang,Nu,0,0,10,Hoa_Ky,<=50K
9305,25,Tu_nhan,195994,Lop_1_4,2,Chua_ket_hon,Giup_viec_gia_dinh,Khong_thuoc_gia_dinh,Da_trang,Nu,0,0,40,Guatemala,<=50K
10307,19,Tu_nhan,138153,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Nhan_vien_van_phong,Con_ruot,Da_trang,Nu,0,0,10,Hoa_Ky,<=50K
10357,49,Tu_kinh_doanh_khong_dang_ky,43479,Hoc_mot_phan_dai_hoc,10,Ket_hon_dan_su,Tho_thu_cong_sua_chua,Chong,Da_trang,Nam,0,0,40,Hoa_Ky,<=50K
11121,49,Tu_nhan,31267,Lop_7_8,4,Ket_hon_dan_su,Tho_thu_cong_sua_chua,Chong,Da_trang,Nam,0,0,40,Hoa_Ky,<=50K
11261,21,Tu_nhan,243368,Mau_giao,1,Chua_ket_hon,Nong_nghiep_danh_bat_ca,Khong_thuoc_gia_dinh,Da_trang,Nam,0,0,50,Mexico,<=50K
11777,28,Tu_nhan,274679,Thac_si,14,Chua_ket_hon,Chuyen_mon_dac_thu,Khong_thuoc_gia_dinh,Da_trang,Nam,0,0,50,Hoa_Ky,<=50K
12202,21,Tu_nhan,250051,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Chuyen_mon_dac_thu,Con_ruot,Da_trang,Nu,0,0,10,Hoa_Ky,<=50K
13260,42,Tu_nhan,204235,Hoc_mot_phan_dai_hoc,10,Ket_hon_dan_su,Chuyen_mon_dac_thu,Chong,Da_trang,Nam,0,0,40,Hoa_Ky,>50K
14346,20,Tu_nhan,107658,Hoc_mot_phan_dai_hoc,10,Chua_ket_hon,Ho_tro_ky_thuat,Khong_thuoc_gia_dinh,Da_trang,Nu,0,0,10,Hoa_Ky,<=50K
14634,46,Tu_nhan,133616,Hoc_mot_phan_dai_hoc,10,Da_ly_hon,Nhan_vien_van_phong,Doc_than,Da_trang,Nu,0,0,40,Hoa_Ky,<=50K
15603,25,Tu_nhan,195994,Lop_1_4,2,Chua_ket_hon,Giup_viec_gia_dinh,Khong_thuoc_gia_dinh,Da_trang,Nu,0,0,40,Guatemala,<=50K

Dataset tồn tại 24 bản ghi được xác định là các lần lặp lại hoàn toàn so với bản ghi trước đó. Tuy nhiên, do dữ liệu không chứa mã định danh cá nhân duy nhất, các bản ghi này chưa được loại bỏ để tránh làm mất các quan sát hợp lệ.

In [353]:
#Dem cac gia tri khac nhau cua tung cot
cardinality=data_clean.nunique()
cardinality

tuoi                      73
loai_cong_viec             8
trong_so_thong_ke      21648
trinh_do_hoc_van          16
so_nam_hoc                16
tinh_trang_hon_nhan        7
nghe_nghiep               14
quan_he_gia_dinh           6
chung_toc                  5
gioi_tinh                  2
loi_nhuan_von            119
lo_von                    92
gio_lam_moi_tuan          94
quoc_gia                  41
thu_nhap                   2
dtype: int64

In [354]:
#sap xep cardinality tu cao xuong thap
cardinality_sort=cardinality.sort_values(
    ascending=False
)
cardinality_sort

trong_so_thong_ke      21648
loi_nhuan_von            119
gio_lam_moi_tuan          94
lo_von                    92
tuoi                      73
quoc_gia                  41
trinh_do_hoc_van          16
so_nam_hoc                16
nghe_nghiep               14
loai_cong_viec             8
tinh_trang_hon_nhan        7
quan_he_gia_dinh           6
chung_toc                  5
gioi_tinh                  2
thu_nhap                   2
dtype: int64

In [355]:
#Tinh ti le
number_of_rows = len(data_clean)

cardinality_percent = (
    data_clean.nunique() / number_of_rows
) * 100

cardinality_percent.sort_values(
    ascending=False
)

trong_so_thong_ke      66.484445
loi_nhuan_von           0.365468
gio_lam_moi_tuan        0.288689
lo_von                  0.282547
tuoi                    0.224195
quoc_gia                0.125918
trinh_do_hoc_van        0.049139
so_nam_hoc              0.049139
nghe_nghiep             0.042996
loai_cong_viec          0.024569
tinh_trang_hon_nhan     0.021498
quan_he_gia_dinh        0.018427
chung_toc               0.015356
gioi_tinh               0.006142
thu_nhap                0.006142
dtype: float64

In [356]:
cardinality_report = pd.DataFrame({
    "so_gia_tri_khac_nhau": data_clean.nunique(),
    "ty_le_cardinality_%": (
        data_clean.nunique() / len(data_clean)
    ) * 100
})

cardinality_report = cardinality_report.sort_values(
    by="ty_le_cardinality_%",
    ascending=False
)

cardinality_report.round(2)

                     so_gia_tri_khac_nhau  ty_le_cardinality_%
trong_so_thong_ke                   21648                66.48
loi_nhuan_von                         119                 0.37
gio_lam_moi_tuan                       94                 0.29
lo_von                                 92                 0.28
tuoi                                   73                 0.22
quoc_gia                               41                 0.13
trinh_do_hoc_van                       16                 0.05
so_nam_hoc                             16                 0.05
nghe_nghiep                            14                 0.04
loai_cong_viec                          8                 0.02
tinh_trang_hon_nhan                     7                 0.02
quan_he_gia_dinh                        6                 0.02
chung_toc                               5                 0.02
gioi_tinh                               2                 0.01
thu_nhap                                2                 0.01

In [357]:
#Dem so luong trong cot trong_so_thong_ke xuat hien bao nhieu lan
frequency=data_clean["trong_so_thong_ke"].value_counts()
frequency.head(10)

trong_so_thong_ke
164190    13
203488    13
123011    13
148995    12
121124    12
113364    12
126675    12
102308    11
188246    11
126569    11
Name: count, dtype: int64

In [358]:
#kiem tra gia tri xuat hien dung mot lan
unique_mask=frequency==1
#Dem so luong gia tri duy nhat
unique_values_count=unique_mask.sum()
print("so gia tri xuat hien 1 lan: ", unique_values_count)

so gia tri xuat hien 1 lan:  15330

In [359]:
#tinh ti le %
unique_rate=(
    unique_mask.sum()/len(data_clean)

)*100

print(
    "Ti le ban ghi co gia tri duy nhat",
    round(unique_rate,2),
    "%"

)

Ti le ban ghi co gia tri duy nhat 47.08 %

32,561 ban ghi co 15,330 ban ghi duy nhat chiem ti le 47.08%

In [360]:
#Dem so lan xuat hien 1 lan
#Tao dictionary de luu ket qua cho tung cot
unique_counts={}
#xet lan luot tung cot trong dataset
for column in data_clean.columns:
#Dem moi gia tri xuat hien bao nhieu lan
    frequency_column=data_clean[column].value_counts(
    dropna=False
)

#Dem so gia tri xuat hien dung 1 lan
    unique_counts[column]=(
    frequency_column==1
).sum()

In [361]:
unique_counts

{'tuoi': np.int64(2),
 'loai_cong_viec': np.int64(0),
 'trong_so_thong_ke': np.int64(15330),
 'trinh_do_hoc_van': np.int64(0),
 'so_nam_hoc': np.int64(0),
 'tinh_trang_hon_nhan': np.int64(0),
 'nghe_nghiep': np.int64(0),
 'quan_he_gia_dinh': np.int64(0),
 'chung_toc': np.int64(0),
 'gioi_tinh': np.int64(0),
 'loi_nhuan_von': np.int64(10),
 'lo_von': np.int64(12),
 'gio_lam_moi_tuan': np.int64(5),
 'quoc_gia': np.int64(1),
 'thu_nhap': np.int64(0)}

In [362]:
#chuyen tu dang dictionary sang dang cot
unique_series=pd.Series(unique_counts)
unique_series

tuoi                       2
loai_cong_viec             0
trong_so_thong_ke      15330
trinh_do_hoc_van           0
so_nam_hoc                 0
tinh_trang_hon_nhan        0
nghe_nghiep                0
quan_he_gia_dinh           0
chung_toc                  0
gioi_tinh                  0
loi_nhuan_von             10
lo_von                    12
gio_lam_moi_tuan           5
quoc_gia                   1
thu_nhap                   0
dtype: int64

In [363]:
#ghep voi gia tri cardinality
#pd.DataFrame tao mot bang moi
unique_report=pd.DataFrame({
    "so_luong_gia_tri_khac_nhau ": data_clean.nunique(),
    "so_gia_tri_xuat_hien_1_lan":unique_series
})
unique_report

                     so_luong_gia_tri_khac_nhau   so_gia_tri_xuat_hien_1_lan
tuoi                                          73                           2
loai_cong_viec                                 8                           0
trong_so_thong_ke                          21648                       15330
trinh_do_hoc_van                              16                           0
so_nam_hoc                                    16                           0
tinh_trang_hon_nhan                            7                           0
nghe_nghiep                                   14                           0
quan_he_gia_dinh                               6                           0
chung_toc                                      5                           0
gioi_tinh                                      2                           0
loi_nhuan_von                                119                          10
lo_von                                        92                          12
gio_lam_moi_tuan                              94                           5
quoc_gia                                      41                           1
thu_nhap                                       2                           0

In [364]:
#them ti le %
unique_report["ti_le_xuat_hien_duy_nhat"]=(
    unique_report["so_gia_tri_xuat_hien_1_lan"]
    /len(data_clean)

)*100
unique_report

,so_luong_gia_tri_khac_nhau,so_gia_tri_xuat_hien_1_lan,ti_le_xuat_hien_duy_nhat
tuoi,73,2,0.006142
loai_cong_viec,8,0,0.000000
trong_so_thong_ke,21648,15330,47.080864
trinh_do_hoc_van,16,0,0.000000
so_nam_hoc,16,0,0.000000
tinh_trang_hon_nhan,7,0,0.000000
nghe_nghiep,14,0,0.000000
quan_he_gia_dinh,6,0,0.000000
chung_toc,5,0,0.000000
gioi_tinh,2,0,0.000000
loi_nhuan_von,119,10,0.030712
lo_von,92,12,0.036854
gio_lam_moi_tuan,94,5,0.015356
quoc_gia,41,1,0.003071
thu_nhap,2,0,0.000000

In [365]:
#sap xep theo ti le duy nhat
unique_report_sorted=unique_report.sort_values(
    by="ti_le_xuat_hien_duy_nhat",
    ascending=False
)
unique_report_sorted.round(2)

,so_luong_gia_tri_khac_nhau,so_gia_tri_xuat_hien_1_lan,ti_le_xuat_hien_duy_nhat
trong_so_thong_ke,21648,15330,47.08
lo_von,92,12,0.04
loi_nhuan_von,119,10,0.03
gio_lam_moi_tuan,94,5,0.02
tuoi,73,2,0.01
quoc_gia,41,1,0.00
loai_cong_viec,8,0,0.00
nghe_nghiep,14,0,0.00
tinh_trang_hon_nhan,7,0,0.00
so_nam_hoc,16,0,0.00
trinh_do_hoc_van,16,0,0.00
gioi_tinh,2,0,0.00
chung_toc,5,0,0.00
quan_he_gia_dinh,6,0,0.00
thu_nhap,2,0,0.00

Danh sách QI thử nghiệm = danh sách những cột mình nghi ngờ rằng khi kết hợp với nhau có thể giúp nhận diện một người.

In [366]:
#Danh sach QI thu nghiem
candidate_qi=[
    "tuoi",
    "loai_cong_viec",
    "trinh_do_hoc_van",
    "tinh_trang_hon_nhan",
    "nghe_nghiep",
    "quan_he_gia_dinh",
    "chung_toc",
    "gioi_tinh",
    "gio_lam_moi_tuan",
    "quoc_gia"
]
candidate_qi

['tuoi',
 'loai_cong_viec',
 'trinh_do_hoc_van',
 'tinh_trang_hon_nhan',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_moi_tuan',
 'quoc_gia']

Không đưa thu nhap vao Qi vì là target của Machine Learning và đồng thời là thuộc tính mà ta muốn bảo vệ khỏi suy luận. Nó không nên dùng để tạo nhóm QI ở bước này.

In [367]:
#Gom cac ban ghi co cung bo gia tri Qi thanh nhom
qi_group_sizes=(
    data_clean
    .groupby(candidate_qi,dropna=False)
    .size()
)
qi_group_sizes

tuoi  loai_cong_viec          trinh_do_hoc_van  tinh_trang_hon_nhan  nghe_nghiep              quan_he_gia_dinh      chung_toc  gioi_tinh  gio_lam_moi_tuan  quoc_gia
17    Chinh_phu_lien_bang     Lop_11            Chua_ket_hon         Nhan_vien_van_phong      Khong_thuoc_gia_dinh  Da_den     Nu         40                Hoa_Ky      1
      Chinh_quyen_bang        Lop_10            Chua_ket_hon         Dich_vu_khac             Con_ruot              Da_trang   Nam        30                Hoa_Ky      1
                                                                     Nong_nghiep_danh_bat_ca  Con_ruot              Da_trang   Nam        40                Hoa_Ky      1
      Chinh_quyen_dia_phuong  Lop_10            Chua_ket_hon         Dich_vu_bao_ve           Con_ruot              Da_trang   Nu         40                Hoa_Ky      1
                                                                     Dich_vu_khac             Con_ruot              Da_trang   Nu         25                Hoa_Ky      1
                                                                                                                                                                       ..
90    NaN                     Lop_1_4           Goa                  NaN                      Khong_thuoc_gia_dinh  Da_den     Nu         40                Hoa_Ky      1
                              Lop_7_8           Ly_than              NaN                      Khong_thuoc_gia_dinh  Da_trang   Nu         15                Hoa_Ky      1
                              Tot_nghiep_THPT   Goa                  NaN                      Khong_thuoc_gia_dinh  Da_trang   Nam        4                 Hoa_Ky      1
                                                                                                                               Nu         40                Hoa_Ky      1
                                                Ket_hon_dan_su       NaN                      Chong                 Da_trang   Nam        40                Hoa_Ky      1
Length: 27515, dtype: int64

Nghĩa là từ 32,561 bản ghi, tổ hợp 10 QI của bạn tạo ra 27,515 nhóm khác nhau.

In [368]:
#Tim k nho nhat de biet muc do te nhat cau dataset hien tai khi xet theo boi QI
k_min=qi_group_sizes.min()
print("k nho nhat: ",k_min)

k nho nhat:  1

Một tổ hợp:
tuổi + loại công việc + học vấn + ... + quốc gia

chỉ xuất hiện ở đúng 1 người/bản ghi.

In [369]:
#Dem so nhom QI co dung 1 ban ghi
unique_qi_groups=(qi_group_sizes==1).sum()
print("so nhom qi co dung mot ban ghi: ",unique_qi_groups)

so nhom qi co dung mot ban ghi:  24802

In [370]:
#Tinh ti le phan tram ban ghi dung mot minh
unique_qi_rate=(
    unique_qi_groups/len(data_clean)

)*100
print("Ti le ban ghi bi co lap: ",
      round(unique_qi_rate,2),"%")

Ti le ban ghi bi co lap:  76.17 %

Với 10 QI có khoảng 76.17% bản ghi có tổ hợp QI chỉ xuất hiện đúng một lần trong dataset.

In [371]:
#Kiem tra QI neu k=5
k_required=5
violation_records=qi_group_sizes[
#Lay cac ban ghi cos so luong nho hon 5
    qi_group_sizes<k_required
].sum()
print("so ban ghi chua dat k=5 la:",violation_records)

so ban ghi chua dat k=5 la: 30633

Nghĩa là trong tổng 32,561 bản ghi, có 30,633 bản ghi đang nằm trong các nhóm QI có kích thước nhỏ hơn 5.

In [372]:
#Tinh ti le phan tram chua datr k=5
violation_rate=(
    violation_records/len(data_clean)
)*100
print("Ty le ban ghi chua dat k=5: ",round(violation_rate,2),"%")

Ty le ban ghi chua dat k=5:  94.08 %

Với tỉ lệ 94.08% vì vậy với 10QI đã chonj chưa đạt 5-anonymity

In [373]:
#Dem so luong nhom theo kich thuoc nhom
qi_group_size_distribution=qi_group_sizes.value_counts().sort_index()
qi_group_size_distribution.head(10)

1     24802
2      1735
3       479
4       231
5       108
6        49
7        33
8        25
9        13
10       10
Name: count, dtype: int64

In [374]:
#tao mot ban sao moi de an danh du lieu
data_anonymized=data_clean.copy()

In [375]:
data_anonymized.shape

(32561, 15)

In [376]:
#Kiem tra do tuoi
age_min=data_anonymized["tuoi"].min()
age_max=data_anonymized["tuoi"].max()
print("tuoi nho nhat: ",age_min)
print("tuoi lon naht: ",age_max)

tuoi nho nhat:  17
tuoi lon naht:  90

In [377]:
#Nhom cac tuoi trong khgoang 10 nam lai
age_start=(data_anonymized["tuoi"]//10)*10
data_anonymized["tuoi_nhom_10"]=(
    age_start.astype(str)
    +"-"
    +(age_start+9).astype(str)
)
data_anonymized[["tuoi","tuoi_nhom_10"]].head(10)

   tuoi tuoi_nhom_10
0    90        90-99
1    82        80-89
2    66        60-69
3    54        50-59
4    41        40-49
5    34        30-39
6    38        30-39
7    74        70-79
8    68        60-69
9    41        40-49

In [378]:
#Tao danh sach QI mới
candidate_qi_age10 = candidate_qi.copy()

candidate_qi_age10[0] = "tuoi_nhom_10"

candidate_qi_age10

['tuoi_nhom_10',
 'loai_cong_viec',
 'trinh_do_hoc_van',
 'tinh_trang_hon_nhan',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_moi_tuan',
 'quoc_gia']

In [379]:
#gom nhon lai sau khi tong quat hoa tuoi
qi_group_sizes_age10=(
    data_anonymized
    .groupby(candidate_qi_age10,dropna=False)
    .size()
)
qi_group_sizes_age10

tuoi_nhom_10  loai_cong_viec       trinh_do_hoc_van      tinh_trang_hon_nhan  nghe_nghiep          quan_he_gia_dinh      chung_toc               gioi_tinh  gio_lam_moi_tuan  quoc_gia
10-19         Chinh_phu_lien_bang  Hoc_mot_phan_dai_hoc  Chua_ket_hon         Ban_hang             Con_ruot              Da_trang                Nu         32                Hoa_Ky         1
                                                                              Boc_xep_don_dep      Con_ruot              Da_trang                Nam        20                Anh            1
                                                                              Nhan_vien_van_phong  Con_ruot              Da_trang                Nu         10                Hoa_Ky         1
                                   Lop_11                Chua_ket_hon         Dich_vu_khac         Con_ruot              Chau_A_Thai_Binh_Duong  Nam        15                Philippines    1
                                                                              Nhan_vien_van_phong  Khong_thuoc_gia_dinh  Da_den                  Nu         40                Hoa_Ky         1
                                                                                                                                                                                            ..
90-99         NaN                  Lop_1_4               Goa                  NaN                  Khong_thuoc_gia_dinh  Da_den                  Nu         40                Hoa_Ky         1
                                   Lop_7_8               Ly_than              NaN                  Khong_thuoc_gia_dinh  Da_trang                Nu         15                Hoa_Ky         1
                                   Tot_nghiep_THPT       Goa                  NaN                  Khong_thuoc_gia_dinh  Da_trang                Nam        4                 Hoa_Ky         1
                                                                                                                                                 Nu         40                Hoa_Ky         1
                                                         Ket_hon_dan_su       NaN                  Chong                 Da_trang                Nam        40                Hoa_Ky         1
Length: 20732, dtype: int64

Số nhóm QI trước: 27,515

Số nhóm QI sau : 20,732

In [380]:
#Tim k min moi
k_min_age_10=qi_group_sizes_age10.min()
print("k nho nhat sau khi gom tuoi ", k_min_age_10)

k nho nhat sau khi gom tuoi  1

In [381]:
# Đếm số nhóm chỉ có 1 bản ghi sau khi gom tuổi
unique_groups_age10 = (
    qi_group_sizes_age10 == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi:",
    unique_groups_age10
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi: 17129

In [382]:
unique_rate_age10 = (
    unique_groups_age10 / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi:",
    round(unique_rate_age10, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi: 52.61 %

In [383]:
k_required = 5

violation_records_age10 = qi_group_sizes_age10[
    qi_group_sizes_age10 < k_required
].sum()

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi:",
    violation_records_age10
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi: 24065

In [384]:
violation_rate_age10 = (
    violation_records_age10 / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi:",
    round(violation_rate_age10, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi: 73.91 %

In [385]:
#Tinh so gio lam it nhat nhieu nhat
hours_min = data_anonymized["gio_lam_moi_tuan"].min()
hours_max = data_anonymized["gio_lam_moi_tuan"].max()

print("Số giờ làm nhỏ nhất:", hours_min)
print("Số giờ làm lớn nhất:", hours_max)

Số giờ làm nhỏ nhất: 1
Số giờ làm lớn nhất: 99

In [386]:
#Chuan hoa so gio lam
hours_start = (
    (data_anonymized["gio_lam_moi_tuan"] - 1) // 10
) * 10 + 1

data_anonymized["gio_lam_nhom_10"] = (
    hours_start.astype(str)
    + "-"
    + (hours_start + 9).astype(str)
)

data_anonymized[
    ["gio_lam_moi_tuan", "gio_lam_nhom_10"]
].head(10)

   gio_lam_moi_tuan gio_lam_nhom_10
0                40           31-40
1                18           11-20
2                40           31-40
3                40           31-40
4                40           31-40
5                45           41-50
6                40           31-40
7                20           11-20
8                40           31-40
9                60           51-60

In [387]:
candidate_qi_age10_hours10 = candidate_qi_age10.copy()

candidate_qi_age10_hours10[
    candidate_qi_age10_hours10.index("gio_lam_moi_tuan")
] = "gio_lam_nhom_10"

candidate_qi_age10_hours10

['tuoi_nhom_10',
 'loai_cong_viec',
 'trinh_do_hoc_van',
 'tinh_trang_hon_nhan',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia']

In [388]:
# Gom nhóm sau khi đã tổng quát hóa tuổi và giờ làm
qi_group_sizes_age10_hours10 = (
    data_anonymized
    .groupby(candidate_qi_age10_hours10, dropna=False)
    .size()
)

qi_group_sizes_age10_hours10

tuoi_nhom_10  loai_cong_viec       trinh_do_hoc_van      tinh_trang_hon_nhan  nghe_nghiep          quan_he_gia_dinh      chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia
10-19         Chinh_phu_lien_bang  Hoc_mot_phan_dai_hoc  Chua_ket_hon         Ban_hang             Con_ruot              Da_trang                Nu         31-40            Hoa_Ky         1
                                                                              Boc_xep_don_dep      Con_ruot              Da_trang                Nam        11-20            Anh            1
                                                                              Nhan_vien_van_phong  Con_ruot              Da_trang                Nu         1-10             Hoa_Ky         1
                                   Lop_11                Chua_ket_hon         Dich_vu_khac         Con_ruot              Chau_A_Thai_Binh_Duong  Nam        11-20            Philippines    1
                                                                              Nhan_vien_van_phong  Khong_thuoc_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky         1
                                                                                                                                                                                           ..
90-99         NaN                  Lop_1_4               Goa                  NaN                  Khong_thuoc_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky         1
                                   Lop_7_8               Ly_than              NaN                  Khong_thuoc_gia_dinh  Da_trang                Nu         11-20            Hoa_Ky         1
                                   Tot_nghiep_THPT       Goa                  NaN                  Khong_thuoc_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky         1
                                                                                                                                                 Nu         31-40            Hoa_Ky         1
                                                         Ket_hon_dan_su       NaN                  Chong                 Da_trang                Nam        31-40            Hoa_Ky         1
Length: 17609, dtype: int64

In [389]:
#Tim k nho nhat
k_min_age10_hours10 = qi_group_sizes_age10_hours10.min()

print(
    "k nhỏ nhất sau khi gom tuổi và giờ làm:",
    k_min_age10_hours10
)

k nhỏ nhất sau khi gom tuổi và giờ làm: 1

In [390]:
unique_groups_age10_hours10 = (
    qi_group_sizes_age10_hours10 == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi và giờ làm:",
    unique_groups_age10_hours10
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi và giờ làm: 13704

In [391]:
unique_rate_age10_hours10 = (
    unique_groups_age10_hours10 / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi và giờ làm:",
    round(unique_rate_age10_hours10, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi và giờ làm: 42.09 %

In [392]:
violation_records_age10_hours10 = qi_group_sizes_age10_hours10[
    qi_group_sizes_age10_hours10 < k_required
].sum()

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi và giờ làm:",
    violation_records_age10_hours10
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi và giờ làm: 20931

In [393]:
violation_rate_age10_hours10 = (
    violation_records_age10_hours10 / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi và giờ làm:",
    round(violation_rate_age10_hours10, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi và giờ làm: 64.28 %

Gom trinh do hoc van

In [394]:
education_counts = data_anonymized[
    "trinh_do_hoc_van"
].value_counts(dropna=False)

education_counts

trinh_do_hoc_van
Tot_nghiep_THPT         10501
Hoc_mot_phan_dai_hoc     7291
Cu_nhan                  5355
Thac_si                  1723
Cao_dang_nghe            1382
Lop_11                   1175
Cao_dang_hoc_thuat       1067
Lop_10                    933
Lop_7_8                   646
Truong_chuyen_nghiep      576
Lop_9                     514
Lop_12                    433
Tien_si                   413
Lop_5_6                   333
Lop_1_4                   168
Mau_giao                   51
Name: count, dtype: int64

In [395]:
education_order = (
    data_anonymized[
        ["trinh_do_hoc_van", "so_nam_hoc"]
    ]
    .drop_duplicates()
    .sort_values("so_nam_hoc")
)

education_order

          trinh_do_hoc_van  so_nam_hoc
1106              Mau_giao           1
26                 Lop_1_4           2
27                 Lop_5_6           3
3                  Lop_7_8           4
197                  Lop_9           5
6                   Lop_10           6
16                  Lop_11           7
178                 Lop_12           8
0          Tot_nghiep_THPT           9
2     Hoc_mot_phan_dai_hoc          10
25           Cao_dang_nghe          11
18      Cao_dang_hoc_thuat          12
12                 Cu_nhan          13
13                 Thac_si          14
11    Truong_chuyen_nghiep          15
7                  Tien_si          16

In [396]:
def generalize_education(education_num):
    if education_num <= 8:
        return "Chua_tot_nghiep_THPT"
    elif education_num == 9:
        return "Tot_nghiep_THPT"
    elif education_num <= 12:
        return "Sau_THPT_Cao_dang"
    elif education_num == 13:
        return "Cu_nhan"
    else:
        return "Sau_dai_hoc"


data_anonymized["hoc_van_nhom"] = (
    data_anonymized["so_nam_hoc"]
    .apply(generalize_education)
)

data_anonymized[
    ["trinh_do_hoc_van", "so_nam_hoc", "hoc_van_nhom"]
].drop_duplicates().sort_values("so_nam_hoc")

          trinh_do_hoc_van  so_nam_hoc          hoc_van_nhom
1106              Mau_giao           1  Chua_tot_nghiep_THPT
26                 Lop_1_4           2  Chua_tot_nghiep_THPT
27                 Lop_5_6           3  Chua_tot_nghiep_THPT
3                  Lop_7_8           4  Chua_tot_nghiep_THPT
197                  Lop_9           5  Chua_tot_nghiep_THPT
6                   Lop_10           6  Chua_tot_nghiep_THPT
16                  Lop_11           7  Chua_tot_nghiep_THPT
178                 Lop_12           8  Chua_tot_nghiep_THPT
0          Tot_nghiep_THPT           9       Tot_nghiep_THPT
2     Hoc_mot_phan_dai_hoc          10     Sau_THPT_Cao_dang
25           Cao_dang_nghe          11     Sau_THPT_Cao_dang
18      Cao_dang_hoc_thuat          12     Sau_THPT_Cao_dang
12                 Cu_nhan          13               Cu_nhan
13                 Thac_si          14           Sau_dai_hoc
11    Truong_chuyen_nghiep          15           Sau_dai_hoc
7                  Tien_si          16           Sau_dai_hoc

In [397]:
candidate_qi_age10_hours10_edu = candidate_qi_age10_hours10.copy()

candidate_qi_age10_hours10_edu[
    candidate_qi_age10_hours10_edu.index("trinh_do_hoc_van")
] = "hoc_van_nhom"

candidate_qi_age10_hours10_edu

['tuoi_nhom_10',
 'loai_cong_viec',
 'hoc_van_nhom',
 'tinh_trang_hon_nhan',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia']

Tức là hiện tại ta đã generalization 3 thuộc tính:

tuoi → tuoi_nhom_10

gio_lam_moi_tuan → gio_lam_nhom_10

trinh_do_hoc_van → hoc_van_nhom

In [398]:
qi_group_sizes_age10_hours10_edu = (
    data_anonymized
    .groupby(candidate_qi_age10_hours10_edu, dropna=False)
    .size()
)

qi_group_sizes_age10_hours10_edu

tuoi_nhom_10  loai_cong_viec       hoc_van_nhom          tinh_trang_hon_nhan  nghe_nghiep          quan_he_gia_dinh      chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia
10-19         Chinh_phu_lien_bang  Chua_tot_nghiep_THPT  Chua_ket_hon         Dich_vu_khac         Con_ruot              Chau_A_Thai_Binh_Duong  Nam        11-20            Philippines       1
                                                                                                                         Da_trang                Nu         21-30            Hoa_Ky            1
                                                                              Nhan_vien_van_phong  Khong_thuoc_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky            1
                                                                              Van_hanh_may_moc     Con_ruot              Da_trang                Nam        1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon         Ban_hang             Con_ruot              Da_trang                Nu         31-40            Hoa_Ky            1
                                                                                                                                                                                              ..
90-99         NaN                  Cu_nhan               Goa                  NaN                  Ho_hang_khac          Da_trang                Nu         1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon         NaN                  Con_ruot              Chau_A_Thai_Binh_Duong  Nam        1-10             Nam_Trieu_Tien    1
                                   Tot_nghiep_THPT       Goa                  NaN                  Khong_thuoc_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky            1
                                                                                                                                                 Nu         31-40            Hoa_Ky            1
                                                         Ket_hon_dan_su       NaN                  Chong                 Da_trang                Nam        31-40            Hoa_Ky            1
Length: 15806, dtype: int64

In [399]:
k_min_age10_hours10_edu = (
    qi_group_sizes_age10_hours10_edu.min()
)

print(
    "k nhỏ nhất sau khi gom tuổi, giờ làm và học vấn:",
    k_min_age10_hours10_edu
)

k nhỏ nhất sau khi gom tuổi, giờ làm và học vấn: 1

In [400]:
unique_groups_age10_hours10_edu = (
    qi_group_sizes_age10_hours10_edu == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm và học vấn:",
    unique_groups_age10_hours10_edu
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm và học vấn: 11855

In [401]:
unique_rate_age10_hours10_edu = (
    unique_groups_age10_hours10_edu / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm và học vấn:",
    round(unique_rate_age10_hours10_edu, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm và học vấn: 36.41 %

In [402]:
violation_records_age10_hours10_edu = (
    qi_group_sizes_age10_hours10_edu[
        qi_group_sizes_age10_hours10_edu < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm và học vấn:",
    violation_records_age10_hours10_edu
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm và học vấn: 19033

In [403]:
violation_rate_age10_hours10_edu = (
    violation_records_age10_hours10_edu / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm và học vấn:",
    round(violation_rate_age10_hours10_edu, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm và học vấn: 58.45 %

Xem cac gia tri cua tinh trang hon n

In [404]:
marital_counts = data_anonymized[
    "tinh_trang_hon_nhan"
].value_counts(dropna=False)

marital_counts

tinh_trang_hon_nhan
Ket_hon_dan_su               14976
Chua_ket_hon                 10683
Da_ly_hon                     4443
Ly_than                       1025
Goa                            993
Ket_hon_vo_chong_vang_mat      418
Ket_hon_voi_quan_nhan           23
Name: count, dtype: int64

In [405]:
def generalize_marital(status):
    if status == "Chua_ket_hon":
        return "Chua_ket_hon"

    elif status in [
        "Ket_hon_dan_su",
        "Ket_hon_vo_chong_vang_mat",
        "Ket_hon_voi_quan_nhan"
    ]:
        return "Da_ket_hon"

    else:
        return "Khong_con_hon_nhan"


data_anonymized["hon_nhan_nhom"] = (
    data_anonymized["tinh_trang_hon_nhan"]
    .apply(generalize_marital)
)

data_anonymized[
    ["tinh_trang_hon_nhan", "hon_nhan_nhom"]
].drop_duplicates()

            tinh_trang_hon_nhan       hon_nhan_nhom
0                           Goa  Khong_con_hon_nhan
3                     Da_ly_hon  Khong_con_hon_nhan
4                       Ly_than  Khong_con_hon_nhan
7                  Chua_ket_hon        Chua_ket_hon
23               Ket_hon_dan_su          Da_ket_hon
45    Ket_hon_vo_chong_vang_mat          Da_ket_hon
2871      Ket_hon_voi_quan_nhan          Da_ket_hon

In [406]:
candidate_qi_age10_hours10_edu_marital = (
    candidate_qi_age10_hours10_edu.copy()
)

candidate_qi_age10_hours10_edu_marital[
    candidate_qi_age10_hours10_edu_marital.index(
        "tinh_trang_hon_nhan"
    )
] = "hon_nhan_nhom"

candidate_qi_age10_hours10_edu_marital

['tuoi_nhom_10',
 'loai_cong_viec',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia']

In [407]:
qi_group_sizes_age10_hours10_edu_marital = (
    data_anonymized
    .groupby(candidate_qi_age10_hours10_edu_marital, dropna=False)
    .size()
)

qi_group_sizes_age10_hours10_edu_marital

tuoi_nhom_10  loai_cong_viec       hoc_van_nhom          hon_nhan_nhom       nghe_nghiep          quan_he_gia_dinh      chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia
10-19         Chinh_phu_lien_bang  Chua_tot_nghiep_THPT  Chua_ket_hon        Dich_vu_khac         Con_ruot              Chau_A_Thai_Binh_Duong  Nam        11-20            Philippines       1
                                                                                                                        Da_trang                Nu         21-30            Hoa_Ky            1
                                                                             Nhan_vien_van_phong  Khong_thuoc_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky            1
                                                                             Van_hanh_may_moc     Con_ruot              Da_trang                Nam        1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Ban_hang             Con_ruot              Da_trang                Nu         31-40            Hoa_Ky            1
                                                                                                                                                                                             ..
90-99         NaN                  Cu_nhan               Khong_con_hon_nhan  NaN                  Ho_hang_khac          Da_trang                Nu         1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        NaN                  Con_ruot              Chau_A_Thai_Binh_Duong  Nam        1-10             Nam_Trieu_Tien    1
                                   Tot_nghiep_THPT       Da_ket_hon          NaN                  Chong                 Da_trang                Nam        31-40            Hoa_Ky            1
                                                         Khong_con_hon_nhan  NaN                  Khong_thuoc_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky            1
                                                                                                                                                Nu         31-40            Hoa_Ky            1
Length: 15268, dtype: int64

In [408]:
k_min_age10_hours10_edu_marital = (
    qi_group_sizes_age10_hours10_edu_marital.min()
)

print(
    "k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn và hôn nhân:",
    k_min_age10_hours10_edu_marital
)

k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn và hôn nhân: 1

In [409]:
unique_groups_age10_hours10_edu_marital = (
    qi_group_sizes_age10_hours10_edu_marital == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn và hôn nhân:",
    unique_groups_age10_hours10_edu_marital
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn và hôn nhân: 11229

In [410]:
unique_rate_age10_hours10_edu_marital = (
    unique_groups_age10_hours10_edu_marital / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn và hôn nhân:",
    round(unique_rate_age10_hours10_edu_marital, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn và hôn nhân: 34.49 %

In [411]:
violation_records_age10_hours10_edu_marital = (
    qi_group_sizes_age10_hours10_edu_marital[
        qi_group_sizes_age10_hours10_edu_marital < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn và hôn nhân:",
    violation_records_age10_hours10_edu_marital
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn và hôn nhân: 18596

In [412]:
violation_rate_age10_hours10_edu_marital = (
    violation_records_age10_hours10_edu_marital
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn và hôn nhân:",
    round(violation_rate_age10_hours10_edu_marital, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn và hôn nhân: 57.11 %

Gom cum nghe nghiep

In [413]:
occupation_counts = data_anonymized[
    "nghe_nghiep"
].value_counts(dropna=False)

occupation_counts

nghe_nghiep
Chuyen_mon_dac_thu         4140
Tho_thu_cong_sua_chua      4099
Quan_ly_dieu_hanh          4066
Nhan_vien_van_phong        3770
Ban_hang                   3650
Dich_vu_khac               3295
Van_hanh_may_moc           2002
<NA>                       1843
Van_tai                    1597
Boc_xep_don_dep            1370
Nong_nghiep_danh_bat_ca     994
Ho_tro_ky_thuat             928
Dich_vu_bao_ve              649
Giup_viec_gia_dinh          149
Quan_doi                      9
Name: count, dtype: int64

In [414]:
occupation_map = {
    "Chuyen_mon_dac_thu": "Chuyen_mon_ky_thuat",
    "Ho_tro_ky_thuat": "Chuyen_mon_ky_thuat",

    "Quan_ly_dieu_hanh": "Van_phong_kinh_doanh",
    "Nhan_vien_van_phong": "Van_phong_kinh_doanh",
    "Ban_hang": "Van_phong_kinh_doanh",

    "Tho_thu_cong_sua_chua": "Lao_dong_ky_thuat",
    "Van_hanh_may_moc": "Lao_dong_ky_thuat",
    "Van_tai": "Lao_dong_ky_thuat",
    "Boc_xep_don_dep": "Lao_dong_ky_thuat",

    "Dich_vu_khac": "Dich_vu",
    "Dich_vu_bao_ve": "Dich_vu",
    "Giup_viec_gia_dinh": "Dich_vu",

    "Nong_nghiep_danh_bat_ca": "Nong_nghiep",

    "Quan_doi": "Quan_doi"
}

data_anonymized["nghe_nghiep_nhom"] = (
    data_anonymized["nghe_nghiep"]
    .map(occupation_map)
    .fillna("Khong_ro")
)

data_anonymized[
    ["nghe_nghiep", "nghe_nghiep_nhom"]
].drop_duplicates().sort_values("nghe_nghiep_nhom")

                  nghe_nghiep      nghe_nghiep_nhom
4          Chuyen_mon_dac_thu   Chuyen_mon_ky_thuat
52            Ho_tro_ky_thuat   Chuyen_mon_ky_thuat
5                Dich_vu_khac               Dich_vu
57             Dich_vu_bao_ve               Dich_vu
1223       Giup_viec_gia_dinh               Dich_vu
0                        <NA>              Khong_ro
3            Van_hanh_may_moc     Lao_dong_ky_thuat
9       Tho_thu_cong_sua_chua     Lao_dong_ky_thuat
16                    Van_tai     Lao_dong_ky_thuat
18            Boc_xep_don_dep     Lao_dong_ky_thuat
47    Nong_nghiep_danh_bat_ca           Nong_nghiep
850                  Quan_doi              Quan_doi
1           Quan_ly_dieu_hanh  Van_phong_kinh_doanh
6         Nhan_vien_van_phong  Van_phong_kinh_doanh
19                   Ban_hang  Van_phong_kinh_doanh

In [415]:
candidate_qi_age10_hours10_edu_marital_occ = (
    candidate_qi_age10_hours10_edu_marital.copy()
)

candidate_qi_age10_hours10_edu_marital_occ[
    candidate_qi_age10_hours10_edu_marital_occ.index("nghe_nghiep")
] = "nghe_nghiep_nhom"

candidate_qi_age10_hours10_edu_marital_occ

['tuoi_nhom_10',
 'loai_cong_viec',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia']

In [416]:
qi_group_sizes_age10_hours10_edu_marital_occ = (
    data_anonymized
    .groupby(candidate_qi_age10_hours10_edu_marital_occ, dropna=False)
    .size()
)

qi_group_sizes_age10_hours10_edu_marital_occ

tuoi_nhom_10  loai_cong_viec       hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh      chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia
10-19         Chinh_phu_lien_bang  Chua_tot_nghiep_THPT  Chua_ket_hon        Dich_vu               Con_ruot              Chau_A_Thai_Binh_Duong  Nam        11-20            Philippines       1
                                                                                                                         Da_trang                Nu         21-30            Hoa_Ky            1
                                                                             Lao_dong_ky_thuat     Con_ruot              Da_trang                Nam        1-10             Hoa_Ky            1
                                                                             Van_phong_kinh_doanh  Khong_thuoc_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Lao_dong_ky_thuat     Con_ruot              Da_trang                Nam        11-20            Anh               1
                                                                                                                                                                                              ..
90-99         NaN                  Cu_nhan               Khong_con_hon_nhan  Khong_ro              Ho_hang_khac          Da_trang                Nu         1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Con_ruot              Chau_A_Thai_Binh_Duong  Nam        1-10             Nam_Trieu_Tien    1
                                   Tot_nghiep_THPT       Da_ket_hon          Khong_ro              Chong                 Da_trang                Nam        31-40            Hoa_Ky            1
                                                         Khong_con_hon_nhan  Khong_ro              Khong_thuoc_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky            1
                                                                                                                                                 Nu         31-40            Hoa_Ky            1
Length: 12690, dtype: int64

In [417]:
k_min_age10_hours10_edu_marital_occ = (
    qi_group_sizes_age10_hours10_edu_marital_occ.min()
)

print(
    "k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp:",
    k_min_age10_hours10_edu_marital_occ
)

k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp: 1

In [418]:
unique_groups_age10_hours10_edu_marital_occ = (
    qi_group_sizes_age10_hours10_edu_marital_occ == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp:",
    unique_groups_age10_hours10_edu_marital_occ
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp: 9084

In [419]:
unique_rate_age10_hours10_edu_marital_occ = (
    unique_groups_age10_hours10_edu_marital_occ
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp:",
    round(unique_rate_age10_hours10_edu_marital_occ, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp: 27.9 %

In [420]:
violation_records_age10_hours10_edu_marital_occ = (
    qi_group_sizes_age10_hours10_edu_marital_occ[
        qi_group_sizes_age10_hours10_edu_marital_occ < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp:",
    violation_records_age10_hours10_edu_marital_occ
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp: 15397

In [421]:
violation_rate_age10_hours10_edu_marital_occ = (
    violation_records_age10_hours10_edu_marital_occ
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp:",
    round(violation_rate_age10_hours10_edu_marital_occ, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân và nghề nghiệp: 47.29 %

Quan he gia dinh

In [422]:
relationship_counts = data_anonymized[
    "quan_he_gia_dinh"
].value_counts(dropna=False)

relationship_counts

quan_he_gia_dinh
Chong                   13193
Khong_thuoc_gia_dinh     8305
Con_ruot                 5068
Doc_than                 3446
Vo                       1568
Ho_hang_khac              981
Name: count, dtype: int64

In [423]:
relationship_map = {
    "Chong": "Vo_chong",
    "Vo": "Vo_chong",

    "Con_ruot": "Nguoi_than",
    "Ho_hang_khac": "Nguoi_than",

    "Khong_thuoc_gia_dinh": "Khong_quan_he_gia_dinh",
    "Doc_than": "Khong_quan_he_gia_dinh"
}

data_anonymized["quan_he_gia_dinh_nhom"] = (
    data_anonymized["quan_he_gia_dinh"]
    .map(relationship_map)
)

data_anonymized[
    ["quan_he_gia_dinh", "quan_he_gia_dinh_nhom"]
].drop_duplicates()

        quan_he_gia_dinh   quan_he_gia_dinh_nhom
0   Khong_thuoc_gia_dinh  Khong_quan_he_gia_dinh
2               Doc_than  Khong_quan_he_gia_dinh
4               Con_ruot              Nguoi_than
7           Ho_hang_khac              Nguoi_than
23                 Chong                Vo_chong
48                    Vo                Vo_chong

In [424]:
candidate_qi_age10_hours10_edu_marital_occ_rel = (
    candidate_qi_age10_hours10_edu_marital_occ.copy()
)

candidate_qi_age10_hours10_edu_marital_occ_rel[
    candidate_qi_age10_hours10_edu_marital_occ_rel.index(
        "quan_he_gia_dinh"
    )
] = "quan_he_gia_dinh_nhom"

candidate_qi_age10_hours10_edu_marital_occ_rel

['tuoi_nhom_10',
 'loai_cong_viec',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia']

In [425]:
qi_group_sizes_age10_hours10_edu_marital_occ_rel = (
    data_anonymized
    .groupby(
        candidate_qi_age10_hours10_edu_marital_occ_rel,
        dropna=False
    )
    .size()
)

qi_group_sizes_age10_hours10_edu_marital_occ_rel

tuoi_nhom_10  loai_cong_viec       hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia
10-19         Chinh_phu_lien_bang  Chua_tot_nghiep_THPT  Chua_ket_hon        Dich_vu               Nguoi_than              Chau_A_Thai_Binh_Duong  Nam        11-20            Philippines       1
                                                                                                                           Da_trang                Nu         21-30            Hoa_Ky            1
                                                                             Lao_dong_ky_thuat     Nguoi_than              Da_trang                Nam        1-10             Hoa_Ky            1
                                                                             Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Lao_dong_ky_thuat     Nguoi_than              Da_trang                Nam        11-20            Anh               1
                                                                                                                                                                                                ..
90-99         NaN                  Cu_nhan               Khong_con_hon_nhan  Khong_ro              Nguoi_than              Da_trang                Nu         1-10             Hoa_Ky            1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              Chau_A_Thai_Binh_Duong  Nam        1-10             Nam_Trieu_Tien    1
                                   Tot_nghiep_THPT       Da_ket_hon          Khong_ro              Vo_chong                Da_trang                Nam        31-40            Hoa_Ky            1
                                                         Khong_con_hon_nhan  Khong_ro              Khong_quan_he_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky            1
                                                                                                                                                   Nu         31-40            Hoa_Ky            1
Length: 11738, dtype: int64

In [426]:
k_min_age10_hours10_edu_marital_occ_rel = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel.min()
)

print(
    "k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình:",
    k_min_age10_hours10_edu_marital_occ_rel
)

k nhỏ nhất sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình: 1

In [427]:
unique_groups_age10_hours10_edu_marital_occ_rel = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình:",
    unique_groups_age10_hours10_edu_marital_occ_rel
)

Số nhóm chỉ có 1 bản ghi sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình: 8210

In [428]:
unique_rate_age10_hours10_edu_marital_occ_rel = (
    unique_groups_age10_hours10_edu_marital_occ_rel
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình:",
    round(unique_rate_age10_hours10_edu_marital_occ_rel, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình: 25.21 %

In [429]:
violation_records_age10_hours10_edu_marital_occ_rel = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel[
        qi_group_sizes_age10_hours10_edu_marital_occ_rel < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình:",
    violation_records_age10_hours10_edu_marital_occ_rel
)

Số bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình: 14199

In [430]:
violation_rate_age10_hours10_edu_marital_occ_rel = (
    violation_records_age10_hours10_edu_marital_occ_rel
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình:",
    round(violation_rate_age10_hours10_edu_marital_occ_rel, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom tuổi, giờ làm, học vấn, hôn nhân, nghề nghiệp và quan hệ gia đình: 43.61 %

In [431]:
country_counts = data_anonymized[
    "quoc_gia"
].value_counts(dropna=False)

country_counts

quoc_gia
Hoa_Ky                   29170
Mexico                     643
<NA>                       583
Philippines                198
Duc                        137
Canada                     121
Puerto_Rico                114
El_Salvador                106
An_Do                      100
Cuba                        95
Anh                         90
Jamaica                     81
Nam_Trieu_Tien              80
Trung_Quoc                  75
Y                           73
Cong_Hoa_Dominica           70
Viet_Nam                    67
Guatemala                   64
Nhat_Ban                    62
Ba_Lan                      60
Colombia                    59
Dai_Loan                    51
Haiti                       44
Iran                        43
Bo_Dao_Nha                  37
Nicaragua                   34
Peru                        31
Hy_Lap                      29
Phap                        29
Ecuador                     28
Ireland                     24
Hong_Kong                   20
Trinidad_va_Tobago          19
Campuchia                   19
Thai_Lan                    18
Lao                         18
Nam_Tu                      16
Lanh_tho_hai_ngoai_My       14
Hungary                     13
Honduras                    13
Scotland                    12
Ha_Lan                       1
Name: count, dtype: int64

In [432]:
country_map = {
    # Hoa Ky
    "Hoa_Ky": "Hoa_Ky",
    "Lanh_tho_hai_ngoai_My": "Hoa_Ky",

    # Bac My khac
    "Canada": "Bac_My_khac",

    # My Latinh va Caribe
    "Mexico": "My_Latinh_Caribe",
    "Puerto_Rico": "My_Latinh_Caribe",
    "El_Salvador": "My_Latinh_Caribe",
    "Cuba": "My_Latinh_Caribe",
    "Jamaica": "My_Latinh_Caribe",
    "Cong_Hoa_Dominica": "My_Latinh_Caribe",
    "Guatemala": "My_Latinh_Caribe",
    "Colombia": "My_Latinh_Caribe",
    "Haiti": "My_Latinh_Caribe",
    "Nicaragua": "My_Latinh_Caribe",
    "Peru": "My_Latinh_Caribe",
    "Ecuador": "My_Latinh_Caribe",
    "Trinidad_va_Tobago": "My_Latinh_Caribe",
    "Honduras": "My_Latinh_Caribe",

    # Chau Au
    "Duc": "Chau_Au",
    "Anh": "Chau_Au",
    "Y": "Chau_Au",
    "Ba_Lan": "Chau_Au",
    "Bo_Dao_Nha": "Chau_Au",
    "Hy_Lap": "Chau_Au",
    "Phap": "Chau_Au",
    "Ireland": "Chau_Au",
    "Nam_Tu": "Chau_Au",
    "Hungary": "Chau_Au",
    "Scotland": "Chau_Au",
    "Ha_Lan": "Chau_Au",

    # Chau A - Thai Binh Duong
    "Philippines": "Chau_A_Thai_Binh_Duong",
    "An_Do": "Chau_A_Thai_Binh_Duong",
    "Nam_Trieu_Tien": "Chau_A_Thai_Binh_Duong",
    "Trung_Quoc": "Chau_A_Thai_Binh_Duong",
    "Viet_Nam": "Chau_A_Thai_Binh_Duong",
    "Nhat_Ban": "Chau_A_Thai_Binh_Duong",
    "Dai_Loan": "Chau_A_Thai_Binh_Duong",
    "Hong_Kong": "Chau_A_Thai_Binh_Duong",
    "Campuchia": "Chau_A_Thai_Binh_Duong",
    "Thai_Lan": "Chau_A_Thai_Binh_Duong",
    "Lao": "Chau_A_Thai_Binh_Duong",

    # Trung Dong
    "Iran": "Trung_Dong"
}

data_anonymized["quoc_gia_nhom"] = (
    data_anonymized["quoc_gia"]
    .map(country_map)
    .fillna("Khong_ro")
)

data_anonymized[
    ["quoc_gia", "quoc_gia_nhom"]
].drop_duplicates().sort_values("quoc_gia_nhom")

                   quoc_gia           quoc_gia_nhom
157                  Canada             Bac_My_khac
508               Hong_Kong  Chau_A_Thai_Binh_Duong
4460               Thai_Lan  Chau_A_Thai_Binh_Duong
487                Nhat_Ban  Chau_A_Thai_Binh_Duong
921               Campuchia  Chau_A_Thai_Binh_Duong
95              Philippines  Chau_A_Thai_Binh_Duong
90                    An_Do  Chau_A_Thai_Binh_Duong
166          Nam_Trieu_Tien  Chau_A_Thai_Binh_Duong
63               Trung_Quoc  Chau_A_Thai_Binh_Duong
47                 Viet_Nam  Chau_A_Thai_Binh_Duong
3804                    Lao  Chau_A_Thai_Binh_Duong
82                 Dai_Loan  Chau_A_Thai_Binh_Duong
3079               Scotland                 Chau_Au
27                   Hy_Lap                 Chau_Au
211                  Ha_Lan                 Chau_Au
2985                 Nam_Tu                 Chau_Au
268                  Ba_Lan                 Chau_Au
2368                   Phap                 Chau_Au
287                     Anh                 Chau_Au
412                     Duc                 Chau_Au
447                       Y                 Chau_Au
3267             Bo_Dao_Nha                 Chau_Au
1180                Hungary                 Chau_Au
781                 Ireland                 Chau_Au
0                    Hoa_Ky                  Hoa_Ky
5581  Lanh_tho_hai_ngoai_My                  Hoa_Ky
9                      <NA>                Khong_ro
26                   Mexico        My_Latinh_Caribe
156      Trinidad_va_Tobago        My_Latinh_Caribe
216             Puerto_Rico        My_Latinh_Caribe
2299                Ecuador        My_Latinh_Caribe
726                    Cuba        My_Latinh_Caribe
938                    Peru        My_Latinh_Caribe
1258               Colombia        My_Latinh_Caribe
535                Honduras        My_Latinh_Caribe
1117            El_Salvador        My_Latinh_Caribe
1044                  Haiti        My_Latinh_Caribe
1004      Cong_Hoa_Dominica        My_Latinh_Caribe
954               Nicaragua        My_Latinh_Caribe
1268              Guatemala        My_Latinh_Caribe
1765                Jamaica        My_Latinh_Caribe
284                    Iran              Trung_Dong

In [433]:
#kiem tra coi con cuoc gia nao sot khong
unmapped_countries = data_anonymized.loc[
    data_anonymized["quoc_gia"].notna()
    & (data_anonymized["quoc_gia_nhom"] == "Khong_ro"),
    "quoc_gia"
].unique()

print("Quốc gia chưa được ánh xạ:", unmapped_countries)

Quốc gia chưa được ánh xạ: []

In [434]:
candidate_qi_age10_hours10_edu_marital_occ_rel_country = (
    candidate_qi_age10_hours10_edu_marital_occ_rel.copy()
)

candidate_qi_age10_hours10_edu_marital_occ_rel_country[
    candidate_qi_age10_hours10_edu_marital_occ_rel_country.index(
        "quoc_gia"
    )
] = "quoc_gia_nhom"

candidate_qi_age10_hours10_edu_marital_occ_rel_country

['tuoi_nhom_10',
 'loai_cong_viec',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia_nhom']

In [435]:
qi_group_sizes_age10_hours10_edu_marital_occ_rel_country = (
    data_anonymized
    .groupby(
        candidate_qi_age10_hours10_edu_marital_occ_rel_country,
        dropna=False
    )
    .size()
)

qi_group_sizes_age10_hours10_edu_marital_occ_rel_country

tuoi_nhom_10  loai_cong_viec       hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   chung_toc               gioi_tinh  gio_lam_nhom_10  quoc_gia_nhom
10-19         Chinh_phu_lien_bang  Chua_tot_nghiep_THPT  Chua_ket_hon        Dich_vu               Nguoi_than              Chau_A_Thai_Binh_Duong  Nam        11-20            Chau_A_Thai_Binh_Duong    1
                                                                                                                           Da_trang                Nu         21-30            Hoa_Ky                    1
                                                                             Lao_dong_ky_thuat     Nguoi_than              Da_trang                Nam        1-10             Hoa_Ky                    1
                                                                             Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  Da_den                  Nu         31-40            Hoa_Ky                    1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Lao_dong_ky_thuat     Nguoi_than              Da_trang                Nam        11-20            Chau_Au                   1
                                                                                                                                                                                                        ..
90-99         NaN                  Cu_nhan               Khong_con_hon_nhan  Khong_ro              Nguoi_than              Da_trang                Nu         1-10             Hoa_Ky                    1
                                   Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              Chau_A_Thai_Binh_Duong  Nam        1-10             Chau_A_Thai_Binh_Duong    1
                                   Tot_nghiep_THPT       Da_ket_hon          Khong_ro              Vo_chong                Da_trang                Nam        31-40            Hoa_Ky                    1
                                                         Khong_con_hon_nhan  Khong_ro              Khong_quan_he_gia_dinh  Da_trang                Nam        1-10             Hoa_Ky                    1
                                                                                                                                                   Nu         31-40            Hoa_Ky                    1
Length: 11392, dtype: int64

In [436]:
k_min_age10_hours10_edu_marital_occ_rel_country = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country.min()
)

print(
    "k nhỏ nhất sau khi gom thêm quốc gia:",
    k_min_age10_hours10_edu_marital_occ_rel_country
)

k nhỏ nhất sau khi gom thêm quốc gia: 1

In [437]:
unique_groups_age10_hours10_edu_marital_occ_rel_country = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom thêm quốc gia:",
    unique_groups_age10_hours10_edu_marital_occ_rel_country
)

Số nhóm chỉ có 1 bản ghi sau khi gom thêm quốc gia: 7747

In [438]:
unique_rate_age10_hours10_edu_marital_occ_rel_country = (
    unique_groups_age10_hours10_edu_marital_occ_rel_country
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom thêm quốc gia:",
    round(unique_rate_age10_hours10_edu_marital_occ_rel_country, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom thêm quốc gia: 23.79 %

In [439]:
violation_records_age10_hours10_edu_marital_occ_rel_country = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country[
        qi_group_sizes_age10_hours10_edu_marital_occ_rel_country < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom thêm quốc gia:",
    violation_records_age10_hours10_edu_marital_occ_rel_country
)

Số bản ghi chưa đạt k=5 sau khi gom thêm quốc gia: 13979

In [440]:
violation_rate_age10_hours10_edu_marital_occ_rel_country = (
    violation_records_age10_hours10_edu_marital_occ_rel_country
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm quốc gia:",
    round(
        violation_rate_age10_hours10_edu_marital_occ_rel_country,
        2
    ),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm quốc gia: 42.93 %

Loai cong viec

In [441]:
workclass_counts = data_anonymized[
    "loai_cong_viec"
].value_counts(dropna=False)

workclass_counts

loai_cong_viec
Tu_nhan                        22696
Tu_kinh_doanh_khong_dang_ky     2541
Chinh_quyen_dia_phuong          2093
<NA>                            1836
Chinh_quyen_bang                1298
Tu_kinh_doanh_co_dang_ky        1116
Chinh_phu_lien_bang              960
Khong_luong                       14
Chua_tung_lam_viec                 7
Name: count, dtype: int64

In [442]:
workclass_map = {
    # Khu vực nhà nước
    "Chinh_phu_lien_bang": "Nha_nuoc",
    "Chinh_quyen_bang": "Nha_nuoc",
    "Chinh_quyen_dia_phuong": "Nha_nuoc",

    # Làm cho doanh nghiệp tư nhân
    "Tu_nhan": "Tu_nhan",

    # Tự kinh doanh
    "Tu_kinh_doanh_khong_dang_ky": "Tu_kinh_doanh",
    "Tu_kinh_doanh_co_dang_ky": "Tu_kinh_doanh",

    # Không có việc làm hưởng lương
    "Khong_luong": "Khong_luong_hoac_chua_lam",
    "Chua_tung_lam_viec": "Khong_luong_hoac_chua_lam"
}

data_anonymized["loai_cong_viec_nhom"] = (
    data_anonymized["loai_cong_viec"]
    .map(workclass_map)
    .fillna("Khong_ro")
)

data_anonymized[
    ["loai_cong_viec", "loai_cong_viec_nhom"]
].drop_duplicates().sort_values("loai_cong_viec_nhom")

                   loai_cong_viec        loai_cong_viec_nhom
3277                  Khong_luong  Khong_luong_hoac_chua_lam
8874           Chua_tung_lam_viec  Khong_luong_hoac_chua_lam
0                            <NA>                   Khong_ro
7                Chinh_quyen_bang                   Nha_nuoc
8             Chinh_phu_lien_bang                   Nha_nuoc
57         Chinh_quyen_dia_phuong                   Nha_nuoc
11    Tu_kinh_doanh_khong_dang_ky              Tu_kinh_doanh
28       Tu_kinh_doanh_co_dang_ky              Tu_kinh_doanh
1                         Tu_nhan                    Tu_nhan

In [443]:
candidate_qi_age10_hours10_edu_marital_occ_rel_country_work = (
    candidate_qi_age10_hours10_edu_marital_occ_rel_country.copy()
)

candidate_qi_age10_hours10_edu_marital_occ_rel_country_work[
    candidate_qi_age10_hours10_edu_marital_occ_rel_country_work.index(
        "loai_cong_viec"
    )
] = "loai_cong_viec_nhom"

candidate_qi_age10_hours10_edu_marital_occ_rel_country_work

['tuoi_nhom_10',
 'loai_cong_viec_nhom',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'chung_toc',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia_nhom']

In [444]:
qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work = (
    data_anonymized
    .groupby(
        candidate_qi_age10_hours10_edu_marital_occ_rel_country_work,
        dropna=False
    )
    .size()
)

qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work

tuoi_nhom_10  loai_cong_viec_nhom        hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   chung_toc  gioi_tinh  gio_lam_nhom_10  quoc_gia_nhom
10-19         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              Da_trang   Nam        21-30            Hoa_Ky              1
                                                                                                                                                       31-40            Hoa_Ky              1
                                                                                                                                            Nu         1-10             Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              Da_trang   Nam        1-10             Hoa_Ky              1
                                         Tot_nghiep_THPT       Chua_ket_hon        Nong_nghiep           Nguoi_than              Da_trang   Nam        1-10             Hoa_Ky              1
                                                                                                                                                                                           ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              Da_trang   Nu         21-30            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                Da_trang   Nam        31-40            Hoa_Ky              2
                                                                                                                                                       41-50            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  Da_trang   Nam        91-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  Da_trang   Nu         21-30            Hoa_Ky              1
Length: 10514, dtype: int64

In [445]:
k_min_age10_hours10_edu_marital_occ_rel_country_work = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work.min()
)

print(
    "k nhỏ nhất sau khi gom thêm loại công việc:",
    k_min_age10_hours10_edu_marital_occ_rel_country_work
)

k nhỏ nhất sau khi gom thêm loại công việc: 1

In [446]:
unique_groups_age10_hours10_edu_marital_occ_rel_country_work = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gom thêm loại công việc:",
    unique_groups_age10_hours10_edu_marital_occ_rel_country_work
)

Số nhóm chỉ có 1 bản ghi sau khi gom thêm loại công việc: 6907

In [447]:
unique_rate_age10_hours10_edu_marital_occ_rel_country_work = (
    unique_groups_age10_hours10_edu_marital_occ_rel_country_work
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gom thêm loại công việc:",
    round(
        unique_rate_age10_hours10_edu_marital_occ_rel_country_work,
        2
    ),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gom thêm loại công việc: 21.21 %

In [448]:
violation_records_age10_hours10_edu_marital_occ_rel_country_work = (
    qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work[
        qi_group_sizes_age10_hours10_edu_marital_occ_rel_country_work < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gom thêm loại công việc:",
    violation_records_age10_hours10_edu_marital_occ_rel_country_work
)

Số bản ghi chưa đạt k=5 sau khi gom thêm loại công việc: 13020

In [449]:
violation_rate_age10_hours10_edu_marital_occ_rel_country_work = (
    violation_records_age10_hours10_edu_marital_occ_rel_country_work
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm loại công việc:",
    round(
        violation_rate_age10_hours10_edu_marital_occ_rel_country_work,
        2
    ),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm loại công việc: 39.99 %

In [450]:
violation_rate_age10_hours10_edu_marital_occ_rel_country_work = (
    violation_records_age10_hours10_edu_marital_occ_rel_country_work
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm loại công việc:",
    round(
        violation_rate_age10_hours10_edu_marital_occ_rel_country_work,
        2
    ),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gom thêm loại công việc: 39.99 %

Gom chung_toc

In [451]:
race_counts = data_anonymized[
    "chung_toc"
].value_counts(dropna=False)

race_counts

chung_toc
Da_trang                   27816
Da_den                      3124
Chau_A_Thai_Binh_Duong      1039
Nguoi_ban_dia_My_Eskimo      311
Khac                         271
Name: count, dtype: int64

In [452]:
candidate_qi_suppress_race = (
    candidate_qi_age10_hours10_edu_marital_occ_rel_country_work.copy()
)

candidate_qi_suppress_race.remove("chung_toc")

candidate_qi_suppress_race

['tuoi_nhom_10',
 'loai_cong_viec_nhom',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gioi_tinh',
 'gio_lam_nhom_10',
 'quoc_gia_nhom']

In [453]:
qi_group_sizes_suppress_race = (
    data_anonymized
    .groupby(
        candidate_qi_suppress_race,
        dropna=False
    )
    .size()
)

qi_group_sizes_suppress_race

tuoi_nhom_10  loai_cong_viec_nhom        hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gioi_tinh  gio_lam_nhom_10  quoc_gia_nhom
10-19         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              Nam        21-30            Hoa_Ky              1
                                                                                                                                            31-40            Hoa_Ky              1
                                                                                                                                 Nu         1-10             Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              Nam        1-10             Hoa_Ky              1
                                         Tot_nghiep_THPT       Chua_ket_hon        Nong_nghiep           Nguoi_than              Nam        1-10             Hoa_Ky              1
                                                                                                                                                                                ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              Nu         21-30            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                Nam        31-40            Hoa_Ky              2
                                                                                                                                            41-50            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  Nam        91-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  Nu         21-30            Hoa_Ky              1
Length: 8743, dtype: int64

In [454]:
k_min_suppress_race = qi_group_sizes_suppress_race.min()

print(
    "k nhỏ nhất sau khi suppression chủng tộc:",
    k_min_suppress_race
)

k nhỏ nhất sau khi suppression chủng tộc: 1

In [455]:
unique_groups_suppress_race = (
    qi_group_sizes_suppress_race == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi suppression chủng tộc:",
    unique_groups_suppress_race
)

Số nhóm chỉ có 1 bản ghi sau khi suppression chủng tộc: 5352

In [456]:
unique_rate_suppress_race = (
    unique_groups_suppress_race
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi suppression chủng tộc:",
    round(unique_rate_suppress_race, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi suppression chủng tộc: 16.44 %

In [457]:
violation_records_suppress_race = (
    qi_group_sizes_suppress_race[
        qi_group_sizes_suppress_race < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi suppression chủng tộc:",
    violation_records_suppress_race
)

Số bản ghi chưa đạt k=5 sau khi suppression chủng tộc: 10753

In [458]:
violation_rate_suppress_race = (
    violation_records_suppress_race
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression chủng tộc:",
    round(violation_rate_suppress_race, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression chủng tộc: 33.02 %

Gioi tinh

In [459]:
gender_counts = data_anonymized[
    "gioi_tinh"
].value_counts(dropna=False)

gender_counts

gioi_tinh
Nam    21790
Nu     10771
Name: count, dtype: int64

Bo gioi_tinh, chung_toc ra khoi QI

In [460]:
candidate_qi_suppress_race_gender = (
    candidate_qi_suppress_race.copy()
)

candidate_qi_suppress_race_gender.remove("gioi_tinh")

candidate_qi_suppress_race_gender

['tuoi_nhom_10',
 'loai_cong_viec_nhom',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_10',
 'quoc_gia_nhom']

In [461]:
qi_group_sizes_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_suppress_race_gender

tuoi_nhom_10  loai_cong_viec_nhom        hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gio_lam_nhom_10  quoc_gia_nhom
10-19         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              1-10             Hoa_Ky              1
                                                                                                                                 21-30            Hoa_Ky              1
                                                                                                                                 31-40            Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              1-10             Hoa_Ky              1
                                         Tot_nghiep_THPT       Chua_ket_hon        Nong_nghiep           Nguoi_than              1-10             Hoa_Ky              1
                                                                                                                                                                     ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              21-30            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                31-40            Hoa_Ky              2
                                                                                                                                 41-50            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  91-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  21-30            Hoa_Ky              1
Length: 7154, dtype: int64

In [462]:
k_min_suppress_race_gender = (
    qi_group_sizes_suppress_race_gender.min()
)

print(
    "k nhỏ nhất sau khi suppression chủng tộc và giới tính:",
    k_min_suppress_race_gender
)

k nhỏ nhất sau khi suppression chủng tộc và giới tính: 1

In [463]:
unique_groups_suppress_race_gender = (
    qi_group_sizes_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi suppression chủng tộc và giới tính:",
    unique_groups_suppress_race_gender
)

Số nhóm chỉ có 1 bản ghi sau khi suppression chủng tộc và giới tính: 4125

In [464]:
unique_rate_suppress_race_gender = (
    unique_groups_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi suppression chủng tộc và giới tính:",
    round(unique_rate_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi suppression chủng tộc và giới tính: 12.67 %

In [465]:
violation_records_suppress_race_gender = (
    qi_group_sizes_suppress_race_gender[
        qi_group_sizes_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi suppression chủng tộc và giới tính:",
    violation_records_suppress_race_gender
)

Số bản ghi chưa đạt k=5 sau khi suppression chủng tộc và giới tính: 8866

In [466]:
violation_rate_suppress_race_gender = (
    violation_records_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression chủng tộc và giới tính:",
    round(violation_rate_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression chủng tộc và giới tính: 27.23 %

Tao nhom tuoi thanh khoang rong 20 nam

In [467]:
age20_map = {
    "10-19": "10-29",
    "20-29": "10-29",

    "30-39": "30-49",
    "40-49": "30-49",

    "50-59": "50-69",
    "60-69": "50-69",

    "70-79": "70-89",
    "80-89": "70-89",

    "90-99": "90-99"
}

data_anonymized["tuoi_nhom_20"] = (
    data_anonymized["tuoi_nhom_10"]
    .map(age20_map)
)

data_anonymized[
    ["tuoi", "tuoi_nhom_10", "tuoi_nhom_20"]
].head(15)

    tuoi tuoi_nhom_10 tuoi_nhom_20
0     90        90-99        90-99
1     82        80-89        70-89
2     66        60-69        50-69
3     54        50-59        50-69
4     41        40-49        30-49
5     34        30-39        30-49
6     38        30-39        30-49
7     74        70-79        70-89
8     68        60-69        50-69
9     41        40-49        30-49
10    45        40-49        30-49
11    38        30-39        30-49
12    52        50-59        50-69
13    32        30-39        30-49
14    51        50-59        50-69

In [468]:
candidate_qi_age20_suppress_race_gender = (
    candidate_qi_suppress_race_gender.copy()
)

candidate_qi_age20_suppress_race_gender[
    candidate_qi_age20_suppress_race_gender.index("tuoi_nhom_10")
] = "tuoi_nhom_20"

candidate_qi_age20_suppress_race_gender

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_10',
 'quoc_gia_nhom']

In [469]:
qi_group_sizes_age20_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_age20_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_age20_suppress_race_gender

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gio_lam_nhom_10  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              1-10             Hoa_Ky              1
                                                                                                                                 21-30            Hoa_Ky              1
                                                                                                                                 31-40            Hoa_Ky              1
                                                               Khong_con_hon_nhan  Khong_ro              Khong_quan_he_gia_dinh  31-40            Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              1-10             Hoa_Ky              1
                                                                                                                                                                     ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              21-30            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                31-40            Hoa_Ky              2
                                                                                                                                 41-50            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  91-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  21-30            Hoa_Ky              1
Length: 5674, dtype: int64

In [470]:
k_min_age20_suppress_race_gender = (
    qi_group_sizes_age20_suppress_race_gender.min()
)

print(
    "k nhỏ nhất sau khi dùng nhóm tuổi 20 năm:",
    k_min_age20_suppress_race_gender
)

k nhỏ nhất sau khi dùng nhóm tuổi 20 năm: 1

In [471]:
unique_groups_age20_suppress_race_gender = (
    qi_group_sizes_age20_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi dùng nhóm tuổi 20 năm:",
    unique_groups_age20_suppress_race_gender
)

Số nhóm chỉ có 1 bản ghi sau khi dùng nhóm tuổi 20 năm: 3110

In [472]:
unique_rate_age20_suppress_race_gender = (
    unique_groups_age20_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi dùng nhóm tuổi 20 năm:",
    round(unique_rate_age20_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi dùng nhóm tuổi 20 năm: 9.55 %

In [473]:
violation_records_age20_suppress_race_gender = (
    qi_group_sizes_age20_suppress_race_gender[
        qi_group_sizes_age20_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi dùng nhóm tuổi 20 năm:",
    violation_records_age20_suppress_race_gender
)

Số bản ghi chưa đạt k=5 sau khi dùng nhóm tuổi 20 năm: 7007

In [474]:
violation_rate_age20_suppress_race_gender = (
    violation_records_age20_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi dùng nhóm tuổi 20 năm:",
    round(violation_rate_age20_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi dùng nhóm tuổi 20 năm: 21.52 %

So gio lam

In [475]:
hours_counts = (
    data_anonymized["gio_lam_moi_tuan"]
    .value_counts()
    .head(15)
)

hours_counts

gio_lam_moi_tuan
40    15217
50     2819
45     1824
60     1475
35     1297
20     1224
30     1149
55      694
25      674
48      517
38      476
15      404
70      291
10      278
32      266
Name: count, dtype: int64

In [476]:
hours_start_20 = (
    (data_anonymized["gio_lam_moi_tuan"] - 1) // 20
) * 20 + 1

data_anonymized["gio_lam_nhom_20"] = (
    hours_start_20.astype(str)
    + "-"
    + (hours_start_20 + 19).astype(str)
)

data_anonymized[
    ["gio_lam_moi_tuan", "gio_lam_nhom_10", "gio_lam_nhom_20"]
].head(15)

    gio_lam_moi_tuan gio_lam_nhom_10 gio_lam_nhom_20
0                 40           31-40           21-40
1                 18           11-20            1-20
2                 40           31-40           21-40
3                 40           31-40           21-40
4                 40           31-40           21-40
5                 45           41-50           41-60
6                 40           31-40           21-40
7                 20           11-20            1-20
8                 40           31-40           21-40
9                 60           51-60           41-60
10                35           31-40           21-40
11                45           41-50           41-60
12                20           11-20            1-20
13                55           51-60           41-60
14                40           31-40           21-40

In [477]:
candidate_qi_age20_hours20_suppress_race_gender = (
    candidate_qi_age20_suppress_race_gender.copy()
)

candidate_qi_age20_hours20_suppress_race_gender[
    candidate_qi_age20_hours20_suppress_race_gender.index("gio_lam_nhom_10")
] = "gio_lam_nhom_20"

candidate_qi_age20_hours20_suppress_race_gender

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_20',
 'quoc_gia_nhom']

In [478]:
qi_group_sizes_age20_hours20_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_age20_hours20_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_age20_hours20_suppress_race_gender

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom          hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gio_lam_nhom_20  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                 21-40            Hoa_Ky              2
                                                               Khong_con_hon_nhan  Khong_ro              Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                 21-40            Hoa_Ky              1
                                                                                                                                                                     ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              21-40            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                21-40            Hoa_Ky              2
                                                                                                                                 41-60            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  81-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
Length: 4402, dtype: int64

In [479]:
k_min_age20_hours20_suppress_race_gender = (
    qi_group_sizes_age20_hours20_suppress_race_gender.min()
)

print(
    "k nhỏ nhất sau khi dùng nhóm tuổi 20 năm và giờ làm 20 giờ:",
    k_min_age20_hours20_suppress_race_gender
)

k nhỏ nhất sau khi dùng nhóm tuổi 20 năm và giờ làm 20 giờ: 1

In [480]:
unique_groups_age20_hours20_suppress_race_gender = (
    qi_group_sizes_age20_hours20_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi dùng tuổi 20 năm và giờ làm 20 giờ:",
    unique_groups_age20_hours20_suppress_race_gender
)

Số nhóm chỉ có 1 bản ghi sau khi dùng tuổi 20 năm và giờ làm 20 giờ: 2235

In [481]:
unique_rate_age20_hours20_suppress_race_gender = (
    unique_groups_age20_hours20_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi dùng tuổi 20 năm và giờ làm 20 giờ:",
    round(unique_rate_age20_hours20_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi dùng tuổi 20 năm và giờ làm 20 giờ: 6.86 %

In [482]:
violation_records_age20_hours20_suppress_race_gender = (
    qi_group_sizes_age20_hours20_suppress_race_gender[
        qi_group_sizes_age20_hours20_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi dùng tuổi 20 năm và giờ làm 20 giờ:",
    violation_records_age20_hours20_suppress_race_gender
)

Số bản ghi chưa đạt k=5 sau khi dùng tuổi 20 năm và giờ làm 20 giờ: 5343

In [483]:
violation_rate_age20_hours20_suppress_race_gender = (
    violation_records_age20_hours20_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi dùng tuổi 20 năm và giờ làm 20 giờ:",
    round(violation_rate_age20_hours20_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi dùng tuổi 20 năm và giờ làm 20 giờ: 16.41 %

Gop tiep hoc_van_nhom

In [484]:
education_group_counts = (
    data_anonymized["hoc_van_nhom"]
    .value_counts(dropna=False)
)

education_group_counts

hoc_van_nhom
Tot_nghiep_THPT         10501
Sau_THPT_Cao_dang        9740
Cu_nhan                  5355
Chua_tot_nghiep_THPT     4253
Sau_dai_hoc              2712
Name: count, dtype: int64

In [485]:
education_map_4 = {
    "Chua_tot_nghiep_THPT": "Chua_tot_nghiep_THPT",
    "Tot_nghiep_THPT": "Tot_nghiep_THPT",
    "Sau_THPT_Cao_dang": "Sau_THPT_Cao_dang",
    "Cu_nhan": "Dai_hoc_tro_len",
    "Sau_dai_hoc": "Dai_hoc_tro_len"
}

data_anonymized["hoc_van_nhom_4"] = (
    data_anonymized["hoc_van_nhom"]
    .map(education_map_4)
)

data_anonymized["hoc_van_nhom_4"].value_counts(dropna=False)

hoc_van_nhom_4
Tot_nghiep_THPT         10501
Sau_THPT_Cao_dang        9740
Dai_hoc_tro_len          8067
Chua_tot_nghiep_THPT     4253
Name: count, dtype: int64

In [486]:
candidate_qi_age20_hours20_edu4_suppress_race_gender = (
    candidate_qi_age20_hours20_suppress_race_gender.copy()
)

candidate_qi_age20_hours20_edu4_suppress_race_gender[
    candidate_qi_age20_hours20_edu4_suppress_race_gender.index("hoc_van_nhom")
] = "hoc_van_nhom_4"

candidate_qi_age20_hours20_edu4_suppress_race_gender

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_20',
 'quoc_gia_nhom']

In [487]:
qi_group_sizes_age20_hours20_edu4_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_age20_hours20_edu4_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_age20_hours20_edu4_suppress_race_gender

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom       nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gio_lam_nhom_20  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Chua_ket_hon        Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                 21-40            Hoa_Ky              2
                                                               Khong_con_hon_nhan  Khong_ro              Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
                                         Sau_THPT_Cao_dang     Chua_ket_hon        Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                 21-40            Hoa_Ky              1
                                                                                                                                                                     ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Chua_ket_hon        Dich_vu               Nguoi_than              21-40            Hoa_Ky              1
                                                               Da_ket_hon          Lao_dong_ky_thuat     Vo_chong                21-40            Hoa_Ky              2
                                                                                                                                 41-60            My_Latinh_Caribe    1
                                                               Khong_con_hon_nhan  Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  81-100           Hoa_Ky              1
                                                                                   Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
Length: 4076, dtype: int64

In [488]:
k_min_age20_hours20_edu4_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_suppress_race_gender.min()
)

print(
    "k nhỏ nhất sau khi gộp học vấn còn 4 nhóm:",
    k_min_age20_hours20_edu4_suppress_race_gender
)

k nhỏ nhất sau khi gộp học vấn còn 4 nhóm: 1

In [489]:
unique_groups_age20_hours20_edu4_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp học vấn còn 4 nhóm:",
    unique_groups_age20_hours20_edu4_suppress_race_gender
)

Số nhóm chỉ có 1 bản ghi sau khi gộp học vấn còn 4 nhóm: 2028

In [490]:
unique_rate_age20_hours20_edu4_suppress_race_gender = (
    unique_groups_age20_hours20_edu4_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp học vấn còn 4 nhóm:",
    round(unique_rate_age20_hours20_edu4_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp học vấn còn 4 nhóm: 6.23 %

In [491]:
violation_records_age20_hours20_edu4_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_suppress_race_gender[
        qi_group_sizes_age20_hours20_edu4_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gộp học vấn còn 4 nhóm:",
    violation_records_age20_hours20_edu4_suppress_race_gender
)

Số bản ghi chưa đạt k=5 sau khi gộp học vấn còn 4 nhóm: 4951

In [492]:
violation_rate_age20_hours20_edu4_suppress_race_gender = (
    violation_records_age20_hours20_edu4_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp học vấn còn 4 nhóm:",
    round(violation_rate_age20_hours20_edu4_suppress_race_gender, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp học vấn còn 4 nhóm: 15.21 %

Hon nhan nhom tiep

In [493]:
marital_group_counts = (
    data_anonymized["hon_nhan_nhom"]
    .value_counts(dropna=False)
)

marital_group_counts

hon_nhan_nhom
Da_ket_hon            15417
Chua_ket_hon          10683
Khong_con_hon_nhan     6461
Name: count, dtype: int64

In [494]:
marital_map_2 = {
    "Da_ket_hon": "Da_ket_hon",
    "Chua_ket_hon": "Khong_ket_hon_hien_tai",
    "Khong_con_hon_nhan": "Khong_ket_hon_hien_tai"
}

data_anonymized["hon_nhan_nhom_2"] = (
    data_anonymized["hon_nhan_nhom"]
    .map(marital_map_2)
)

data_anonymized["hon_nhan_nhom_2"].value_counts(dropna=False)

hon_nhan_nhom_2
Khong_ket_hon_hien_tai    17144
Da_ket_hon                15417
Name: count, dtype: int64

In [495]:
candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender = (
    candidate_qi_age20_hours20_edu4_suppress_race_gender.copy()
)

candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender[
    candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender.index("hon_nhan_nhom")
] = "hon_nhan_nhom_2"

candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_20',
 'quoc_gia_nhom']

In [496]:
qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom      quan_he_gia_dinh_nhom   gio_lam_nhom_20  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
                                                                                                             Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                     21-40            Hoa_Ky              2
                                         Sau_THPT_Cao_dang     Da_ket_hon              Nong_nghiep           Nguoi_than              61-80            Hoa_Ky              1
                                                               Khong_ket_hon_hien_tai  Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                                                         ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Da_ket_hon              Lao_dong_ky_thuat     Vo_chong                41-60            My_Latinh_Caribe    1
                                                               Khong_ket_hon_hien_tai  Dich_vu               Khong_quan_he_gia_dinh  21-40            Hoa_Ky              2
                                                                                                             Nguoi_than              21-40            Hoa_Ky              1
                                                                                       Lao_dong_ky_thuat     Khong_quan_he_gia_dinh  81-100           Hoa_Ky              1
                                                                                       Van_phong_kinh_doanh  Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
Length: 3539, dtype: int64

In [497]:
k_min_age20_hours20_edu4_marital2_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender.min()
)

print(
    "k nhỏ nhất sau khi gộp tình trạng hôn nhân còn 2 nhóm:",
    k_min_age20_hours20_edu4_marital2_suppress_race_gender
)

k nhỏ nhất sau khi gộp tình trạng hôn nhân còn 2 nhóm: 1

In [498]:
violation_records_age20_hours20_edu4_marital2_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender[
        qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gộp hôn nhân còn 2 nhóm:",
    violation_records_age20_hours20_edu4_marital2_suppress_race_gender
)

Số bản ghi chưa đạt k=5 sau khi gộp hôn nhân còn 2 nhóm: 4228

In [499]:
violation_rate_age20_hours20_edu4_marital2_suppress_race_gender = (
    violation_records_age20_hours20_edu4_marital2_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp hôn nhân còn 2 nhóm:",
    round(
        violation_rate_age20_hours20_edu4_marital2_suppress_race_gender,
        2
    ),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp hôn nhân còn 2 nhóm: 12.98 %

In [500]:
unique_groups_age20_hours20_edu4_marital2_suppress_race_gender = (
    qi_group_sizes_age20_hours20_edu4_marital2_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp hôn nhân còn 2 nhóm:",
    unique_groups_age20_hours20_edu4_marital2_suppress_race_gender
)

Số nhóm chỉ có 1 bản ghi sau khi gộp hôn nhân còn 2 nhóm: 1693

In [501]:
unique_rate_age20_hours20_edu4_marital2_suppress_race_gender = (
    unique_groups_age20_hours20_edu4_marital2_suppress_race_gender
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp hôn nhân còn 2 nhóm:",
    round(
        unique_rate_age20_hours20_edu4_marital2_suppress_race_gender,
        2
    ),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp hôn nhân còn 2 nhóm: 5.2 %

Nghe nghiep nhom moi

In [502]:
occupation_group_counts = (
    data_anonymized["nghe_nghiep_nhom"]
    .value_counts(dropna=False)
)

occupation_group_counts

nghe_nghiep_nhom
Van_phong_kinh_doanh    11486
Lao_dong_ky_thuat        9068
Chuyen_mon_ky_thuat      5068
Dich_vu                  4093
Khong_ro                 1843
Nong_nghiep               994
Quan_doi                    9
Name: count, dtype: int64

In [503]:
occupation_map_4 = {
    "Van_phong_kinh_doanh": "Van_phong_chuyen_mon",
    "Chuyen_mon_ky_thuat": "Van_phong_chuyen_mon",

    "Lao_dong_ky_thuat": "Lao_dong_truc_tiep",
    "Nong_nghiep": "Lao_dong_truc_tiep",

    "Dich_vu": "Dich_vu",
    "Quan_doi": "Dich_vu",

    "Khong_ro": "Khong_ro"
}

data_anonymized["nghe_nghiep_nhom_4"] = (
    data_anonymized["nghe_nghiep_nhom"]
    .map(occupation_map_4)
)

data_anonymized["nghe_nghiep_nhom_4"].value_counts(dropna=False)

nghe_nghiep_nhom_4
Van_phong_chuyen_mon    16554
Lao_dong_truc_tiep      10062
Dich_vu                  4102
Khong_ro                 1843
Name: count, dtype: int64

In [504]:
candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender = (
    candidate_qi_age20_hours20_edu4_marital2_suppress_race_gender.copy()
)

candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender[
    candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender.index(
        "nghe_nghiep_nhom"
    )
] = "nghe_nghiep_nhom_4"

candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'quan_he_gia_dinh_nhom',
 'gio_lam_nhom_20',
 'quoc_gia_nhom']

In [505]:
qi_group_sizes_age20_hours20_edu4_marital2_occ4_suppress_race_gender = (
    data_anonymized
    .groupby(
        candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender,
        dropna=False
    )
    .size()
)

qi_group_sizes_age20_hours20_edu4_marital2_occ4_suppress_race_gender

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    quan_he_gia_dinh_nhom   gio_lam_nhom_20  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
                                                                                                             Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                     21-40            Hoa_Ky              2
                                         Sau_THPT_Cao_dang     Da_ket_hon              Lao_dong_truc_tiep    Nguoi_than              61-80            Hoa_Ky              1
                                                               Khong_ket_hon_hien_tai  Khong_ro              Nguoi_than              1-20             Hoa_Ky              1
                                                                                                                                                                         ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Da_ket_hon              Lao_dong_truc_tiep    Vo_chong                41-60            My_Latinh_Caribe    1
                                                               Khong_ket_hon_hien_tai  Dich_vu               Khong_quan_he_gia_dinh  21-40            Hoa_Ky              2
                                                                                                             Nguoi_than              21-40            Hoa_Ky              1
                                                                                       Lao_dong_truc_tiep    Khong_quan_he_gia_dinh  81-100           Hoa_Ky              1
                                                                                       Van_phong_chuyen_mon  Khong_quan_he_gia_dinh  21-40            Hoa_Ky              1
Length: 2886, dtype: int64

In [506]:
violation_records_occ4 = (
    qi_group_sizes_age20_hours20_edu4_marital2_occ4_suppress_race_gender[
        qi_group_sizes_age20_hours20_edu4_marital2_occ4_suppress_race_gender < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gộp nghề nghiệp còn 4 nhóm:",
    violation_records_occ4
)

Số bản ghi chưa đạt k=5 sau khi gộp nghề nghiệp còn 4 nhóm: 3369

In [507]:
violation_rate_occ4 = (
    violation_records_occ4
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp nghề nghiệp còn 4 nhóm:",
    round(violation_rate_occ4, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp nghề nghiệp còn 4 nhóm: 10.35 %

In [508]:
unique_groups_occ4 = (
    qi_group_sizes_age20_hours20_edu4_marital2_occ4_suppress_race_gender == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp nghề nghiệp còn 4 nhóm:",
    unique_groups_occ4
)

Số nhóm chỉ có 1 bản ghi sau khi gộp nghề nghiệp còn 4 nhóm: 1307

In [509]:
unique_rate_occ4 = (
    unique_groups_occ4
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp nghề nghiệp còn 4 nhóm:",
    round(unique_rate_occ4, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp nghề nghiệp còn 4 nhóm: 4.01 %

In [510]:
relationship_group_counts = (
    data_anonymized["quan_he_gia_dinh_nhom"]
    .value_counts(dropna=False)
)

relationship_group_counts

quan_he_gia_dinh_nhom
Vo_chong                  14761
Khong_quan_he_gia_dinh    11751
Nguoi_than                 6049
Name: count, dtype: int64

Xoa quan he hon nhan ra khoir QI

In [511]:
candidate_qi_suppress_relationship = (
    candidate_qi_age20_hours20_edu4_marital2_occ4_suppress_race_gender.copy()
)

candidate_qi_suppress_relationship.remove(
    "quan_he_gia_dinh_nhom"
)

candidate_qi_suppress_relationship

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'gio_lam_nhom_20',
 'quoc_gia_nhom']

In [512]:
qi_group_sizes_suppress_relationship = (
    data_anonymized
    .groupby(
        candidate_qi_suppress_relationship,
        dropna=False
    )
    .size()
)

qi_group_sizes_suppress_relationship

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    gio_lam_nhom_20  quoc_gia_nhom
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              1-20             Hoa_Ky              1
                                                                                                             21-40            Hoa_Ky              3
                                         Sau_THPT_Cao_dang     Da_ket_hon              Lao_dong_truc_tiep    61-80            Hoa_Ky              1
                                                               Khong_ket_hon_hien_tai  Khong_ro              1-20             Hoa_Ky              1
                                                                                                             21-40            Hoa_Ky              1
                                                                                                                                                 ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Da_ket_hon              Lao_dong_truc_tiep    21-40            Hoa_Ky              2
                                                                                                             41-60            My_Latinh_Caribe    1
                                                               Khong_ket_hon_hien_tai  Dich_vu               21-40            Hoa_Ky              3
                                                                                       Lao_dong_truc_tiep    81-100           Hoa_Ky              1
                                                                                       Van_phong_chuyen_mon  21-40            Hoa_Ky              1
Length: 2171, dtype: int64

In [513]:
violation_records_suppress_relationship = (
    qi_group_sizes_suppress_relationship[
        qi_group_sizes_suppress_relationship < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi suppression quan hệ gia đình:",
    violation_records_suppress_relationship
)

Số bản ghi chưa đạt k=5 sau khi suppression quan hệ gia đình: 2428

In [514]:
violation_rate_suppress_relationship = (
    violation_records_suppress_relationship
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression quan hệ gia đình:",
    round(violation_rate_suppress_relationship, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi suppression quan hệ gia đình: 7.46 %

Nhom quoc gia

In [515]:
country_group_counts = (
    data_anonymized["quoc_gia_nhom"]
    .value_counts(dropna=False)
)

country_group_counts

quoc_gia_nhom
Hoa_Ky                    29184
My_Latinh_Caribe           1401
Chau_A_Thai_Binh_Duong      708
Khong_ro                    583
Chau_Au                     521
Bac_My_khac                 121
Trung_Dong                   43
Name: count, dtype: int64

In [516]:
country_map_3 = {
    "Hoa_Ky": "Hoa_Ky",

    "My_Latinh_Caribe": "Ngoai_Hoa_Ky",
    "Chau_A_Thai_Binh_Duong": "Ngoai_Hoa_Ky",
    "Chau_Au": "Ngoai_Hoa_Ky",
    "Bac_My_khac": "Ngoai_Hoa_Ky",
    "Trung_Dong": "Ngoai_Hoa_Ky",

    "Khong_ro": "Khong_ro"
}

data_anonymized["quoc_gia_nhom_3"] = (
    data_anonymized["quoc_gia_nhom"]
    .map(country_map_3)
)

data_anonymized["quoc_gia_nhom_3"].value_counts(dropna=False)

quoc_gia_nhom_3
Hoa_Ky          29184
Ngoai_Hoa_Ky     2794
Khong_ro          583
Name: count, dtype: int64

In [517]:
#Thay quoc_gia_nhom bang quoc_gia_nhom_3
candidate_qi_country3 = (
    candidate_qi_suppress_relationship.copy()
)

candidate_qi_country3[
    candidate_qi_country3.index("quoc_gia_nhom")
] = "quoc_gia_nhom_3"

candidate_qi_country3

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'gio_lam_nhom_20',
 'quoc_gia_nhom_3']

In [518]:
qi_group_sizes_country3 = (
    data_anonymized
    .groupby(
        candidate_qi_country3,
        dropna=False
    )
    .size()
)

qi_group_sizes_country3

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    gio_lam_nhom_20  quoc_gia_nhom_3
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              1-20             Hoa_Ky             1
                                                                                                             21-40            Hoa_Ky             3
                                         Sau_THPT_Cao_dang     Da_ket_hon              Lao_dong_truc_tiep    61-80            Hoa_Ky             1
                                                               Khong_ket_hon_hien_tai  Khong_ro              1-20             Hoa_Ky             1
                                                                                                             21-40            Hoa_Ky             1
                                                                                                                                                ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Da_ket_hon              Lao_dong_truc_tiep    21-40            Hoa_Ky             2
                                                                                                             41-60            Ngoai_Hoa_Ky       1
                                                               Khong_ket_hon_hien_tai  Dich_vu               21-40            Hoa_Ky             3
                                                                                       Lao_dong_truc_tiep    81-100           Hoa_Ky             1
                                                                                       Van_phong_chuyen_mon  21-40            Hoa_Ky             1
Length: 1786, dtype: int64

In [519]:
k_min_country3 = qi_group_sizes_country3.min()

print(
    "k nhỏ nhất sau khi gộp quốc gia còn 3 nhóm:",
    k_min_country3
)

k nhỏ nhất sau khi gộp quốc gia còn 3 nhóm: 1

In [520]:
violation_records_country3 = (
    qi_group_sizes_country3[
        qi_group_sizes_country3 < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gộp quốc gia còn 3 nhóm:",
    violation_records_country3
)

Số bản ghi chưa đạt k=5 sau khi gộp quốc gia còn 3 nhóm: 1863

In [521]:
violation_rate_country3 = (
    violation_records_country3
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp quốc gia còn 3 nhóm:",
    round(violation_rate_country3, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp quốc gia còn 3 nhóm: 5.72 %

In [522]:
unique_groups_country3 = (
    qi_group_sizes_country3 == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp quốc gia còn 3 nhóm:",
    unique_groups_country3
)

Số nhóm chỉ có 1 bản ghi sau khi gộp quốc gia còn 3 nhóm: 596

In [523]:
unique_rate_country3 = (
    unique_groups_country3
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp quốc gia còn 3 nhóm:",
    round(unique_rate_country3, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp quốc gia còn 3 nhóm: 1.83 %

Xem lai cong viec en gop tiep hay la laoi bo

In [524]:
workclass_group_counts = (
    data_anonymized["loai_cong_viec_nhom"]
    .value_counts(dropna=False)
)

workclass_group_counts

loai_cong_viec_nhom
Tu_nhan                      22696
Nha_nuoc                      4351
Tu_kinh_doanh                 3657
Khong_ro                      1836
Khong_luong_hoac_chua_lam       21
Name: count, dtype: int64

In [525]:
workclass_map_4 = {
    "Tu_nhan": "Tu_nhan",
    "Nha_nuoc": "Nha_nuoc",
    "Tu_kinh_doanh": "Tu_kinh_doanh",

    "Khong_ro": "Khac_hoac_khong_ro",
    "Khong_luong_hoac_chua_lam": "Khac_hoac_khong_ro"
}

data_anonymized["loai_cong_viec_nhom_4"] = (
    data_anonymized["loai_cong_viec_nhom"]
    .map(workclass_map_4)
)

data_anonymized[
    "loai_cong_viec_nhom_4"
].value_counts(dropna=False)

loai_cong_viec_nhom_4
Tu_nhan               22696
Nha_nuoc               4351
Tu_kinh_doanh          3657
Khac_hoac_khong_ro     1857
Name: count, dtype: int64

In [526]:
candidate_qi_work4 = candidate_qi_country3.copy()

candidate_qi_work4[
    candidate_qi_work4.index("loai_cong_viec_nhom")
] = "loai_cong_viec_nhom_4"

candidate_qi_work4

['tuoi_nhom_20',
 'loai_cong_viec_nhom_4',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'gio_lam_nhom_20',
 'quoc_gia_nhom_3']

In [527]:
qi_group_sizes_work4 = (
    data_anonymized
    .groupby(
        candidate_qi_work4,
        dropna=False
    )
    .size()
)

qi_group_sizes_work4

tuoi_nhom_20  loai_cong_viec_nhom_4  hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    gio_lam_nhom_20  quoc_gia_nhom_3
10-29         Khac_hoac_khong_ro     Chua_tot_nghiep_THPT  Da_ket_hon              Khong_ro              1-20             Ngoai_Hoa_Ky        1
                                                                                                         21-40            Hoa_Ky              5
                                                                                                                          Ngoai_Hoa_Ky        4
                                                                                                         41-60            Hoa_Ky              3
                                                           Khong_ket_hon_hien_tai  Khong_ro              1-20             Hoa_Ky             40
                                                                                                                                             ..
90-99         Tu_nhan                Tot_nghiep_THPT       Da_ket_hon              Lao_dong_truc_tiep    21-40            Hoa_Ky              2
                                                                                                         41-60            Ngoai_Hoa_Ky        1
                                                           Khong_ket_hon_hien_tai  Dich_vu               21-40            Hoa_Ky              3
                                                                                   Lao_dong_truc_tiep    81-100           Hoa_Ky              1
                                                                                   Van_phong_chuyen_mon  21-40            Hoa_Ky              1
Length: 1781, dtype: int64

In [528]:
k_min_work4 = qi_group_sizes_work4.min()

print(
    "k nhỏ nhất sau khi gộp loại công việc còn 4 nhóm:",
    k_min_work4
)

k nhỏ nhất sau khi gộp loại công việc còn 4 nhóm: 1

In [529]:
violation_records_work4 = (
    qi_group_sizes_work4[
        qi_group_sizes_work4 < k_required
    ].sum()
)

print(
    "Số bản ghi chưa đạt k=5 sau khi gộp loại công việc còn 4 nhóm:",
    violation_records_work4
)

Số bản ghi chưa đạt k=5 sau khi gộp loại công việc còn 4 nhóm: 1856

In [530]:
violation_rate_work4 = (
    violation_records_work4
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp loại công việc còn 4 nhóm:",
    round(violation_rate_work4, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp loại công việc còn 4 nhóm: 5.7 %

In [531]:
unique_groups_work4 = (
    qi_group_sizes_work4 == 1
).sum()

print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp loại công việc còn 4 nhóm:",
    unique_groups_work4
)

Số nhóm chỉ có 1 bản ghi sau khi gộp loại công việc còn 4 nhóm: 592

In [532]:
unique_rate_work4 = (
    unique_groups_work4
    / len(data_anonymized)
) * 100

print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp loại công việc còn 4 nhóm:",
    round(unique_rate_work4, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp loại công việc còn 4 nhóm: 1.82 %

In [533]:
#xem kichg thuoc tung k
violation_group_distribution_country3 = (
    qi_group_sizes_country3[
        qi_group_sizes_country3 < k_required
    ]
    .value_counts()
    .sort_index()
)

violation_group_distribution_country3

1    596
2    269
3    139
4     78
Name: count, dtype: int64

596 × 1 = 596

269 × 2 = 538

139 × 3 = 417

 78 × 4 = 312

----------------

Tổng      = 1,863 bản ghi

In [534]:
group_size_per_record_country3 = (
    data_anonymized
    .groupby(
        candidate_qi_country3,
        dropna=False
    )["tuoi"]
    .transform("size")
)

group_size_per_record_country3.head(15)

0       1
1      11
2      19
3      86
4     619
5      15
6      56
7       5
8      58
9       2
10    452
11     66
12      2
13    329
14     11
Name: tuoi, dtype: int64

In [535]:
#lay rieng pham vi k=5
violation_mask_country3 = (
    group_size_per_record_country3 < k_required
)

violating_records_country3 = (
    data_anonymized
    .loc[violation_mask_country3]
    .copy()
)

print(
    "Số bản ghi đang vi phạm k=5:",
    len(violating_records_country3)
)

Số bản ghi đang vi phạm k=5: 1863

Tính đên hiện tại

Tổng dữ liệu                 = 32,561 bản ghi

Bản ghi chưa đạt k=5         = 1,863

Tỷ lệ chưa đạt k=5           = 5.72%

Bản ghi còn lại đạt k >= 5   = 30,698

In [536]:
#Gan so luong ban ghi trong tung nhom QI tuong ung
#Cho tung ban ghi ptrong pham vi K
violating_records_country3["group_size"] = (
    group_size_per_record_country3[
        violation_mask_country3
    ]
)
#Chay 15 dong dau
violating_records_country3[
    candidate_qi_country3 + ["group_size"]
].head(15)

,tuoi_nhom_20,loai_cong_viec_nhom,hoc_van_nhom_4,hon_nhan_nhom_2,nghe_nghiep_nhom_4,gio_lam_nhom_20,quoc_gia_nhom_3,group_size
0,90-99,Khong_ro,Tot_nghiep_THPT,Khong_ket_hon_hien_tai,Khong_ro,21-40,Hoa_Ky,1
9,30-49,Tu_nhan,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,41-60,Khong_ro,2
12,50-69,Tu_nhan,Dai_hoc_tro_len,Khong_ket_hon_hien_tai,Dich_vu,1-20,Hoa_Ky,2
28,30-49,Tu_kinh_doanh,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,41-60,Hoa_Ky,4
29,30-49,Tu_nhan,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,81-100,Hoa_Ky,2
31,50-69,Tu_kinh_doanh,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,41-60,Hoa_Ky,4
46,70-89,Tu_nhan,Tot_nghiep_THPT,Da_ket_hon,Van_phong_chuyen_mon,41-60,Hoa_Ky,2
47,70-89,Tu_kinh_doanh,Tot_nghiep_THPT,Da_ket_hon,Lao_dong_truc_tiep,21-40,Ngoai_Hoa_Ky,2
51,50-69,Tu_nhan,Tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,61-80,Hoa_Ky,3
65,50-69,Tu_kinh_doanh,Sau_THPT_Cao_dang,Da_ket_hon,Lao_dong_truc_tiep,61-80,Khong_ro,1
87,30-49,Nha_nuoc,Dai_hoc_tro_len,Da_ket_hon,Van_phong_chuyen_mon,41-60,Khong_ro,4
124,70-89,Tu_kinh_doanh,Dai_hoc_tro_len,Da_ket_hon,Lao_dong_truc_tiep,1-20,Hoa_Ky,4
130,70-89,Tu_nhan,Tot_nghiep_THPT,Da_ket_hon,Van_phong_chuyen_mon,41-60,Hoa_Ky,2
132,50-69,Nha_nuoc,Dai_hoc_tro_len,Da_ket_hon,Van_phong_chuyen_mon,41-60,Khong_ro,2
148,30-49,Tu_nhan,Dai_hoc_tro_len,Da_ket_hon,Lao_dong_truc_tiep,21-40,Khong_ro,4

In [537]:
# Tạo bảng để so sánh tổng số bản ghi và số bản ghi vi phạm k=5 theo từng nhóm quốc gia
country_risk = pd.DataFrame({

    # Đếm tổng số bản ghi thuộc từng nhóm quốc gia
    "tong_ban_ghi": (
        data_anonymized["quoc_gia_nhom_3"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi đang vi phạm k=5 thuộc từng nhóm quốc gia
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["quoc_gia_nhom_3"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm quốc gia
country_risk["ty_le_vi_pham_%"] = (
    country_risk["ban_ghi_vi_pham_k5"]
    / country_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm về kiểu số nguyên để bảng dễ đọc hơn
country_risk["ban_ghi_vi_pham_k5"] = (
    country_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp các nhóm quốc gia từ tỷ lệ vi phạm cao nhất xuống thấp nhất
country_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                 tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
quoc_gia_nhom_3
Khong_ro                  583                 314        53.859348
Ngoai_Hoa_Ky             2794                 574        20.544023
Hoa_Ky                  29184                 975         3.340872

In [538]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm tuổi
age_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm tuổi trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["tuoi_nhom_20"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm tuổi
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["tuoi_nhom_20"]
        .value_counts(dropna=False)
    )

# Nếu nhóm tuổi nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm trong từng nhóm tuổi
age_risk["ty_le_vi_pham_%"] = (
    age_risk["ban_ghi_vi_pham_k5"]
    / age_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm về số nguyên để bảng dễ đọc
age_risk["ban_ghi_vi_pham_k5"] = (
    age_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm tuổi có tỷ lệ vi phạm cao nhất lên đầu
age_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

              tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
tuoi_nhom_20
90-99                   43                  43       100.000000
70-89                  586                 229        39.078498
50-69                 6433                 513         7.974506
10-29                 9711                 488         5.025229
30-49                15788                 590         3.737015

Nhóm 90–99 tuổi: 43 người, cả 43 đều vi phạm k=5 → rủi ro cao nhất.

Nhóm 70–89 tuổi: khoảng 39% vi phạm.
Các nhóm tuổi trẻ hơn có tỷ lệ vi phạm thấp hơn.

Ý nghĩa là: người càng thuộc nhóm tuổi hiếm thì càng dễ bị nhận diện hơn.

In [539]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm giờ làm việc
hours_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm giờ làm trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["gio_lam_nhom_20"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm giờ làm
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["gio_lam_nhom_20"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm giờ làm
hours_risk["ty_le_vi_pham_%"] = (
    hours_risk["ban_ghi_vi_pham_k5"]
    / hours_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm sang số nguyên để bảng dễ đọc
hours_risk["ban_ghi_vi_pham_k5"] = (
    hours_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm có tỷ lệ vi phạm cao nhất lên đầu
hours_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                 tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
gio_lam_nhom_20
81-100                    208                 152        73.076923
61-80                     902                 288        31.929047
1-20                     2928                 481        16.427596
41-60                    8471                 455         5.371267
21-40                   20052                 487         2.428685

81–100 giờ/tuần: 208 bản ghi, có 152 vi phạm → khoảng 73.08%, rủi ro cao nhất.

61–80 giờ: khoảng 31.93% vi phạm.

1–20 giờ: khoảng 16.43% vi phạm.

41–60 giờ: khoảng 5.37% vi phạm.

21–40 giờ: chỉ khoảng 2.43% vi phạm, an toàn hơn.

In [540]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm học vấn
education_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm học vấn trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["hoc_van_nhom_4"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm học vấn
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["hoc_van_nhom_4"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm học vấn
education_risk["ty_le_vi_pham_%"] = (
    education_risk["ban_ghi_vi_pham_k5"]
    / education_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm sang số nguyên để bảng dễ đọc
education_risk["ban_ghi_vi_pham_k5"] = (
    education_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm học vấn có tỷ lệ vi phạm cao nhất lên đầu
education_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                      tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
hoc_van_nhom_4
Chua_tot_nghiep_THPT          4253                 482        11.333177
Dai_hoc_tro_len               8067                 462         5.727036
Tot_nghiep_THPT              10501                 497         4.732883
Sau_THPT_Cao_dang             9740                 422         4.332649

Kết quả này cho thấy trình độ học vấn có ảnh hưởng đến mức vi phạm k=5, nhưng không mạnh bằng tuổi hay giờ làm.

Chua_tot_nghiep_THPT: 11.33% vi phạm → cao nhất.

Dai_hoc_tro_len: 5.73%

Tot_nghiep_THPT: 4.73%

In [541]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm tình trạng hôn nhân
marital_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm hôn nhân trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["hon_nhan_nhom_2"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm hôn nhân
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["hon_nhan_nhom_2"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm hôn nhân
marital_risk["ty_le_vi_pham_%"] = (
    marital_risk["ban_ghi_vi_pham_k5"]
    / marital_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm sang số nguyên để bảng dễ đọc
marital_risk["ban_ghi_vi_pham_k5"] = (
    marital_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm có tỷ lệ vi phạm cao nhất lên đầu
marital_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                        tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
hon_nhan_nhom_2
Da_ket_hon                     15417                 963         6.246351
Khong_ket_hon_hien_tai         17144                 900         5.249650

Từ kết quả cho ta thấy

tuổi 90-99 → 100% vi phạm

giờ làm 81-100 → 73.08%

hôn nhân → chỉ khoảng 5–6%

In [542]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm nghề nghiệp
occupation_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm nghề nghiệp trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["nghe_nghiep_nhom_4"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm nghề nghiệp
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["nghe_nghiep_nhom_4"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm nghề nghiệp
occupation_risk["ty_le_vi_pham_%"] = (
    occupation_risk["ban_ghi_vi_pham_k5"]
    / occupation_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm sang số nguyên để bảng dễ đọc
occupation_risk["ban_ghi_vi_pham_k5"] = (
    occupation_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm nghề nghiệp có tỷ lệ vi phạm cao nhất lên đầu
occupation_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                      tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
nghe_nghiep_nhom_4
Dich_vu                       4102                 491        11.969771
Khong_ro                      1843                 182         9.875203
Lao_dong_truc_tiep           10062                 541         5.376665
Van_phong_chuyen_mon         16554                 649         3.920503

Nhóm nghề Dich_vu có tỷ lệ vi phạm k=5 cao nhất (11.97%), trong khi nhóm Van_phong_chuyen_mon có tỷ lệ thấp nhất (3.92%). Nghề nghiệp có ảnh hưởng đến rủi ro tái nhận diện, nhưng mức độ không nghiêm trọng bằng các nhóm tuổi cao và số giờ làm rất cao.

In [543]:
# Tạo bảng phân tích rủi ro k=5 theo từng nhóm loại công việc
workclass_risk = pd.DataFrame({

    # Đếm tổng số bản ghi của từng nhóm loại công việc trong toàn bộ dữ liệu
    "tong_ban_ghi": (
        data_anonymized["loai_cong_viec_nhom"]
        .value_counts(dropna=False)
    ),

    # Đếm số bản ghi vi phạm k=5 thuộc từng nhóm loại công việc
    "ban_ghi_vi_pham_k5": (
        violating_records_country3["loai_cong_viec_nhom"]
        .value_counts(dropna=False)
    )

# Nếu nhóm nào không có bản ghi vi phạm thì thay giá trị thiếu bằng 0
}).fillna(0)


# Tính tỷ lệ phần trăm bản ghi vi phạm k=5 trong từng nhóm loại công việc
workclass_risk["ty_le_vi_pham_%"] = (
    workclass_risk["ban_ghi_vi_pham_k5"]
    / workclass_risk["tong_ban_ghi"]
) * 100


# Chuyển số bản ghi vi phạm sang số nguyên để bảng dễ đọc
workclass_risk["ban_ghi_vi_pham_k5"] = (
    workclass_risk["ban_ghi_vi_pham_k5"].astype(int)
)


# Sắp xếp nhóm có tỷ lệ vi phạm cao nhất lên đầu
workclass_risk.sort_values(
    "ty_le_vi_pham_%",
    ascending=False
)

                           tong_ban_ghi  ban_ghi_vi_pham_k5  ty_le_vi_pham_%
loai_cong_viec_nhom
Khong_luong_hoac_chua_lam            21                  21       100.000000
Tu_kinh_doanh                      3657                 562        15.367788
Khong_ro                           1836                 175         9.531590
Nha_nuoc                           4351                 383         8.802574
Tu_nhan                           22696                 722         3.181177

Nhóm không lương hoặc chưa làm có tỷ lệ vi phạm k=5 cao nhất, tiếp theo là nhóm tự kinh doanh. Nhóm tư nhân có tỷ lệ vi phạm thấp nhất.

In [544]:
# Tạo bảng tổng hợp nhóm có tỷ lệ vi phạm cao nhất của từng QI
risk_summary = pd.DataFrame({
    "QI": [
        "tuoi_nhom_20",
        "loai_cong_viec_nhom",
        "hoc_van_nhom_4",
        "hon_nhan_nhom_2",
        "nghe_nghiep_nhom_4",
        "gio_lam_nhom_20",
        "quoc_gia_nhom_3"
    ],

    # Lấy tên nhóm có tỷ lệ vi phạm cao nhất trong từng QI
    "nhom_rui_ro_cao_nhat": [
        age_risk["ty_le_vi_pham_%"].idxmax(),
        workclass_risk["ty_le_vi_pham_%"].idxmax(),
        education_risk["ty_le_vi_pham_%"].idxmax(),
        marital_risk["ty_le_vi_pham_%"].idxmax(),
        occupation_risk["ty_le_vi_pham_%"].idxmax(),
        hours_risk["ty_le_vi_pham_%"].idxmax(),
        country_risk["ty_le_vi_pham_%"].idxmax()
    ],

    # Lấy tỷ lệ vi phạm cao nhất tương ứng của từng QI
    "ty_le_vi_pham_cao_nhat_%": [
        age_risk["ty_le_vi_pham_%"].max(),
        workclass_risk["ty_le_vi_pham_%"].max(),
        education_risk["ty_le_vi_pham_%"].max(),
        marital_risk["ty_le_vi_pham_%"].max(),
        occupation_risk["ty_le_vi_pham_%"].max(),
        hours_risk["ty_le_vi_pham_%"].max(),
        country_risk["ty_le_vi_pham_%"].max()
    ]
})

# Sắp xếp QI có nhóm rủi ro cao nhất lên đầu
risk_summary = risk_summary.sort_values(
    "ty_le_vi_pham_cao_nhat_%",
    ascending=False
)

# Hiển thị bảng tổng hợp
risk_summary

                    QI       nhom_rui_ro_cao_nhat  ty_le_vi_pham_cao_nhat_%
0         tuoi_nhom_20                      90-99                100.000000
1  loai_cong_viec_nhom  Khong_luong_hoac_chua_lam                100.000000
5      gio_lam_nhom_20                     81-100                 73.076923
6      quoc_gia_nhom_3                   Khong_ro                 53.859348
4   nghe_nghiep_nhom_4                    Dich_vu                 11.969771
2       hoc_van_nhom_4       Chua_tot_nghiep_THPT                 11.333177
3      hon_nhan_nhom_2                 Da_ket_hon                  6.246351

In [545]:
# Thêm tổng số bản ghi của nhóm rủi ro cao nhất trong từng QI
risk_summary["tong_ban_ghi_nhom_rui_ro"] = [
    age_risk.loc[
        age_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    workclass_risk.loc[
        workclass_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    education_risk.loc[
        education_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    marital_risk.loc[
        marital_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    occupation_risk.loc[
        occupation_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    hours_risk.loc[
        hours_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ],
    country_risk.loc[
        country_risk["ty_le_vi_pham_%"].idxmax(),
        "tong_ban_ghi"
    ]
]


# Thêm số bản ghi vi phạm k=5 của nhóm rủi ro cao nhất trong từng QI
risk_summary["so_ban_ghi_vi_pham"] = [
    age_risk.loc[
        age_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    workclass_risk.loc[
        workclass_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    education_risk.loc[
        education_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    marital_risk.loc[
        marital_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    occupation_risk.loc[
        occupation_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    hours_risk.loc[
        hours_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ],
    country_risk.loc[
        country_risk["ty_le_vi_pham_%"].idxmax(),
        "ban_ghi_vi_pham_k5"
    ]
]


# Hiển thị lại bảng tổng hợp sau khi bổ sung quy mô nhóm rủi ro
risk_summary

,QI,nhom_rui_ro_cao_nhat,ty_le_vi_pham_cao_nhat_%,tong_ban_ghi_nhom_rui_ro,so_ban_ghi_vi_pham
0,tuoi_nhom_20,90-99,100.000000,43,43
1,loai_cong_viec_nhom,Khong_luong_hoac_chua_lam,100.000000,21,21
5,gio_lam_nhom_20,81-100,73.076923,4253,482
6,quoc_gia_nhom_3,Khong_ro,53.859348,15417,963
4,nghe_nghiep_nhom_4,Dich_vu,11.969771,4102,491
2,hoc_van_nhom_4,Chua_tot_nghiep_THPT,11.333177,208,152
3,hon_nhan_nhom_2,Da_ket_hon,6.246351,583,314

In [546]:
# Gom các bảng phân tích rủi ro vào một nơi để dễ xử lý
risk_tables = {
    "tuoi_nhom_20": age_risk,
    "loai_cong_viec_nhom": workclass_risk,
    "hoc_van_nhom_4": education_risk,
    "hon_nhan_nhom_2": marital_risk,
    "nghe_nghiep_nhom_4": occupation_risk,
    "gio_lam_nhom_20": hours_risk,
    "quoc_gia_nhom_3": country_risk
}


# Tạo danh sách để lưu kết quả tổng hợp của từng QI
risk_summary_rows = []


# Lần lượt phân tích từng QI
for qi_name, risk_table in risk_tables.items():

    # Tìm tên nhóm có tỷ lệ vi phạm k=5 cao nhất
    highest_risk_group = risk_table["ty_le_vi_pham_%"].idxmax()

    # Lấy đúng thông tin của nhóm rủi ro cao nhất và lưu vào danh sách
    risk_summary_rows.append({
        "QI": qi_name,
        "nhom_rui_ro_cao_nhat": highest_risk_group,
        "ty_le_vi_pham_cao_nhat_%": risk_table.loc[
            highest_risk_group,
            "ty_le_vi_pham_%"
        ],
        "tong_ban_ghi_nhom_rui_ro": int(
            risk_table.loc[
                highest_risk_group,
                "tong_ban_ghi"
            ]
        ),
        "so_ban_ghi_vi_pham": int(
            risk_table.loc[
                highest_risk_group,
                "ban_ghi_vi_pham_k5"
            ]
        )
    })


# Chuyển danh sách kết quả thành DataFrame
risk_summary = pd.DataFrame(risk_summary_rows)


# Sắp xếp QI có nhóm rủi ro cao nhất lên đầu
risk_summary = risk_summary.sort_values(
    "ty_le_vi_pham_cao_nhat_%",
    ascending=False
).reset_index(drop=True)


# Hiển thị bảng tổng hợp đã sửa đúng
risk_summary

,QI,nhom_rui_ro_cao_nhat,ty_le_vi_pham_cao_nhat_%,tong_ban_ghi_nhom_rui_ro,so_ban_ghi_vi_pham
0,tuoi_nhom_20,90-99,100.000000,43,43
1,loai_cong_viec_nhom,Khong_luong_hoac_chua_lam,100.000000,21,21
2,gio_lam_nhom_20,81-100,73.076923,208,152
3,quoc_gia_nhom_3,Khong_ro,53.859348,583,314
4,nghe_nghiep_nhom_4,Dich_vu,11.969771,4102,491
5,hoc_van_nhom_4,Chua_tot_nghiep_THPT,11.333177,4253,482
6,hon_nhan_nhom_2,Da_ket_hon,6.246351,15417,963

In [547]:
# Lấy tổng số bản ghi đang vi phạm k=5
tong_vi_pham_k5 = len(violating_records_country3)


# Tính tỷ lệ mỗi nhóm rủi ro cao đóng góp vào tổng số bản ghi vi phạm k=5
risk_summary["ty_le_dong_gop_vi_pham_%"] = (
    risk_summary["so_ban_ghi_vi_pham"]
    / tong_vi_pham_k5
) * 100


# Làm tròn tỷ lệ đến 2 chữ số thập phân để bảng dễ đọc
risk_summary["ty_le_dong_gop_vi_pham_%"] = (
    risk_summary["ty_le_dong_gop_vi_pham_%"]
    .round(2)
)


# Hiển thị lại bảng tổng hợp sau khi thêm tỷ lệ đóng góp vi phạm
risk_summary

,QI,nhom_rui_ro_cao_nhat,ty_le_vi_pham_cao_nhat_%,tong_ban_ghi_nhom_rui_ro,so_ban_ghi_vi_pham,ty_le_dong_gop_vi_pham_%
0,tuoi_nhom_20,90-99,100.000000,43,43,2.31
1,loai_cong_viec_nhom,Khong_luong_hoac_chua_lam,100.000000,21,21,1.13
2,gio_lam_nhom_20,81-100,73.076923,208,152,8.16
3,quoc_gia_nhom_3,Khong_ro,53.859348,583,314,16.85
4,nghe_nghiep_nhom_4,Dich_vu,11.969771,4102,491,26.36
5,hoc_van_nhom_4,Chua_tot_nghiep_THPT,11.333177,4253,482,25.87
6,hon_nhan_nhom_2,Da_ket_hon,6.246351,15417,963,51.69

In [548]:
# Tính tỷ lệ vi phạm k=5 chung của toàn bộ dataset
global_violation_rate = (
    len(violating_records_country3)
    / len(data_anonymized)
) * 100


# Tính xem nhóm rủi ro cao nhất của mỗi QI
# có tỷ lệ vi phạm cao gấp bao nhiêu lần mức trung bình toàn dataset
risk_summary["he_so_rui_ro_so_voi_toan_bo"] = (
    risk_summary["ty_le_vi_pham_cao_nhat_%"]
    / global_violation_rate
)


# Làm tròn hệ số rủi ro đến 2 chữ số thập phân để dễ đọc
risk_summary["he_so_rui_ro_so_voi_toan_bo"] = (
    risk_summary["he_so_rui_ro_so_voi_toan_bo"]
    .round(2)
)


# Hiển thị bảng tổng hợp sau khi bổ sung hệ số rủi ro
risk_summary

,QI,nhom_rui_ro_cao_nhat,ty_le_vi_pham_cao_nhat_%,tong_ban_ghi_nhom_rui_ro,so_ban_ghi_vi_pham,ty_le_dong_gop_vi_pham_%,he_so_rui_ro_so_voi_toan_bo
0,tuoi_nhom_20,90-99,100.000000,43,43,2.31,17.48
1,loai_cong_viec_nhom,Khong_luong_hoac_chua_lam,100.000000,21,21,1.13,17.48
2,gio_lam_nhom_20,81-100,73.076923,208,152,8.16,12.77
3,quoc_gia_nhom_3,Khong_ro,53.859348,583,314,16.85,9.41
4,nghe_nghiep_nhom_4,Dich_vu,11.969771,4102,491,26.36,2.09
5,hoc_van_nhom_4,Chua_tot_nghiep_THPT,11.333177,4253,482,25.87,1.98
6,hon_nhan_nhom_2,Da_ket_hon,6.246351,15417,963,51.69,1.09

In [549]:
# Tạo danh sách để lưu bảng rủi ro chi tiết của tất cả QI
all_risk_tables = []


# Gom tên QI và bảng phân tích rủi ro tương ứng
risk_tables = {
    "tuoi_nhom_20": age_risk,
    "loai_cong_viec_nhom": workclass_risk,
    "hoc_van_nhom_4": education_risk,
    "hon_nhan_nhom_2": marital_risk,
    "nghe_nghiep_nhom_4": occupation_risk,
    "gio_lam_nhom_20": hours_risk,
    "quoc_gia_nhom_3": country_risk
}


# Lần lượt xử lý từng bảng rủi ro
for qi_name, risk_table in risk_tables.items():

    # Đưa tên nhóm đang nằm ở index thành một cột bình thường
    temp = risk_table.reset_index()

    # Đổi tên cột đầu tiên thành tên dễ hiểu hơn
    temp = temp.rename(
        columns={temp.columns[0]: "nhom_gia_tri"}
    )

    # Gắn tên QI tương ứng cho từng dòng
    temp["QI"] = qi_name

    # Tính nhóm này có rủi ro cao gấp bao nhiêu lần mức chung của dataset
    temp["he_so_rui_ro"] = (
        temp["ty_le_vi_pham_%"]
        / global_violation_rate
    )

    # Lưu bảng vừa xử lý vào danh sách
    all_risk_tables.append(temp)


# Ghép tất cả bảng QI thành một bảng rủi ro chung
risk_detail_all = pd.concat(
    all_risk_tables,
    ignore_index=True
)


# Làm tròn hệ số rủi ro để bảng dễ đọc hơn
risk_detail_all["he_so_rui_ro"] = (
    risk_detail_all["he_so_rui_ro"]
    .round(2)
)


# Sắp xếp nhóm có hệ số rủi ro cao nhất lên đầu
risk_detail_all = risk_detail_all.sort_values(
    "he_so_rui_ro",
    ascending=False
)


# Hiển thị toàn bộ bảng rủi ro chi tiết
risk_detail_all

,nhom_gia_tri,tong_ban_ghi,ban_ghi_vi_pham_k5,ty_le_vi_pham_%,QI,he_so_rui_ro
5,Khong_luong_hoac_chua_lam,21,21,100.000000,loai_cong_viec_nhom,17.48
4,90-99,43,43,100.000000,tuoi_nhom_20,17.48
24,81-100,208,152,73.076923,gio_lam_nhom_20,12.77
27,Khong_ro,583,314,53.859348,quoc_gia_nhom_3,9.41
3,70-89,586,229,39.078498,tuoi_nhom_20,6.83
23,61-80,902,288,31.929047,gio_lam_nhom_20,5.58
26,Ngoai_Hoa_Ky,2794,574,20.544023,quoc_gia_nhom_3,3.59
20,1-20,2928,481,16.427596,gio_lam_nhom_20,2.87
8,Tu_kinh_doanh,3657,562,15.367788,loai_cong_viec_nhom,2.69
18,Dich_vu,4102,491,11.969771,nghe_nghiep_nhom_4,2.09
10,Chua_tot_nghiep_THPT,4253,482,11.333177,hoc_van_nhom_4,1.98
19,Khong_ro,1843,182,9.875203,nghe_nghiep_nhom_4,1.73
6,Khong_ro,1836,175,9.531590,loai_cong_viec_nhom,1.67
7,Nha_nuoc,4351,383,8.802574,loai_cong_viec_nhom,1.54
2,50-69,6433,513,7.974506,tuoi_nhom_20,1.39
14,Da_ket_hon,15417,963,6.246351,hon_nhan_nhom_2,1.09
11,Dai_hoc_tro_len,8067,462,5.727036,hoc_van_nhom_4,1.00
17,Lao_dong_truc_tiep,10062,541,5.376665,nghe_nghiep_nhom_4,0.94
22,41-60,8471,455,5.371267,gio_lam_nhom_20,0.94
15,Khong_ket_hon_hien_tai,17144,900,5.249650,hon_nhan_nhom_2,0.92
0,10-29,9711,488,5.025229,tuoi_nhom_20,0.88
13,Tot_nghiep_THPT,10501,497,4.732883,hoc_van_nhom_4,0.83
12,Sau_THPT_Cao_dang,9740,422,4.332649,hoc_van_nhom_4,0.76
16,Van_phong_chuyen_mon,16554,649,3.920503,nghe_nghiep_nhom_4,0.69
1,30-49,15788,590,3.737015,tuoi_nhom_20,0.65
25,Hoa_Ky,29184,975,3.340872,quoc_gia_nhom_3,0.58
9,Tu_nhan,22696,722,3.181177,loai_cong_viec_nhom,0.56
21,21-40,20052,487,2.428685,gio_lam_nhom_20,0.42

In [550]:
# Tính tỷ lệ vi phạm k=5 chung của toàn bộ dataset dưới dạng số thập phân
global_violation_rate_decimal = (
    len(violating_records_country3)
    / len(data_anonymized)
)


# Tính số bản ghi vi phạm dự kiến nếu mỗi nhóm chỉ có
# mức rủi ro bằng đúng mức trung bình của toàn bộ dataset
risk_detail_all["so_vi_pham_ky_vong"] = (
    risk_detail_all["tong_ban_ghi"]
    * global_violation_rate_decimal
)


# Tính số bản ghi vi phạm vượt quá mức dự kiến của toàn dataset
risk_detail_all["vi_pham_du_thua"] = (
    risk_detail_all["ban_ghi_vi_pham_k5"]
    - risk_detail_all["so_vi_pham_ky_vong"]
)


# Làm tròn các giá trị để bảng dễ đọc hơn
risk_detail_all["so_vi_pham_ky_vong"] = (
    risk_detail_all["so_vi_pham_ky_vong"].round(2)
)

risk_detail_all["vi_pham_du_thua"] = (
    risk_detail_all["vi_pham_du_thua"].round(2)
)


# Sắp xếp để xem những nhóm có số vi phạm dư thừa lớn nhất
risk_detail_all.sort_values(
    "vi_pham_du_thua",
    ascending=False
).head(15)

,nhom_gia_tri,tong_ban_ghi,ban_ghi_vi_pham_k5,ty_le_vi_pham_%,QI,he_so_rui_ro,so_vi_pham_ky_vong,vi_pham_du_thua
26,Ngoai_Hoa_Ky,2794,574,20.544023,quoc_gia_nhom_3,3.59,159.86,414.14
8,Tu_kinh_doanh,3657,562,15.367788,loai_cong_viec_nhom,2.69,209.24,352.76
20,1-20,2928,481,16.427596,gio_lam_nhom_20,2.87,167.53,313.47
27,Khong_ro,583,314,53.859348,quoc_gia_nhom_3,9.41,33.36,280.64
18,Dich_vu,4102,491,11.969771,nghe_nghiep_nhom_4,2.09,234.70,256.30
10,Chua_tot_nghiep_THPT,4253,482,11.333177,hoc_van_nhom_4,1.98,243.34,238.66
23,61-80,902,288,31.929047,gio_lam_nhom_20,5.58,51.61,236.39
3,70-89,586,229,39.078498,tuoi_nhom_20,6.83,33.53,195.47
2,50-69,6433,513,7.974506,tuoi_nhom_20,1.39,368.07,144.93
24,81-100,208,152,73.076923,gio_lam_nhom_20,12.77,11.90,140.10
7,Nha_nuoc,4351,383,8.802574,loai_cong_viec_nhom,1.54,248.95,134.05
14,Da_ket_hon,15417,963,6.246351,hon_nhan_nhom_2,1.09,882.09,80.91
19,Khong_ro,1843,182,9.875203,nghe_nghiep_nhom_4,1.73,105.45,76.55
6,Khong_ro,1836,175,9.531590,loai_cong_viec_nhom,1.67,105.05,69.95
4,90-99,43,43,100.000000,tuoi_nhom_20,17.48,2.46,40.54

In [551]:
# Chỉ giữ phần vi phạm dư thừa lớn hơn 0
# Nếu một nhóm có rủi ro thấp hơn mức trung bình thì không tính vào phần rủi ro dư thừa
risk_detail_all["vi_pham_du_thua_duong"] = (
    risk_detail_all["vi_pham_du_thua"]
    .clip(lower=0)
)


# Cộng tổng số vi phạm dư thừa của các nhóm thuộc cùng một QI
qi_risk_priority = (
    risk_detail_all
    .groupby("QI")["vi_pham_du_thua_duong"]
    .sum()
    .reset_index()
)


# Đổi tên cột để ý nghĩa dễ hiểu hơn
qi_risk_priority = qi_risk_priority.rename(
    columns={
        "vi_pham_du_thua_duong": "tong_vi_pham_du_thua"
    }
)


# Làm tròn kết quả đến 2 chữ số thập phân
qi_risk_priority["tong_vi_pham_du_thua"] = (
    qi_risk_priority["tong_vi_pham_du_thua"]
    .round(2)
)


# Sắp xếp QI có mức rủi ro tập trung lớn nhất lên đầu
qi_risk_priority = qi_risk_priority.sort_values(
    "tong_vi_pham_du_thua",
    ascending=False
)


# Hiển thị bảng xếp hạng QI cần ưu tiên phân tích
qi_risk_priority

                    QI  tong_vi_pham_du_thua
5      quoc_gia_nhom_3                694.78
0      gio_lam_nhom_20                689.96
3  loai_cong_viec_nhom                576.56
6         tuoi_nhom_20                380.94
4   nghe_nghiep_nhom_4                332.85
1       hoc_van_nhom_4                239.10
2      hon_nhan_nhom_2                 80.91

In [552]:
# Tạo quy tắc generalization mới cho giờ làm việc
# Chỉ gộp hai nhóm giờ làm cao 61-80 và 81-100 thành 61-100
hours_map_4 = {
    "1-20": "1-20",
    "21-40": "21-40",
    "41-60": "41-60",
    "61-80": "61-100",
    "81-100": "61-100"
}


# Tạo cột giờ làm mới theo mức generalization 4 nhóm
data_anonymized["gio_lam_nhom_4"] = (
    data_anonymized["gio_lam_nhom_20"]
    .map(hours_map_4)
)


# Đếm số bản ghi của từng nhóm mới để kiểm tra việc gộp đã đúng
data_anonymized["gio_lam_nhom_4"].value_counts(dropna=False)

gio_lam_nhom_4
21-40     20052
41-60      8471
1-20       2928
61-100     1110
Name: count, dtype: int64

In [553]:
# Sao chép bộ QI hiện tại để giữ nguyên phương án cũ
candidate_qi_hours4 = candidate_qi_country3.copy()


# Tìm vị trí của cột giờ làm cũ và thay bằng cột giờ làm mới
candidate_qi_hours4[
    candidate_qi_hours4.index("gio_lam_nhom_20")
] = "gio_lam_nhom_4"


# Hiển thị bộ QI mới để kiểm tra việc thay thế đã đúng
candidate_qi_hours4

['tuoi_nhom_20',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'gio_lam_nhom_4',
 'quoc_gia_nhom_3']

Kiểm tra bản g

In [554]:
# Gom các bản ghi có cùng 7 QI của phương án giờ làm mới vào cùng một nhóm
qi_group_sizes_hours4 = (
    data_anonymized
    .groupby(
        candidate_qi_hours4,
        dropna=False
    )
    .size()
)


# Hiển thị kích thước của các equivalence class vừa tạo
qi_group_sizes_hours4

tuoi_nhom_20  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    gio_lam_nhom_4  quoc_gia_nhom_3
10-29         Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              1-20            Hoa_Ky             1
                                                                                                             21-40           Hoa_Ky             3
                                         Sau_THPT_Cao_dang     Da_ket_hon              Lao_dong_truc_tiep    61-100          Hoa_Ky             1
                                                               Khong_ket_hon_hien_tai  Khong_ro              1-20            Hoa_Ky             1
                                                                                                             21-40           Hoa_Ky             1
                                                                                                                                               ..
90-99         Tu_nhan                    Tot_nghiep_THPT       Da_ket_hon              Lao_dong_truc_tiep    21-40           Hoa_Ky             2
                                                                                                             41-60           Ngoai_Hoa_Ky       1
                                                               Khong_ket_hon_hien_tai  Dich_vu               21-40           Hoa_Ky             3
                                                                                       Lao_dong_truc_tiep    61-100          Hoa_Ky             1
                                                                                       Van_phong_chuyen_mon  21-40           Hoa_Ky             1
Length: 1710, dtype: int64

In [555]:
# Tìm kích thước nhỏ nhất trong tất cả equivalence class của strategy mới
k_min_hours4 = qi_group_sizes_hours4.min()


# Hiển thị k nhỏ nhất để kiểm tra toàn bộ dữ liệu đã đạt k=5 hay chưa
print(
    "k nhỏ nhất sau khi gộp giờ làm cao thành 61-100:",
    k_min_hours4
)

k nhỏ nhất sau khi gộp giờ làm cao thành 61-100: 1

Điều này có nghĩa là sau khi gộp 61-80 và 81-100 thành 61-100, vẫn còn ít nhất một equivalence class chỉ có 1 bản ghi. Nhưng chưa thể kết luận strategy này không hiệu quả, vì k_min chỉ nhìn đúng nhóm nhỏ nhất. Trong khi số equivalence class đã giảm từ 1,786 xuống 1,710, nên đã có dấu hiệu các bản ghi được gom lại tốt hơn.

In [556]:
# Lấy các equivalence class có kích thước nhỏ hơn k=5
# Đây là những nhóm vẫn chưa đạt yêu cầu k-anonymity đang thử nghiệm
violation_groups_hours4 = (
    qi_group_sizes_hours4[
        qi_group_sizes_hours4 < k_required
    ]
)


# Cộng số bản ghi nằm trong tất cả các nhóm chưa đạt k=5
violation_records_hours4 = (
    violation_groups_hours4.sum()
)


# Hiển thị số bản ghi vẫn chưa đạt k=5 của strategy giờ làm mới
print(
    "Số bản ghi chưa đạt k=5 sau khi gộp giờ làm cao thành 61-100:",
    violation_records_hours4
)

Số bản ghi chưa đạt k=5 sau khi gộp giờ làm cao thành 61-100: 1747

In [557]:
# Tính tỷ lệ phần trăm bản ghi vẫn chưa đạt k=5 sau strategy giờ làm mới
violation_rate_hours4 = (
    violation_records_hours4
    / len(data_anonymized)
) * 100


# Hiển thị tỷ lệ vi phạm và làm tròn đến 2 chữ số thập phân
print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp giờ làm cao thành 61-100:",
    round(violation_rate_hours4, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp giờ làm cao thành 61-100: 5.37 %

In [558]:
# Đếm số equivalence class chỉ có đúng 1 bản ghi
# Đây là những bản ghi có mức cô lập cao nhất trong dữ liệu
unique_groups_hours4 = (
    qi_group_sizes_hours4 == 1
).sum()


# Hiển thị số nhóm chỉ có 1 bản ghi sau strategy giờ làm mới
print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp giờ làm cao thành 61-100:",
    unique_groups_hours4
)

Số nhóm chỉ có 1 bản ghi sau khi gộp giờ làm cao thành 61-100: 549

Trước strategy mới: 596 nhóm chỉ có 1 bản ghi

Sau strategy mới:   549 nhóm chỉ có 1 bản ghi

Giảm:                47 nhóm cô lập

In [559]:
# Tính tỷ lệ phần trăm bản ghi đang nằm một mình trong equivalence class
unique_rate_hours4 = (
    unique_groups_hours4
    / len(data_anonymized)
) * 100


# Hiển thị tỷ lệ cô lập và làm tròn đến 2 chữ số thập phân
print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp giờ làm cao thành 61-100:",
    round(unique_rate_hours4, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp giờ làm cao thành 61-100: 1.69 %

Kết luận

Trước strategy giờ làm mới:
- k_min = 1
- Số nhóm cô lập = 596
- Tỷ lệ cô lập = 1.83%
- Bản ghi chưa đạt k=5 = 1,863
- Tỷ lệ vi phạm k=5 = 5.72%


Sau khi gộp 61-80 và 81-100 → 61-100:
- k_min = 1
- Số nhóm cô lập = 549
- Tỷ lệ cô lập = 1.69%
- Bản ghi chưa đạt k=5 = 1,747
- Tỷ lệ vi phạm k=5 = 5.37%

In [560]:
# Tạo bảng so sánh kết quả privacy giữa strategy cũ và strategy giờ làm mới
strategy_privacy_comparison = pd.DataFrame({

    # Đặt tên cho từng phương án để sau này dễ theo dõi
    "strategy": [
        "Country3_Hours20",
        "Country3_Hours4"
    ],

    # Số equivalence class của từng phương án
    "so_equivalence_class": [
        len(qi_group_sizes_country3),
        len(qi_group_sizes_hours4)
    ],

    # Giá trị k nhỏ nhất của từng phương án
    "k_min": [
        qi_group_sizes_country3.min(),
        qi_group_sizes_hours4.min()
    ],

    # Số nhóm chỉ có đúng 1 bản ghi
    "so_nhom_co_lap": [
        unique_groups_country3,
        unique_groups_hours4
    ],

    # Tỷ lệ bản ghi bị cô lập
    "ty_le_co_lap_%": [
        unique_rate_country3,
        unique_rate_hours4
    ],

    # Số bản ghi đang nằm trong nhóm có kích thước nhỏ hơn 5
    "so_ban_ghi_vi_pham_k5": [
        violation_records_country3,
        violation_records_hours4
    ],

    # Tỷ lệ bản ghi chưa đạt k=5
    "ty_le_vi_pham_k5_%": [
        violation_rate_country3,
        violation_rate_hours4
    ]
})


# Làm tròn các cột phần trăm để bảng dễ đọc hơn
strategy_privacy_comparison[
    ["ty_le_co_lap_%", "ty_le_vi_pham_k5_%"]
] = (
    strategy_privacy_comparison[
        ["ty_le_co_lap_%", "ty_le_vi_pham_k5_%"]
    ].round(2)
)


# Hiển thị bảng so sánh hai strategy
strategy_privacy_comparison

,strategy,so_equivalence_class,k_min,so_nhom_co_lap,ty_le_co_lap_%,so_ban_ghi_vi_pham_k5,ty_le_vi_pham_k5_%
0,Country3_Hours20,1786,1,596,1.83,1863,5.72
1,Country3_Hours4,1710,1,549,1.69,1747,5.37

In [561]:
# Tạo quy tắc generalization mới cho nhóm tuổi
# Giữ nguyên các nhóm tuổi phổ biến và chỉ gộp hai nhóm tuổi cao
age_map_high = {
    "10-29": "10-29",
    "30-49": "30-49",
    "50-69": "50-69",
    "70-89": "70-99",
    "90-99": "70-99"
}


# Tạo cột tuổi mới theo strategy generalization vùng tuổi cao
data_anonymized["tuoi_nhom_high"] = (
    data_anonymized["tuoi_nhom_20"]
    .map(age_map_high)
)


# Đếm số bản ghi của từng nhóm tuổi mới để kiểm tra việc gộp
data_anonymized["tuoi_nhom_high"].value_counts(dropna=False)

tuoi_nhom_high
30-49    15788
10-29     9711
50-69     6433
70-99      629
Name: count, dtype: int64

In [562]:
# Sao chép strategy giờ làm mới để giữ nguyên phương án cũ
candidate_qi_hours4_agehigh = candidate_qi_hours4.copy()


# Tìm vị trí của cột tuổi cũ và thay bằng cột tuổi mới đã gộp 70-99
candidate_qi_hours4_agehigh[
    candidate_qi_hours4_agehigh.index("tuoi_nhom_20")
] = "tuoi_nhom_high"


# Hiển thị bộ QI mới để kiểm tra việc thay thế đã đúng
candidate_qi_hours4_agehigh

['tuoi_nhom_high',
 'loai_cong_viec_nhom',
 'hoc_van_nhom_4',
 'hon_nhan_nhom_2',
 'nghe_nghiep_nhom_4',
 'gio_lam_nhom_4',
 'quoc_gia_nhom_3']

In [563]:
# Gom các bản ghi có cùng 7 QI của strategy mới vào cùng một equivalence class
qi_group_sizes_hours4_agehigh = (
    data_anonymized
    .groupby(
        candidate_qi_hours4_agehigh,
        dropna=False
    )
    .size()
)


# Hiển thị kích thước của từng equivalence class sau khi gộp nhóm tuổi cao
qi_group_sizes_hours4_agehigh

tuoi_nhom_high  loai_cong_viec_nhom        hoc_van_nhom_4        hon_nhan_nhom_2         nghe_nghiep_nhom_4    gio_lam_nhom_4  quoc_gia_nhom_3
10-29           Khong_luong_hoac_chua_lam  Chua_tot_nghiep_THPT  Khong_ket_hon_hien_tai  Khong_ro              1-20            Hoa_Ky              1
                                                                                                               21-40           Hoa_Ky              3
                                           Sau_THPT_Cao_dang     Da_ket_hon              Lao_dong_truc_tiep    61-100          Hoa_Ky              1
                                                                 Khong_ket_hon_hien_tai  Khong_ro              1-20            Hoa_Ky              1
                                                                                                               21-40           Hoa_Ky              1
                                                                                                                                                  ..
70-99           Tu_nhan                    Tot_nghiep_THPT       Khong_ket_hon_hien_tai  Dich_vu               41-60           Hoa_Ky              1
                                                                                         Lao_dong_truc_tiep    1-20            Hoa_Ky              2
                                                                                                               61-100          Hoa_Ky              1
                                                                                         Van_phong_chuyen_mon  1-20            Hoa_Ky             11
                                                                                                               21-40           Hoa_Ky              7
Length: 1681, dtype: int64

In [564]:
# Tìm kích thước nhỏ nhất trong tất cả equivalence class của strategy mới
k_min_hours4_agehigh = (
    qi_group_sizes_hours4_agehigh.min()
)


# Hiển thị k nhỏ nhất để kiểm tra còn nhóm chỉ có ít người hay không
print(
    "k nhỏ nhất sau khi gộp giờ làm cao và tuổi cao:",
    k_min_hours4_agehigh
)

k nhỏ nhất sau khi gộp giờ làm cao và tuổi cao: 1

In [565]:
# Lấy các equivalence class có kích thước nhỏ hơn 5
# Đây là những nhóm vẫn chưa đạt mục tiêu k=5
violation_groups_hours4_agehigh = (
    qi_group_sizes_hours4_agehigh[
        qi_group_sizes_hours4_agehigh < k_required
    ]
)


# Cộng số bản ghi nằm trong tất cả các nhóm chưa đạt k=5
violation_records_hours4_agehigh = (
    violation_groups_hours4_agehigh.sum()
)


# Hiển thị số bản ghi còn vi phạm k=5 của strategy mới
print(
    "Số bản ghi chưa đạt k=5 sau khi gộp giờ làm cao và tuổi cao:",
    violation_records_hours4_agehigh
)

Số bản ghi chưa đạt k=5 sau khi gộp giờ làm cao và tuổi cao: 1713

Strategy trước: Hours4
- Bản ghi chưa đạt k=5: 1,747

Strategy mới: Hours4 + AgeHigh
- Bản ghi chưa đạt k=5: 1,713

Giảm thêm:
1,747 - 1,713 = 34 bản ghi

In [566]:
# Tính tỷ lệ phần trăm bản ghi vẫn chưa đạt k=5 của strategy mới
violation_rate_hours4_agehigh = (
    violation_records_hours4_agehigh
    / len(data_anonymized)
) * 100


# Hiển thị tỷ lệ vi phạm và làm tròn đến 2 chữ số thập phân
print(
    "Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp giờ làm cao và tuổi cao:",
    round(violation_rate_hours4_agehigh, 2),
    "%"
)

Tỷ lệ bản ghi chưa đạt k=5 sau khi gộp giờ làm cao và tuổi cao: 5.26 %

In [567]:
# Đếm số equivalence class chỉ có đúng 1 bản ghi
# Đây là những bản ghi có mức cô lập và rủi ro tái nhận diện cao nhất
unique_groups_hours4_agehigh = (
    qi_group_sizes_hours4_agehigh == 1
).sum()


# Hiển thị số nhóm cô lập của strategy giờ làm + tuổi cao
print(
    "Số nhóm chỉ có 1 bản ghi sau khi gộp giờ làm cao và tuổi cao:",
    unique_groups_hours4_agehigh
)

Số nhóm chỉ có 1 bản ghi sau khi gộp giờ làm cao và tuổi cao: 519

In [568]:
# Tính tỷ lệ phần trăm bản ghi đang nằm một mình trong equivalence class
unique_rate_hours4_agehigh = (
    unique_groups_hours4_agehigh
    / len(data_anonymized)
) * 100


# Hiển thị tỷ lệ cô lập và làm tròn đến 2 chữ số thập phân
print(
    "Tỷ lệ bản ghi bị cô lập sau khi gộp giờ làm cao và tuổi cao:",
    round(unique_rate_hours4_agehigh, 2),
    "%"
)

Tỷ lệ bản ghi bị cô lập sau khi gộp giờ làm cao và tuổi cao: 1.59 %

In [569]:
# Tạo lại bảng so sánh privacy của 3 strategy đã thử nghiệm
strategy_privacy_comparison = pd.DataFrame({

    # Đặt tên cho từng strategy để dễ phân biệt
    "strategy": [
        "Country3_Hours20",
        "Country3_Hours4",
        "Country3_Hours4_AgeHigh"
    ],

    # Số equivalence class của từng strategy
    "so_equivalence_class": [
        len(qi_group_sizes_country3),
        len(qi_group_sizes_hours4),
        len(qi_group_sizes_hours4_agehigh)
    ],

    # Giá trị k nhỏ nhất của từng strategy
    "k_min": [
        qi_group_sizes_country3.min(),
        qi_group_sizes_hours4.min(),
        qi_group_sizes_hours4_agehigh.min()
    ],

    # Số nhóm chỉ có đúng 1 bản ghi
    "so_nhom_co_lap": [
        unique_groups_country3,
        unique_groups_hours4,
        unique_groups_hours4_agehigh
    ],

    # Tỷ lệ phần trăm bản ghi bị cô lập
    "ty_le_co_lap_%": [
        unique_rate_country3,
        unique_rate_hours4,
        unique_rate_hours4_agehigh
    ],

    # Số bản ghi đang nằm trong equivalence class có kích thước nhỏ hơn 5
    "so_ban_ghi_vi_pham_k5": [
        violation_records_country3,
        violation_records_hours4,
        violation_records_hours4_agehigh
    ],

    # Tỷ lệ phần trăm bản ghi chưa đạt k=5
    "ty_le_vi_pham_k5_%": [
        violation_rate_country3,
        violation_rate_hours4,
        violation_rate_hours4_agehigh
    ]
})


# Làm tròn các cột phần trăm đến 2 chữ số thập phân để dễ đọc
strategy_privacy_comparison[
    ["ty_le_co_lap_%", "ty_le_vi_pham_k5_%"]
] = (
    strategy_privacy_comparison[
        ["ty_le_co_lap_%", "ty_le_vi_pham_k5_%"]
    ].round(2)
)


# Hiển thị bảng so sánh 3 strategy
strategy_privacy_comparison

,strategy,so_equivalence_class,k_min,so_nhom_co_lap,ty_le_co_lap_%,so_ban_ghi_vi_pham_k5,ty_le_vi_pham_k5_%
0,Country3_Hours20,1786,1,596,1.83,1863,5.72
1,Country3_Hours4,1710,1,549,1.69,1747,5.37
2,Country3_Hours4_AgeHigh,1681,1,519,1.59,1713,5.26

In [570]:
# Lấy số bản ghi vi phạm k=5 của strategy gốc làm mốc so sánh
baseline_violation_records = strategy_privacy_comparison.loc[
    0,
    "so_ban_ghi_vi_pham_k5"
]


# Lấy số nhóm cô lập của strategy gốc làm mốc so sánh
baseline_unique_groups = strategy_privacy_comparison.loc[
    0,
    "so_nhom_co_lap"
]


# Tính mỗi strategy đã giảm được bao nhiêu bản ghi vi phạm k=5 so với strategy gốc
strategy_privacy_comparison["giam_ban_ghi_vi_pham_k5"] = (
    baseline_violation_records
    - strategy_privacy_comparison["so_ban_ghi_vi_pham_k5"]
)


# Tính mỗi strategy đã giảm được bao nhiêu nhóm cô lập so với strategy gốc
strategy_privacy_comparison["giam_nhom_co_lap"] = (
    baseline_unique_groups
    - strategy_privacy_comparison["so_nhom_co_lap"]
)


# Hiển thị lại bảng so sánh sau khi thêm mức cải thiện
strategy_privacy_comparison

,strategy,so_equivalence_class,k_min,so_nhom_co_lap,ty_le_co_lap_%,so_ban_ghi_vi_pham_k5,ty_le_vi_pham_k5_%,giam_ban_ghi_vi_pham_k5,giam_nhom_co_lap
0,Country3_Hours20,1786,1,596,1.83,1863,5.72,0,0
1,Country3_Hours4,1710,1,549,1.69,1747,5.37,116,47
2,Country3_Hours4_AgeHigh,1681,1,519,1.59,1713,5.26,150,77

In [571]:
# Tạo một nơi lưu các strategy ẩn danh đã xây dựng
# Mỗi strategy gồm tên phương án và danh sách QI tương ứng
strategies = {
    "Country3_Hours20": candidate_qi_country3,
    "Country3_Hours4": candidate_qi_hours4,
    "Country3_Hours4_AgeHigh": candidate_qi_hours4_agehigh
}


# Hiển thị từng strategy và các QI mà strategy đó đang sử dụng
for strategy_name, qi_columns in strategies.items():

    # In tên strategy
    print("\nStrategy:", strategy_name)

    # In danh sách QI của strategy tương ứng
    print("QI:", qi_columns)

Strategy: Country3_Hours20
QI: ['tuoi_nhom_20', 'loai_cong_viec_nhom', 'hoc_van_nhom_4', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_20', 'quoc_gia_nhom_3']

Strategy: Country3_Hours4
QI: ['tuoi_nhom_20', 'loai_cong_viec_nhom', 'hoc_van_nhom_4', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_4', 'quoc_gia_nhom_3']

Strategy: Country3_Hours4_AgeHigh
QI: ['tuoi_nhom_high', 'loai_cong_viec_nhom', 'hoc_van_nhom_4', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_4', 'quoc_gia_nhom_3']

Country3_Hours20
→ phương án gốc hiện tại

Country3_Hours4
→ gộp vùng giờ làm cao

Country3_Hours4_AgeHigh
→ gộp vùng giờ làm cao + vùng tuổi cao

In [572]:
# Tạo hàm dùng chung để đánh giá privacy cho một strategy bất kỳ
def evaluate_privacy(dataframe, qi_columns, k_required=5):

    # Gom các bản ghi có cùng bộ QI vào cùng một equivalence class
    group_sizes = (
        dataframe
        .groupby(
            qi_columns,
            dropna=False
        )
        .size()
    )

    # Đếm tổng số equivalence class được tạo ra
    so_equivalence_class = len(group_sizes)

    # Tìm kích thước nhỏ nhất trong tất cả equivalence class
    k_min = int(group_sizes.min())

    # Đếm số equivalence class chỉ có đúng 1 bản ghi
    so_nhom_co_lap = int(
        (group_sizes == 1).sum()
    )

    # Tính tỷ lệ phần trăm bản ghi bị cô lập
    ty_le_co_lap = (
        so_nhom_co_lap
        / len(dataframe)
    ) * 100

    # Cộng số bản ghi nằm trong các nhóm có kích thước nhỏ hơn k yêu cầu
    so_ban_ghi_vi_pham_k = int(
        group_sizes[
            group_sizes < k_required
        ].sum()
    )

    # Tính tỷ lệ phần trăm bản ghi chưa đạt k-anonymity yêu cầu
    ty_le_vi_pham_k = (
        so_ban_ghi_vi_pham_k
        / len(dataframe)
    ) * 100

    # Trả về toàn bộ kết quả privacy của strategy
    return {
        "so_equivalence_class": so_equivalence_class,
        "k_min": k_min,
        "so_nhom_co_lap": so_nhom_co_lap,
        "ty_le_co_lap_%": round(ty_le_co_lap, 2),
        "so_ban_ghi_vi_pham_k5": so_ban_ghi_vi_pham_k,
        "ty_le_vi_pham_k5_%": round(ty_le_vi_pham_k, 2)
    }

Hàm evaluate_privacy() có tác dụng:

Đánh giá mức độ riêng tư của một phương án ẩn danh.

In [573]:
# Dùng hàm evaluate_privacy để đánh giá strategy Country3_Hours20
privacy_test_country3 = evaluate_privacy(
    data_anonymized,
    candidate_qi_country3,
    k_required=5
)


# Hiển thị kết quả privacy mà hàm tự tính
privacy_test_country3

{'so_equivalence_class': 1786,
 'k_min': 1,
 'so_nhom_co_lap': 596,
 'ty_le_co_lap_%': 1.83,
 'so_ban_ghi_vi_pham_k5': 1863,
 'ty_le_vi_pham_k5_%': 5.72}

In [574]:
# Tạo danh sách để lưu kết quả đánh giá privacy của từng strategy
privacy_results = []


# Lần lượt lấy tên strategy và bộ QI tương ứng
for strategy_name, qi_columns in strategies.items():

    # Dùng hàm evaluate_privacy để tự động tính các chỉ số privacy
    result = evaluate_privacy(
        data_anonymized,
        qi_columns,
        k_required=5
    )

    # Gắn tên strategy vào kết quả để biết kết quả thuộc phương án nào
    result["strategy"] = strategy_name

    # Lưu kết quả của strategy hiện tại vào danh sách
    privacy_results.append(result)


# Chuyển danh sách kết quả thành DataFrame để dễ xem và so sánh
strategy_evaluation = pd.DataFrame(
    privacy_results
)


# Sắp xếp lại thứ tự các cột để tên strategy nằm ở đầu bảng
strategy_evaluation = strategy_evaluation[
    [
        "strategy",
        "so_equivalence_class",
        "k_min",
        "so_nhom_co_lap",
        "ty_le_co_lap_%",
        "so_ban_ghi_vi_pham_k5",
        "ty_le_vi_pham_k5_%"
    ]
]


# Hiển thị bảng kết quả đánh giá tự động của tất cả strategy
strategy_evaluation

,strategy,so_equivalence_class,k_min,so_nhom_co_lap,ty_le_co_lap_%,so_ban_ghi_vi_pham_k5,ty_le_vi_pham_k5_%
0,Country3_Hours20,1786,1,596,1.83,1863,5.72
1,Country3_Hours4,1710,1,549,1.69,1747,5.37
2,Country3_Hours4_AgeHigh,1681,1,519,1.59,1713,5.26

In [575]:
# Sắp xếp các strategy theo tỷ lệ vi phạm k=5 từ thấp đến cao
# Nếu hai strategy có tỷ lệ vi phạm giống nhau thì ưu tiên strategy có tỷ lệ cô lập thấp hơn
privacy_ranking = strategy_evaluation.sort_values(
    by=[
        "ty_le_vi_pham_k5_%",
        "ty_le_co_lap_%"
    ],
    ascending=[
        True,
        True
    ]
)


# Lấy strategy đứng đầu sau khi xếp hạng privacy
best_privacy_strategy = privacy_ranking.iloc[0]


# Hiển thị tên strategy đang tốt nhất về mặt privacy
print(
    "Strategy tốt nhất về Privacy hiện tại:",
    best_privacy_strategy["strategy"]
)


# Hiển thị toàn bộ thông tin privacy của strategy tốt nhất
best_privacy_strategy

Strategy tốt nhất về Privacy hiện tại: Country3_Hours4_AgeHigh

strategy                 Country3_Hours4_AgeHigh
so_equivalence_class                        1681
k_min                                          1
so_nhom_co_lap                               519
ty_le_co_lap_%                              1.59
so_ban_ghi_vi_pham_k5                       1713
ty_le_vi_pham_k5_%                          5.26
Name: 2, dtype: object

Kiểm tra k nằm trong khoảng 1,2,3,4

In [576]:
# Lấy riêng các equivalence class có kích thước nhỏ hơn k=5
violation_groups_best = (
    qi_group_sizes_hours4_agehigh[
        qi_group_sizes_hours4_agehigh < k_required
    ]
)

# Đếm xem có bao nhiêu nhóm có kích thước 1, 2, 3 hoặc 4
violation_distribution_best = (
    violation_groups_best
    .value_counts()
    .sort_index()
)

# Hiển thị phân bố các nhóm đang vi phạm k=5
violation_distribution_best

1    519
2    249
3    124
4     81
Name: count, dtype: int64

In [577]:
# Tính kích thước equivalence class tương ứng cho từng bản ghi
group_size_per_record_best = (
    data_anonymized
    .groupby(
        candidate_qi_hours4_agehigh,
        dropna=False
    )["tuoi"]
    .transform("size")
)


# Đánh dấu những bản ghi đang nằm trong nhóm có kích thước nhỏ hơn k=5
violation_mask_best = (
    group_size_per_record_best < k_required
)


# Lấy riêng các bản ghi chưa đạt k=5
violating_records_best = (
    data_anonymized
    .loc[violation_mask_best]
    .copy()
)


# Gắn kích thước equivalence class vào từng bản ghi vi phạm
# Ví dụ group_size = 1, 2, 3 hoặc 4
violating_records_best["group_size"] = (
    group_size_per_record_best[
        violation_mask_best
    ]
)


# Kiểm tra số lượng bản ghi vi phạm
print(
    "Số bản ghi chưa đạt k=5:",
    len(violating_records_best)
)


# Hiển thị 10 bản ghi vi phạm đầu tiên để kiểm tra
violating_records_best[
    candidate_qi_hours4_agehigh + ["group_size"]
].head(10)

Số bản ghi chưa đạt k=5: 1713

,tuoi_nhom_high,loai_cong_viec_nhom,hoc_van_nhom_4,hon_nhan_nhom_2,nghe_nghiep_nhom_4,gio_lam_nhom_4,quoc_gia_nhom_3,group_size
9,30-49,Tu_nhan,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,41-60,Khong_ro,2
12,50-69,Tu_nhan,Dai_hoc_tro_len,Khong_ket_hon_hien_tai,Dich_vu,1-20,Hoa_Ky,2
28,30-49,Tu_kinh_doanh,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,41-60,Hoa_Ky,4
29,30-49,Tu_nhan,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,61-100,Hoa_Ky,2
31,50-69,Tu_kinh_doanh,Chua_tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,41-60,Hoa_Ky,4
46,70-99,Tu_nhan,Tot_nghiep_THPT,Da_ket_hon,Van_phong_chuyen_mon,41-60,Hoa_Ky,2
47,70-99,Tu_kinh_doanh,Tot_nghiep_THPT,Da_ket_hon,Lao_dong_truc_tiep,21-40,Ngoai_Hoa_Ky,2
51,50-69,Tu_nhan,Tot_nghiep_THPT,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,61-100,Hoa_Ky,3
65,50-69,Tu_kinh_doanh,Sau_THPT_Cao_dang,Da_ket_hon,Lao_dong_truc_tiep,61-100,Khong_ro,1
87,30-49,Nha_nuoc,Dai_hoc_tro_len,Da_ket_hon,Van_phong_chuyen_mon,41-60,Khong_ro,4

In [578]:
# Tạo danh sách để lưu kết quả phân tích rủi ro của từng QI
risk_summary_best = []


# Lần lượt phân tích từng QI trong strategy tốt nhất hiện tại
for qi_column in candidate_qi_hours4_agehigh:

    # Đếm tổng số bản ghi của từng nhóm giá trị QI trong toàn bộ dữ liệu
    total_by_group = (
        data_anonymized
        .groupby(qi_column, dropna=False)
        .size()
        .rename("tong_ban_ghi")
    )

    # Đếm số bản ghi vi phạm k=5 của từng nhóm giá trị QI
    violation_by_group = (
        violating_records_best
        .groupby(qi_column, dropna=False)
        .size()
        .rename("so_ban_ghi_vi_pham")
    )

    # Ghép tổng số bản ghi và số bản ghi vi phạm vào cùng một bảng
    risk_table = (
        pd.concat(
            [total_by_group, violation_by_group],
            axis=1
        )
        .fillna(0)
    )

    # Tính tỷ lệ phần trăm vi phạm k=5 trong từng nhóm giá trị
    risk_table["ty_le_vi_pham_%"] = (
        risk_table["so_ban_ghi_vi_pham"]
        / risk_table["tong_ban_ghi"]
        * 100
    )

    # Tìm nhóm giá trị có tỷ lệ vi phạm cao nhất của QI hiện tại
    highest_risk_group = (
        risk_table
        .sort_values(
            "ty_le_vi_pham_%",
            ascending=False
        )
        .iloc[0]
    )

    # Lưu thông tin nhóm rủi ro cao nhất của QI hiện tại
    risk_summary_best.append(
        {
            "QI": qi_column,
            "nhom_rui_ro_cao_nhat": highest_risk_group.name,
            "tong_ban_ghi_nhom": int(highest_risk_group["tong_ban_ghi"]),
            "so_ban_ghi_vi_pham": int(highest_risk_group["so_ban_ghi_vi_pham"]),
            "ty_le_vi_pham_%": round(highest_risk_group["ty_le_vi_pham_%"], 2)
        }
    )


# Chuyển kết quả thành DataFrame để dễ so sánh
risk_summary_best = pd.DataFrame(
    risk_summary_best
)


# Sắp xếp QI từ nhóm có tỷ lệ vi phạm cao nhất xuống thấp nhất
risk_summary_best = (
    risk_summary_best
    .sort_values(
        "ty_le_vi_pham_%",
        ascending=False
    )
    .reset_index(drop=True)
)


# Hiển thị bảng tổng hợp rủi ro của 7 QI
risk_summary_best

,QI,nhom_rui_ro_cao_nhat,tong_ban_ghi_nhom,so_ban_ghi_vi_pham,ty_le_vi_pham_%
0,loai_cong_viec_nhom,Khong_luong_hoac_chua_lam,21,21,100.00
1,quoc_gia_nhom_3,Khong_ro,583,314,53.86
2,tuoi_nhom_high,70-99,629,238,37.84
3,gio_lam_nhom_4,61-100,1110,324,29.19
4,nghe_nghiep_nhom_4,Dich_vu,4102,471,11.48
5,hoc_van_nhom_4,Chua_tot_nghiep_THPT,4253,462,10.86
6,hon_nhan_nhom_2,Da_ket_hon,15417,878,5.70

Thay đổi quy tắc đưa từ 3 quốc gia xuống còn 2 quốc gia

In [579]:
# Tạo quy tắc tổng quát hóa quốc gia từ 3 nhóm xuống còn 2 nhóm
country_map_2 = {
    "Hoa_Ky": "Hoa_Ky",
    "Ngoai_Hoa_Ky": "Khac_hoac_khong_ro",
    "Khong_ro": "Khac_hoac_khong_ro"
}


# Tạo cột quốc gia mới gồm 2 nhóm
# Không sửa trực tiếp cột cũ để còn có thể so sánh các strategy
data_anonymized["quoc_gia_nhom_2"] = (
    data_anonymized["quoc_gia_nhom_3"]
    .map(country_map_2)
)


# Kiểm tra số lượng bản ghi của từng nhóm quốc gia mới
data_anonymized["quoc_gia_nhom_2"].value_counts(dropna=False)

quoc_gia_nhom_2
Hoa_Ky                29184
Khac_hoac_khong_ro     3377
Name: count, dtype: int64

In [580]:
# Tạo bộ QI cho strategy mới
# Giữ nguyên các QI của strategy tốt nhất hiện tại
# Chỉ thay quoc_gia_nhom_3 bằng quoc_gia_nhom_2
candidate_qi_country2_hours4_agehigh = [
    "tuoi_nhom_high",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_4",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_4",
    "quoc_gia_nhom_2"
]


# Dùng hàm evaluate_privacy đã xây dựng trước đó
# để đánh giá strategy quốc gia 2 nhóm
privacy_country2_hours4_agehigh = evaluate_privacy(
    data_anonymized,
    candidate_qi_country2_hours4_agehigh,
    k_required=5
)


# Hiển thị kết quả Privacy của strategy mới
privacy_country2_hours4_agehigh

{'so_equivalence_class': 1484,
 'k_min': 1,
 'so_nhom_co_lap': 385,
 'ty_le_co_lap_%': 1.18,
 'so_ban_ghi_vi_pham_k5': 1477,
 'ty_le_vi_pham_k5_%': 4.54}

In [581]:
# Thêm strategy Country2_Hours4_AgeHigh vào danh sách strategy của hệ thống
strategies["Country2_Hours4_AgeHigh"] = (
    candidate_qi_country2_hours4_agehigh
)


# Tạo danh sách mới để lưu kết quả privacy của tất cả strategy
privacy_results = []


# Lần lượt đánh giá từng strategy đang có trong hệ thống
for strategy_name, qi_columns in strategies.items():

    # Tính các chỉ số privacy của strategy hiện tại
    result = evaluate_privacy(
        data_anonymized,
        qi_columns,
        k_required=5
    )

    # Gắn tên strategy vào kết quả để dễ phân biệt
    result["strategy"] = strategy_name

    # Lưu kết quả của strategy hiện tại vào danh sách
    privacy_results.append(result)


# Chuyển toàn bộ kết quả thành DataFrame để dễ so sánh
strategy_evaluation = pd.DataFrame(
    privacy_results
)


# Sắp xếp strategy theo tỷ lệ vi phạm k=5 từ thấp đến cao
strategy_evaluation = (
    strategy_evaluation
    .sort_values(
        "ty_le_vi_pham_k5_%",
        ascending=True
    )
    .reset_index(drop=True)
)


# Hiển thị bảng xếp hạng privacy mới
strategy_evaluation

,so_equivalence_class,k_min,so_nhom_co_lap,ty_le_co_lap_%,so_ban_ghi_vi_pham_k5,ty_le_vi_pham_k5_%,strategy
0,1484,1,385,1.18,1477,4.54,Country2_Hours4_AgeHigh
1,1681,1,519,1.59,1713,5.26,Country3_Hours4_AgeHigh
2,1710,1,549,1.69,1747,5.37,Country3_Hours4
3,1786,1,596,1.83,1863,5.72,Country3_Hours20

In [582]:
# In toàn bộ bảng strategy_evaluation dưới dạng văn bản
# Cách này giúp kiểm tra kết quả khi PyCharm không hiển thị DataFrame bình thường
print(
    strategy_evaluation.to_string(
        index=False
    )
)

 so_equivalence_class  k_min  so_nhom_co_lap  ty_le_co_lap_%  so_ban_ghi_vi_pham_k5  ty_le_vi_pham_k5_%                strategy
                 1484      1             385            1.18                   1477                4.54 Country2_Hours4_AgeHigh
                 1681      1             519            1.59                   1713                5.26 Country3_Hours4_AgeHigh
                 1710      1             549            1.69                   1747                5.37         Country3_Hours4
                 1786      1             596            1.83                   1863                5.72        Country3_Hours20

In [583]:
# Tính kích thước equivalence class cho từng bản ghi
# theo strategy Country2_Hours4_AgeHigh mới
group_size_per_record_country2 = (
    data_anonymized
    .groupby(
        candidate_qi_country2_hours4_agehigh,
        dropna=False
    )["tuoi"]
    .transform("size")
)


# Đánh dấu các bản ghi nằm trong equivalence class nhỏ hơn k=5
violation_mask_country2 = (
    group_size_per_record_country2 < k_required
)


# Lấy riêng các bản ghi chưa đạt k=5 của strategy mới
violating_records_country2 = (
    data_anonymized
    .loc[violation_mask_country2]
    .copy()
)


# Gắn kích thước nhóm vào từng bản ghi để phục vụ phân tích tiếp theo
violating_records_country2["group_size"] = (
    group_size_per_record_country2[
        violation_mask_country2
    ]
)


# Kiểm tra số lượng bản ghi chưa đạt k=5
print(
    "Số bản ghi chưa đạt k=5 của Country2:",
    len(violating_records_country2)
)


# Kiểm tra số nhóm có kích thước 1, 2, 3 và 4
print(
    violating_records_country2["group_size"]
    .value_counts()
    .sort_index()
)

Số bản ghi chưa đạt k=5 của Country2: 1477
group_size
1    385
2    400
3    372
4    320
Name: count, dtype: int64

In [584]:
# Tạo một bản sao dữ liệu mới cho strategy có suppression
# Chỉ giữ các bản ghi đang thuộc equivalence class có kích thước từ 5 trở lên
data_country2_suppressed = (
    data_anonymized
    .loc[~violation_mask_country2]
    .copy()
)


# Tính số bản ghi còn lại sau khi suppression
so_ban_ghi_con_lai = len(data_country2_suppressed)


# Tính số bản ghi đã bị suppression
so_ban_ghi_suppression = (
    len(data_anonymized) - so_ban_ghi_con_lai
)


# Tính tỷ lệ phần trăm dữ liệu bị suppression
ty_le_suppression = (
    so_ban_ghi_suppression
    / len(data_anonymized)
    * 100
)


# Hiển thị kết quả để kiểm tra
print("Số bản ghi ban đầu:", len(data_anonymized))
print("Số bản ghi bị suppression:", so_ban_ghi_suppression)
print("Số bản ghi còn lại:", so_ban_ghi_con_lai)
print("Tỷ lệ suppression:", round(ty_le_suppression, 2), "%")

Số bản ghi ban đầu: 32561
Số bản ghi bị suppression: 1477
Số bản ghi còn lại: 31084
Tỷ lệ suppression: 4.54 %

In [585]:
# Đánh giá lại privacy trên dữ liệu sau khi đã suppression
privacy_after_suppression = evaluate_privacy(
    data_country2_suppressed,
    candidate_qi_country2_hours4_agehigh,
    k_required=5
)


# Hiển thị kết quả để kiểm tra dataset sau suppression có thật sự đạt k=5 hay chưa
privacy_after_suppression

{'so_equivalence_class': 695,
 'k_min': 5,
 'so_nhom_co_lap': 0,
 'ty_le_co_lap_%': 0.0,
 'so_ban_ghi_vi_pham_k5': 0,
 'ty_le_vi_pham_k5_%': 0.0}

In [586]:
# Lấy giá trị k nhỏ nhất của dữ liệu sau khi suppression
k_min_after_suppression = privacy_after_suppression["k_min"]

# Hiển thị giá trị k nhỏ nhất
print(
    "k nhỏ nhất sau suppression:",
    k_min_after_suppression
)

k nhỏ nhất sau suppression: 5

In [587]:
# Đặt ngưỡng l-diversity cần kiểm tra
# Vì thu_nhap chỉ có 2 giá trị nên ta thử nghiệm với l = 2
l_required = 2


# Với mỗi equivalence class, đếm số giá trị thu_nhap khác nhau
l_values_country2 = (
    data_country2_suppressed
    .groupby(
        candidate_qi_country2_hours4_agehigh,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất của toàn bộ các equivalence class
l_min_country2 = int(
    l_values_country2.min()
)


# Đếm số equivalence class chưa đạt l = 2
so_nhom_vi_pham_l2 = int(
    (l_values_country2 < l_required).sum()
)


# Xem có bao nhiêu nhóm đạt l = 1 hoặc l = 2
l_distribution_country2 = (
    l_values_country2
    .value_counts()
    .sort_index()
)


# Hiển thị kết quả kiểm tra l-diversity
print("l_min:", l_min_country2)
print("Số equivalence class chưa đạt l=2:", so_nhom_vi_pham_l2)

print("\nPhân bố l-diversity:")
print(l_distribution_country2)

l_min: 1
Số equivalence class chưa đạt l=2: 225

Phân bố l-diversity:
thu_nhap
1    225
2    470
Name: count, dtype: int64

In [588]:
# Tính số bản ghi của từng equivalence class sau suppression
group_sizes_after_suppression = (
    data_country2_suppressed
    .groupby(
        candidate_qi_country2_hours4_agehigh,
        dropna=False
    )
    .size()
)


# Ghép kích thước nhóm và giá trị l-diversity của từng equivalence class
l_group_analysis = pd.DataFrame({
    "group_size": group_sizes_after_suppression,
    "l_value": l_values_country2
})


# Chỉ lấy những equivalence class chưa đạt l=2
l2_violating_groups = (
    l_group_analysis[
        l_group_analysis["l_value"] < l_required
    ]
)


# Tính tổng số bản ghi nằm trong các nhóm chưa đạt l=2
so_ban_ghi_vi_pham_l2 = int(
    l2_violating_groups["group_size"].sum()
)


# Tính tỷ lệ bản ghi bị ảnh hưởng bởi vi phạm l=2
ty_le_ban_ghi_vi_pham_l2 = (
    so_ban_ghi_vi_pham_l2
    / len(data_country2_suppressed)
    * 100
)


# Hiển thị kết quả
print("Số equivalence class chưa đạt l=2:", len(l2_violating_groups))
print("Số bản ghi nằm trong các nhóm chưa đạt l=2:", so_ban_ghi_vi_pham_l2)
print(
    "Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2:",
    round(ty_le_ban_ghi_vi_pham_l2, 2),
    "%"
)

Số equivalence class chưa đạt l=2: 225
Số bản ghi nằm trong các nhóm chưa đạt l=2: 5671
Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2: 18.24 %

In [589]:
# Tạo bảng thông tin cho từng equivalence class sau khi đã đạt k=5
l_group_detail = (
    data_country2_suppressed
    .groupby(
        candidate_qi_country2_hours4_agehigh,
        dropna=False
    )
    .agg(
        # Đếm số bản ghi trong từng equivalence class
        group_size=("thu_nhap", "size"),

        # Đếm số giá trị thu_nhap khác nhau trong từng equivalence class
        l_value=("thu_nhap", "nunique"),

        # Lấy một giá trị thu_nhap đại diện
        # Với nhóm l=1 thì toàn bộ nhóm chỉ có đúng giá trị này
        thu_nhap_dai_dien=("thu_nhap", "first")
    )
    .reset_index()
)


# Chỉ lấy các equivalence class chưa đạt l=2
l1_groups = (
    l_group_detail[
        l_group_detail["l_value"] == 1
    ]
    .copy()
)


# Tổng hợp xem các nhóm l=1 đang thuộc loại thu_nhap nào
l1_income_summary = (
    l1_groups
    .groupby("thu_nhap_dai_dien")
    .agg(
        # Đếm số equivalence class l=1 của từng loại thu nhập
        so_equivalence_class=("group_size", "size"),

        # Cộng tổng số bản ghi nằm trong các nhóm đó
        so_ban_ghi=("group_size", "sum")
    )
)


# Hiển thị kết quả
l1_income_summary

                   so_equivalence_class  so_ban_ghi
thu_nhap_dai_dien
<=50K                               224        5666
>50K                                  1           5

In [590]:
# Tính giá trị l-diversity tương ứng cho từng bản ghi
# Các bản ghi có cùng bộ QI sẽ nhận cùng một giá trị l
l_value_per_record_country2 = (
    data_country2_suppressed
    .groupby(
        candidate_qi_country2_hours4_agehigh,
        dropna=False
    )["thu_nhap"]
    .transform("nunique")
)


# Đánh dấu những bản ghi đang nằm trong equivalence class chưa đạt l=2
l2_violation_mask_country2 = (
    l_value_per_record_country2 < l_required
)


# Lấy riêng các bản ghi chưa đạt l=2
# Tạo bản sao để không làm thay đổi dataset sau suppression
violating_l2_records_country2 = (
    data_country2_suppressed
    .loc[l2_violation_mask_country2]
    .copy()
)


# Gắn giá trị l vào từng bản ghi để tiện phân tích ở các bước sau
violating_l2_records_country2["l_value"] = (
    l_value_per_record_country2[
        l2_violation_mask_country2
    ]
)


# Kiểm tra số lượng bản ghi chưa đạt l=2
print(
    "Số bản ghi chưa đạt l=2:",
    len(violating_l2_records_country2)
)


# Kiểm tra các bản ghi vi phạm đang thuộc loại thu nhập nào
print("\nPhân bố thu nhập trong các bản ghi chưa đạt l=2:")
print(
    violating_l2_records_country2["thu_nhap"]
    .value_counts()
)

Số bản ghi chưa đạt l=2: 5671

Phân bố thu nhập trong các bản ghi chưa đạt l=2:
thu_nhap
<=50K    5666
>50K        5
Name: count, dtype: int64

In [591]:
# Tạo danh sách để lưu kết quả phân tích vi phạm l=2 của từng QI
l2_risk_summary = []


# Lần lượt phân tích từng QI của strategy Country2_Hours4_AgeHigh
for qi_column in candidate_qi_country2_hours4_agehigh:

    # Đếm tổng số bản ghi của từng nhóm giá trị QI
    # trên dataset sau khi đã đạt k=5
    total_by_group = (
        data_country2_suppressed
        .groupby(qi_column, dropna=False)
        .size()
        .rename("tong_ban_ghi")
    )

    # Đếm số bản ghi chưa đạt l=2 trong từng nhóm giá trị QI
    violation_by_group = (
        violating_l2_records_country2
        .groupby(qi_column, dropna=False)
        .size()
        .rename("so_ban_ghi_vi_pham_l2")
    )

    # Ghép tổng số bản ghi và số bản ghi vi phạm vào cùng một bảng
    l2_risk_table = (
        pd.concat(
            [total_by_group, violation_by_group],
            axis=1
        )
        .fillna(0)
    )

    # Tính tỷ lệ bản ghi chưa đạt l=2 của từng nhóm giá trị
    l2_risk_table["ty_le_vi_pham_l2_%"] = (
        l2_risk_table["so_ban_ghi_vi_pham_l2"]
        / l2_risk_table["tong_ban_ghi"]
        * 100
    )

    # Tìm nhóm giá trị có tỷ lệ vi phạm l=2 cao nhất của QI hiện tại
    highest_risk_group = (
        l2_risk_table
        .sort_values(
            "ty_le_vi_pham_l2_%",
            ascending=False
        )
        .iloc[0]
    )

    # Lưu kết quả của QI hiện tại vào danh sách tổng hợp
    l2_risk_summary.append(
        {
            "QI": qi_column,
            "nhom_rui_ro_cao_nhat": highest_risk_group.name,
            "tong_ban_ghi_nhom": int(
                highest_risk_group["tong_ban_ghi"]
            ),
            "so_ban_ghi_vi_pham_l2": int(
                highest_risk_group["so_ban_ghi_vi_pham_l2"]
            ),
            "ty_le_vi_pham_l2_%": round(
                highest_risk_group["ty_le_vi_pham_l2_%"],
                2
            )
        }
    )


# Chuyển kết quả thành DataFrame để dễ xem
l2_risk_summary = pd.DataFrame(
    l2_risk_summary
)


# Sắp xếp từ nhóm có tỷ lệ vi phạm l=2 cao nhất xuống thấp nhất
l2_risk_summary = (
    l2_risk_summary
    .sort_values(
        "ty_le_vi_pham_l2_%",
        ascending=False
    )
    .reset_index(drop=True)
)


# Hiển thị bảng tổng hợp
l2_risk_summary

,QI,nhom_rui_ro_cao_nhat,tong_ban_ghi_nhom,so_ban_ghi_vi_pham_l2,ty_le_vi_pham_l2_%
0,gio_lam_nhom_4,1-20,2486,1941,78.08
1,nghe_nghiep_nhom_4,Khong_ro,1685,1041,61.78
2,loai_cong_viec_nhom,Khong_ro,1685,1041,61.78
3,tuoi_nhom_high,70-99,391,199,50.90
4,hoc_van_nhom_4,Chua_tot_nghiep_THPT,3852,1721,44.68
5,hon_nhan_nhom_2,Khong_ket_hon_hien_tai,16413,5349,32.59
6,quoc_gia_nhom_2,Khac_hoac_khong_ro,2732,861,31.52

In [592]:
# Tạo quy tắc generalization giờ làm mới từ 4 nhóm xuống còn 3 nhóm
# Gộp nhóm 1-20 và 21-40 thành một nhóm rộng hơn là 1-40
hours_map_3 = {
    "1-20": "1-40",
    "21-40": "1-40",
    "41-60": "41-60",
    "61-100": "61-100"
}


# Tạo cột giờ làm mới trên dữ liệu đầy đủ
# Không ghi đè cột gio_lam_nhom_4 để còn so sánh các strategy
data_anonymized["gio_lam_nhom_3"] = (
    data_anonymized["gio_lam_nhom_4"]
    .map(hours_map_3)
)


# Kiểm tra số lượng bản ghi trong từng nhóm giờ làm mới
data_anonymized["gio_lam_nhom_3"].value_counts(dropna=False)

gio_lam_nhom_3
1-40      22980
41-60      8471
61-100     1110
Name: count, dtype: int64

In [593]:
# Tạo bộ QI cho strategy mới
# Giữ nguyên các QI hiện tại và chỉ thay gio_lam_nhom_4 bằng gio_lam_nhom_3
candidate_qi_country2_hours3_agehigh = [
    "tuoi_nhom_high",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_4",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Đánh giá privacy của strategy mới trên toàn bộ dữ liệu
# Chưa suppression để xem bản thân generalization mới cải thiện k-anonymity bao nhiêu
privacy_country2_hours3_agehigh = evaluate_privacy(
    data_anonymized,
    candidate_qi_country2_hours3_agehigh,
    k_required=5
)


# Hiển thị kết quả đánh giá k-anonymity của strategy mới
privacy_country2_hours3_agehigh

{'so_equivalence_class': 1147,
 'k_min': 1,
 'so_nhom_co_lap': 269,
 'ty_le_co_lap_%': 0.83,
 'so_ban_ghi_vi_pham_k5': 1060,
 'ty_le_vi_pham_k5_%': 3.26}

In [594]:
# Tính kích thước equivalence class tương ứng cho từng bản ghi
# theo strategy Country2_Hours3_AgeHigh
group_size_per_record_hours3 = (
    data_anonymized
    .groupby(
        candidate_qi_country2_hours3_agehigh,
        dropna=False
    )["tuoi"]
    .transform("size")
)


# Đánh dấu các bản ghi đang nằm trong nhóm có kích thước nhỏ hơn k=5
violation_mask_hours3 = (
    group_size_per_record_hours3 < k_required
)


# Tạo dataset mới và loại các bản ghi vẫn chưa đạt k=5
# Không sửa trực tiếp data_anonymized để còn dùng so sánh strategy
data_country2_hours3_suppressed = (
    data_anonymized
    .loc[~violation_mask_hours3]
    .copy()
)


# Tính số bản ghi bị suppression ở strategy mới
so_suppression_hours3 = (
    len(data_anonymized)
    - len(data_country2_hours3_suppressed)
)


# Hiển thị kết quả để kiểm tra
print("Số bản ghi ban đầu:", len(data_anonymized))
print("Số bản ghi bị suppression:", so_suppression_hours3)
print(
    "Số bản ghi còn lại:",
    len(data_country2_hours3_suppressed)
)
print(
    "Tỷ lệ suppression:",
    round(
        so_suppression_hours3 / len(data_anonymized) * 100,
        2
    ),
    "%"
)

Số bản ghi ban đầu: 32561
Số bản ghi bị suppression: 1060
Số bản ghi còn lại: 31501
Tỷ lệ suppression: 3.26 %

In [595]:
# Đánh giá lại privacy trên dataset của strategy Hours3 sau khi suppression
privacy_hours3_after_suppression = evaluate_privacy(
    data_country2_hours3_suppressed,
    candidate_qi_country2_hours3_agehigh,
    k_required=5
)


# Hiển thị kết quả để kiểm tra dataset có thật sự đạt k=5 hay chưa
privacy_hours3_after_suppression

{'so_equivalence_class': 591,
 'k_min': 5,
 'so_nhom_co_lap': 0,
 'ty_le_co_lap_%': 0.0,
 'so_ban_ghi_vi_pham_k5': 0,
 'ty_le_vi_pham_k5_%': 0.0}

In [596]:
# Đặt ngưỡng l-diversity cần kiểm tra
# Vì thu_nhap có 2 giá trị nên tiếp tục dùng l = 2
l_required = 2


# Với mỗi equivalence class của strategy Hours3,
# đếm số giá trị thu_nhap khác nhau
l_values_hours3 = (
    data_country2_hours3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất trong toàn bộ dataset
l_min_hours3 = int(
    l_values_hours3.min()
)


# Đếm số equivalence class chưa đạt l = 2
so_nhom_vi_pham_l2_hours3 = int(
    (l_values_hours3 < l_required).sum()
)


# Xem có bao nhiêu equivalence class có l = 1 và l = 2
l_distribution_hours3 = (
    l_values_hours3
    .value_counts()
    .sort_index()
)


# Hiển thị kết quả kiểm tra l-diversity của strategy Hours3
print("l_min:", l_min_hours3)
print(
    "Số equivalence class chưa đạt l=2:",
    so_nhom_vi_pham_l2_hours3
)

print("\nPhân bố l-diversity:")
print(l_distribution_hours3)

l_min: 1
Số equivalence class chưa đạt l=2: 145

Phân bố l-diversity:
thu_nhap
1    145
2    446
Name: count, dtype: int64

In [597]:
# Tính số bản ghi của từng equivalence class
# trong strategy Hours3 sau khi đã suppression
group_sizes_hours3_after_suppression = (
    data_country2_hours3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh,
        dropna=False
    )
    .size()
)


# Tạo bảng chứa kích thước nhóm và giá trị l-diversity
# của từng equivalence class
l_group_analysis_hours3 = pd.DataFrame({
    "group_size": group_sizes_hours3_after_suppression,
    "l_value": l_values_hours3
})


# Chỉ lấy những equivalence class chưa đạt l=2
l2_violating_groups_hours3 = (
    l_group_analysis_hours3[
        l_group_analysis_hours3["l_value"] < l_required
    ]
)


# Cộng số bản ghi nằm trong tất cả các nhóm chưa đạt l=2
so_ban_ghi_vi_pham_l2_hours3 = int(
    l2_violating_groups_hours3["group_size"].sum()
)


# Tính tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2
ty_le_ban_ghi_vi_pham_l2_hours3 = (
    so_ban_ghi_vi_pham_l2_hours3
    / len(data_country2_hours3_suppressed)
    * 100
)


# Hiển thị kết quả để so sánh với strategy Hours4 trước đó
print(
    "Số equivalence class chưa đạt l=2:",
    len(l2_violating_groups_hours3)
)

print(
    "Số bản ghi nằm trong các nhóm chưa đạt l=2:",
    so_ban_ghi_vi_pham_l2_hours3
)

print(
    "Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2:",
    round(ty_le_ban_ghi_vi_pham_l2_hours3, 2),
    "%"
)

Số equivalence class chưa đạt l=2: 145
Số bản ghi nằm trong các nhóm chưa đạt l=2: 4628
Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2: 14.69 %

Ta cần tạo riêng 4,628 bản ghi còn vi phạm l=2 của Hours3, để sau đó xem chúng tập trung ở nhóm QI nào.

In [598]:
# Tính giá trị l-diversity tương ứng cho từng bản ghi
# Các bản ghi cùng equivalence class sẽ nhận cùng một giá trị l
l_value_per_record_hours3 = (
    data_country2_hours3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh,
        dropna=False
    )["thu_nhap"]
    .transform("nunique")
)


# Đánh dấu các bản ghi đang nằm trong nhóm chưa đạt l=2
l2_violation_mask_hours3 = (
    l_value_per_record_hours3 < l_required
)


# Lấy riêng các bản ghi chưa đạt l=2
# Dùng copy để không làm thay đổi dataset đã đạt k=5
violating_l2_records_hours3 = (
    data_country2_hours3_suppressed
    .loc[l2_violation_mask_hours3]
    .copy()
)


# Gắn giá trị l vào từng bản ghi để tiện phân tích tiếp theo
violating_l2_records_hours3["l_value"] = (
    l_value_per_record_hours3[
        l2_violation_mask_hours3
    ]
)


# Kiểm tra số lượng bản ghi còn vi phạm l=2
print(
    "Số bản ghi chưa đạt l=2 của Hours3:",
    len(violating_l2_records_hours3)
)


# Kiểm tra các bản ghi vi phạm đang thuộc loại thu nhập nào
print("\nPhân bố thu nhập:")
print(
    violating_l2_records_hours3["thu_nhap"]
    .value_counts()
)

Số bản ghi chưa đạt l=2 của Hours3: 4628

Phân bố thu nhập:
thu_nhap
<=50K    4623
>50K        5
Name: count, dtype: int64

Như vậy sau khi chuyển từ Hours4 sang Hours3, số bản ghi vi phạm l=2 đã giảm từ 5,671 xuống 4,628, nhưng vấn đề vẫn gần như toàn bộ nằm ở nhóm <=50K.

Phân tích lại QI nào đang tập trung vi phạm l=2 ở strategy Hours3

In [599]:
# Tạo danh sách để lưu kết quả phân tích rủi ro l=2 của từng QI
l2_risk_summary_hours3 = []


# Lần lượt phân tích từng QI trong strategy Country2_Hours3_AgeHigh
for qi_column in candidate_qi_country2_hours3_agehigh:

    # Đếm tổng số bản ghi của từng nhóm giá trị QI
    # trên dataset Hours3 sau khi đã suppression để đạt k=5
    total_by_group = (
        data_country2_hours3_suppressed
        .groupby(qi_column, dropna=False)
        .size()
        .rename("tong_ban_ghi")
    )

    # Đếm số bản ghi chưa đạt l=2 trong từng nhóm giá trị QI
    violation_by_group = (
        violating_l2_records_hours3
        .groupby(qi_column, dropna=False)
        .size()
        .rename("so_ban_ghi_vi_pham_l2")
    )

    # Ghép tổng số bản ghi và số bản ghi vi phạm vào cùng một bảng
    l2_risk_table = (
        pd.concat(
            [total_by_group, violation_by_group],
            axis=1
        )
        .fillna(0)
    )

    # Tính tỷ lệ vi phạm l=2 của từng nhóm giá trị
    l2_risk_table["ty_le_vi_pham_l2_%"] = (
        l2_risk_table["so_ban_ghi_vi_pham_l2"]
        / l2_risk_table["tong_ban_ghi"]
        * 100
    )

    # Tìm nhóm có tỷ lệ vi phạm l=2 cao nhất của QI hiện tại
    highest_risk_group = (
        l2_risk_table
        .sort_values(
            "ty_le_vi_pham_l2_%",
            ascending=False
        )
        .iloc[0]
    )

    # Lưu nhóm rủi ro cao nhất của QI hiện tại
    l2_risk_summary_hours3.append(
        {
            "QI": qi_column,
            "nhom_rui_ro_cao_nhat": highest_risk_group.name,
            "tong_ban_ghi_nhom": int(
                highest_risk_group["tong_ban_ghi"]
            ),
            "so_ban_ghi_vi_pham_l2": int(
                highest_risk_group["so_ban_ghi_vi_pham_l2"]
            ),
            "ty_le_vi_pham_l2_%": round(
                highest_risk_group["ty_le_vi_pham_l2_%"],
                2
            )
        }
    )


# Chuyển kết quả thành DataFrame
l2_risk_summary_hours3 = pd.DataFrame(
    l2_risk_summary_hours3
)


# Sắp xếp từ nhóm có tỷ lệ vi phạm l=2 cao nhất xuống thấp nhất
l2_risk_summary_hours3 = (
    l2_risk_summary_hours3
    .sort_values(
        "ty_le_vi_pham_l2_%",
        ascending=False
    )
    .reset_index(drop=True)
)


# Hiển thị bảng kết quả
l2_risk_summary_hours3

,QI,nhom_rui_ro_cao_nhat,tong_ban_ghi_nhom,so_ban_ghi_vi_pham_l2,ty_le_vi_pham_l2_%
0,loai_cong_viec_nhom,Khong_ro,1723,968,56.18
1,nghe_nghiep_nhom_4,Khong_ro,1723,968,56.18
2,hoc_van_nhom_4,Chua_tot_nghiep_THPT,3968,1718,43.30
3,tuoi_nhom_high,70-99,468,166,35.47
4,quoc_gia_nhom_2,Khac_hoac_khong_ro,2849,862,30.26
5,hon_nhan_nhom_2,Khong_ket_hon_hien_tai,16603,4371,26.33
6,gio_lam_nhom_3,1-40,22598,4038,17.87

Kết quả này cho thấy bước tiếp theo hợp lý nhất không phải gộp Khong_ro của nghề nghiệp/loại công việc, dù tỷ lệ vi phạm cao nhất là 56.18%, vì Khong_ro là dữ liệu thiếu — gộp nó vào một nghề cụ thể sẽ làm sai ý nghĩa dữ liệu.

Để kiểm tra thêm ta gôp Chua_tot_nghiep_THPT -> Tot_nghiep_THPT -> THPT_tro_xuong

In [600]:
# Tạo quy tắc generalization học vấn từ 4 nhóm xuống còn 3 nhóm
education_map_3 = {
    "Chua_tot_nghiep_THPT": "THPT_tro_xuong",
    "Tot_nghiep_THPT": "THPT_tro_xuong",
    "Sau_THPT_Cao_dang": "Sau_THPT_Cao_dang",
    "Dai_hoc_tro_len": "Dai_hoc_tro_len"
}


# Tạo cột học vấn mới
# Không ghi đè hoc_van_nhom_4 để còn so sánh strategy cũ và mới
data_anonymized["hoc_van_nhom_3"] = (
    data_anonymized["hoc_van_nhom_4"]
    .map(education_map_3)
)


# Kiểm tra số lượng bản ghi trong từng nhóm học vấn mới
data_anonymized["hoc_van_nhom_3"].value_counts(dropna=False)

hoc_van_nhom_3
THPT_tro_xuong       14754
Sau_THPT_Cao_dang     9740
Dai_hoc_tro_len       8067
Name: count, dtype: int64

In [601]:
# Tạo bộ QI cho strategy mới
# Giữ nguyên Country2, Hours3 và AgeHigh
# Chỉ thay hoc_van_nhom_4 bằng hoc_van_nhom_3
candidate_qi_country2_hours3_agehigh_edu3 = [
    "tuoi_nhom_high",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Đánh giá k-anonymity của strategy mới trên toàn bộ dữ liệu
# Chưa suppression để xem riêng generalization học vấn cải thiện được bao nhiêu
privacy_country2_hours3_agehigh_edu3 = evaluate_privacy(
    data_anonymized,
    candidate_qi_country2_hours3_agehigh_edu3,
    k_required=5
)


# Hiển thị kết quả đánh giá privacy của strategy mới
privacy_country2_hours3_agehigh_edu3

{'so_equivalence_class': 912,
 'k_min': 1,
 'so_nhom_co_lap': 188,
 'ty_le_co_lap_%': 0.58,
 'so_ban_ghi_vi_pham_k5': 810,
 'ty_le_vi_pham_k5_%': 2.49}

In [602]:
# Tính kích thước equivalence class tương ứng cho từng bản ghi
# theo strategy Country2_Hours3_AgeHigh_Edu3
group_size_per_record_edu3 = (
    data_anonymized
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )["tuoi"]
    .transform("size")
)


# Đánh dấu các bản ghi đang nằm trong nhóm có kích thước nhỏ hơn k=5
violation_mask_edu3 = (
    group_size_per_record_edu3 < k_required
)


# Tạo dataset mới sau suppression
# Không sửa data_anonymized để còn dùng so sánh các strategy khác
data_country2_hours3_edu3_suppressed = (
    data_anonymized
    .loc[~violation_mask_edu3]
    .copy()
)


# Tính số bản ghi bị suppression
so_suppression_edu3 = (
    len(data_anonymized)
    - len(data_country2_hours3_edu3_suppressed)
)


# Hiển thị kết quả suppression của strategy mới
print("Số bản ghi ban đầu:", len(data_anonymized))
print("Số bản ghi bị suppression:", so_suppression_edu3)
print(
    "Số bản ghi còn lại:",
    len(data_country2_hours3_edu3_suppressed)
)
print(
    "Tỷ lệ suppression:",
    round(
        so_suppression_edu3 / len(data_anonymized) * 100,
        2
    ),
    "%"
)

Số bản ghi ban đầu: 32561
Số bản ghi bị suppression: 810
Số bản ghi còn lại: 31751
Tỷ lệ suppression: 2.49 %

Hours4 + Suppression        → 4.54%

Hours3 + Suppression        → 3.26%

Hours3 + Edu3 + Suppression → 2.49%

In [603]:
# Đánh giá lại k-anonymity trên dataset Edu3 sau khi suppression
privacy_edu3_after_suppression = evaluate_privacy(
    data_country2_hours3_edu3_suppressed,
    candidate_qi_country2_hours3_agehigh_edu3,
    k_required=5
)


# Hiển thị kết quả để kiểm tra strategy mới có thật sự đạt k=5 hay chưa
privacy_edu3_after_suppression

{'so_equivalence_class': 503,
 'k_min': 5,
 'so_nhom_co_lap': 0,
 'ty_le_co_lap_%': 0.0,
 'so_ban_ghi_vi_pham_k5': 0,
 'ty_le_vi_pham_k5_%': 0.0}

In [604]:
# Đặt ngưỡng l-diversity cần kiểm tra
# Vì thu_nhap có 2 giá trị nên tiếp tục dùng l = 2
l_required = 2


# Với mỗi equivalence class của strategy Edu3,
# đếm số giá trị thu_nhap khác nhau
l_values_edu3 = (
    data_country2_hours3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất trong toàn bộ dataset
l_min_edu3 = int(
    l_values_edu3.min()
)


# Đếm số equivalence class chưa đạt l = 2
so_nhom_vi_pham_l2_edu3 = int(
    (l_values_edu3 < l_required).sum()
)


# Đếm số equivalence class có l = 1 hoặc l = 2
l_distribution_edu3 = (
    l_values_edu3
    .value_counts()
    .sort_index()
)


# Hiển thị kết quả kiểm tra l-diversity
print("l_min:", l_min_edu3)

print(
    "Số equivalence class chưa đạt l=2:",
    so_nhom_vi_pham_l2_edu3
)

print("\nPhân bố l-diversity:")
print(l_distribution_edu3)

l_min: 1
Số equivalence class chưa đạt l=2: 94

Phân bố l-diversity:
thu_nhap
1     94
2    409
Name: count, dtype: int64

Strategy Hours3 trước:

l_min = 1

145 nhóm chưa đạt l=2

Strategy Hours3 + Edu3:

l_min = 1

94 nhóm chưa đạt l=2

In [605]:
# Tính số bản ghi của từng equivalence class
# trong strategy Edu3 sau khi đã suppression để đạt k=5
group_sizes_edu3_after_suppression = (
    data_country2_hours3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )
    .size()
)


# Tạo bảng gồm kích thước nhóm và giá trị l-diversity
# để biết mỗi nhóm vi phạm đang chứa bao nhiêu bản ghi
l_group_analysis_edu3 = pd.DataFrame({
    "group_size": group_sizes_edu3_after_suppression,
    "l_value": l_values_edu3
})


# Chỉ lấy các equivalence class chưa đạt l=2
l2_violating_groups_edu3 = (
    l_group_analysis_edu3[
        l_group_analysis_edu3["l_value"] < l_required
    ]
)


# Cộng tổng số bản ghi nằm trong các nhóm chưa đạt l=2
so_ban_ghi_vi_pham_l2_edu3 = int(
    l2_violating_groups_edu3["group_size"].sum()
)


# Tính tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2
ty_le_ban_ghi_vi_pham_l2_edu3 = (
    so_ban_ghi_vi_pham_l2_edu3
    / len(data_country2_hours3_edu3_suppressed)
    * 100
)


# Hiển thị kết quả
print(
    "Số equivalence class chưa đạt l=2:",
    len(l2_violating_groups_edu3)
)

print(
    "Số bản ghi nằm trong các nhóm chưa đạt l=2:",
    so_ban_ghi_vi_pham_l2_edu3
)

print(
    "Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2:",
    round(ty_le_ban_ghi_vi_pham_l2_edu3, 2),
    "%"
)

Số equivalence class chưa đạt l=2: 94
Số bản ghi nằm trong các nhóm chưa đạt l=2: 3416
Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2: 10.76 %

In [606]:
# Tính giá trị l-diversity tương ứng cho từng bản ghi
# Các bản ghi cùng một equivalence class sẽ có cùng giá trị l
l_value_per_record_edu3 = (
    data_country2_hours3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )["thu_nhap"]
    .transform("nunique")
)


# Đánh dấu những bản ghi nằm trong equivalence class chưa đạt l=2
l2_violation_mask_edu3 = (
    l_value_per_record_edu3 < l_required
)


# Lấy riêng các bản ghi chưa đạt l=2
# Dùng copy để không làm thay đổi dataset đã đạt k=5
violating_l2_records_edu3 = (
    data_country2_hours3_edu3_suppressed
    .loc[l2_violation_mask_edu3]
    .copy()
)


# Gắn giá trị l vào từng bản ghi để tiện phân tích ở bước sau
violating_l2_records_edu3["l_value"] = (
    l_value_per_record_edu3[
        l2_violation_mask_edu3
    ]
)


# Kiểm tra số lượng bản ghi chưa đạt l=2
print(
    "Số bản ghi chưa đạt l=2 của Edu3:",
    len(violating_l2_records_edu3)
)


# Kiểm tra các bản ghi vi phạm đang thuộc loại thu nhập nào
print("\nPhân bố thu nhập:")
print(
    violating_l2_records_edu3["thu_nhap"]
    .value_counts()
)

Số bản ghi chưa đạt l=2 của Edu3: 3416

Phân bố thu nhập:
thu_nhap
<=50K    3411
>50K        5
Name: count, dtype: int64

In [607]:
# Tạo danh sách để lưu kết quả phân tích rủi ro l=2 của từng QI
l2_risk_summary_edu3 = []


# Lần lượt phân tích từng QI trong strategy Edu3 hiện tại
for qi_column in candidate_qi_country2_hours3_agehigh_edu3:

    # Đếm tổng số bản ghi của từng nhóm giá trị QI
    # trên dataset Edu3 sau khi suppression để đạt k=5
    total_by_group = (
        data_country2_hours3_edu3_suppressed
        .groupby(qi_column, dropna=False)
        .size()
        .rename("tong_ban_ghi")
    )

    # Đếm số bản ghi chưa đạt l=2 trong từng nhóm giá trị QI
    violation_by_group = (
        violating_l2_records_edu3
        .groupby(qi_column, dropna=False)
        .size()
        .rename("so_ban_ghi_vi_pham_l2")
    )

    # Ghép tổng số bản ghi và số bản ghi vi phạm vào cùng một bảng
    l2_risk_table = (
        pd.concat(
            [total_by_group, violation_by_group],
            axis=1
        )
        .fillna(0)
    )

    # Tính tỷ lệ bản ghi vi phạm l=2 trong từng nhóm giá trị
    l2_risk_table["ty_le_vi_pham_l2_%"] = (
        l2_risk_table["so_ban_ghi_vi_pham_l2"]
        / l2_risk_table["tong_ban_ghi"]
        * 100
    )

    # Tìm nhóm giá trị có tỷ lệ vi phạm l=2 cao nhất của QI hiện tại
    highest_risk_group = (
        l2_risk_table
        .sort_values(
            "ty_le_vi_pham_l2_%",
            ascending=False
        )
        .iloc[0]
    )

    # Lưu nhóm rủi ro cao nhất của QI hiện tại vào danh sách
    l2_risk_summary_edu3.append(
        {
            "QI": qi_column,
            "nhom_rui_ro_cao_nhat": highest_risk_group.name,
            "tong_ban_ghi_nhom": int(
                highest_risk_group["tong_ban_ghi"]
            ),
            "so_ban_ghi_vi_pham_l2": int(
                highest_risk_group["so_ban_ghi_vi_pham_l2"]
            ),
            "ty_le_vi_pham_l2_%": round(
                highest_risk_group["ty_le_vi_pham_l2_%"],
                2
            )
        }
    )


# Chuyển kết quả thành DataFrame để dễ xem
l2_risk_summary_edu3 = pd.DataFrame(
    l2_risk_summary_edu3
)


# Sắp xếp từ nhóm có tỷ lệ vi phạm l=2 cao nhất xuống thấp nhất
l2_risk_summary_edu3 = (
    l2_risk_summary_edu3
    .sort_values(
        "ty_le_vi_pham_l2_%",
        ascending=False
    )
    .reset_index(drop=True)
)


# Hiển thị bảng tổng hợp rủi ro l=2 của strategy Edu3
l2_risk_summary_edu3

,QI,nhom_rui_ro_cao_nhat,tong_ban_ghi_nhom,so_ban_ghi_vi_pham_l2,ty_le_vi_pham_l2_%
0,loai_cong_viec_nhom,Khong_ro,1741,866,49.74
1,nghe_nghiep_nhom_4,Khong_ro,1741,866,49.74
2,tuoi_nhom_high,10-29,9488,2574,27.13
3,quoc_gia_nhom_2,Khac_hoac_khong_ro,2945,664,22.55
4,hon_nhan_nhom_2,Khong_ket_hon_hien_tai,16708,3307,19.79
5,hoc_van_nhom_3,THPT_tro_xuong,14442,2414,16.72
6,gio_lam_nhom_3,1-40,22688,2859,12.60

In [608]:
# Tạo quy tắc generalization tuổi từ 4 nhóm xuống còn 3 nhóm
# Gộp 10-29 và 30-49 thành nhóm rộng hơn là 10-49
age_map_3 = {
    "10-29": "10-49",
    "30-49": "10-49",
    "50-69": "50-69",
    "70-99": "70-99"
}


# Tạo cột tuổi mới để thử strategy tiếp theo
# Không ghi đè tuoi_nhom_high để còn so sánh với strategy cũ
data_anonymized["tuoi_nhom_3"] = (
    data_anonymized["tuoi_nhom_high"]
    .map(age_map_3)
)


# Kiểm tra số lượng bản ghi trong từng nhóm tuổi mới
data_anonymized["tuoi_nhom_3"].value_counts(dropna=False)

tuoi_nhom_3
10-49    25499
50-69     6433
70-99      629
Name: count, dtype: int64

In [609]:
# Tạo bộ QI cho strategy mới
# Giữ nguyên Country2, Hours3 và Edu3
# Chỉ thay tuoi_nhom_high bằng tuoi_nhom_3
candidate_qi_country2_hours3_age3_edu3 = [
    "tuoi_nhom_3",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Đánh giá k-anonymity của strategy Age3 trên toàn bộ dữ liệu
# Chưa suppression để xem riêng việc generalize tuổi cải thiện được bao nhiêu
privacy_country2_hours3_age3_edu3 = evaluate_privacy(
    data_anonymized,
    candidate_qi_country2_hours3_age3_edu3,
    k_required=5
)


# Hiển thị kết quả đánh giá privacy của strategy mới
privacy_country2_hours3_age3_edu3

{'so_equivalence_class': 682,
 'k_min': 1,
 'so_nhom_co_lap': 137,
 'ty_le_co_lap_%': 0.42,
 'so_ban_ghi_vi_pham_k5': 557,
 'ty_le_vi_pham_k5_%': 1.71}

In [610]:
# Tính kích thước equivalence class tương ứng cho từng bản ghi
# theo strategy Country2 + Hours3 + Age3 + Edu3
group_size_per_record_age3_edu3 = (
    data_anonymized
    .groupby(
        candidate_qi_country2_hours3_age3_edu3,
        dropna=False
    )["tuoi"]
    .transform("size")
)


# Đánh dấu các bản ghi đang nằm trong nhóm có kích thước nhỏ hơn k=5
violation_mask_age3_edu3 = (
    group_size_per_record_age3_edu3 < k_required
)


# Tạo dataset mới sau suppression
# Không sửa data_anonymized để còn dùng so sánh các strategy
data_country2_hours3_age3_edu3_suppressed = (
    data_anonymized
    .loc[~violation_mask_age3_edu3]
    .copy()
)


# Tính số bản ghi bị suppression
so_suppression_age3_edu3 = (
    len(data_anonymized)
    - len(data_country2_hours3_age3_edu3_suppressed)
)


# Hiển thị số bản ghi ban đầu
print(
    "Số bản ghi ban đầu:",
    len(data_anonymized)
)


# Hiển thị số bản ghi bị suppression
print(
    "Số bản ghi bị suppression:",
    so_suppression_age3_edu3
)


# Hiển thị số bản ghi còn lại sau suppression
print(
    "Số bản ghi còn lại:",
    len(data_country2_hours3_age3_edu3_suppressed)
)


# Tính và hiển thị tỷ lệ suppression
print(
    "Tỷ lệ suppression:",
    round(
        so_suppression_age3_edu3
        / len(data_anonymized)
        * 100,
        2
    ),
    "%"
)

Số bản ghi ban đầu: 32561
Số bản ghi bị suppression: 557
Số bản ghi còn lại: 32004
Tỷ lệ suppression: 1.71 %

In [611]:
# Đánh giá lại k-anonymity trên dữ liệu Age3 + Edu3 sau suppression
privacy_age3_edu3_after_suppression = evaluate_privacy(
    data_country2_hours3_age3_edu3_suppressed,
    candidate_qi_country2_hours3_age3_edu3,
    k_required=5
)


# Hiển thị kết quả để kiểm tra strategy mới có thật sự đạt k=5 hay chưa
privacy_age3_edu3_after_suppression

{'so_equivalence_class': 395,
 'k_min': 5,
 'so_nhom_co_lap': 0,
 'ty_le_co_lap_%': 0.0,
 'so_ban_ghi_vi_pham_k5': 0,
 'ty_le_vi_pham_k5_%': 0.0}

Kiểm tra l_m

In [612]:
# Đặt ngưỡng l-diversity cần kiểm tra
# Vì thu_nhap chỉ có 2 giá trị nên tiếp tục sử dụng l = 2
l_required = 2


# Với mỗi equivalence class của strategy Age3 + Edu3,
# đếm xem có bao nhiêu giá trị thu_nhap khác nhau
l_values_age3_edu3 = (
    data_country2_hours3_age3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_age3_edu3,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất trong toàn bộ dataset
l_min_age3_edu3 = int(
    l_values_age3_edu3.min()
)


# Đếm số equivalence class chưa đạt l = 2
so_nhom_vi_pham_l2_age3_edu3 = int(
    (l_values_age3_edu3 < l_required).sum()
)


# Đếm số equivalence class có l = 1 hoặc l = 2
l_distribution_age3_edu3 = (
    l_values_age3_edu3
    .value_counts()
    .sort_index()
)


# Hiển thị kết quả kiểm tra l-diversity
print(
    "l_min:",
    l_min_age3_edu3
)

print(
    "Số equivalence class chưa đạt l=2:",
    so_nhom_vi_pham_l2_age3_edu3
)

print("\nPhân bố l-diversity:")
print(
    l_distribution_age3_edu3
)

l_min: 1
Số equivalence class chưa đạt l=2: 56

Phân bố l-diversity:
thu_nhap
1     56
2    339
Name: count, dtype: int64

In [613]:
# Tính số bản ghi của từng equivalence class
# trong strategy Age3 + Edu3 sau suppression
group_sizes_age3_edu3_after_suppression = (
    data_country2_hours3_age3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_age3_edu3,
        dropna=False
    )
    .size()
)


# Tạo bảng gồm kích thước nhóm và giá trị l-diversity
l_group_analysis_age3_edu3 = pd.DataFrame({
    "group_size": group_sizes_age3_edu3_after_suppression,
    "l_value": l_values_age3_edu3
})


# Chỉ lấy các equivalence class chưa đạt l=2
l2_violating_groups_age3_edu3 = (
    l_group_analysis_age3_edu3[
        l_group_analysis_age3_edu3["l_value"] < l_required
    ]
)


# Cộng tổng số bản ghi nằm trong các nhóm chưa đạt l=2
so_ban_ghi_vi_pham_l2_age3_edu3 = int(
    l2_violating_groups_age3_edu3["group_size"].sum()
)


# Tính tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2
ty_le_ban_ghi_vi_pham_l2_age3_edu3 = (
    so_ban_ghi_vi_pham_l2_age3_edu3
    / len(data_country2_hours3_age3_edu3_suppressed)
    * 100
)


# Hiển thị kết quả
print(
    "Số equivalence class chưa đạt l=2:",
    len(l2_violating_groups_age3_edu3)
)

print(
    "Số bản ghi nằm trong các nhóm chưa đạt l=2:",
    so_ban_ghi_vi_pham_l2_age3_edu3
)

print(
    "Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2:",
    round(ty_le_ban_ghi_vi_pham_l2_age3_edu3, 2),
    "%"
)

Số equivalence class chưa đạt l=2: 56
Số bản ghi nằm trong các nhóm chưa đạt l=2: 1400
Tỷ lệ bản ghi nằm trong các nhóm chưa đạt l=2: 4.37 %

In [614]:
# Tính giá trị l-diversity tương ứng cho từng bản ghi
# Các bản ghi cùng một equivalence class sẽ nhận cùng giá trị l
l_value_per_record_age3_edu3 = (
    data_country2_hours3_age3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_age3_edu3,
        dropna=False
    )["thu_nhap"]
    .transform("nunique")
)


# Đánh dấu các bản ghi nằm trong equivalence class chưa đạt l=2
l2_violation_mask_age3_edu3 = (
    l_value_per_record_age3_edu3 < l_required
)


# Tạo dataset mới bằng cách loại toàn bộ các nhóm chưa đạt l=2
# Không sửa dataset cũ để còn dùng so sánh strategy
data_country2_hours3_age3_edu3_l2_suppressed = (
    data_country2_hours3_age3_edu3_suppressed
    .loc[~l2_violation_mask_age3_edu3]
    .copy()
)


# Tính số bản ghi bị suppression thêm để đạt l=2
so_suppression_them_l2 = (
    len(data_country2_hours3_age3_edu3_suppressed)
    - len(data_country2_hours3_age3_edu3_l2_suppressed)
)


# Tính tổng số bản ghi đã bị suppression tính từ dataset ban đầu
tong_suppression = (
    len(data_anonymized)
    - len(data_country2_hours3_age3_edu3_l2_suppressed)
)


# Hiển thị kết quả suppression thêm cho l-diversity
print(
    "Số bản ghi suppression thêm để xử lý l=2:",
    so_suppression_them_l2
)

print(
    "Tổng số bản ghi suppression từ dữ liệu ban đầu:",
    tong_suppression
)

print(
    "Số bản ghi còn lại:",
    len(data_country2_hours3_age3_edu3_l2_suppressed)
)

print(
    "Tỷ lệ suppression tổng:",
    round(
        tong_suppression / len(data_anonymized) * 100,
        2
    ),
    "%"
)

Số bản ghi suppression thêm để xử lý l=2: 1400
Tổng số bản ghi suppression từ dữ liệu ban đầu: 1957
Số bản ghi còn lại: 30604
Tỷ lệ suppression tổng: 6.01 %

In [615]:
# Đánh giá lại k-anonymity trên dataset sau khi suppression cả k=5 và l=2
privacy_final_candidate = evaluate_privacy(
    data_country2_hours3_age3_edu3_l2_suppressed,
    candidate_qi_country2_hours3_age3_edu3,
    k_required=5
)


# Với mỗi equivalence class còn lại,
# đếm số giá trị thu_nhap khác nhau để kiểm tra l-diversity
l_values_final_candidate = (
    data_country2_hours3_age3_edu3_l2_suppressed
    .groupby(
        candidate_qi_country2_hours3_age3_edu3,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất của dataset sau cùng
l_min_final_candidate = int(
    l_values_final_candidate.min()
)


# Đếm số equivalence class còn vi phạm l=2
so_nhom_vi_pham_l2_final = int(
    (l_values_final_candidate < 2).sum()
)


# Hiển thị kết quả k-anonymity
print("KẾT QUẢ K-ANONYMITY:")
print("k_min:", privacy_final_candidate["k_min"])
print(
    "Số bản ghi vi phạm k=5:",
    privacy_final_candidate["so_ban_ghi_vi_pham_k5"]
)


# Hiển thị kết quả l-diversity
print("\nKẾT QUẢ L-DIVERSITY:")
print("l_min:", l_min_final_candidate)
print(
    "Số equivalence class vi phạm l=2:",
    so_nhom_vi_pham_l2_final
)

KẾT QUẢ K-ANONYMITY:
k_min: 5
Số bản ghi vi phạm k=5: 0

KẾT QUẢ L-DIVERSITY:
l_min: 2
Số equivalence class vi phạm l=2: 0

Giữ lại các cột dữ liệu để ml
    "tuoi_nhom_3",

    "loai_cong_viec_nhom",

    "hoc_van_nhom_3",

    "hon_nhan_nhom_2",

    "nghe_nghiep_nhom_4",

    "gio_lam_nhom_3",

    "quoc_gia_nhom_2"

thêm cột thu_n

Tạo lại cột dữ liệu mới, chỉ dữ lại những cột đã được phép dùng sau ẩn da

In [616]:
# Tạo danh sách các cột được phép giữ lại trong dữ liệu ẩn danh
# Gồm 7 QI đã được generalization và cột thu_nhap dùng làm thuộc tính nhạy cảm / nhãn ML
release_columns = (
    candidate_qi_country2_hours3_age3_edu3
    + ["thu_nhap"]
)


# Tạo dataset sạch chỉ chứa các cột đã được phép phát hành
# Không giữ các cột QI gốc chi tiết như tuoi, gio_lam_moi_tuan, quoc_gia...
data_release_candidate = (
    data_country2_hours3_age3_edu3_l2_suppressed[
        release_columns
    ]
    .copy()
)


# Kiểm tra kích thước dataset sạch
print(
    "Kích thước dữ liệu phát hành:",
    data_release_candidate.shape
)


# Hiển thị danh sách các cột còn lại
print("\nCác cột trong dữ liệu phát hành:")
print(
    data_release_candidate.columns.tolist()
)


# Hiển thị 5 bản ghi đầu tiên để kiểm tra
data_release_candidate.head()

Kích thước dữ liệu phát hành: (30604, 8)

Các cột trong dữ liệu phát hành:
['tuoi_nhom_3', 'loai_cong_viec_nhom', 'hoc_van_nhom_3', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_3', 'quoc_gia_nhom_2', 'thu_nhap']

,tuoi_nhom_3,loai_cong_viec_nhom,hoc_van_nhom_3,hon_nhan_nhom_2,nghe_nghiep_nhom_4,gio_lam_nhom_3,quoc_gia_nhom_2,thu_nhap
0,70-99,Khong_ro,THPT_tro_xuong,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
1,70-99,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K
2,50-69,Khong_ro,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
3,50-69,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,1-40,Hoa_Ky,<=50K
4,10-49,Tu_nhan,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K

In [617]:
# Lấy chỉ số gốc của 30.604 bản ghi còn lại sau quá trình suppression
retained_row_indices = (
    data_country2_hours3_age3_edu3_l2_suppressed
    .index
    .to_series()
    .reset_index(drop=True)
)


# Đặt tên cột để sau này biết đây là vị trí của bản ghi trong dataset gốc
retained_row_indices.name = "original_row_index"


# Tạo đường dẫn để lưu danh sách chỉ số vào thư mục dữ liệu đã xử lý
retained_indices_path = Path(
    "../data/processed_da_xu_li/retained_row_indices_k5_l2.csv"
)


# Lưu danh sách chỉ số xuống file CSV
# index=False để không tạo thêm cột số thứ tự thừa
retained_row_indices.to_csv(
    retained_indices_path,
    index=False,
    encoding="utf-8-sig"
)


# Kiểm tra số lượng bản ghi được giữ lại
print(
    "Số bản ghi được giữ lại:",
    len(retained_row_indices)
)


# Hiển thị vị trí file vừa lưu
print(
    "Đã lưu tại:",
    retained_indices_path.resolve()
)

Số bản ghi được giữ lại: 30604
Đã lưu tại: D:\Do_an_project\data\processed_da_xu_li\retained_row_indices_k5_l2.csv

Lưu file chứa dữ liệu sau khi ẩn dữ liệu s

In [618]:
# Tạo đường dẫn đến file checkpoint của dữ liệu ẩn danh hiện tại
release_path = Path(
    "../data/processed_da_xu_li/anonymized_candidate_k5_l2.csv"
)


# Lưu dữ liệu phát hành sạch ra file CSV
data_release_candidate.to_csv(
    release_path,
    index=False,
    encoding="utf-8-sig"
)


# Hiển thị đường dẫn để xác nhận file đã được lưu
print("Đã lưu dữ liệu tại:")
print(release_path.resolve())

Đã lưu dữ liệu tại:
D:\Do_an_project\data\processed_da_xu_li\anonymized_candidate_k5_l2.csv

In [619]:
# Tính lại giá trị l-diversity cho từng bản ghi
# của strategy Country2 + Hours3 + AgeHigh + Edu3 sau khi đã đạt k=5
l_value_per_record_strategy2 = (
    data_country2_hours3_edu3_suppressed
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )["thu_nhap"]
    .transform("nunique")
)


# Đánh dấu các bản ghi nằm trong equivalence class chưa đạt l=2
l2_violation_mask_strategy2 = (
    l_value_per_record_strategy2 < 2
)


# Tạo dữ liệu cuối của Strategy 2
# Loại nguyên các equivalence class còn vi phạm l=2
data_strategy2_k5_l2 = (
    data_country2_hours3_edu3_suppressed
    .loc[~l2_violation_mask_strategy2]
    .copy()
)


# Tính số bản ghi phải suppression thêm để đạt l=2
so_suppression_them_strategy2 = int(
    l2_violation_mask_strategy2.sum()
)


# Tính tổng số bản ghi bị suppression so với dữ liệu ban đầu
tong_suppression_strategy2 = (
    len(data_anonymized)
    - len(data_strategy2_k5_l2)
)


# Tính tỷ lệ suppression tổng của Strategy 2
ty_le_suppression_strategy2 = (
    tong_suppression_strategy2
    / len(data_anonymized)
    * 100
)


# Hiển thị kết quả để kiểm tra Strategy 2
print(
    "Suppression thêm để đạt l=2:",
    so_suppression_them_strategy2
)

print(
    "Tổng số bản ghi suppression:",
    tong_suppression_strategy2
)

print(
    "Số bản ghi còn lại:",
    len(data_strategy2_k5_l2)
)

print(
    "Tỷ lệ suppression tổng:",
    round(ty_le_suppression_strategy2, 2),
    "%"
)

Suppression thêm để đạt l=2: 3416
Tổng số bản ghi suppression: 4226
Số bản ghi còn lại: 28335
Tỷ lệ suppression tổng: 12.98 %

In [620]:
# Đánh giá lại k-anonymity trên dữ liệu cuối của Strategy 2
privacy_strategy2 = evaluate_privacy(
    data_strategy2_k5_l2,
    candidate_qi_country2_hours3_agehigh_edu3,
    k_required=5
)


# Với mỗi equivalence class của Strategy 2,
# đếm số giá trị thu_nhap khác nhau để kiểm tra l-diversity
l_values_strategy2 = (
    data_strategy2_k5_l2
    .groupby(
        candidate_qi_country2_hours3_agehigh_edu3,
        dropna=False
    )["thu_nhap"]
    .nunique(dropna=False)
)


# Tìm giá trị l nhỏ nhất của toàn bộ Strategy 2
l_min_strategy2 = int(
    l_values_strategy2.min()
)


# Đếm số equivalence class còn vi phạm l=2
so_nhom_vi_pham_l2_strategy2 = int(
    (l_values_strategy2 < 2).sum()
)


# Hiển thị kết quả kiểm tra k-anonymity
print("KẾT QUẢ K-ANONYMITY - STRATEGY 2")
print(
    "k_min:",
    privacy_strategy2["k_min"]
)
print(
    "Số bản ghi vi phạm k=5:",
    privacy_strategy2["so_ban_ghi_vi_pham_k5"]
)


# Hiển thị kết quả kiểm tra l-diversity
print("\nKẾT QUẢ L-DIVERSITY - STRATEGY 2")
print(
    "l_min:",
    l_min_strategy2
)
print(
    "Số equivalence class vi phạm l=2:",
    so_nhom_vi_pham_l2_strategy2
)

KẾT QUẢ K-ANONYMITY - STRATEGY 2
k_min: 5
Số bản ghi vi phạm k=5: 0

KẾT QUẢ L-DIVERSITY - STRATEGY 2
l_min: 2
Số equivalence class vi phạm l=2: 0

Strategy 2 đạt cả k-anonymity với k=5 và l-diversity với l=2. Không còn bản ghi vi phạm k=5 và không còn equivalence class vi phạm l=2. Do đó Strategy 2 đáp ứng các điều kiện Privacy đã đặt ra.

In [621]:
# Tạo danh sách 7 cột QI đã được generalization của Strategy 2
# Strategy 2 vẫn dùng tuoi_nhom_high, chưa gộp tuổi thành tuoi_nhom_3
strategy2_release_columns = [
    "tuoi_nhom_high",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2",
    "thu_nhap"
]


# Tạo dataset phát hành sạch cho Strategy 2
# Chỉ giữ các cột đã generalization và cột thu_nhap
# Không giữ các cột gốc chi tiết như tuoi, gio_lam_moi_tuan, quoc_gia...
data_release_strategy2 = (
    data_strategy2_k5_l2[
        strategy2_release_columns
    ]
    .copy()
)


# Kiểm tra kích thước dataset Strategy 2 sau khi làm sạch
print(
    "Kích thước dữ liệu phát hành Strategy 2:",
    data_release_strategy2.shape
)


# Hiển thị danh sách các cột còn lại
print(
    "\nCác cột trong Strategy 2:"
)

print(
    data_release_strategy2.columns.tolist()
)

Kích thước dữ liệu phát hành Strategy 2: (28335, 8)

Các cột trong Strategy 2:
['tuoi_nhom_high', 'loai_cong_viec_nhom', 'hoc_van_nhom_3', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_3', 'quoc_gia_nhom_2', 'thu_nhap']

In [622]:
#Lưu file kết quả lại
# Tạo đường dẫn để lưu dữ liệu ẩn danh của Strategy 2
strategy2_release_path = Path(
    "../data/processed_da_xu_li/anonymized_strategy2_k5_l2.csv"
)


# Lưu bản dữ liệu phát hành sạch của Strategy 2 xuống file CSV
# index=False để không tạo thêm cột số thứ tự thừa
# utf-8-sig giúp file hiển thị tiếng Việt đúng khi mở bằng Excel
data_release_strategy2.to_csv(
    strategy2_release_path,
    index=False,
    encoding="utf-8-sig"
)


# Hiển thị đường dẫn để kiểm tra file đã được lưu thành công
print(
    "Đã lưu Strategy 2 tại:",
    strategy2_release_path.resolve()
)


# Kiểm tra số lượng bản ghi đã lưu
print(
    "Số bản ghi Strategy 2:",
    len(data_release_strategy2)
)

Đã lưu Strategy 2 tại: D:\Do_an_project\data\processed_da_xu_li\anonymized_strategy2_k5_l2.csv
Số bản ghi Strategy 2: 28335

In [623]:
# Lấy chỉ số gốc của 28.335 bản ghi còn lại trong Strategy 2
# Những chỉ số này giúp tìm lại đúng các bản ghi tương ứng trong dataset gốc
retained_indices_strategy2 = (
    data_strategy2_k5_l2
    .index
    .to_series()
    .reset_index(drop=True)
)


# Đặt tên cột để sau này đọc lại dễ hiểu
retained_indices_strategy2.name = "original_row_index"


# Tạo đường dẫn đến file lưu chỉ số của Strategy 2
strategy2_indices_path = Path(
    "../data/processed_da_xu_li/retained_row_indices_strategy2_k5_l2.csv"
)


# Lưu danh sách chỉ số xuống file CSV
# File này chỉ dùng nội bộ để ghép đúng dữ liệu gốc khi đánh giá Machine Learning
retained_indices_strategy2.to_csv(
    strategy2_indices_path,
    index=False,
    encoding="utf-8-sig"
)


# Kiểm tra số lượng chỉ số đã lưu
# Kết quả phải bằng đúng số bản ghi còn lại của Strategy 2
print(
    "Số chỉ số Strategy 2 đã lưu:",
    len(retained_indices_strategy2)
)


# Hiển thị vị trí file vừa được tạo
print(
    "Đã lưu file chỉ số Strategy 2 tại:",
    strategy2_indices_path.resolve()
)

Số chỉ số Strategy 2 đã lưu: 28335
Đã lưu file chỉ số Strategy 2 tại: D:\Do_an_project\data\processed_da_xu_li\retained_row_indices_strategy2_k5_l2.csv

In [624]:
# Import sys để Python có thể quản lý các thư mục dùng để tìm module
import sys

# Import Path để tạo đường dẫn đến file và thư mục dễ dàng hơn
from pathlib import Path

# Import pandas để đọc file CSV đã lưu
import pandas as pd


# Tạo đường dẫn đến thư mục src
# Notebook đang nằm trong notebooks nên ../src nghĩa là:
# đi ra khỏi notebooks một cấp rồi đi vào thư mục src
src_path = Path("../src").resolve()


# Kiểm tra thư mục src đã có trong danh sách tìm kiếm module của Python chưa
if str(src_path) not in sys.path:

    # Nếu chưa có thì thêm src vào sys.path
    # Nhờ vậy Python mới tìm thấy file privacy_analyzer.py
    sys.path.append(
        str(src_path)
    )


# Import hàm evaluate_privacy từ file src/privacy_analyzer.py
# Đổi tên thành evaluate_privacy_from_src để dễ nhận biết
# đây là hàm lấy từ code hệ thống, không phải hàm cũ trong notebook
from privacy_analyzer import evaluate_privacy as evaluate_privacy_from_src


# Tạo đường dẫn đến dataset Strategy 1 đã lưu trên ổ cứng
# Đây là dữ liệu cuối đã qua generalization + suppression
strategy1_path = Path(
    "../data/processed_da_xu_li/anonymized_candidate_k5_l2.csv"
)


# Đọc dataset Strategy 1 từ file CSV vào RAM
# Như vậy không cần biến cũ data_country2_hours3_age3_edu3_l2_suppressed
data_strategy1_test = pd.read_csv(
    strategy1_path,
    encoding="utf-8-sig"
)


# Khai báo lại 7 cột QI của Strategy 1
# Đây là các cột đã được generalization dùng để kiểm tra k-anonymity
qi_strategy1 = [
    "tuoi_nhom_3",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Gọi hàm evaluate_privacy nằm trong file src/privacy_analyzer.py
# dataframe là dataset Strategy 1 vừa đọc từ CSV
# qi_columns là 7 cột QI của Strategy 1
# k_required=5 nghĩa là yêu cầu mỗi nhóm QI phải có ít nhất 5 bản ghi
privacy_test_from_src = evaluate_privacy_from_src(
    data_strategy1_test,
    qi_strategy1,
    k_required=5
)


# Hiển thị kết quả để kiểm tra hàm trong src có chạy đúng hay không
print(
    privacy_test_from_src
)

{'so_equivalence_class': 339, 'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_nhom_1_ban_ghi': 0, 'so_ban_ghi_bi_co_lap': 0, 'ty_le_bi_co_lap_%': 0.0, 'so_nhom_vi_pham_k': 0, 'so_ban_ghi_vi_pham_k': 0, 'ty_le_ban_ghi_vi_pham_k_%': 0.0, 'so_nhom_vi_pham_k5': 0, 'so_ban_ghi_vi_pham_k5': 0, 'ty_le_vi_pham_k5_%': 0.0}

In [625]:
# Import importlib để có thể nạp lại file privacy_analyzer.py
# Việc reload cần thiết vì file này vừa được bổ sung hàm mới
import importlib


# Import toàn bộ module privacy_analyzer từ thư mục src
# Trước đó notebook đã thêm thư mục src vào sys.path rồi
import privacy_analyzer


# Nạp lại phiên bản mới nhất của privacy_analyzer.py
# Nhờ vậy notebook nhận được hàm evaluate_l_diversity() vừa thêm
importlib.reload(
    privacy_analyzer
)


# Gọi hàm evaluate_l_diversity() nằm trong file src/privacy_analyzer.py
# data_strategy1_test là Strategy 1 đã đọc lại từ file CSV
l_diversity_test_from_src = privacy_analyzer.evaluate_l_diversity(

    # Dataset cuối của Strategy 1
    dataframe=data_strategy1_test,

    # 7 cột QI dùng để tạo equivalence class
    qi_columns=qi_strategy1,

    # Cột thu_nhap là thuộc tính nhạy cảm cần kiểm tra
    sensitive_column="thu_nhap",

    # Yêu cầu mỗi equivalence class phải có ít nhất 2 giá trị thu_nhap khác nhau
    l_required=2
)


# Hiển thị kết quả do hàm trong src tính ra
print(
    l_diversity_test_from_src
)

{'so_equivalence_class': 339, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'ty_le_ban_ghi_vi_pham_l_%': 0.0}

In [626]:
# Import importlib để nạp lại phiên bản mới nhất của privacy_analyzer.py
# Vì chúng ta vừa thêm hàm evaluate_privacy_full() vào file
import importlib


# Import module privacy_analyzer từ thư mục src
# Notebook trước đó đã thêm thư mục src vào sys.path rồi
import privacy_analyzer


# Nạp lại file privacy_analyzer.py
# Giúp notebook nhận được hàm evaluate_privacy_full() vừa thêm
importlib.reload(
    privacy_analyzer
)


# Gọi hàm đánh giá Privacy tổng hợp từ file src
# Hàm này sẽ tự kiểm tra cả k-anonymity và l-diversity
privacy_full_test = privacy_analyzer.evaluate_privacy_full(

    # Dataset Strategy 1 đã được đọc từ file CSV
    dataframe=data_strategy1_test,

    # Danh sách 7 cột QI của Strategy 1
    qi_columns=qi_strategy1,

    # Cột thu_nhap là thuộc tính nhạy cảm dùng để kiểm tra l-diversity
    sensitive_column="thu_nhap",

    # Yêu cầu mỗi equivalence class phải có ít nhất 5 bản ghi
    k_required=5,

    # Yêu cầu mỗi equivalence class phải có ít nhất 2 giá trị thu_nhap khác nhau
    l_required=2
)


# Hiển thị kết quả tổng hợp để kiểm tra hàm trong src
print(
    privacy_full_test
)

{'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_ban_ghi_vi_pham_k': 0, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'privacy_valid': True}

In [627]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine nằm trong thư mục src
# Notebook trước đó đã thêm thư mục src vào sys.path nên có thể import trực tiếp
import anonymization_engine


# Nạp lại module để chắc chắn notebook đang dùng code mới nhất
importlib.reload(
    anonymization_engine
)


# Tạo một danh sách tuổi mẫu để kiểm tra hàm generalization
# Các tuổi này được chọn để kiểm tra đủ cả 3 nhóm tuổi
test_ages = [
    25,
    49,
    50,
    69,
    70,
    90
]


# Lần lượt lấy từng tuổi trong danh sách test_ages
for age in test_ages:

    # Gọi hàm generalize_age_3() trong file anonymization_engine.py
    # Hàm sẽ biến tuổi cụ thể thành một khoảng tuổi
    age_group = anonymization_engine.generalize_age_3(
        age
    )

    # Hiển thị tuổi gốc và nhóm tuổi sau generalization
    print(
        age,
        "→",
        age_group
    )

25 → 10-49
49 → 10-49
50 → 50-69
69 → 50-69
70 → 70-99
90 → 70-99

In [628]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
# Vì chúng ta vừa thêm hàm generalize_hours_3()
import importlib


# Import module anonymization_engine từ thư mục src
import anonymization_engine


# Nạp lại module để notebook sử dụng đúng code mới nhất
importlib.reload(
    anonymization_engine
)


# Tạo các giá trị giờ làm mẫu để kiểm tra
# Đặc biệt kiểm tra các ranh giới 40/41 và 60/61
test_hours = [
    20,
    40,
    41,
    60,
    61,
    90
]


# Lần lượt kiểm tra từng giá trị giờ làm
for hours in test_hours:

    # Gọi hàm generalize_hours_3() trong anonymization_engine.py
    # Hàm sẽ chuyển số giờ cụ thể thành một khoảng giờ
    hours_group = anonymization_engine.generalize_hours_3(
        hours
    )

    # Hiển thị giờ gốc và nhóm giờ sau generalization
    print(
        hours,
        "→",
        hours_group
    )

20 → 1-40
40 → 1-40
41 → 41-60
60 → 41-60
61 → 61-100
90 → 61-100

In [629]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
# Vì chúng ta vừa thêm hàm generalize_education_3()
import importlib


# Import module anonymization_engine từ thư mục src
import anonymization_engine


# Nạp lại module để notebook sử dụng đúng code mới nhất
importlib.reload(
    anonymization_engine
)


# Tạo một số giá trị so_nam_hoc mẫu để kiểm tra
# Đặc biệt chọn các mốc 9/10 và 12/13 vì đây là ranh giới giữa các nhóm
test_education_nums = [
    8,
    9,
    10,
    12,
    13,
    16
]


# Lần lượt lấy từng giá trị học vấn để kiểm tra
for education_num in test_education_nums:

    # Gọi hàm generalize_education_3() trong anonymization_engine.py
    # Hàm sẽ chuyển mã học vấn thành một nhóm học vấn rộng hơn
    education_group = anonymization_engine.generalize_education_3(
        education_num
    )

    # Hiển thị giá trị gốc và nhóm học vấn sau generalization
    print(
        education_num,
        "→",
        education_group
    )

8 → THPT_tro_xuong
9 → THPT_tro_xuong
10 → Sau_THPT_Cao_dang
12 → Sau_THPT_Cao_dang
13 → Dai_hoc_tro_len
16 → Dai_hoc_tro_len

In [630]:
# Import pandas để đọc file CSV
import pandas as pd

# Import Path để tạo đường dẫn đến dataset
from pathlib import Path


# Tạo đường dẫn đến dataset gốc
# Notebook nằm trong thư mục notebooks nên ../data nghĩa là đi ra 1 cấp rồi vào data
dataset_check_path = Path(
    "../data/dataset_anonymization.csv"
)


# Đọc lại dataset gốc vào một biến riêng tên data_check
# Dùng tên mới để không phụ thuộc vào biến data cũ đã mất khỏi bộ nhớ
data_check = pd.read_csv(
    dataset_check_path,
    encoding="utf-8-sig"
)


# Đếm số lượng của từng giá trị trong cột tinh_trang_hon_nhan
# Mục đích là xem chính xác dataset đang dùng những tên trạng thái nào
marital_status_counts = (
    data_check["tinh_trang_hon_nhan"]
    .value_counts(
        dropna=False
    )
)


# Hiển thị toàn bộ các trạng thái hôn nhân và số bản ghi tương ứng
print(
    marital_status_counts
)

tinh_trang_hon_nhan
Ket_hon_dan_su               14976
Chua_ket_hon                 10683
Da_ly_hon                     4443
Ly_than                       1025
Goa                            993
Ket_hon_vo_chong_vang_mat      418
Ket_hon_voi_quan_nhan           23
Name: count, dtype: int64

In [631]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
# Vì chúng ta vừa thêm hàm generalize_marital_2()
import importlib


# Import module anonymization_engine trong thư mục src
import anonymization_engine


# Nạp lại module để notebook sử dụng đúng code mới nhất
importlib.reload(
    anonymization_engine
)


# Tạo danh sách chứa đầy đủ 7 trạng thái hôn nhân có thật trong dataset
# Mục đích là kiểm tra không bỏ sót trường hợp nào
test_marital_statuses = [
    "Ket_hon_dan_su",
    "Chua_ket_hon",
    "Da_ly_hon",
    "Ly_than",
    "Goa",
    "Ket_hon_vo_chong_vang_mat",
    "Ket_hon_voi_quan_nhan"
]


# Lần lượt lấy từng trạng thái hôn nhân để kiểm tra
for marital_status in test_marital_statuses:

    # Gọi hàm generalize_marital_2() trong anonymization_engine.py
    # Hàm sẽ chuyển 7 trạng thái chi tiết thành 2 nhóm rộng hơn
    marital_group = anonymization_engine.generalize_marital_2(
        marital_status
    )

    # Hiển thị trạng thái gốc và nhóm sau generalization
    print(
        marital_status,
        "→",
        marital_group
    )

Ket_hon_dan_su → Da_ket_hon
Chua_ket_hon → Khong_ket_hon_hien_tai
Da_ly_hon → Khong_ket_hon_hien_tai
Ly_than → Khong_ket_hon_hien_tai
Goa → Khong_ket_hon_hien_tai
Ket_hon_vo_chong_vang_mat → Da_ket_hon
Ket_hon_voi_quan_nhan → Da_ket_hon

In [632]:
# Đếm số lượng của từng giá trị trong cột nghe_nghiep
# Mục đích là xem chính xác dataset đang dùng những tên nghề nghiệp nào
occupation_counts = (
    data_check["nghe_nghiep"]
    .value_counts(
        dropna=False
    )
)


# Hiển thị toàn bộ nghề nghiệp và số bản ghi tương ứng
# Ta sẽ dựa đúng vào các tên này để viết hàm generalize_occupation_4()
print(
    occupation_counts
)

nghe_nghiep
Chuyen_mon_dac_thu         4140
Tho_thu_cong_sua_chua      4099
Quan_ly_dieu_hanh          4066
Nhan_vien_van_phong        3770
Ban_hang                   3650
Dich_vu_khac               3295
Van_hanh_may_moc           2002
?                          1843
Van_tai                    1597
Boc_xep_don_dep            1370
Nong_nghiep_danh_bat_ca     994
Ho_tro_ky_thuat             928
Dich_vu_bao_ve              649
Giup_viec_gia_dinh          149
Quan_doi                      9
Name: count, dtype: int64

In [633]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine nằm trong thư mục src
import anonymization_engine


# Nạp lại module để notebook sử dụng đúng code mới nhất
# Vì chúng ta vừa thêm hàm generalize_occupation_4()
importlib.reload(
    anonymization_engine
)


# Tạo danh sách chứa đầy đủ 15 giá trị nghề nghiệp có thật trong dataset
# Mục đích là kiểm tra không bỏ sót bất kỳ nghề nào
test_occupations = [
    "Chuyen_mon_dac_thu",
    "Tho_thu_cong_sua_chua",
    "Quan_ly_dieu_hanh",
    "Nhan_vien_van_phong",
    "Ban_hang",
    "Dich_vu_khac",
    "Van_hanh_may_moc",
    "?",
    "Van_tai",
    "Boc_xep_don_dep",
    "Nong_nghiep_danh_bat_ca",
    "Ho_tro_ky_thuat",
    "Dich_vu_bao_ve",
    "Giup_viec_gia_dinh",
    "Quan_doi"
]


# Lần lượt lấy từng nghề nghiệp trong danh sách để kiểm tra
for occupation in test_occupations:

    # Gọi hàm generalize_occupation_4() trong anonymization_engine.py
    # Hàm sẽ chuyển nghề nghiệp chi tiết thành một trong 4 nhóm lớn
    occupation_group = anonymization_engine.generalize_occupation_4(
        occupation
    )

    # Hiển thị nghề nghiệp gốc và nhóm nghề sau generalization
    print(
        occupation,
        "→",
        occupation_group
    )

Chuyen_mon_dac_thu → Van_phong_chuyen_mon
Tho_thu_cong_sua_chua → Lao_dong_truc_tiep
Quan_ly_dieu_hanh → Van_phong_chuyen_mon
Nhan_vien_van_phong → Van_phong_chuyen_mon
Ban_hang → Van_phong_chuyen_mon
Dich_vu_khac → Dich_vu
Van_hanh_may_moc → Lao_dong_truc_tiep
? → Khong_ro
Van_tai → Lao_dong_truc_tiep
Boc_xep_don_dep → Lao_dong_truc_tiep
Nong_nghiep_danh_bat_ca → Lao_dong_truc_tiep
Ho_tro_ky_thuat → Van_phong_chuyen_mon
Dich_vu_bao_ve → Dich_vu
Giup_viec_gia_dinh → Dich_vu
Quan_doi → Dich_vu

In [634]:
# Đếm số lượng của từng giá trị trong cột loai_cong_viec
# Mục đích là xem chính xác dataset đang sử dụng những tên nào
workclass_counts = (
    data_check["loai_cong_viec"]
    .value_counts(
        dropna=False
    )
)


# Hiển thị toàn bộ loại công việc và số bản ghi tương ứng
# Ta sẽ dùng đúng các tên này để viết hàm generalization tiếp theo
print(
    workclass_counts
)

loai_cong_viec
Tu_nhan                        22696
Tu_kinh_doanh_khong_dang_ky     2541
Chinh_quyen_dia_phuong          2093
?                               1836
Chinh_quyen_bang                1298
Tu_kinh_doanh_co_dang_ky        1116
Chinh_phu_lien_bang              960
Khong_luong                       14
Chua_tung_lam_viec                 7
Name: count, dtype: int64

In [635]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module để notebook nhận hàm generalize_workclass_5() vừa thêm
importlib.reload(
    anonymization_engine
)


# Tạo danh sách chứa đầy đủ 9 giá trị loại công việc có thật trong dataset
# Mục đích là kiểm tra không bỏ sót bất kỳ trường hợp nào
test_workclasses = [
    "Tu_nhan",
    "Tu_kinh_doanh_khong_dang_ky",
    "Chinh_quyen_dia_phuong",
    "?",
    "Chinh_quyen_bang",
    "Tu_kinh_doanh_co_dang_ky",
    "Chinh_phu_lien_bang",
    "Khong_luong",
    "Chua_tung_lam_viec"
]


# Lần lượt lấy từng loại công việc trong danh sách để kiểm tra
for workclass in test_workclasses:

    # Gọi hàm generalize_workclass_5() để chuyển giá trị chi tiết thành nhóm rộng hơn
    workclass_group = anonymization_engine.generalize_workclass_5(
        workclass
    )

    # Hiển thị giá trị gốc và nhóm sau generalization
    print(
        workclass,
        "→",
        workclass_group
    )

Tu_nhan → Tu_nhan
Tu_kinh_doanh_khong_dang_ky → Tu_kinh_doanh
Chinh_quyen_dia_phuong → Nha_nuoc
? → Khong_ro
Chinh_quyen_bang → Nha_nuoc
Tu_kinh_doanh_co_dang_ky → Tu_kinh_doanh
Chinh_phu_lien_bang → Nha_nuoc
Khong_luong → Khong_luong_hoac_chua_lam
Chua_tung_lam_viec → Khong_luong_hoac_chua_lam

In [636]:
# Đếm số lượng của từng giá trị trong cột quoc_gia
# Mục đích là xem chính xác dataset đang sử dụng những tên quốc gia nào
country_counts = (
    data_check["quoc_gia"]
    .value_counts(
        dropna=False
    )
)


# Hiển thị toàn bộ quốc gia và số bản ghi tương ứng
# Ta sẽ dùng đúng các giá trị này để xây dựng generalize_country_2()
print(
    country_counts
)

quoc_gia
Hoa_Ky                   29170
Mexico                     643
?                          583
Philippines                198
Duc                        137
Canada                     121
Puerto_Rico                114
El_Salvador                106
An_Do                      100
Cuba                        95
Anh                         90
Jamaica                     81
Nam_Trieu_Tien              80
Trung_Quoc                  75
Y                           73
Cong_Hoa_Dominica           70
Viet_Nam                    67
Guatemala                   64
Nhat_Ban                    62
Ba_Lan                      60
Colombia                    59
Dai_Loan                    51
Haiti                       44
Iran                        43
Bo_Dao_Nha                  37
Nicaragua                   34
Peru                        31
Hy_Lap                      29
Phap                        29
Ecuador                     28
Ireland                     24
Hong_Kong                   20
Trinidad_va_Tobago          19
Campuchia                   19
Thai_Lan                    18
Lao                         18
Nam_Tu                      16
Lanh_tho_hai_ngoai_My       14
Hungary                     13
Honduras                    13
Scotland                    12
Ha_Lan                       1
Name: count, dtype: int64

In [637]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine chứa các hàm generalization
import anonymization_engine


# Nạp lại module để notebook nhận hàm generalize_country_2() vừa thêm
importlib.reload(
    anonymization_engine
)


# Tạo một số giá trị quốc gia thật trong dataset để kiểm tra
# Chọn Hoa_Ky, một số quốc gia khác và dấu ? để kiểm tra đủ hai nhánh của hàm
test_countries = [
    "Hoa_Ky",
    "Mexico",
    "Viet_Nam",
    "Canada",
    "Duc",
    "?"
]


# Lần lượt lấy từng quốc gia trong danh sách để kiểm tra
for country in test_countries:

    # Gọi hàm generalize_country_2() để chuyển quốc gia chi tiết thành nhóm rộng hơn
    country_group = anonymization_engine.generalize_country_2(
        country
    )

    # Hiển thị quốc gia gốc và nhóm sau generalization
    print(
        country,
        "→",
        country_group
    )

Hoa_Ky → Hoa_Ky
Mexico → Khac_hoac_khong_ro
Viet_Nam → Khac_hoac_khong_ro
Canada → Khac_hoac_khong_ro
Duc → Khac_hoac_khong_ro
? → Khac_hoac_khong_ro

In [638]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module để notebook nhận hàm apply_strategy_1_generalization() vừa thêm
importlib.reload(
    anonymization_engine
)


# Áp dụng toàn bộ 7 phép generalization của Strategy 1
# lên dataset gốc đang lưu trong biến data_check
generalized_strategy1_check = (
    anonymization_engine.apply_strategy_1_generalization(
        data_check
    )
)


# Hiển thị kích thước dataset gốc
# Dataset gốc của chúng ta có 15 cột
print(
    "Kích thước dữ liệu gốc:",
    data_check.shape
)


# Hiển thị kích thước sau khi generalization
# Vì hàm tạo thêm 7 cột mới nên dự kiến sẽ có 22 cột
print(
    "Kích thước sau generalization:",
    generalized_strategy1_check.shape
)


# Chọn các cột gốc và cột sau generalization để đối chiếu trực tiếp
columns_to_check = [
    "tuoi",
    "tuoi_nhom_3",
    "loai_cong_viec",
    "loai_cong_viec_nhom",
    "so_nam_hoc",
    "hoc_van_nhom_3",
    "tinh_trang_hon_nhan",
    "hon_nhan_nhom_2",
    "nghe_nghiep",
    "nghe_nghiep_nhom_4",
    "gio_lam_moi_tuan",
    "gio_lam_nhom_3",
    "quoc_gia",
    "quoc_gia_nhom_2"
]


# Hiển thị 10 bản ghi đầu tiên
# để kiểm tra giá trị gốc đã được chuyển sang nhóm mới như thế nào
display(
    generalized_strategy1_check[
        columns_to_check
    ].head(
        10
    )
)

Kích thước dữ liệu gốc: (32561, 15)
Kích thước sau generalization: (32561, 22)

,tuoi,tuoi_nhom_3,loai_cong_viec,loai_cong_viec_nhom,so_nam_hoc,hoc_van_nhom_3,tinh_trang_hon_nhan,hon_nhan_nhom_2,nghe_nghiep,nghe_nghiep_nhom_4,gio_lam_moi_tuan,gio_lam_nhom_3,quoc_gia,quoc_gia_nhom_2
0,90,70-99,?,Khong_ro,9,THPT_tro_xuong,Goa,Khong_ket_hon_hien_tai,?,Khong_ro,40,1-40,Hoa_Ky,Hoa_Ky
1,82,70-99,Tu_nhan,Tu_nhan,9,THPT_tro_xuong,Goa,Khong_ket_hon_hien_tai,Quan_ly_dieu_hanh,Van_phong_chuyen_mon,18,1-40,Hoa_Ky,Hoa_Ky
2,66,50-69,?,Khong_ro,10,Sau_THPT_Cao_dang,Goa,Khong_ket_hon_hien_tai,?,Khong_ro,40,1-40,Hoa_Ky,Hoa_Ky
3,54,50-69,Tu_nhan,Tu_nhan,4,THPT_tro_xuong,Da_ly_hon,Khong_ket_hon_hien_tai,Van_hanh_may_moc,Lao_dong_truc_tiep,40,1-40,Hoa_Ky,Hoa_Ky
4,41,10-49,Tu_nhan,Tu_nhan,10,Sau_THPT_Cao_dang,Ly_than,Khong_ket_hon_hien_tai,Chuyen_mon_dac_thu,Van_phong_chuyen_mon,40,1-40,Hoa_Ky,Hoa_Ky
5,34,10-49,Tu_nhan,Tu_nhan,9,THPT_tro_xuong,Da_ly_hon,Khong_ket_hon_hien_tai,Dich_vu_khac,Dich_vu,45,41-60,Hoa_Ky,Hoa_Ky
6,38,10-49,Tu_nhan,Tu_nhan,6,THPT_tro_xuong,Ly_than,Khong_ket_hon_hien_tai,Nhan_vien_van_phong,Van_phong_chuyen_mon,40,1-40,Hoa_Ky,Hoa_Ky
7,74,70-99,Chinh_quyen_bang,Nha_nuoc,16,Dai_hoc_tro_len,Chua_ket_hon,Khong_ket_hon_hien_tai,Chuyen_mon_dac_thu,Van_phong_chuyen_mon,20,1-40,Hoa_Ky,Hoa_Ky
8,68,50-69,Chinh_phu_lien_bang,Nha_nuoc,9,THPT_tro_xuong,Da_ly_hon,Khong_ket_hon_hien_tai,Chuyen_mon_dac_thu,Van_phong_chuyen_mon,40,1-40,Hoa_Ky,Hoa_Ky
9,41,10-49,Tu_nhan,Tu_nhan,10,Sau_THPT_Cao_dang,Chua_ket_hon,Khong_ket_hon_hien_tai,Tho_thu_cong_sua_chua,Lao_dong_truc_tiep,60,41-60,?,Khac_hoac_khong_ro

In [639]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa sửa hàm generalize_country_2()
importlib.reload(
    anonymization_engine
)


# Áp dụng 7 phép generalization của Strategy 1 lên dataset gốc
# Kết quả được lưu vào biến riêng để kiểm tra, chưa ghi ra file
generalized_strategy1_check = (
    anonymization_engine.apply_strategy_1_generalization(
        data_check
    )
)


# Đếm số bản ghi của từng nhóm quốc gia sau generalization
# Mục đích là kiểm tra Lanh_tho_hai_ngoai_My đã được nhập đúng vào Hoa_Ky
country2_counts = (
    generalized_strategy1_check["quoc_gia_nhom_2"]
    .value_counts(
        dropna=False
    )
)


# Hiển thị kết quả kiểm tra
print(
    country2_counts
)

quoc_gia_nhom_2
Hoa_Ky                29184
Khac_hoac_khong_ro     3377
Name: count, dtype: int64

In [640]:
# Import importlib để có thể nạp lại module privacy_analyzer mới nhất
import importlib


# Import module privacy_analyzer chứa hàm đánh giá k-anonymity
import privacy_analyzer


# Nạp lại module để notebook sử dụng phiên bản code hiện tại
importlib.reload(
    privacy_analyzer
)


# Khai báo 7 QI sau generalization của Strategy 1
# Đây chính là các thuộc tính dùng để tạo equivalence class
strategy1_qi_columns = [
    "tuoi_nhom_3",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Đánh giá mức độ k-anonymity của dữ liệu sau generalization
# k_required=5 nghĩa là mỗi equivalence class cần có ít nhất 5 bản ghi
strategy1_privacy_before_suppression = (
    privacy_analyzer.evaluate_privacy(
        generalized_strategy1_check,
        strategy1_qi_columns,
        k_required=5
    )
)


# Hiển thị kết quả đánh giá privacy trước khi suppression
print(
    strategy1_privacy_before_suppression
)

{'so_equivalence_class': 682, 'k_min': 1, 'k_required': 5, 'k_valid': False, 'so_nhom_1_ban_ghi': 137, 'so_ban_ghi_bi_co_lap': 137, 'ty_le_bi_co_lap_%': 0.42, 'so_nhom_vi_pham_k': 287, 'so_ban_ghi_vi_pham_k': 557, 'ty_le_ban_ghi_vi_pham_k_%': 1.71, 'so_nhom_vi_pham_k5': 287, 'so_ban_ghi_vi_pham_k5': 557, 'ty_le_vi_pham_k5_%': 1.71}

In [641]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine chứa hàm suppression vừa thêm
import anonymization_engine


# Nạp lại module để notebook nhận hàm suppress_k_anonymity() mới nhất
importlib.reload(
    anonymization_engine
)


# Thực hiện suppression các bản ghi nằm trong equivalence class có kích thước < 5
# Dữ liệu đầu vào là Strategy 1 sau generalization
strategy1_after_k_suppression = (
    anonymization_engine.suppress_k_anonymity(
        generalized_strategy1_check,
        strategy1_qi_columns,
        k_required=5
    )
)


# Lấy số bản ghi trước khi suppression
so_ban_ghi_truoc_k = len(
    generalized_strategy1_check
)


# Lấy số bản ghi còn lại sau khi suppression
so_ban_ghi_sau_k = len(
    strategy1_after_k_suppression
)


# Tính số bản ghi đã bị suppression
so_ban_ghi_suppression_k = (
    so_ban_ghi_truoc_k
    - so_ban_ghi_sau_k
)


# Hiển thị số bản ghi trước suppression
print(
    "Số bản ghi trước suppression:",
    so_ban_ghi_truoc_k
)


# Hiển thị số bản ghi bị suppression để đạt k=5
print(
    "Số bản ghi suppression k=5:",
    so_ban_ghi_suppression_k
)


# Hiển thị số bản ghi còn lại
print(
    "Số bản ghi còn lại:",
    so_ban_ghi_sau_k
)

Số bản ghi trước suppression: 32561
Số bản ghi suppression k=5: 557
Số bản ghi còn lại: 32004

In [642]:
# Đánh giá lại k-anonymity sau khi đã suppression
# Mục đích là xác nhận không còn equivalence class nào có kích thước nhỏ hơn 5
strategy1_privacy_after_k = (
    privacy_analyzer.evaluate_privacy(
        strategy1_after_k_suppression,
        strategy1_qi_columns,
        k_required=5
    )
)


# Hiển thị toàn bộ kết quả đánh giá sau suppression
print(
    strategy1_privacy_after_k
)

{'so_equivalence_class': 395, 'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_nhom_1_ban_ghi': 0, 'so_ban_ghi_bi_co_lap': 0, 'ty_le_bi_co_lap_%': 0.0, 'so_nhom_vi_pham_k': 0, 'so_ban_ghi_vi_pham_k': 0, 'ty_le_ban_ghi_vi_pham_k_%': 0.0, 'so_nhom_vi_pham_k5': 0, 'so_ban_ghi_vi_pham_k5': 0, 'ty_le_vi_pham_k5_%': 0.0}

In [643]:
# Đánh giá l-diversity trên dữ liệu đã đạt k=5
# Mục đích là kiểm tra trong mỗi equivalence class
# có đủ ít nhất 2 giá trị thu_nhap khác nhau hay không
strategy1_l_diversity_after_k = (
    privacy_analyzer.evaluate_l_diversity(
        strategy1_after_k_suppression,
        strategy1_qi_columns,
        sensitive_column="thu_nhap",
        l_required=2
    )
)


# Hiển thị toàn bộ kết quả đánh giá l-diversity
print(
    strategy1_l_diversity_after_k
)

{'so_equivalence_class': 395, 'l_min': 1, 'l_required': 2, 'l_valid': False, 'so_nhom_vi_pham_l': 56, 'so_ban_ghi_vi_pham_l': 1400, 'ty_le_ban_ghi_vi_pham_l_%': 4.37}

In [644]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module anonymization_engine chứa hàm suppress_l_diversity() vừa thêm
import anonymization_engine


# Nạp lại module để notebook nhận code mới nhất
importlib.reload(
    anonymization_engine
)


# Thực hiện suppression các equivalence class chưa đạt l=2
# Dữ liệu đầu vào là dữ liệu đã đạt k=5
strategy1_after_l_suppression = (
    anonymization_engine.suppress_l_diversity(
        strategy1_after_k_suppression,
        strategy1_qi_columns,
        sensitive_column="thu_nhap",
        l_required=2
    )
)


# Lấy số bản ghi trước khi l-suppression
so_ban_ghi_truoc_l = len(
    strategy1_after_k_suppression
)


# Lấy số bản ghi còn lại sau l-suppression
so_ban_ghi_sau_l = len(
    strategy1_after_l_suppression
)


# Tính số bản ghi bị suppression thêm vì chưa đạt l=2
so_ban_ghi_suppression_l = (
    so_ban_ghi_truoc_l
    - so_ban_ghi_sau_l
)


# Hiển thị số bản ghi trước l-suppression
print(
    "Số bản ghi trước l-suppression:",
    so_ban_ghi_truoc_l
)


# Hiển thị số bản ghi bị suppression thêm vì l=2
print(
    "Số bản ghi suppression thêm vì l=2:",
    so_ban_ghi_suppression_l
)


# Hiển thị số bản ghi còn lại cuối cùng
print(
    "Số bản ghi còn lại:",
    so_ban_ghi_sau_l
)

Số bản ghi trước l-suppression: 32004
Số bản ghi suppression thêm vì l=2: 1400
Số bản ghi còn lại: 30604

In [645]:
# Đánh giá đồng thời k-anonymity và l-diversity
# trên dữ liệu sau khi đã thực hiện cả k-suppression và l-suppression
strategy1_final_privacy = (
    privacy_analyzer.evaluate_privacy_full(

        # Dữ liệu cuối cùng hiện có 30.604 bản ghi
        strategy1_after_l_suppression,

        # 7 cột QI của Strategy 1
        strategy1_qi_columns,

        # Cột thu_nhap là thuộc tính nhạy cảm dùng để kiểm tra l-diversity
        "thu_nhap",

        # Yêu cầu mỗi equivalence class phải có ít nhất 5 bản ghi
        k_required=5,

        # Yêu cầu mỗi equivalence class phải có ít nhất 2 giá trị thu_nhap khác nhau
        l_required=2
    )
)


# Hiển thị toàn bộ kết quả kiểm tra Privacy cuối cùng
print(
    strategy1_final_privacy
)

{'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_ban_ghi_vi_pham_k': 0, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'privacy_valid': True}

In [646]:
# Tạo danh sách các cột được phép giữ lại
# trong dữ liệu cuối cùng sau khi ẩn danh hóa
release_columns_strategy1 = [

    # Nhóm tuổi đã được generalization
    "tuoi_nhom_3",

    # Loại công việc đã được generalization
    "loai_cong_viec_nhom",

    # Học vấn đã được generalization
    "hoc_van_nhom_3",

    # Tình trạng hôn nhân đã được generalization
    "hon_nhan_nhom_2",

    # Nghề nghiệp đã được generalization
    "nghe_nghiep_nhom_4",

    # Giờ làm việc đã được generalization
    "gio_lam_nhom_3",

    # Quốc gia đã được generalization
    "quoc_gia_nhom_2",

    # Giữ lại thu_nhap vì đây là thuộc tính nhạy cảm
    # đồng thời là target dùng cho Machine Learning
    "thu_nhap"
]


# Chỉ lấy 8 cột được phép phát hành
# từ dữ liệu đã đạt cả k=5 và l=2
strategy1_release = (
    strategy1_after_l_suppression[
        release_columns_strategy1
    ]
    .copy()
)


# Hiển thị kích thước của dữ liệu phát hành
# Kỳ vọng kết quả là 30.604 dòng và 8 cột
print(
    "Kích thước dữ liệu phát hành:",
    strategy1_release.shape
)


# Hiển thị chính xác tên các cột còn lại
# để chắc chắn không còn cột dữ liệu gốc chi tiết
print(
    "Các cột dữ liệu phát hành:",
    strategy1_release.columns.tolist()
)


# Hiển thị 5 bản ghi đầu tiên
# để kiểm tra trực quan dữ liệu cuối cùng
display(
    strategy1_release.head()
)

Kích thước dữ liệu phát hành: (30604, 8)
Các cột dữ liệu phát hành: ['tuoi_nhom_3', 'loai_cong_viec_nhom', 'hoc_van_nhom_3', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_3', 'quoc_gia_nhom_2', 'thu_nhap']

,tuoi_nhom_3,loai_cong_viec_nhom,hoc_van_nhom_3,hon_nhan_nhom_2,nghe_nghiep_nhom_4,gio_lam_nhom_3,quoc_gia_nhom_2,thu_nhap
0,70-99,Khong_ro,THPT_tro_xuong,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
1,70-99,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K
2,50-69,Khong_ro,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
3,50-69,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,1-40,Hoa_Ky,<=50K
4,10-49,Tu_nhan,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K

In [647]:
# Import pandas để đọc lại file Strategy 1 đã lưu trước đây
import pandas as pd


# Đọc file dữ liệu ẩn danh Strategy 1 cũ từ ổ đĩa
# Mục đích là dùng file này làm kết quả tham chiếu để đối chiếu
strategy1_saved_old = pd.read_csv(
    "../data/processed_da_xu_li/anonymized_candidate_k5_l2.csv",
    encoding="utf-8-sig"
)


# Reset index của dữ liệu vừa tạo bằng anonymization_engine
# Vì dữ liệu hiện tại vẫn giữ index gốc để phục vụ Machine Learning
strategy1_release_for_compare = (
    strategy1_release
    .reset_index(
        drop=True
    )
)


# Reset index của file cũ để hai DataFrame có cùng kiểu index khi so sánh
strategy1_saved_old_for_compare = (
    strategy1_saved_old
    .reset_index(
        drop=True
    )
)


# So sánh toàn bộ DataFrame:
# - số dòng
# - số cột
# - tên cột
# - thứ tự dòng
# - giá trị của từng ô
# Nếu tất cả giống nhau thì kết quả sẽ là True
same_as_saved_strategy1 = (
    strategy1_release_for_compare
    .equals(
        strategy1_saved_old_for_compare
    )
)


# Hiển thị kích thước của dữ liệu vừa tái tạo
print(
    "Kích thước dữ liệu mới:",
    strategy1_release_for_compare.shape
)


# Hiển thị kích thước của file Strategy 1 cũ
print(
    "Kích thước dữ liệu cũ:",
    strategy1_saved_old_for_compare.shape
)


# Hiển thị kết quả so sánh toàn bộ hai DataFrame
print(
    "Hai bộ dữ liệu có giống hoàn toàn không?:",
    same_as_saved_strategy1
)

Kích thước dữ liệu mới: (30604, 8)
Kích thước dữ liệu cũ: (30604, 8)
Hai bộ dữ liệu có giống hoàn toàn không?: True

In [648]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa toàn bộ quá trình ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa thêm hàm anonymize_strategy_1()
importlib.reload(
    anonymization_engine
)


# Chạy toàn bộ Strategy 1 chỉ bằng một hàm
# Hàm sẽ thực hiện:
# generalization -> k-suppression -> l-suppression -> chọn cột phát hành
strategy1_release_auto, strategy1_retained_indices_auto = (
    anonymization_engine.anonymize_strategy_1(
        data_check,

        # Yêu cầu k-anonymity tối thiểu bằng 5
        k_required=5,

        # Yêu cầu l-diversity tối thiểu bằng 2
        l_required=2
    )
)


# Hiển thị kích thước dataset ẩn danh do hàm tổng vừa tạo
print(
    "Kích thước dữ liệu ẩn danh:",
    strategy1_release_auto.shape
)


# Hiển thị số lượng index gốc được giữ lại
# Số này phải bằng đúng số bản ghi của dataset ẩn danh
print(
    "Số index được giữ lại:",
    len(
        strategy1_retained_indices_auto
    )
)


# So sánh kết quả hàm tự động với strategy1_release
# mà chúng ta đã tạo thủ công và kiểm tra đúng ở bước trước
same_release_data = (
    strategy1_release_auto
    .reset_index(
        drop=True
    )
    .equals(
        strategy1_release
        .reset_index(
            drop=True
        )
    )
)


# Hiển thị kết quả so sánh
# Nếu True nghĩa là hàm tổng tái tạo đúng kết quả thủ công trước đó
print(
    "Kết quả tự động có giống kết quả thủ công không?:",
    same_release_data
)

Kích thước dữ liệu ẩn danh: (30604, 8)
Số index được giữ lại: 30604
Kết quả tự động có giống kết quả thủ công không?: True

In [649]:
# Đọc file chứa index của các bản ghi được giữ lại
# mà Strategy 1 trước đây đã lưu để phục vụ đánh giá Machine Learning
saved_retained_indices = pd.read_csv(
    "../data/processed_da_xu_li/retained_row_indices_k5_l2.csv",
    encoding="utf-8-sig"
)


# Hiển thị kích thước của file index cũ
# Mục đích là kiểm tra file đang chứa bao nhiêu index và bao nhiêu cột
print(
    "Kích thước file index cũ:",
    saved_retained_indices.shape
)


# Hiển thị tên cột của file index cũ
# Ta cần biết chính xác tên cột trước khi so sánh với index mới
print(
    "Tên cột:",
    saved_retained_indices.columns.tolist()
)


# Hiển thị 10 index đầu tiên trong file cũ
# để kiểm tra cấu trúc dữ liệu bên trong
display(
    saved_retained_indices.head(
        10
    )
)

Kích thước file index cũ: (30604, 1)
Tên cột: ['original_row_index']

   original_row_index
0                   0
1                   1
2                   2
3                   3
4                   4
5                   5
6                   6
7                   7
8                   8
9                   9

In [650]:
# Lấy danh sách index gốc từ file Strategy 1 đã lưu trước đây
# Cột original_row_index chứa vị trí của các bản ghi được giữ lại
saved_indices_list = (
    saved_retained_indices["original_row_index"]
    .tolist()
)


# Chuyển Index do hàm anonymize_strategy_1() vừa tạo
# thành danh sách để có thể so sánh trực tiếp
auto_indices_list = (
    strategy1_retained_indices_auto
    .tolist()
)


# So sánh toàn bộ 30.604 index theo đúng thứ tự
# Kết quả True nghĩa là từng index đều giống file cũ
same_retained_indices = (
    saved_indices_list
    ==
    auto_indices_list
)


# Hiển thị số index trong file cũ
print(
    "Số index trong file cũ:",
    len(
        saved_indices_list
    )
)


# Hiển thị số index do hệ thống mới tự động tạo
print(
    "Số index hệ thống mới:",
    len(
        auto_indices_list
    )
)


# Hiển thị kết quả so sánh toàn bộ index
print(
    "Hai bộ index có giống hoàn toàn không?:",
    same_retained_indices
)

Số index trong file cũ: 30604
Số index hệ thống mới: 30604
Hai bộ index có giống hoàn toàn không?: True

In [651]:
# Import importlib để có thể nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa thêm hàm generalize_age_high()
importlib.reload(
    anonymization_engine
)


# Tạo các tuổi mẫu nằm ở sát ranh giới của từng nhóm
# Mục đích là kiểm tra điều kiện phân nhóm có chính xác hay không
test_ages_high = [
    17,
    29,
    30,
    49,
    50,
    69,
    70,
    90
]


# Lần lượt kiểm tra từng tuổi
for age in test_ages_high:

    # Gọi hàm generalize_age_high() để chuyển tuổi cụ thể thành nhóm tuổi
    age_group = anonymization_engine.generalize_age_high(
        age
    )

    # Hiển thị tuổi gốc và nhóm tuổi sau generalization
    print(
        age,
        "→",
        age_group
    )

17 → 10-29
29 → 10-29
30 → 30-49
49 → 30-49
50 → 50-69
69 → 50-69
70 → 70-99
90 → 70-99

In [652]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa thêm apply_strategy_2_generalization()
importlib.reload(
    anonymization_engine
)


# Áp dụng toàn bộ generalization của Strategy 2 lên dataset gốc
# Strategy 2 dùng tuoi_nhom_high thay cho tuoi_nhom_3
strategy2_generalized_check = (
    anonymization_engine.apply_strategy_2_generalization(
        data_check
    )
)


# Khai báo 7 cột QI của Strategy 2
# Điểm khác Strategy 1 nằm ở cột tuoi_nhom_high
strategy2_qi_columns = [
    "tuoi_nhom_high",
    "loai_cong_viec_nhom",
    "hoc_van_nhom_3",
    "hon_nhan_nhom_2",
    "nghe_nghiep_nhom_4",
    "gio_lam_nhom_3",
    "quoc_gia_nhom_2"
]


# Đánh giá k-anonymity của Strategy 2 trước khi suppression
# Mục đích là kiểm tra code mới có tái tạo đúng Strategy 2 cũ hay không
strategy2_privacy_before_suppression = (
    privacy_analyzer.evaluate_privacy(
        strategy2_generalized_check,
        strategy2_qi_columns,
        k_required=5
    )
)


# Hiển thị kích thước dữ liệu sau generalization
# Vì thêm 7 cột mới nên dự kiến là 32.561 dòng và 22 cột
print(
    "Kích thước sau generalization Strategy 2:",
    strategy2_generalized_check.shape
)


# Hiển thị toàn bộ kết quả k-anonymity trước suppression
print(
    strategy2_privacy_before_suppression
)

Kích thước sau generalization Strategy 2: (32561, 22)
{'so_equivalence_class': 912, 'k_min': 1, 'k_required': 5, 'k_valid': False, 'so_nhom_1_ban_ghi': 188, 'so_ban_ghi_bi_co_lap': 188, 'ty_le_bi_co_lap_%': 0.58, 'so_nhom_vi_pham_k': 409, 'so_ban_ghi_vi_pham_k': 810, 'ty_le_ban_ghi_vi_pham_k_%': 2.49, 'so_nhom_vi_pham_k5': 409, 'so_ban_ghi_vi_pham_k5': 810, 'ty_le_vi_pham_k5_%': 2.49}

In [653]:
# Thực hiện suppression các bản ghi của Strategy 2
# nằm trong equivalence class có kích thước nhỏ hơn 5
strategy2_after_k_suppression = (
    anonymization_engine.suppress_k_anonymity(

        # Dữ liệu Strategy 2 sau generalization
        strategy2_generalized_check,

        # 7 cột QI của Strategy 2
        strategy2_qi_columns,

        # Yêu cầu mỗi equivalence class phải có ít nhất 5 bản ghi
        k_required=5
    )
)


# Lấy tổng số bản ghi trước khi thực hiện k-suppression
so_ban_ghi_truoc_k_strategy2 = len(
    strategy2_generalized_check
)


# Lấy tổng số bản ghi còn lại sau khi thực hiện k-suppression
so_ban_ghi_sau_k_strategy2 = len(
    strategy2_after_k_suppression
)


# Tính số bản ghi đã bị suppression vì chưa đạt k=5
so_ban_ghi_suppression_k_strategy2 = (
    so_ban_ghi_truoc_k_strategy2
    - so_ban_ghi_sau_k_strategy2
)


# Hiển thị số bản ghi trước suppression
print(
    "Số bản ghi trước suppression:",
    so_ban_ghi_truoc_k_strategy2
)


# Hiển thị số bản ghi bị suppression vì chưa đạt k=5
print(
    "Số bản ghi suppression k=5:",
    so_ban_ghi_suppression_k_strategy2
)


# Hiển thị số bản ghi còn lại sau k-suppression
print(
    "Số bản ghi còn lại:",
    so_ban_ghi_sau_k_strategy2
)

Số bản ghi trước suppression: 32561
Số bản ghi suppression k=5: 810
Số bản ghi còn lại: 31751

In [654]:
# Đánh giá lại k-anonymity của Strategy 2
# sau khi đã loại các bản ghi thuộc nhóm có kích thước nhỏ hơn 5
strategy2_privacy_after_k = (
    privacy_analyzer.evaluate_privacy(

        # Dữ liệu Strategy 2 sau k-suppression
        strategy2_after_k_suppression,

        # 7 cột QI của Strategy 2
        strategy2_qi_columns,

        # Yêu cầu k tối thiểu bằng 5
        k_required=5
    )
)


# Hiển thị toàn bộ kết quả kiểm tra sau k-suppression
print(
    strategy2_privacy_after_k
)

{'so_equivalence_class': 503, 'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_nhom_1_ban_ghi': 0, 'so_ban_ghi_bi_co_lap': 0, 'ty_le_bi_co_lap_%': 0.0, 'so_nhom_vi_pham_k': 0, 'so_ban_ghi_vi_pham_k': 0, 'ty_le_ban_ghi_vi_pham_k_%': 0.0, 'so_nhom_vi_pham_k5': 0, 'so_ban_ghi_vi_pham_k5': 0, 'ty_le_vi_pham_k5_%': 0.0}

In [655]:
# Đánh giá l-diversity trên dữ liệu Strategy 2
# sau khi dữ liệu đã đạt k-anonymity với k=5
strategy2_l_diversity_after_k = (
    privacy_analyzer.evaluate_l_diversity(

        # Dữ liệu Strategy 2 sau k-suppression
        strategy2_after_k_suppression,

        # 7 cột QI của Strategy 2
        strategy2_qi_columns,

        # Cột thu_nhap là thuộc tính nhạy cảm
        # cần được bảo vệ khỏi việc suy luận trong từng equivalence class
        sensitive_column="thu_nhap",

        # Yêu cầu mỗi equivalence class
        # phải có ít nhất 2 giá trị thu_nhap khác nhau
        l_required=2
    )
)


# Hiển thị toàn bộ kết quả đánh giá l-diversity
print(
    strategy2_l_diversity_after_k
)

{'so_equivalence_class': 503, 'l_min': 1, 'l_required': 2, 'l_valid': False, 'so_nhom_vi_pham_l': 94, 'so_ban_ghi_vi_pham_l': 3416, 'ty_le_ban_ghi_vi_pham_l_%': 10.76}

In [656]:
# Thực hiện suppression các equivalence class của Strategy 2
# chưa đạt yêu cầu l-diversity với l=2
strategy2_after_l_suppression = (
    anonymization_engine.suppress_l_diversity(

        # Dữ liệu Strategy 2 đã đạt k=5
        strategy2_after_k_suppression,

        # 7 cột QI của Strategy 2
        strategy2_qi_columns,

        # Cột thu_nhap là thuộc tính nhạy cảm
        # dùng để kiểm tra l-diversity
        sensitive_column="thu_nhap",

        # Yêu cầu mỗi equivalence class
        # phải có ít nhất 2 giá trị thu_nhap khác nhau
        l_required=2
    )
)


# Lấy số bản ghi trước khi thực hiện l-suppression
so_ban_ghi_truoc_l_strategy2 = len(
    strategy2_after_k_suppression
)


# Lấy số bản ghi còn lại sau khi thực hiện l-suppression
so_ban_ghi_sau_l_strategy2 = len(
    strategy2_after_l_suppression
)


# Tính số bản ghi bị suppression thêm
# do nằm trong equivalence class chưa đạt l=2
so_ban_ghi_suppression_l_strategy2 = (
    so_ban_ghi_truoc_l_strategy2
    - so_ban_ghi_sau_l_strategy2
)


# Hiển thị số bản ghi trước l-suppression
print(
    "Số bản ghi trước l-suppression:",
    so_ban_ghi_truoc_l_strategy2
)


# Hiển thị số bản ghi bị suppression thêm vì chưa đạt l=2
print(
    "Số bản ghi suppression thêm vì l=2:",
    so_ban_ghi_suppression_l_strategy2
)


# Hiển thị số bản ghi còn lại sau l-suppression
print(
    "Số bản ghi còn lại:",
    so_ban_ghi_sau_l_strategy2
)

Số bản ghi trước l-suppression: 31751
Số bản ghi suppression thêm vì l=2: 3416
Số bản ghi còn lại: 28335

In [657]:
# Đánh giá đồng thời k-anonymity và l-diversity
# trên dữ liệu Strategy 2 sau khi đã thực hiện cả:
# k-suppression và l-suppression
strategy2_final_privacy = (
    privacy_analyzer.evaluate_privacy_full(

        # Dữ liệu Strategy 2 cuối cùng hiện còn 28.335 bản ghi
        strategy2_after_l_suppression,

        # 7 cột QI của Strategy 2
        strategy2_qi_columns,

        # Cột thu_nhap là thuộc tính nhạy cảm
        # dùng để kiểm tra l-diversity
        "thu_nhap",

        # Yêu cầu mỗi equivalence class
        # phải có ít nhất 5 bản ghi
        k_required=5,

        # Yêu cầu mỗi equivalence class
        # phải có ít nhất 2 giá trị thu_nhap khác nhau
        l_required=2
    )
)


# Hiển thị toàn bộ kết quả Privacy cuối cùng của Strategy 2
print(
    strategy2_final_privacy
)

{'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_ban_ghi_vi_pham_k': 0, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'privacy_valid': True}

In [658]:
# Tạo danh sách các cột được phép giữ lại
# trong dữ liệu cuối cùng của Strategy 2
release_columns_strategy2 = [

    # Nhóm tuổi của Strategy 2
    "tuoi_nhom_high",

    # Loại công việc đã được generalization
    "loai_cong_viec_nhom",

    # Học vấn đã được generalization
    "hoc_van_nhom_3",

    # Tình trạng hôn nhân đã được generalization
    "hon_nhan_nhom_2",

    # Nghề nghiệp đã được generalization
    "nghe_nghiep_nhom_4",

    # Giờ làm việc đã được generalization
    "gio_lam_nhom_3",

    # Quốc gia đã được generalization
    "quoc_gia_nhom_2",

    # Thu nhập được giữ lại vì đây là target Machine Learning
    # đồng thời là thuộc tính nhạy cảm dùng cho l-diversity
    "thu_nhap"
]


# Chỉ lấy 8 cột được phép phát hành
# từ dữ liệu Strategy 2 đã đạt k=5 và l=2
strategy2_release = (
    strategy2_after_l_suppression[
        release_columns_strategy2
    ]
    .copy()
)


# Hiển thị kích thước dữ liệu phát hành
# Kỳ vọng là 28.335 dòng và 8 cột
print(
    "Kích thước dữ liệu phát hành Strategy 2:",
    strategy2_release.shape
)


# Hiển thị danh sách tên các cột cuối cùng
# để kiểm tra không còn các cột dữ liệu gốc chi tiết
print(
    "Các cột dữ liệu phát hành Strategy 2:",
    strategy2_release.columns.tolist()
)


# Hiển thị 5 dòng đầu tiên để kiểm tra trực quan
display(
    strategy2_release.head()
)

Kích thước dữ liệu phát hành Strategy 2: (28335, 8)
Các cột dữ liệu phát hành Strategy 2: ['tuoi_nhom_high', 'loai_cong_viec_nhom', 'hoc_van_nhom_3', 'hon_nhan_nhom_2', 'nghe_nghiep_nhom_4', 'gio_lam_nhom_3', 'quoc_gia_nhom_2', 'thu_nhap']

,tuoi_nhom_high,loai_cong_viec_nhom,hoc_van_nhom_3,hon_nhan_nhom_2,nghe_nghiep_nhom_4,gio_lam_nhom_3,quoc_gia_nhom_2,thu_nhap
0,70-99,Khong_ro,THPT_tro_xuong,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
1,70-99,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K
2,50-69,Khong_ro,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Khong_ro,1-40,Hoa_Ky,<=50K
3,50-69,Tu_nhan,THPT_tro_xuong,Khong_ket_hon_hien_tai,Lao_dong_truc_tiep,1-40,Hoa_Ky,<=50K
4,30-49,Tu_nhan,Sau_THPT_Cao_dang,Khong_ket_hon_hien_tai,Van_phong_chuyen_mon,1-40,Hoa_Ky,<=50K

In [659]:
# Đọc lại file Strategy 2 cũ đã lưu trước đây
# File này được dùng làm kết quả tham chiếu để kiểm tra code mới
strategy2_saved_old = pd.read_csv(
    "../data/processed_da_xu_li/anonymized_strategy2_k5_l2.csv",
    encoding="utf-8-sig"
)


# Reset index của Strategy 2 vừa tạo bằng code mới
# Vì sau suppression dữ liệu mới vẫn đang giữ index gốc
strategy2_release_for_compare = (
    strategy2_release
    .reset_index(
        drop=True
    )
)


# Reset index của file Strategy 2 cũ
# để hai DataFrame có cùng kiểu index khi so sánh
strategy2_saved_old_for_compare = (
    strategy2_saved_old
    .reset_index(
        drop=True
    )
)


# So sánh toàn bộ hai DataFrame
# equals() sẽ kiểm tra:
# - kích thước
# - tên cột
# - thứ tự cột
# - thứ tự dòng
# - giá trị trong từng ô
same_as_saved_strategy2 = (
    strategy2_release_for_compare
    .equals(
        strategy2_saved_old_for_compare
    )
)


# Hiển thị kích thước Strategy 2 vừa được tái tạo
print(
    "Kích thước dữ liệu mới:",
    strategy2_release_for_compare.shape
)


# Hiển thị kích thước file Strategy 2 cũ
print(
    "Kích thước dữ liệu cũ:",
    strategy2_saved_old_for_compare.shape
)


# Hiển thị kết quả so sánh toàn bộ dữ liệu
# Nếu True nghĩa là Strategy 2 mới giống hoàn toàn Strategy 2 cũ
print(
    "Hai bộ dữ liệu có giống hoàn toàn không?:",
    same_as_saved_strategy2
)

Kích thước dữ liệu mới: (28335, 8)
Kích thước dữ liệu cũ: (28335, 8)
Hai bộ dữ liệu có giống hoàn toàn không?: True

In [660]:
# Đọc file index Strategy 2 đã lưu trước đây
# File này chứa index gốc của các bản ghi được giữ lại sau ẩn danh hóa
strategy2_saved_indices = pd.read_csv(
    "../data/processed_da_xu_li/retained_row_indices_strategy2_k5_l2.csv",
    encoding="utf-8-sig"
)


# Lấy index hiện tại của dữ liệu Strategy 2 sau cả k-suppression và l-suppression
# Chúng ta chưa reset index nên đây vẫn là index của dataset gốc
strategy2_auto_indices_list = (
    strategy2_after_l_suppression
    .index
    .tolist()
)


# Lấy index gốc đã được lưu trong file Strategy 2 cũ
# Cột original_row_index chứa index của dataset ban đầu
strategy2_saved_indices_list = (
    strategy2_saved_indices["original_row_index"]
    .tolist()
)


# So sánh toàn bộ 28.335 index theo đúng thứ tự
# Nếu tất cả index giống nhau thì kết quả sẽ là True
same_strategy2_indices = (
    strategy2_auto_indices_list
    ==
    strategy2_saved_indices_list
)


# Hiển thị số index mà hệ thống mới tạo ra
print(
    "Số index hệ thống mới:",
    len(
        strategy2_auto_indices_list
    )
)


# Hiển thị số index trong file Strategy 2 cũ
print(
    "Số index trong file cũ:",
    len(
        strategy2_saved_indices_list
    )
)


# Hiển thị kết quả so sánh toàn bộ index
print(
    "Hai bộ index có giống hoàn toàn không?:",
    same_strategy2_indices
)

Số index hệ thống mới: 28335
Số index trong file cũ: 28335
Hai bộ index có giống hoàn toàn không?: True

In [661]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa toàn bộ các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa thêm hàm anonymize_strategy_2()
importlib.reload(
    anonymization_engine
)


# Chạy toàn bộ Strategy 2 chỉ bằng một hàm duy nhất
# Hàm sẽ tự thực hiện:
# generalization -> k-suppression -> l-suppression -> chọn cột phát hành
strategy2_release_auto, strategy2_retained_indices_auto = (
    anonymization_engine.anonymize_strategy_2(

        # Dataset gốc dùng để thực hiện ẩn danh hóa
        data_check,

        # Yêu cầu k-anonymity tối thiểu bằng 5
        k_required=5,

        # Yêu cầu l-diversity tối thiểu bằng 2
        l_required=2
    )
)


# Hiển thị kích thước dataset ẩn danh
# Kỳ vọng phải là 28.335 dòng và 8 cột
print(
    "Kích thước dữ liệu ẩn danh Strategy 2:",
    strategy2_release_auto.shape
)


# Hiển thị số index gốc được giữ lại
# Số index phải bằng đúng số bản ghi của dữ liệu ẩn danh
print(
    "Số index được giữ lại:",
    len(
        strategy2_retained_indices_auto
    )
)


# So sánh dataset do hàm tự động tạo
# với dataset Strategy 2 mà chúng ta vừa tạo thủ công trước đó
same_strategy2_release_auto = (
    strategy2_release_auto
    .reset_index(
        drop=True
    )
    .equals(
        strategy2_release
        .reset_index(
            drop=True
        )
    )
)


# Hiển thị kết quả so sánh dataset
# True nghĩa là kết quả tự động giống hoàn toàn kết quả thủ công
print(
    "Dữ liệu tự động có giống kết quả thủ công không?:",
    same_strategy2_release_auto
)


# Chuyển index do hàm tự động trả về thành danh sách
# để có thể so sánh với index thủ công trước đó
strategy2_retained_indices_auto_list = (
    strategy2_retained_indices_auto
    .tolist()
)


# So sánh toàn bộ index của hai cách thực hiện
# True nghĩa là hàm tự động giữ đúng các bản ghi gốc
same_strategy2_indices_auto = (
    strategy2_retained_indices_auto_list
    ==
    strategy2_auto_indices_list
)


# Hiển thị kết quả so sánh index
print(
    "Index tự động có giống kết quả thủ công không?:",
    same_strategy2_indices_auto
)

Kích thước dữ liệu ẩn danh Strategy 2: (28335, 8)
Số index được giữ lại: 28335
Dữ liệu tự động có giống kết quả thủ công không?: True
Index tự động có giống kết quả thủ công không?: True

In [662]:
# Import importlib để nạp lại phiên bản mới nhất của anonymization_engine.py
import importlib


# Import module chứa các hàm ẩn danh hóa
import anonymization_engine


# Nạp lại module vì chúng ta vừa thêm hàm anonymize_by_strategy()
importlib.reload(
    anonymization_engine
)


# TEST STRATEGY 1 QUA HÀM CHUNG

# Gọi Strategy 1 thông qua hàm anonymize_by_strategy()
# Hàm phải tự chuyển tiếp sang anonymize_strategy_1()
strategy1_from_common, strategy1_indices_from_common = (
    anonymization_engine.anonymize_by_strategy(

        # Dataset gốc cần ẩn danh hóa
        data_check,

        # Chỉ định hệ thống chạy Strategy 1
        strategy_name="strategy_1",

        # Yêu cầu k-anonymity bằng 5
        k_required=5,

        # Yêu cầu l-diversity bằng 2
        l_required=2
    )
)


# Kiểm tra dữ liệu Strategy 1 từ hàm chung
# có giống kết quả Strategy 1 đã kiểm chứng trước đó hay không
strategy1_common_is_correct = (
    strategy1_from_common
    .reset_index(
        drop=True
    )
    .equals(
        strategy1_release_auto
        .reset_index(
            drop=True
        )
    )
)


# TEST STRATEGY 2 QUA HÀM CHUNG


# Gọi Strategy 2 thông qua cùng một hàm anonymize_by_strategy()
# Hàm phải tự chuyển tiếp sang anonymize_strategy_2()
strategy2_from_common, strategy2_indices_from_common = (
    anonymization_engine.anonymize_by_strategy(

        # Dataset gốc cần ẩn danh hóa
        data_check,

        # Chỉ định hệ thống chạy Strategy 2
        strategy_name="strategy_2",

        # Yêu cầu k-anonymity bằng 5
        k_required=5,

        # Yêu cầu l-diversity bằng 2
        l_required=2
    )
)


# Kiểm tra dữ liệu Strategy 2 từ hàm chung
# có giống kết quả Strategy 2 đã kiểm chứng trước đó hay không
strategy2_common_is_correct = (
    strategy2_from_common
    .reset_index(
        drop=True
    )
    .equals(
        strategy2_release_auto
        .reset_index(
            drop=True
        )
    )
)


# HIỂN THỊ KẾT QUẢ



# Hiển thị kích thước Strategy 1 được chạy qua hàm chung
print(
    "Strategy 1 - kích thước:",
    strategy1_from_common.shape
)


# Hiển thị Strategy 1 có chạy đúng hay không
print(
    "Strategy 1 qua hàm chung có đúng không?:",
    strategy1_common_is_correct
)


# Hiển thị kích thước Strategy 2 được chạy qua hàm chung
print(
    "Strategy 2 - kích thước:",
    strategy2_from_common.shape
)


# Hiển thị Strategy 2 có chạy đúng hay không
print(
    "Strategy 2 qua hàm chung có đúng không?:",
    strategy2_common_is_correct
)

Strategy 1 - kích thước: (30604, 8)
Strategy 1 qua hàm chung có đúng không?: True
Strategy 2 - kích thước: (28335, 8)
Strategy 2 qua hàm chung có đúng không?: True

In [663]:

# TỰ ĐỘNG CHẠY NHIỀU STRATEGY



# Tạo danh sách tên các Strategy mà hệ thống cần chạy
# Sau này nếu có Strategy 3, Strategy 4 thì chỉ cần thêm tên vào đây
strategy_names = [
    "strategy_1",
    "strategy_2"
]


# Tạo dictionary rỗng để lưu kết quả của từng Strategy
# Mỗi Strategy sẽ lưu:
# - dữ liệu ẩn danh
# - index gốc được giữ lại
strategy_results = {}


# Lần lượt lấy từng tên Strategy trong danh sách
for strategy_name in strategy_names:

    # Gọi hàm chung anonymize_by_strategy()
    # để hệ thống tự chạy đúng pipeline tương ứng
    release_data, retained_indices = (
        anonymization_engine.anonymize_by_strategy(

            # Dataset gốc
            data_check,

            # Strategy đang được chạy trong vòng lặp
            strategy_name=strategy_name,

            # Yêu cầu k-anonymity bằng 5
            k_required=5,

            # Yêu cầu l-diversity bằng 2
            l_required=2
        )
    )


    # Lưu kết quả của Strategy hiện tại vào dictionary
    strategy_results[strategy_name] = {

        # Dataset sau ẩn danh hóa
        "release_data": release_data,

        # Index gốc của các bản ghi được giữ lại
        "retained_indices": retained_indices
    }


    # Hiển thị tên Strategy vừa chạy
    print(
        "Strategy:",
        strategy_name
    )


    # Hiển thị kích thước dữ liệu ẩn danh của Strategy đó
    print(
        "Kích thước:",
        release_data.shape
    )


    # Hiển thị số bản ghi còn được giữ lại
    print(
        "Số bản ghi giữ lại:",
        len(
            retained_indices
        )
    )


    # In dòng phân cách để kết quả dễ đọc
    print(
        "----------------------------------------"
    )

Strategy: strategy_1
Kích thước: (30604, 8)
Số bản ghi giữ lại: 30604
----------------------------------------
Strategy: strategy_2
Kích thước: (28335, 8)
Số bản ghi giữ lại: 28335
----------------------------------------

In [664]:

# TỰ ĐỘNG ĐÁNH GIÁ PRIVACY CHO NHIỀU STRATEGY


# Tạo dictionary để khai báo các cột QI tương ứng
# với từng Strategy
#
# Strategy 1 sử dụng tuoi_nhom_3
# Strategy 2 sử dụng tuoi_nhom_high
strategy_qi_map = {

    # 7 QI của Strategy 1
    "strategy_1": [
        "tuoi_nhom_3",
        "loai_cong_viec_nhom",
        "hoc_van_nhom_3",
        "hon_nhan_nhom_2",
        "nghe_nghiep_nhom_4",
        "gio_lam_nhom_3",
        "quoc_gia_nhom_2"
    ],

    # 7 QI của Strategy 2
    "strategy_2": [
        "tuoi_nhom_high",
        "loai_cong_viec_nhom",
        "hoc_van_nhom_3",
        "hon_nhan_nhom_2",
        "nghe_nghiep_nhom_4",
        "gio_lam_nhom_3",
        "quoc_gia_nhom_2"
    ]
}


# Lần lượt lấy từng Strategy đã chạy trước đó
for strategy_name in strategy_names:

    # Lấy dataset ẩn danh cuối cùng của Strategy hiện tại
    release_data = (
        strategy_results[strategy_name]["release_data"]
    )


    # Lấy đúng danh sách QI tương ứng với Strategy hiện tại
    qi_columns = (
        strategy_qi_map[strategy_name]
    )


    # Đánh giá đồng thời:
    # - k-anonymity
    # - l-diversity
    # - privacy_valid
    privacy_result = (
        privacy_analyzer.evaluate_privacy_full(

            # Dataset ẩn danh cuối cùng
            release_data,

            # Các cột QI của Strategy hiện tại
            qi_columns,

            # Cột thu_nhap là thuộc tính nhạy cảm
            "thu_nhap",

            # Yêu cầu k=5
            k_required=5,

            # Yêu cầu l=2
            l_required=2
        )
    )


    # Lưu kết quả Privacy vào strategy_results
    # để các bước sau có thể dùng tiếp mà không phải tính lại
    strategy_results[strategy_name]["privacy"] = (
        privacy_result
    )


    # Hiển thị tên Strategy đang được đánh giá
    print(
        "Strategy:",
        strategy_name
    )


    # Hiển thị toàn bộ kết quả Privacy
    print(
        privacy_result
    )


    # In dòng phân cách để dễ đọc
    print(
        "----------------------------------------"
    )

Strategy: strategy_1
{'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_ban_ghi_vi_pham_k': 0, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'privacy_valid': True}
----------------------------------------
Strategy: strategy_2
{'k_min': 5, 'k_required': 5, 'k_valid': True, 'so_ban_ghi_vi_pham_k': 0, 'l_min': 2, 'l_required': 2, 'l_valid': True, 'so_nhom_vi_pham_l': 0, 'so_ban_ghi_vi_pham_l': 0, 'privacy_valid': True}
----------------------------------------

In [665]:
# ============================================================
# TỰ ĐỘNG TÍNH SUPPRESSION VÀ DATA RETENTION
# CHO TỪNG STRATEGY
# ============================================================


# Lấy tổng số bản ghi của dataset gốc
# Dataset ban đầu có 32.561 bản ghi
total_original_records = len(
    data_check
)


# Lần lượt lấy từng Strategy đã chạy trước đó
for strategy_name in strategy_names:

    # Lấy danh sách index của các bản ghi
    # còn được giữ lại sau quá trình ẩn danh hóa
    retained_indices = (
        strategy_results[strategy_name]["retained_indices"]
    )


    # Đếm số bản ghi còn được giữ lại
    retained_records = len(
        retained_indices
    )


    # Tính số bản ghi đã bị suppression
    # bằng tổng dữ liệu gốc trừ số bản ghi còn lại
    suppressed_records = (
        total_original_records
        - retained_records
    )


    # Tính tỷ lệ suppression theo phần trăm
    # Ví dụ 1.957 / 32.561 * 100 ≈ 6.01%
    suppression_percent = (
        suppressed_records
        / total_original_records
        * 100
    )


    # Tính tỷ lệ dữ liệu còn được giữ lại
    # Data Retention = 100% - Suppression %
    data_retention_percent = (
        retained_records
        / total_original_records
        * 100
    )


    # Lưu số bản ghi bị suppression
    # vào kết quả của Strategy hiện tại
    strategy_results[strategy_name]["suppressed_records"] = (
        suppressed_records
    )


    # Lưu tỷ lệ suppression
    # làm tròn đến 2 chữ số thập phân
    strategy_results[strategy_name]["suppression_percent"] = round(
        suppression_percent,
        2
    )


    # Lưu tỷ lệ dữ liệu được giữ lại
    # làm tròn đến 2 chữ số thập phân
    strategy_results[strategy_name]["data_retention_percent"] = round(
        data_retention_percent,
        2
    )


    # Hiển thị tên Strategy
    print(
        "Strategy:",
        strategy_name
    )


    # Hiển thị số bản ghi bị suppression
    print(
        "Số bản ghi suppression:",
        suppressed_records
    )


    # Hiển thị tỷ lệ suppression
    print(
        "Suppression (%):",
        round(
            suppression_percent,
            2
        )
    )


    # Hiển thị tỷ lệ dữ liệu còn được giữ lại
    print(
        "Data Retention (%):",
        round(
            data_retention_percent,
            2
        )
    )


    # In dòng phân cách để kết quả dễ đọc
    print(
        "----------------------------------------"
    )

Strategy: strategy_1
Số bản ghi suppression: 1957
Suppression (%): 6.01
Data Retention (%): 93.99
----------------------------------------
Strategy: strategy_2
Số bản ghi suppression: 4226
Suppression (%): 12.98
Data Retention (%): 87.02
----------------------------------------

In [666]:
# ============================================================
# GẮN VALIDATION UTILITY SCORE TỰ ĐỘNG CHO TỪNG STRATEGY
# ============================================================


# Tạo dictionary chứa Utility Score của từng Strategy
# Các giá trị này KHÔNG còn nhập thủ công 97.41 và 97.46
# mà được lấy trực tiếp từ kết quả Machine Learning tự động
validation_utility_scores = {

    # Lấy Utility Score tự động của Strategy 1
    # Giá trị này được Hàm 9 trong ml_evaluator.py tính ra
    "strategy_1": (
        strategy1_ml_auto_result[
            "utility_score_percent"
        ]
    ),

    # Lấy Utility Score tự động của Strategy 2
    # Giá trị này cũng được Hàm 9 tự động tính ra
    "strategy_2": (
        strategy2_ml_auto_result[
            "utility_score_percent"
        ]
    )
}


# Lần lượt duyệt qua từng Strategy
# strategy_names hiện chứa strategy_1 và strategy_2
for strategy_name in strategy_names:

    # Lấy Utility Score tự động
    # tương ứng với Strategy đang được xét
    utility_score = (
        validation_utility_scores[
            strategy_name
        ]
    )


    # Gắn Utility Score vừa tính tự động
    # vào dictionary kết quả của Strategy tương ứng
    #
    # strategy_selector.py sẽ dùng giá trị này
    # để tính Selection Score ở bước sau
    strategy_results[
        strategy_name
    ][
        "utility_score_percent"
    ] = utility_score


    # Hiển thị tên Strategy đang được kiểm tra
    print(
        "Strategy:",
        strategy_name
    )


    # Hiển thị Validation Utility Score
    # làm tròn đến 2 chữ số thập phân
    print(
        "Validation Utility Score (%):",
        round(
            strategy_results[
                strategy_name
            ][
                "utility_score_percent"
            ],
            2
        )
    )


    # In dòng phân cách
    # để kết quả của hai Strategy dễ đọc hơn
    print(
        "----------------------------------------"
    )

NameError: name 'strategy1_ml_auto_result' is not defined

In [ ]:
# ============================================================
# CHUẨN BỊ DỮ LIỆU ĐẦU VÀO CHO STRATEGY SELECTOR
# ============================================================


# Tạo danh sách chứa thông tin cần thiết
# để strategy_selector.py so sánh các Strategy
strategies_for_selection = []


# Duyệt lần lượt từng Strategy
for strategy_name in strategy_names:

    # Lấy toàn bộ kết quả đã lưu
    # của Strategy hiện tại
    current_result = (
        strategy_results[
            strategy_name
        ]
    )


    # Tạo dictionary chứa những thông tin
    # mà Strategy Selector cần sử dụng
    strategy_selection_data = {

        # Tên Strategy
        "strategy": strategy_name,

        # Tỷ lệ suppression của Strategy
        # Giá trị này được tính tự động từ quá trình ẩn danh hóa
        "suppression_percent": (
            current_result[
                "suppression_percent"
            ]
        ),

        # Utility Score Validation
        # Giá trị này hiện đã được ml_evaluator.py tính tự động
        "utility_score_percent": (
            current_result[
                "utility_score_percent"
            ]
        ),

        # Kiểm tra Strategy có đạt điều kiện privacy
        # k >= 5 và l >= 2 theo tiêu chí của đồ án hay không
        "privacy_valid": (
            current_result[
                "privacy"
            ][
                "privacy_valid"
            ]
        )
    }


    # Thêm Strategy hiện tại
    # vào danh sách dùng để xếp hạng
    strategies_for_selection.append(
        strategy_selection_data
    )


# ============================================================
# HIỂN THỊ DỮ LIỆU ĐẦU VÀO
# ============================================================


# Duyệt từng Strategy để kiểm tra
# dữ liệu trước khi đưa sang Strategy Selector
for strategy_data in strategies_for_selection:

    # Hiển thị tên Strategy
    print(
        "Strategy:",
        strategy_data[
            "strategy"
        ]
    )


    # Hiển thị tỷ lệ suppression
    print(
        "Suppression (%):",
        round(
            strategy_data[
                "suppression_percent"
            ],
            2
        )
    )


    # Hiển thị Utility Score tự động
    print(
        "Validation Utility Score (%):",
        round(
            strategy_data[
                "utility_score_percent"
            ],
            2
        )
    )


    # Hiển thị trạng thái Privacy
    print(
        "Privacy hợp lệ?:",
        strategy_data[
            "privacy_valid"
        ]
    )


    # In dòng phân cách
    print(
        "----------------------------------------"
    )

In [ ]:
# Import importlib để có thể nạp lại phiên bản mới nhất của strategy_selector.py
import importlib


# Import module chứa các hàm tính điểm và xếp hạng Strategy
import strategy_selector


# Nạp lại module để notebook chắc chắn sử dụng code mới nhất
importlib.reload(
    strategy_selector
)


# Gọi hàm rank_strategies() để tự động xếp hạng các Strategy
# Chỉ các Strategy có privacy_valid=True mới đủ điều kiện được xếp hạng
ranked_strategies = (
    strategy_selector.rank_strategies(

        # Danh sách Strategy đã chuẩn bị ở bước trước
        strategies_for_selection,

        # Trọng số dành cho tỷ lệ dữ liệu được giữ lại
        # 0.5 nghĩa là chiếm 50% Selection Score
        weight_data_retention=0.5,

        # Trọng số dành cho Validation Utility Score
        # 0.5 nghĩa là chiếm 50% Selection Score
        weight_utility=0.5
    )
)


# Lần lượt lấy từng Strategy sau khi đã được xếp hạng
for strategy in ranked_strategies:

    # Hiển thị toàn bộ thông tin của Strategy
    print(
        strategy
    )

In [ ]:
# ============================================================
# TỰ ĐỘNG CHỌN STRATEGY TỐT NHẤT
# ============================================================


# Gọi hàm select_best_strategy() để hệ thống
# tự chọn Strategy có Selection Score cao nhất
#
# Chỉ những Strategy có privacy_valid=True
# mới đủ điều kiện được lựa chọn
best_strategy = (
    strategy_selector.select_best_strategy(

        # Danh sách các Strategy đã có:
        # - Suppression
        # - Utility
        # - Privacy
        strategies_for_selection,

        # Data Retention chiếm 50% Selection Score
        weight_data_retention=0.5,

        # Validation Utility chiếm 50% Selection Score
        weight_utility=0.5
    )
)


# Hiển thị toàn bộ thông tin
# của Strategy được hệ thống lựa chọn
print(
    best_strategy
)

In [ ]:
# ============================================================
# LẤY KẾT QUẢ CỦA STRATEGY ĐƯỢC HỆ THỐNG TỰ ĐỘNG CHỌN
# ============================================================


# Lấy tên Strategy tốt nhất
# từ kết quả mà strategy_selector vừa trả về
selected_strategy_name = (
    best_strategy[
        "strategy"
    ]
)


# Lấy dataset ẩn danh cuối cùng
# tương ứng với Strategy đã được chọn
selected_release_data = (
    strategy_results[
        selected_strategy_name
    ][
        "release_data"
    ]
)


# Lấy index gốc của các bản ghi
# được giữ lại trong Strategy đã chọn
selected_retained_indices = (
    strategy_results[
        selected_strategy_name
    ][
        "retained_indices"
    ]
)


# Hiển thị tên Strategy mà hệ thống đã chọn
print(
    "Strategy được chọn:",
    selected_strategy_name
)


# Hiển thị kích thước dataset ẩn danh cuối cùng
print(
    "Kích thước dữ liệu cuối cùng:",
    selected_release_data.shape
)


# Hiển thị số index gốc được giữ lại
print(
    "Số index được giữ lại:",
    len(
        selected_retained_indices
    )
)

In [ ]:
# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module chứa các hàm đánh giá Machine Learning
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm hàm get_aligned_original_data()
importlib.reload(
    ml_evaluator
)


# Lấy đúng các bản ghi gốc tương ứng với Strategy 1
# strategy1_retained_indices_auto chứa 30.604 index gốc được giữ lại
strategy1_original_aligned = (
    ml_evaluator.get_aligned_original_data(

        # Dataset gốc ban đầu
        data_check,

        # Index gốc còn lại sau khi ẩn danh hóa Strategy 1
        strategy1_retained_indices_auto
    )
)


# Hiển thị kích thước dữ liệu gốc đã được căn chỉnh
# Kỳ vọng phải có 30.604 dòng và vẫn giữ 15 cột gốc
print(
    "Kích thước dữ liệu gốc đã căn chỉnh:",
    strategy1_original_aligned.shape
)


# Hiển thị kích thước dữ liệu ẩn danh Strategy 1
# Kỳ vọng có cùng 30.604 dòng nhưng chỉ còn 8 cột phát hành
print(
    "Kích thước dữ liệu ẩn danh Strategy 1:",
    strategy1_release_auto.shape
)


# Kiểm tra số dòng của dữ liệu gốc và dữ liệu ẩn danh có bằng nhau không
# True nghĩa là hai bộ dữ liệu đang cùng số lượng bản ghi
same_number_of_rows = (
    len(
        strategy1_original_aligned
    )
    ==
    len(
        strategy1_release_auto
    )
)


# Hiển thị kết quả kiểm tra số dòng
print(
    "Hai bộ dữ liệu có cùng số dòng không?:",
    same_number_of_rows
)

In [ ]:
# ============================================================
# KIỂM TRA DỮ LIỆU GỐC VÀ DỮ LIỆU ẨN DANH
# CÓ THỰC SỰ CĂN CHỈNH ĐÚNG TỪNG BẢN GHI HAY KHÔNG
# ============================================================


# So sánh index của dữ liệu gốc đã căn chỉnh
# với index của dữ liệu ẩn danh Strategy 1
#
# Nếu True nghĩa là hai DataFrame đang chứa
# đúng cùng các bản ghi gốc và cùng thứ tự
same_indices_strategy1 = (
    strategy1_original_aligned.index.tolist()
    ==
    strategy1_release_auto.index.tolist()
)


# So sánh cột thu_nhap của hai bộ dữ liệu
# Vì thu_nhap không bị thay đổi trong quá trình ẩn danh hóa
# nên từng giá trị thu_nhap phải giống nhau hoàn toàn
same_target_strategy1 = (
    strategy1_original_aligned["thu_nhap"].tolist()
    ==
    strategy1_release_auto["thu_nhap"].tolist()
)


# Hiển thị kết quả kiểm tra index
print(
    "Index hai bộ dữ liệu có giống hoàn toàn không?:",
    same_indices_strategy1
)


# Hiển thị kết quả kiểm tra target thu_nhap
print(
    "Target thu_nhap có giống hoàn toàn không?:",
    same_target_strategy1
)

In [ ]:
# ============================================================
# KIỂM TRA HÀM CHIA TRAIN / VALIDATION / TEST
# VỚI STRATEGY 1
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module chứa các hàm đánh giá Machine Learning
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm split_train_validation_test_indices()
importlib.reload(
    ml_evaluator
)


# Chia 30.604 bản ghi của Strategy 1 thành:
# - Train      = 60%
# - Validation = 20%
# - Test       = 20%
#
# Hàm chỉ chia INDEX để sau này dữ liệu gốc
# và dữ liệu ẩn danh sử dụng đúng cùng các bản ghi
train_indices_s1, validation_indices_s1, test_indices_s1 = (
    ml_evaluator.split_train_validation_test_indices(

        # Dữ liệu gốc đã được căn chỉnh đúng với Strategy 1
        strategy1_original_aligned,

        # Cột thu_nhap là target dùng để stratify
        target_column="thu_nhap",

        # Cố định random_state để kết quả có thể tái lập
        random_state=42
    )
)


# Hiển thị số bản ghi trong tập Train
print(
    "Số bản ghi Train:",
    len(
        train_indices_s1
    )
)


# Hiển thị số bản ghi trong tập Validation
print(
    "Số bản ghi Validation:",
    len(
        validation_indices_s1
    )
)


# Hiển thị số bản ghi trong tập Test
print(
    "Số bản ghi Test:",
    len(
        test_indices_s1
    )
)


# Tính tổng số bản ghi sau khi chia
# Tổng này phải bằng đúng 30.604 bản ghi ban đầu
total_split_records_s1 = (
    len(train_indices_s1)
    + len(validation_indices_s1)
    + len(test_indices_s1)
)


# Hiển thị tổng số bản ghi sau khi chia
print(
    "Tổng số bản ghi sau khi chia:",
    total_split_records_s1
)

In [ ]:
# ============================================================
# KIỂM TRA ORIGINAL VÀ ANONYMIZED
# CÓ ĐƯỢC CHIA ĐÚNG CÙNG TRAIN / VALIDATION / TEST KHÔNG
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module chứa các hàm đánh giá Machine Learning
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm hàm get_data_splits_by_indices()
importlib.reload(
    ml_evaluator
)


# ============================================================
# CHIA DỮ LIỆU GỐC STRATEGY 1
# ============================================================


# Lấy Train / Validation / Test của dữ liệu gốc
# bằng đúng 3 bộ index đã chia ở bước trước
original_train_s1, original_validation_s1, original_test_s1 = (
    ml_evaluator.get_data_splits_by_indices(

        # Dữ liệu gốc đã căn chỉnh còn đúng 30.604 bản ghi
        strategy1_original_aligned,

        # Index của tập Train
        train_indices_s1,

        # Index của tập Validation
        validation_indices_s1,

        # Index của tập Test
        test_indices_s1
    )
)


# ============================================================
# CHIA DỮ LIỆU ẨN DANH STRATEGY 1
# ============================================================


# Lấy Train / Validation / Test của dữ liệu ẩn danh
# bằng CHÍNH XÁC cùng 3 bộ index ở trên
anonymized_train_s1, anonymized_validation_s1, anonymized_test_s1 = (
    ml_evaluator.get_data_splits_by_indices(

        # Dataset ẩn danh Strategy 1
        strategy1_release_auto,

        # Dùng cùng index Train với dữ liệu gốc
        train_indices_s1,

        # Dùng cùng index Validation với dữ liệu gốc
        validation_indices_s1,

        # Dùng cùng index Test với dữ liệu gốc
        test_indices_s1
    )
)


# ============================================================
# KIỂM TRA KÍCH THƯỚC
# ============================================================


# Hiển thị kích thước Train của Original và Anonymized
print(
    "Original Train:",
    original_train_s1.shape,
    "| Anonymized Train:",
    anonymized_train_s1.shape
)


# Hiển thị kích thước Validation của Original và Anonymized
print(
    "Original Validation:",
    original_validation_s1.shape,
    "| Anonymized Validation:",
    anonymized_validation_s1.shape
)


# Hiển thị kích thước Test của Original và Anonymized
print(
    "Original Test:",
    original_test_s1.shape,
    "| Anonymized Test:",
    anonymized_test_s1.shape
)


# ============================================================
# KIỂM TRA TARGET THU_NHAP
# ============================================================


# Kiểm tra target của tập Train có giống hoàn toàn không
train_target_match = (
    original_train_s1["thu_nhap"].tolist()
    ==
    anonymized_train_s1["thu_nhap"].tolist()
)


# Kiểm tra target của tập Validation có giống hoàn toàn không
validation_target_match = (
    original_validation_s1["thu_nhap"].tolist()
    ==
    anonymized_validation_s1["thu_nhap"].tolist()
)


# Kiểm tra target của tập Test có giống hoàn toàn không
test_target_match = (
    original_test_s1["thu_nhap"].tolist()
    ==
    anonymized_test_s1["thu_nhap"].tolist()
)


# Hiển thị kết quả kiểm tra target Train
print(
    "Target Train giống nhau?:",
    train_target_match
)


# Hiển thị kết quả kiểm tra target Validation
print(
    "Target Validation giống nhau?:",
    validation_target_match
)


# Hiển thị kết quả kiểm tra target Test
print(
    "Target Test giống nhau?:",
    test_target_match
)

In [ ]:
# ============================================================
# KIỂM TRA HÀM CHUẨN BỊ FEATURE VÀ TARGET CỦA ORIGINAL
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module chứa các hàm đánh giá Machine Learning
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm prepare_original_features_target()
importlib.reload(
    ml_evaluator
)


# Gọi hàm để tách:
# - X = 7 feature gốc dùng cho Machine Learning
# - y = target thu_nhap
#
# Dữ liệu đầu vào là tập Train của Original Strategy 1
X_original_train_s1, y_original_train_s1 = (
    ml_evaluator.prepare_original_features_target(
        original_train_s1,
        target_column="thu_nhap"
    )
)


# Hiển thị kích thước của X
# Kỳ vọng có 18.362 dòng và 7 feature
print(
    "Kích thước X Original Train:",
    X_original_train_s1.shape
)


# Hiển thị số lượng giá trị target
# Kỳ vọng có đúng 18.362 nhãn thu_nhap
print(
    "Số lượng y Original Train:",
    len(
        y_original_train_s1
    )
)


# Hiển thị tên 7 feature
# để chắc chắn không lấy nhầm các cột khác của dataset gốc
print(
    "Các feature Original:",
    X_original_train_s1.columns.tolist()
)


# Đếm số missing value sau khi dấu ? đã được chuyển thành np.nan
# Mục đích là xác nhận dữ liệu thiếu đã được chuẩn bị đúng
print(
    "Số missing value trong từng feature:"
)


# Hiển thị số lượng missing của từng cột
print(
    X_original_train_s1
    .isna()
    .sum()
)

In [ ]:
# ============================================================
# KIỂM TRA HÀM CHUẨN BỊ FEATURE VÀ TARGET
# CỦA DỮ LIỆU ẨN DANH STRATEGY 1
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module chứa các hàm đánh giá Machine Learning
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm prepare_anonymized_features_target()
importlib.reload(
    ml_evaluator
)


# Tách dữ liệu ẩn danh Train của Strategy 1 thành:
# - X = 7 feature đã được ẩn danh hóa
# - y = target thu_nhap
X_anonymized_train_s1, y_anonymized_train_s1 = (
    ml_evaluator.prepare_anonymized_features_target(
        anonymized_train_s1,
        target_column="thu_nhap"
    )
)


# Hiển thị kích thước X của dữ liệu ẩn danh
# Kỳ vọng: 18.362 dòng và 7 feature
print(
    "Kích thước X Anonymized Train:",
    X_anonymized_train_s1.shape
)


# Hiển thị số lượng target
# Kỳ vọng: 18.362 giá trị
print(
    "Số lượng y Anonymized Train:",
    len(
        y_anonymized_train_s1
    )
)


# Hiển thị tên các feature sau khi ẩn danh hóa
print(
    "Các feature Anonymized:",
    X_anonymized_train_s1.columns.tolist()
)


# Kiểm tra target Original và Anonymized có giống nhau không
# True nghĩa là hai mô hình sẽ học trên đúng cùng nhãn
same_train_target = (
    y_original_train_s1.tolist()
    ==
    y_anonymized_train_s1.tolist()
)


# Hiển thị kết quả kiểm tra target
print(
    "Target Original và Anonymized giống nhau?:",
    same_train_target
)

In [ ]:
# ============================================================
# KIỂM TRA BỘ PREPROCESSING CỦA DỮ LIỆU ORIGINAL
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module ml_evaluator
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm build_original_preprocessor()
importlib.reload(
    ml_evaluator
)


# Tạo bộ preprocessing dành cho dữ liệu Original
# Lúc này preprocessor mới chỉ được tạo, chưa học từ dữ liệu
original_preprocessor_s1 = (
    ml_evaluator.build_original_preprocessor()
)


# Fit preprocessing CHỈ trên tập Train
# Điều này rất quan trọng để tránh data leakage
#
# fit_transform() sẽ:
# - học median của các cột số
# - học giá trị phổ biến nhất của cột phân loại
# - học các category cho OneHotEncoder
# - chuẩn hóa các cột số
# - chuyển toàn bộ dữ liệu thành dạng số
X_original_train_processed_s1 = (
    original_preprocessor_s1.fit_transform(
        X_original_train_s1
    )
)


# Hiển thị kích thước dữ liệu sau preprocessing
# Số dòng vẫn phải là 18.362
# Số cột sẽ tăng vì OneHotEncoder tạo thêm nhiều cột 0/1
print(
    "Kích thước Original Train sau preprocessing:",
    X_original_train_processed_s1.shape
)


# Hiển thị kiểu dữ liệu sau preprocessing
# Kết quả có thể là numpy array hoặc sparse matrix
print(
    "Kiểu dữ liệu sau preprocessing:",
    type(
        X_original_train_processed_s1
    )
)

In [ ]:
# ============================================================
# KIỂM TRA BỘ PREPROCESSING CỦA DỮ LIỆU ANONYMIZED
# STRATEGY 1
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module ml_evaluator
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm build_anonymized_preprocessor()
importlib.reload(
    ml_evaluator
)


# Lấy danh sách tên 7 feature của dữ liệu ẩn danh Strategy 1
# Danh sách này sẽ được truyền vào bộ preprocessing
anonymized_feature_columns_s1 = (
    X_anonymized_train_s1.columns.tolist()
)


# Tạo bộ preprocessing dành cho dữ liệu ẩn danh Strategy 1
# Lúc này preprocessor mới chỉ được tạo, chưa học từ dữ liệu
anonymized_preprocessor_s1 = (
    ml_evaluator.build_anonymized_preprocessor(
        anonymized_feature_columns_s1
    )
)


# Fit preprocessing CHỈ trên tập Train
# để tránh data leakage từ Validation hoặc Test
#
# fit_transform() sẽ:
# - học giá trị phổ biến nhất nếu có missing
# - học các category xuất hiện trong Train
# - chuyển category thành các cột 0/1 bằng OneHotEncoder
X_anonymized_train_processed_s1 = (
    anonymized_preprocessor_s1.fit_transform(
        X_anonymized_train_s1
    )
)


# Hiển thị kích thước dữ liệu ẩn danh sau preprocessing
# Số dòng phải giữ nguyên là 18.362
print(
    "Kích thước Anonymized Train sau preprocessing:",
    X_anonymized_train_processed_s1.shape
)


# Hiển thị kiểu dữ liệu sau preprocessing
# Thường sẽ là sparse matrix do OneHotEncoder tạo ra
print(
    "Kiểu dữ liệu sau preprocessing:",
    type(
        X_anonymized_train_processed_s1
    )
)

In [ ]:
# ============================================================
# KIỂM TRA HÀM TẠO PIPELINE LOGISTIC REGRESSION
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Import module ml_evaluator
import ml_evaluator


# Nạp lại module vì chúng ta vừa thêm
# hàm build_logistic_regression_pipeline()
importlib.reload(
    ml_evaluator
)


# Tạo một bộ preprocessing mới dành cho dữ liệu Original
# Chúng ta tạo mới để pipeline chưa bị ảnh hưởng
# bởi lần fit thử preprocessing trước đó
original_preprocessor_for_model_s1 = (
    ml_evaluator.build_original_preprocessor()
)


# Tạo Pipeline hoàn chỉnh gồm:
# preprocessing → Logistic Regression
original_model_pipeline_s1 = (
    ml_evaluator.build_logistic_regression_pipeline(
        original_preprocessor_for_model_s1
    )
)


# Hiển thị kiểu đối tượng được tạo
# Kỳ vọng đây phải là sklearn Pipeline
print(
    "Kiểu pipeline:",
    type(
        original_model_pipeline_s1
    )
)


# Hiển thị tên các bước có trong Pipeline
# Kỳ vọng gồm đúng:
# preprocessor và model
print(
    "Các bước trong pipeline:",
    list(
        original_model_pipeline_s1.named_steps.keys()
    )
)


# Kiểm tra loại mô hình nằm ở bước model
# Kỳ vọng là LogisticRegression
print(
    "Mô hình:",
    type(
        original_model_pipeline_s1.named_steps["model"]
    )
)


# Kiểm tra max_iter đã được cấu hình đúng là 1000 chưa
print(
    "max_iter:",
    original_model_pipeline_s1.named_steps["model"].max_iter
)

In [ ]:
# ============================================================
# HUẤN LUYỆN LOGISTIC REGRESSION
# TRÊN DỮ LIỆU ORIGINAL TRAIN CỦA STRATEGY 1
# ============================================================


# Huấn luyện toàn bộ Pipeline trên tập Train
#
# Pipeline sẽ tự động thực hiện:
# 1. Điền missing value
# 2. Chuẩn hóa các feature số
# 3. One-Hot Encoding các feature phân loại
# 4. Huấn luyện Logistic Regression
original_model_pipeline_s1.fit(
    X_original_train_s1,
    y_original_train_s1
)


# Lấy mô hình Logistic Regression
# sau khi đã được huấn luyện xong
trained_original_model_s1 = (
    original_model_pipeline_s1
    .named_steps[
        "model"
    ]
)


# Hiển thị các lớp mà mô hình đã học
# Kỳ vọng gồm hai lớp <=50K và >50K
print(
    "Các lớp mô hình đã học:",
    trained_original_model_s1.classes_
)


# Hiển thị kích thước hệ số của Logistic Regression
# Nếu preprocessing đúng thì mô hình phải nhận 71 feature
print(
    "Kích thước hệ số mô hình:",
    trained_original_model_s1.coef_.shape
)

In [ ]:
# ============================================================
# HUẤN LUYỆN LOGISTIC REGRESSION
# TRÊN DỮ LIỆU ANONYMIZED TRAIN CỦA STRATEGY 1
# ============================================================


# Lấy danh sách 7 feature của dữ liệu ẩn danh Strategy 1
# Danh sách này sẽ được dùng để tạo bộ preprocessing
anonymized_feature_columns_for_model_s1 = (
    X_anonymized_train_s1.columns.tolist()
)


# Tạo một bộ preprocessing MỚI cho dữ liệu ẩn danh
# Không dùng lại preprocessor đã fit thử trước đó
anonymized_preprocessor_for_model_s1 = (
    ml_evaluator.build_anonymized_preprocessor(
        anonymized_feature_columns_for_model_s1
    )
)


# Tạo Pipeline gồm:
# preprocessing → Logistic Regression
anonymized_model_pipeline_s1 = (
    ml_evaluator.build_logistic_regression_pipeline(
        anonymized_preprocessor_for_model_s1
    )
)


# Huấn luyện Pipeline trên tập Anonymized Train
# Pipeline sẽ tự:
# - xử lý missing nếu có
# - One-Hot Encoding
# - huấn luyện Logistic Regression
anonymized_model_pipeline_s1.fit(
    X_anonymized_train_s1,
    y_anonymized_train_s1
)


# Lấy mô hình Logistic Regression
# sau khi đã huấn luyện xong
trained_anonymized_model_s1 = (
    anonymized_model_pipeline_s1
    .named_steps[
        "model"
    ]
)


# Hiển thị các lớp mà mô hình đã học
print(
    "Các lớp mô hình Anonymized đã học:",
    trained_anonymized_model_s1.classes_
)


# Hiển thị kích thước hệ số của mô hình
# Kỳ vọng mô hình nhận 21 feature sau preprocessing
print(
    "Kích thước hệ số mô hình Anonymized:",
    trained_anonymized_model_s1.coef_.shape
)

In [ ]:
# ============================================================
# CHUẨN BỊ DỮ LIỆU VALIDATION CHO STRATEGY 1
# ============================================================


# Chuẩn bị X và y của dữ liệu Original Validation
# Hàm sẽ lấy đúng 7 feature gốc
# và chuyển dấu ? thành missing value nếu có
X_original_validation_s1, y_original_validation_s1 = (
    ml_evaluator.prepare_original_features_target(
        original_validation_s1,
        target_column="thu_nhap"
    )
)


# Chuẩn bị X và y của dữ liệu Anonymized Validation
# Hàm sẽ lấy 7 feature đã được generalization
# và tách riêng target thu_nhap
X_anonymized_validation_s1, y_anonymized_validation_s1 = (
    ml_evaluator.prepare_anonymized_features_target(
        anonymized_validation_s1,
        target_column="thu_nhap"
    )
)


# Hiển thị kích thước X Original Validation
# Kỳ vọng có 6.121 dòng và 7 feature
print(
    "X Original Validation:",
    X_original_validation_s1.shape
)


# Hiển thị kích thước X Anonymized Validation
# Kỳ vọng cũng có 6.121 dòng và 7 feature
print(
    "X Anonymized Validation:",
    X_anonymized_validation_s1.shape
)


# Kiểm tra số lượng target của Original
print(
    "Số lượng y Original Validation:",
    len(
        y_original_validation_s1
    )
)


# Kiểm tra số lượng target của Anonymized
print(
    "Số lượng y Anonymized Validation:",
    len(
        y_anonymized_validation_s1
    )
)


# So sánh target của hai tập Validation
# True nghĩa là Original và Anonymized
# đang được đánh giá trên chính xác cùng nhãn
same_validation_target_s1 = (
    y_original_validation_s1.tolist()
    ==
    y_anonymized_validation_s1.tolist()
)


# Hiển thị kết quả kiểm tra target
print(
    "Target Validation giống nhau?:",
    same_validation_target_s1
)

In [ ]:
# ============================================================
# DỰ ĐOÁN TRÊN TẬP VALIDATION
# CHO ORIGINAL VÀ ANONYMIZED STRATEGY 1
# ============================================================


# ============================================================
# 1. DỰ ĐOÁN VỚI MÔ HÌNH ORIGINAL
# ============================================================


# Dùng mô hình Original đã huấn luyện
# để dự đoán nhãn thu_nhap trên tập Validation
y_pred_original_validation_s1 = (
    original_model_pipeline_s1.predict(
        X_original_validation_s1
    )
)


# Lấy danh sách các lớp mà mô hình Original đã học
# Ví dụ: ['<=50K', '>50K']
original_classes_s1 = (
    original_model_pipeline_s1
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
# Không viết cứng [:, 1] để code an toàn hơn
original_positive_index_s1 = (
    list(
        original_classes_s1
    )
    .index(
        ">50K"
    )
)


# Dự đoán xác suất của lớp >50K
# Xác suất này sẽ được dùng để tính ROC-AUC
y_prob_original_validation_s1 = (
    original_model_pipeline_s1.predict_proba(
        X_original_validation_s1
    )[
        :,
        original_positive_index_s1
    ]
)


# ============================================================
# 2. DỰ ĐOÁN VỚI MÔ HÌNH ANONYMIZED
# ============================================================


# Dùng mô hình Anonymized đã huấn luyện
# để dự đoán nhãn trên cùng tập Validation
y_pred_anonymized_validation_s1 = (
    anonymized_model_pipeline_s1.predict(
        X_anonymized_validation_s1
    )
)


# Lấy danh sách các lớp mà mô hình Anonymized đã học
anonymized_classes_s1 = (
    anonymized_model_pipeline_s1
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
anonymized_positive_index_s1 = (
    list(
        anonymized_classes_s1
    )
    .index(
        ">50K"
    )
)


# Dự đoán xác suất thuộc lớp >50K
# để sau này tính ROC-AUC cho dữ liệu ẩn danh
y_prob_anonymized_validation_s1 = (
    anonymized_model_pipeline_s1.predict_proba(
        X_anonymized_validation_s1
    )[
        :,
        anonymized_positive_index_s1
    ]
)


# ============================================================
# 3. KIỂM TRA KẾT QUẢ DỰ ĐOÁN
# ============================================================


# Kiểm tra số lượng nhãn dự đoán Original
# Phải bằng đúng 6.121 bản ghi Validation
print(
    "Số dự đoán Original:",
    len(
        y_pred_original_validation_s1
    )
)


# Kiểm tra số lượng xác suất Original
# Cũng phải bằng 6.121
print(
    "Số xác suất Original:",
    len(
        y_prob_original_validation_s1
    )
)


# Kiểm tra số lượng nhãn dự đoán Anonymized
print(
    "Số dự đoán Anonymized:",
    len(
        y_pred_anonymized_validation_s1
    )
)


# Kiểm tra số lượng xác suất Anonymized
print(
    "Số xác suất Anonymized:",
    len(
        y_prob_anonymized_validation_s1
    )
)


# Kiểm tra xác suất nhỏ nhất và lớn nhất của Original
# Các giá trị phải nằm trong khoảng từ 0 đến 1
print(
    "Khoảng xác suất Original:",
    y_prob_original_validation_s1.min(),
    "→",
    y_prob_original_validation_s1.max()
)


# Kiểm tra xác suất nhỏ nhất và lớn nhất của Anonymized
# Các giá trị cũng phải nằm trong khoảng từ 0 đến 1
print(
    "Khoảng xác suất Anonymized:",
    y_prob_anonymized_validation_s1.min(),
    "→",
    y_prob_anonymized_validation_s1.max()
)

In [ ]:
# ============================================================
# TÍNH CÁC METRIC VALIDATION
# CHO ORIGINAL VÀ ANONYMIZED STRATEGY 1
# ============================================================


# Import importlib để có thể nạp lại module mới nhất
import importlib


# Import module utility_evaluator
# Module này chứa hàm tính Accuracy, Precision, Recall,
# F1-score, Balanced Accuracy và ROC-AUC
import utility_evaluator


# Nạp lại utility_evaluator để chắc chắn
# notebook đang dùng phiên bản code mới nhất
importlib.reload(
    utility_evaluator
)


# ============================================================
# 1. TÍNH METRIC CHO ORIGINAL
# ============================================================


# Tính các chỉ số đánh giá cho mô hình Original
original_validation_metrics_s1 = (
    utility_evaluator.evaluate_classification_metrics(

        # Nhãn thật của tập Original Validation
        y_true=y_original_validation_s1,

        # Nhãn mà mô hình Original dự đoán
        y_pred=y_pred_original_validation_s1,

        # Xác suất dự đoán lớp >50K
        y_prob=y_prob_original_validation_s1,

        # Xác định >50K là lớp dương
        positive_label=">50K"
    )
)


# ============================================================
# 2. TÍNH METRIC CHO ANONYMIZED
# ============================================================


# Tính các chỉ số đánh giá cho mô hình Anonymized
anonymized_validation_metrics_s1 = (
    utility_evaluator.evaluate_classification_metrics(

        # Nhãn thật của tập Anonymized Validation
        y_true=y_anonymized_validation_s1,

        # Nhãn mà mô hình Anonymized dự đoán
        y_pred=y_pred_anonymized_validation_s1,

        # Xác suất dự đoán lớp >50K
        y_prob=y_prob_anonymized_validation_s1,

        # Xác định >50K là lớp dương
        positive_label=">50K"
    )
)


# ============================================================
# 3. HIỂN THỊ KẾT QUẢ ORIGINAL
# ============================================================


# In tiêu đề kết quả của Original
print(
    "===== ORIGINAL VALIDATION ====="
)


# Duyệt từng metric của Original
for metric_name, metric_value in original_validation_metrics_s1.items():

    # Hiển thị tên metric và giá trị dưới dạng phần trăm
    print(
        metric_name,
        ":",
        round(
            metric_value * 100,
            2
        ),
        "%"
    )


# ============================================================
# 4. HIỂN THỊ KẾT QUẢ ANONYMIZED
# ============================================================


# In tiêu đề kết quả của Anonymized
print(
    "\n===== ANONYMIZED VALIDATION ====="
)


# Duyệt từng metric của Anonymized
for metric_name, metric_value in anonymized_validation_metrics_s1.items():

    # Hiển thị tên metric và giá trị dưới dạng phần trăm
    print(
        metric_name,
        ":",
        round(
            metric_value * 100,
            2
        ),
        "%"
    )

In [ ]:
# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib

# Import module ml_evaluator chứa hàm chia dữ liệu
import ml_evaluator

# Nạp lại module vì chúng ta vừa sửa cách chia Train / Validation / Test
importlib.reload(ml_evaluator)

# Chia lại index Strategy 1 theo đúng cách của notebook ML cũ:
# 60% Train → 40% Temp → chia Temp thành 20% Validation và 20% Test
train_indices_s1, validation_indices_s1, test_indices_s1 = (
    ml_evaluator.split_train_validation_test_indices(
        # Dữ liệu gốc đã căn chỉnh với Strategy 1
        strategy1_original_aligned,

        # Cột mục tiêu dùng để stratify
        target_column="thu_nhap",

        # Cố định kết quả ngẫu nhiên giống thí nghiệm cũ
        random_state=42
    )
)

# Hiển thị số lượng bản ghi Train sau khi chia lại
print(
    "Số bản ghi Train:",
    len(train_indices_s1)
)

# Hiển thị số lượng bản ghi Validation sau khi chia lại
print(
    "Số bản ghi Validation:",
    len(validation_indices_s1)
)

# Hiển thị số lượng bản ghi Test sau khi chia lại
print(
    "Số bản ghi Test:",
    len(test_indices_s1)
)

# Kiểm tra tổng số bản ghi vẫn phải bằng 30.604
print(
    "Tổng số bản ghi:",
    len(train_indices_s1)
    + len(validation_indices_s1)
    + len(test_indices_s1)
)

In [ ]:
# ============================================================
# CHIA LẠI STRATEGY 1 BẰNG HÀM ĐÃ SỬA
# VÀ KIỂM TRA VỚI CÁCH CHIA THAM CHIẾU
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất của ml_evaluator.py
import importlib


# Nạp lại module để chắc chắn notebook dùng hàm vừa kiểm tra
ml_evaluator = importlib.reload(
    ml_evaluator
)


# Chia LẠI index Strategy 1 bằng hàm mới
# Việc gán lại này sẽ thay thế các biến đang chứa kết quả chia cũ
train_indices_s1, validation_indices_s1, test_indices_s1 = (
    ml_evaluator.split_train_validation_test_indices(

        # Dữ liệu Original đã căn chỉnh với Strategy 1
        strategy1_original_aligned,

        # Cột target dùng để stratify
        target_column="thu_nhap",

        # Giữ đúng random_state của thí nghiệm cũ
        random_state=42
    )
)


# Kiểm tra Train của module
# có giống phép chia 60/40 tham chiếu đã tạo trước đó không
same_train_s1 = (
    list(train_indices_s1)
    ==
    list(reference_train_indices_s1)
)


# Kiểm tra Validation
# có giống phép chia tham chiếu không
same_validation_s1 = (
    list(validation_indices_s1)
    ==
    list(reference_validation_indices_s1)
)


# Kiểm tra Test
# có giống phép chia tham chiếu không
same_test_s1 = (
    list(test_indices_s1)
    ==
    list(reference_test_indices_s1)
)


# Hiển thị kết quả kiểm tra Train
print(
    "Train giống cách chia tham chiếu?:",
    same_train_s1
)


# Hiển thị kết quả kiểm tra Validation
print(
    "Validation giống cách chia tham chiếu?:",
    same_validation_s1
)


# Hiển thị kết quả kiểm tra Test
print(
    "Test giống cách chia tham chiếu?:",
    same_test_s1
)


# Kiểm tra lại số lượng bản ghi sau khi chia
print(
    "Số bản ghi:",
    len(train_indices_s1),
    len(validation_indices_s1),
    len(test_indices_s1)
)

In [ ]:
# ============================================================
# TẠO LẠI TRAIN / VALIDATION / TEST
# SAU KHI ĐÃ SỬA CÁCH CHIA INDEX
# ============================================================


# Lấy lại 3 tập của dữ liệu Original
# bằng bộ index mới vừa được xác nhận là đúng
original_train_s1, original_validation_s1, original_test_s1 = (
    ml_evaluator.get_data_splits_by_indices(

        # Dữ liệu gốc đã căn chỉnh với Strategy 1
        strategy1_original_aligned,

        # Index Train mới
        train_indices_s1,

        # Index Validation mới
        validation_indices_s1,

        # Index Test mới
        test_indices_s1
    )
)


# Lấy lại 3 tập của dữ liệu Anonymized
# bằng CHÍNH XÁC cùng bộ index với Original
anonymized_train_s1, anonymized_validation_s1, anonymized_test_s1 = (
    ml_evaluator.get_data_splits_by_indices(

        # Dữ liệu ẩn danh của Strategy 1
        strategy1_release_auto,

        # Dùng cùng index Train
        train_indices_s1,

        # Dùng cùng index Validation
        validation_indices_s1,

        # Dùng cùng index Test
        test_indices_s1
    )
)


# Kiểm tra kích thước tập Train
print(
    "Train:",
    original_train_s1.shape,
    anonymized_train_s1.shape
)


# Kiểm tra kích thước tập Validation
print(
    "Validation:",
    original_validation_s1.shape,
    anonymized_validation_s1.shape
)


# Kiểm tra kích thước tập Test
print(
    "Test:",
    original_test_s1.shape,
    anonymized_test_s1.shape
)


# Kiểm tra target Train giữa Original và Anonymized
# True nghĩa là hai bên đang chứa đúng cùng nhãn
print(
    "Target Train giống nhau?:",
    original_train_s1["thu_nhap"].tolist()
    ==
    anonymized_train_s1["thu_nhap"].tolist()
)


# Kiểm tra target Validation giữa Original và Anonymized
print(
    "Target Validation giống nhau?:",
    original_validation_s1["thu_nhap"].tolist()
    ==
    anonymized_validation_s1["thu_nhap"].tolist()
)


# Kiểm tra target Test giữa Original và Anonymized
print(
    "Target Test giống nhau?:",
    original_test_s1["thu_nhap"].tolist()
    ==
    anonymized_test_s1["thu_nhap"].tolist()
)

In [ ]:
# ============================================================
# TẠO LẠI X VÀ y CỦA TẬP TRAIN
# SAU KHI ĐÃ SỬA CÁCH CHIA DỮ LIỆU
# ============================================================


# Tạo lại feature X và target y
# cho dữ liệu Original Train mới
X_original_train_s1, y_original_train_s1 = (
    ml_evaluator.prepare_original_features_target(

        # Tập Original Train vừa được tạo lại bằng index đúng
        original_train_s1,

        # Cột cần dự đoán của bài toán Machine Learning
        target_column="thu_nhap"
    )
)


# Tạo lại feature X và target y
# cho dữ liệu Anonymized Train mới
X_anonymized_train_s1, y_anonymized_train_s1 = (
    ml_evaluator.prepare_anonymized_features_target(

        # Tập Anonymized Train vừa được tạo lại bằng cùng index
        anonymized_train_s1,

        # Cột target không bị thay đổi khi ẩn danh hóa
        target_column="thu_nhap"
    )
)


# Kiểm tra kích thước X Original
# Phải có 18.362 dòng và 7 feature
print(
    "X Original Train:",
    X_original_train_s1.shape
)


# Kiểm tra kích thước X Anonymized
# Cũng phải có 18.362 dòng và 7 feature
print(
    "X Anonymized Train:",
    X_anonymized_train_s1.shape
)


# Kiểm tra số lượng target Original
print(
    "y Original Train:",
    len(
        y_original_train_s1
    )
)


# Kiểm tra số lượng target Anonymized
print(
    "y Anonymized Train:",
    len(
        y_anonymized_train_s1
    )
)


# So sánh target của hai tập Train
# True nghĩa là hai mô hình sẽ được huấn luyện
# trên chính xác cùng 18.362 nhãn
print(
    "Target Train giống nhau?:",
    y_original_train_s1.tolist()
    ==
    y_anonymized_train_s1.tolist()
)

In [ ]:
# ============================================================
# TẠO MỚI VÀ HUẤN LUYỆN LẠI HAI MÔ HÌNH
# SAU KHI ĐÃ SỬA CÁCH CHIA DỮ LIỆU
# ============================================================


# ============================================================
# 1. TẠO VÀ HUẤN LUYỆN MÔ HÌNH ORIGINAL
# ============================================================


# Tạo một bộ preprocessing MỚI cho dữ liệu Original
# Không dùng lại preprocessor đã fit trên cách chia cũ
original_preprocessor_s1 = (
    ml_evaluator.build_original_preprocessor()
)


# Tạo một Pipeline Logistic Regression MỚI
# gồm preprocessing và mô hình Logistic Regression
original_model_pipeline_s1 = (
    ml_evaluator.build_logistic_regression_pipeline(
        original_preprocessor_s1
    )
)


# Huấn luyện mô hình Original
# trên đúng 18.362 bản ghi Train mới
original_model_pipeline_s1.fit(
    X_original_train_s1,
    y_original_train_s1
)


# ============================================================
# 2. TẠO VÀ HUẤN LUYỆN MÔ HÌNH ANONYMIZED
# ============================================================


# Lấy danh sách 7 feature của Strategy 1
# để tạo preprocessing cho dữ liệu ẩn danh
anonymized_feature_columns_s1 = (
    X_anonymized_train_s1
    .columns
    .tolist()
)


# Tạo một bộ preprocessing MỚI
# cho dữ liệu Anonymized Strategy 1
anonymized_preprocessor_s1 = (
    ml_evaluator.build_anonymized_preprocessor(
        anonymized_feature_columns_s1
    )
)


# Tạo một Pipeline Logistic Regression MỚI
# dành cho dữ liệu Anonymized
anonymized_model_pipeline_s1 = (
    ml_evaluator.build_logistic_regression_pipeline(
        anonymized_preprocessor_s1
    )
)


# Huấn luyện mô hình Anonymized
# trên đúng cùng 18.362 bản ghi Train
anonymized_model_pipeline_s1.fit(
    X_anonymized_train_s1,
    y_anonymized_train_s1
)


# ============================================================
# 3. KIỂM TRA SAU KHI HUẤN LUYỆN
# ============================================================


# Lấy số feature mà mô hình Original thực sự nhận
# sau preprocessing
original_coef_shape_s1 = (
    original_model_pipeline_s1
    .named_steps["model"]
    .coef_
    .shape
)


# Lấy số feature mà mô hình Anonymized thực sự nhận
# sau preprocessing
anonymized_coef_shape_s1 = (
    anonymized_model_pipeline_s1
    .named_steps["model"]
    .coef_
    .shape
)


# Hiển thị kích thước hệ số của mô hình Original
print(
    "Original model coef:",
    original_coef_shape_s1
)


# Hiển thị kích thước hệ số của mô hình Anonymized
print(
    "Anonymized model coef:",
    anonymized_coef_shape_s1
)


# Xác nhận hai mô hình đều đã được huấn luyện
print(
    "Đã huấn luyện lại hai mô hình thành công."
)

In [ ]:
# ============================================================
# TẠO LẠI X VÀ y CỦA TẬP VALIDATION
# SAU KHI ĐÃ SỬA CÁCH CHIA DỮ LIỆU
# ============================================================


# Chuẩn bị lại feature X và target y
# cho tập Original Validation mới
X_original_validation_s1, y_original_validation_s1 = (
    ml_evaluator.prepare_original_features_target(

        # Tập Original Validation được tạo từ index đúng
        original_validation_s1,

        # Cột target cần dự đoán
        target_column="thu_nhap"
    )
)


# Chuẩn bị lại feature X và target y
# cho tập Anonymized Validation mới
X_anonymized_validation_s1, y_anonymized_validation_s1 = (
    ml_evaluator.prepare_anonymized_features_target(

        # Tập Anonymized Validation dùng cùng index với Original
        anonymized_validation_s1,

        # Cột target không bị thay đổi khi ẩn danh hóa
        target_column="thu_nhap"
    )
)


# Kiểm tra kích thước X Original Validation
# Kỳ vọng có 6.121 dòng và 7 feature
print(
    "X Original Validation:",
    X_original_validation_s1.shape
)


# Kiểm tra kích thước X Anonymized Validation
# Kỳ vọng cũng có 6.121 dòng và 7 feature
print(
    "X Anonymized Validation:",
    X_anonymized_validation_s1.shape
)


# Kiểm tra số lượng target Original Validation
print(
    "y Original Validation:",
    len(
        y_original_validation_s1
    )
)


# Kiểm tra số lượng target Anonymized Validation
print(
    "y Anonymized Validation:",
    len(
        y_anonymized_validation_s1
    )
)


# Kiểm tra target của Original và Anonymized
# có giống nhau hoàn toàn hay không
print(
    "Target Validation giống nhau?:",
    y_original_validation_s1.tolist()
    ==
    y_anonymized_validation_s1.tolist()
)

In [ ]:
# ============================================================
# DỰ ĐOÁN LẠI TRÊN VALIDATION
# SAU KHI ĐÃ SỬA CÁCH CHIA DỮ LIỆU
# ============================================================


# ============================================================
# 1. DỰ ĐOÁN VỚI MÔ HÌNH ORIGINAL
# ============================================================


# Dùng mô hình Original vừa huấn luyện lại
# để dự đoán nhãn thu_nhap trên tập Validation mới
y_pred_original_validation_s1 = (
    original_model_pipeline_s1.predict(
        X_original_validation_s1
    )
)


# Lấy danh sách các lớp mà mô hình Original đã học
# Kỳ vọng gồm <=50K và >50K
original_classes_s1 = (
    original_model_pipeline_s1
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
# để lấy đúng xác suất dùng cho ROC-AUC
original_positive_index_s1 = (
    list(
        original_classes_s1
    )
    .index(
        ">50K"
    )
)


# Lấy xác suất dự đoán thuộc lớp >50K
# cho từng bản ghi Validation
y_prob_original_validation_s1 = (
    original_model_pipeline_s1.predict_proba(
        X_original_validation_s1
    )[
        :,
        original_positive_index_s1
    ]
)


# ============================================================
# 2. DỰ ĐOÁN VỚI MÔ HÌNH ANONYMIZED
# ============================================================


# Dùng mô hình Anonymized vừa huấn luyện lại
# để dự đoán trên tập Validation tương ứng
y_pred_anonymized_validation_s1 = (
    anonymized_model_pipeline_s1.predict(
        X_anonymized_validation_s1
    )
)


# Lấy danh sách các lớp mà mô hình Anonymized đã học
anonymized_classes_s1 = (
    anonymized_model_pipeline_s1
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
# trong mô hình Anonymized
anonymized_positive_index_s1 = (
    list(
        anonymized_classes_s1
    )
    .index(
        ">50K"
    )
)


# Lấy xác suất dự đoán thuộc lớp >50K
# để sau này tính ROC-AUC
y_prob_anonymized_validation_s1 = (
    anonymized_model_pipeline_s1.predict_proba(
        X_anonymized_validation_s1
    )[
        :,
        anonymized_positive_index_s1
    ]
)


# ============================================================
# 3. KIỂM TRA SỐ LƯỢNG DỰ ĐOÁN
# ============================================================


# Kiểm tra số nhãn dự đoán của Original
print(
    "Số dự đoán Original:",
    len(
        y_pred_original_validation_s1
    )
)


# Kiểm tra số xác suất của Original
print(
    "Số xác suất Original:",
    len(
        y_prob_original_validation_s1
    )
)


# Kiểm tra số nhãn dự đoán của Anonymized
print(
    "Số dự đoán Anonymized:",
    len(
        y_pred_anonymized_validation_s1
    )
)


# Kiểm tra số xác suất của Anonymized
print(
    "Số xác suất Anonymized:",
    len(
        y_prob_anonymized_validation_s1
    )
)

In [ ]:
# ============================================================
# TÍNH LẠI METRIC VALIDATION CHO STRATEGY 1
# SAU KHI ĐÃ SỬA ĐÚNG CÁCH CHIA DỮ LIỆU
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất
# của module utility_evaluator
import importlib


# Import module chứa các hàm tính metric Machine Learning
import utility_evaluator


# Nạp lại module để chắc chắn notebook
# đang sử dụng phiên bản code mới nhất
importlib.reload(
    utility_evaluator
)


# ============================================================
# 1. TÍNH METRIC CHO ORIGINAL
# ============================================================


# Tính Accuracy, Precision, Recall, F1-score,
# Balanced Accuracy và ROC-AUC của mô hình Original
original_validation_metrics_s1 = (
    utility_evaluator.evaluate_classification_metrics(

        # Nhãn thật của tập Validation
        y_true=y_original_validation_s1,

        # Nhãn dự đoán của mô hình Original
        y_pred=y_pred_original_validation_s1,

        # Xác suất dự đoán lớp >50K
        y_prob=y_prob_original_validation_s1,

        # Xác định >50K là lớp dương
        positive_label=">50K"
    )
)


# ============================================================
# 2. TÍNH METRIC CHO ANONYMIZED
# ============================================================


# Tính các metric của mô hình học trên dữ liệu ẩn danh
anonymized_validation_metrics_s1 = (
    utility_evaluator.evaluate_classification_metrics(

        # Nhãn thật của cùng tập Validation
        y_true=y_anonymized_validation_s1,

        # Nhãn dự đoán từ dữ liệu ẩn danh
        y_pred=y_pred_anonymized_validation_s1,

        # Xác suất dự đoán lớp >50K
        y_prob=y_prob_anonymized_validation_s1,

        # Xác định >50K là lớp dương
        positive_label=">50K"
    )
)


# ============================================================
# 3. HIỂN THỊ METRIC ORIGINAL
# ============================================================


# In tiêu đề kết quả Original
print(
    "===== ORIGINAL VALIDATION ====="
)


# Duyệt từng metric của Original
for metric_name, metric_value in original_validation_metrics_s1.items():

    # Chuyển metric sang phần trăm
    # và làm tròn 2 chữ số thập phân
    print(
        metric_name,
        ":",
        round(
            metric_value * 100,
            2
        ),
        "%"
    )


# ============================================================
# 4. HIỂN THỊ METRIC ANONYMIZED
# ============================================================


# In tiêu đề kết quả Anonymized
print(
    "\n===== ANONYMIZED VALIDATION ====="
)


# Duyệt từng metric của Anonymized
for metric_name, metric_value in anonymized_validation_metrics_s1.items():

    # Chuyển metric sang phần trăm
    # và làm tròn 2 chữ số thập phân
    print(
        metric_name,
        ":",
        round(
            metric_value * 100,
            2
        ),
        "%"
    )

In [ ]:
# ============================================================
# TÍNH UTILITY RETENTION VÀ UTILITY SCORE
# CHO STRATEGY 1 TRÊN TẬP VALIDATION
# ============================================================


# Gọi hàm calculate_utility_retention()
# để so sánh hiệu quả mô hình:
# Original so với Anonymized
utility_result_validation_s1 = (
    utility_evaluator.calculate_utility_retention(

        # Các metric của mô hình học trên dữ liệu gốc
        original_metrics=original_validation_metrics_s1,

        # Các metric của mô hình học trên dữ liệu ẩn danh
        anonymized_metrics=anonymized_validation_metrics_s1
    )
)


# In tiêu đề để kết quả dễ đọc
print(
    "===== UTILITY RETENTION - STRATEGY 1 ====="
)


# Duyệt từng kết quả Utility Retention
for metric_name, metric_value in utility_result_validation_s1.items():

    # Hiển thị tên chỉ số và giá trị
    # Hàm utility_evaluator đã trả kết quả theo dạng phần trăm
    print(
        metric_name,
        ":",
        round(
            metric_value,
            2
        ),
        "%"
    )

In [ ]:
# ============================================================
# TEST HÀM 9:
# TỰ ĐỘNG ĐÁNH GIÁ UTILITY CỦA STRATEGY 2
# ============================================================


# Gọi Hàm 9 để tự động đánh giá Machine Learning
# cho dữ liệu ẩn danh của Strategy 2
strategy2_ml_auto_result = (
    ml_evaluator.evaluate_strategy_validation(

        # Dataset gốc ban đầu
        original_dataframe=data_check,

        # Dataset ẩn danh được tạo tự động bởi Strategy 2
        anonymized_dataframe=strategy2_release_auto,

        # Các index gốc còn lại sau suppression của Strategy 2
        retained_indices=strategy2_retained_indices_auto,

        # Cột target của bài toán phân loại
        target_column="thu_nhap",

        # Giữ cùng random_state để có thể tái lập thí nghiệm
        random_state=42
    )
)


# Lấy toàn bộ kết quả Utility Retention
# mà hệ thống vừa tự động tính cho Strategy 2
strategy2_utility_auto = (
    strategy2_ml_auto_result[
        "utility_result"
    ]
)


# In tiêu đề kết quả để dễ theo dõi
print(
    "===== UTILITY AUTO - STRATEGY 2 ====="
)


# Duyệt qua từng chỉ số Utility Retention
for metric_name, metric_value in strategy2_utility_auto.items():

    # Hiển thị tên metric và giá trị
    # làm tròn đến 2 chữ số thập phân
    print(
        metric_name,
        ":",
        round(
            metric_value,
            2
        ),
        "%"
    )


# In riêng Utility Score
# Đây là giá trị sau này dùng để so sánh các Strategy
print(
    "\nUtility Score tự động:",
    round(
        strategy2_ml_auto_result[
            "utility_score_percent"
        ],
        2
    ),
    "%"
)

In [ ]:
# ============================================================
# KIỂM TRA CHÍNH XÁC THAM SỐ CỦA HÀM rank_strategies()
# ============================================================


# Import inspect để xem cấu trúc
# của hàm trong strategy_selector.py
import inspect


# Hiển thị chữ ký của hàm
# để biết chính xác hàm nhận những tham số nào
print(
    "Chữ ký của rank_strategies:"
)


# In tên hàm và toàn bộ tham số mà hàm chấp nhận
print(
    inspect.signature(
        strategy_selector.rank_strategies
    )
)


# In toàn bộ code của hàm rank_strategies()
# để chúng ta biết chính xác cách truyền trọng số
print(
    "\n===== CODE HÀM rank_strategies ====="
)


# Hiển thị mã nguồn thật đang được notebook sử dụng
print(
    inspect.getsource(
        strategy_selector.rank_strategies
    )
)

In [ ]:
# ============================================================
# XẾP HẠNG CÁC STRATEGY
# ============================================================


# Import importlib để nạp lại phiên bản mới nhất
# của module strategy_selector
import importlib


# Import module chứa logic tính điểm và xếp hạng Strategy
import strategy_selector


# Nạp lại module để chắc chắn notebook
# đang sử dụng phiên bản mới nhất của strategy_selector.py
strategy_selector = importlib.reload(
    strategy_selector
)


# ============================================================
# GỌI HÀM XẾP HẠNG
# ============================================================


# Gọi hàm rank_strategies()
# để tính Data Retention, Selection Score
# và xếp hạng các Strategy
ranked_strategies = (
    strategy_selector.rank_strategies(

        # Danh sách các Strategy
        # đã được chuẩn bị ở cell trước
        strategies=strategies_for_selection,

        # Trọng số dành cho khả năng giữ lại dữ liệu
        # 0.5 nghĩa là chiếm 50% Selection Score
        weight_data_retention=0.50,

        # Trọng số dành cho Utility Score của Machine Learning
        # 0.5 nghĩa là chiếm 50% Selection Score
        weight_utility=0.50
    )
)


# ============================================================
# HIỂN THỊ KẾT QUẢ XẾP HẠNG
# ============================================================


# Duyệt từng Strategy sau khi đã được xếp hạng
for strategy_result in ranked_strategies:

    # Hiển thị thứ hạng của Strategy
    print(
        "Hạng:",
        strategy_result[
            "rank"
        ]
    )


    # Hiển thị tên Strategy
    print(
        "Strategy:",
        strategy_result[
            "strategy"
        ]
    )


    # Hiển thị tỷ lệ dữ liệu còn được giữ lại
    print(
        "Data Retention (%):",
        round(
            strategy_result[
                "data_retention_%"
            ],
            2
        )
    )


    # Hiển thị Utility Score trên Validation
    print(
        "Utility Score (%):",
        round(
            strategy_result[
                "utility_score_%"
            ],
            2
        )
    )


    # Hiển thị Selection Score
    # Đây là điểm tổng hợp giữa Data Retention và Utility
    print(
        "Selection Score:",
        round(
            strategy_result[
                "selection_score"
            ],
            2
        )
    )


    # Hiển thị Strategy có đạt điều kiện Privacy
    # để được tham gia xếp hạng hay không
    print(
        "Đủ điều kiện?:",
        strategy_result[
            "eligible"
        ]
    )


    # In dòng phân cách để dễ đọc kết quả
    print(
        "----------------------------------------"
    )

In [ ]:
# ============================================================
# KIỂM TRA HÀM select_best_strategy()
# TRƯỚC KHI GỌI HÀM CHỌN STRATEGY TỐT NHẤT
# ============================================================


# Import inspect để xem chính xác
# hàm select_best_strategy() nhận những tham số nào
import inspect


# Hiển thị chữ ký của hàm
# để tránh truyền sai tên tham số
print(
    "Chữ ký của select_best_strategy:"
)


# In danh sách tham số thật của hàm
print(
    inspect.signature(
        strategy_selector.select_best_strategy
    )
)


# Hiển thị toàn bộ code của hàm
# để kiểm tra nó chọn Strategy tốt nhất theo cách nào
print(
    "\n===== CODE HÀM select_best_strategy ====="
)


# In mã nguồn thật mà notebook đang sử dụng
print(
    inspect.getsource(
        strategy_selector.select_best_strategy
    )
)

In [ ]:
# ============================================================
# CHỌN STRATEGY TỐT NHẤT
# ============================================================


# Gọi hàm select_best_strategy()
# để lấy Strategy đứng hạng 1
best_strategy = (
    strategy_selector.select_best_strategy(

        # Danh sách các Strategy đã chuẩn bị trước đó
        strategies=strategies_for_selection,

        # Trọng số 50% dành cho khả năng giữ lại dữ liệu
        weight_data_retention=0.50,

        # Trọng số 50% dành cho Utility Score
        weight_utility=0.50
    )
)


# Kiểm tra xem có Strategy nào đạt điều kiện Privacy hay không
if best_strategy is None:

    # Nếu không có Strategy hợp lệ thì thông báo
    print(
        "Không có Strategy nào đạt điều kiện Privacy."
    )

else:

    # Hiển thị Strategy được hệ thống chọn
    print(
        "Strategy tốt nhất:",
        best_strategy[
            "strategy"
        ]
    )


    # Hiển thị thứ hạng
    print(
        "Hạng:",
        best_strategy[
            "rank"
        ]
    )


    # Hiển thị tỷ lệ dữ liệu được giữ lại
    print(
        "Data Retention (%):",
        round(
            best_strategy[
                "data_retention_%"
            ],
            2
        )
    )


    # Hiển thị Utility Score
    print(
        "Utility Score (%):",
        round(
            best_strategy[
                "utility_score_%"
            ],
            2
        )
    )


    # Hiển thị Selection Score
    print(
        "Selection Score:",
        round(
            best_strategy[
                "selection_score"
            ],
            2
        )
    )


    # Hiển thị trạng thái Privacy
    print(
        "Privacy hợp lệ?:",
        best_strategy[
            "privacy_valid"
        ]
    )

Strategy 1 được chọn vì vừa đạt yêu cầu Privacy, vừa giữ lại 93.99% dữ liệu, vừa duy trì 97.41% Utility cho Machine Learning, nên được xếp hạng 1 với Selection Score 95.7.

In [ ]:
# ============================================================
# LẤY DATASET CỦA STRATEGY TỐT NHẤT
# ============================================================


# Lấy tên Strategy mà hệ thống vừa chọn
# Kết quả hiện tại kỳ vọng là "strategy_1"
selected_strategy_name = (
    best_strategy[
        "strategy"
    ]
)


# Lấy dataset ẩn danh tương ứng
# từ dictionary strategy_results
selected_release_data = (
    strategy_results[
        selected_strategy_name
    ][
        "release_data"
    ]
)


# Lấy danh sách index gốc
# của các bản ghi còn được giữ lại
selected_retained_indices = (
    strategy_results[
        selected_strategy_name
    ][
        "retained_indices"
    ]
)


# Hiển thị tên Strategy được chọn
print(
    "Strategy được chọn:",
    selected_strategy_name
)


# Hiển thị kích thước dataset ẩn danh cuối cùng
# Strategy 1 kỳ vọng có 30.604 dòng và 8 cột
print(
    "Kích thước dataset được chọn:",
    selected_release_data.shape
)


# Hiển thị số lượng index gốc còn giữ lại
# Kỳ vọng bằng đúng 30.604
print(
    "Số retained indices:",
    len(
        selected_retained_indices
    )
)


# Kiểm tra số dòng dataset
# có bằng số lượng retained indices hay không
selected_data_match = (
    len(
        selected_release_data
    )
    ==
    len(
        selected_retained_indices
    )
)


# Hiển thị kết quả kiểm tra
# True nghĩa là dữ liệu đầu ra và index đang khớp nhau
print(
    "Dataset và retained indices khớp nhau?:",
    selected_data_match
)

In [ ]:
# ============================================================
# LẤY KẾT QUẢ ML VALIDATION
# CỦA STRATEGY ĐƯỢC HỆ THỐNG CHỌN
# ============================================================


# Lấy trực tiếp kết quả ML Validation
# đã được lưu tự động trong strategy_results
selected_ml_result = (
    strategy_results[
        selected_strategy_name
    ][
        "ml_validation"
    ]
)


# ============================================================
# KIỂM TRA
# ============================================================


# Hiển thị tên Strategy được hệ thống lựa chọn
print(
    "Strategy được chọn:",
    selected_strategy_name
)


# Hiển thị Utility Score trên tập Validation
print(
    "Validation Utility Score (%):",
    round(
        selected_ml_result[
            "utility_score_percent"
        ],
        2
    )
)


# Kiểm tra số lượng bản ghi Test
# đã được giữ riêng trong quá trình chia dữ liệu
print(
    "Số bản ghi Test:",
    len(
        selected_ml_result[
            "test_indices"
        ]
    )
)

In [ ]:
# ============================================================
# KIỂM TRA HÀM FINAL TEST TỰ ĐỘNG
# ============================================================


# Import importlib để nạp lại
# phiên bản mới nhất của ml_evaluator.py
import importlib


# Nạp lại module sau khi vừa thêm hàm mới
ml_evaluator = importlib.reload(
    ml_evaluator
)


# GỌI HÀM ĐÁNH GIÁ TEST TỰ ĐỘNG

# Đánh giá Test cuối cùng của Strategy
# mà hệ thống đã tự động lựa chọn
final_test_auto_result = (
    ml_evaluator.evaluate_selected_strategy_test(

        # Dataset gốc ban đầu
        original_dataframe=data_check,

        # Dataset ẩn danh của Strategy được chọn
        anonymized_dataframe=selected_release_data,

        # Các index còn giữ lại sau Suppression
        retained_indices=selected_retained_indices,

        # Kết quả Validation đã lưu của Strategy được chọn
        validation_result=selected_ml_result,

        # Cột target
        target_column="thu_nhap"
    )
)


# KIỂM TRA KẾT QUẢ


# Hiển thị số bản ghi Test
print(
    "Test size:",
    final_test_auto_result[
        "test_size"
    ]
)


# Kiểm tra hai tập Test có cùng index
print(
    "Index Test giống nhau?:",
    final_test_auto_result[
        "same_test_indices"
    ]
)


# Kiểm tra hai tập Test có cùng target
print(
    "Target Test giống nhau?:",
    final_test_auto_result[
        "same_test_target"
    ]
)


# Hiển thị Accuracy của Original Test
print(
    "Original Accuracy (%):",
    round(
        final_test_auto_result[
            "original_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Accuracy của Anonymized Test
print(
    "Anonymized Accuracy (%):",
    round(
        final_test_auto_result[
            "anonymized_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Utility Score cuối cùng
print(
    "Final Test Utility Score (%):",
    final_test_auto_result[
        "utility_score_percent"
    ]
)

In [ ]:
# DỰ ĐOÁN TRÊN TẬP TEST CUỐI CÙNG
# CỦA STRATEGY ĐÃ ĐƯỢC HỆ THỐNG CHỌN


# Lấy mô hình Original đã được huấn luyện
# từ kết quả ML của Strategy được chọn
selected_original_model = (
    selected_ml_result[
        "original_model_pipeline"
    ]
)


# Lấy mô hình Anonymized đã được huấn luyện
# từ kết quả ML của Strategy được chọn
selected_anonymized_model = (
    selected_ml_result[
        "anonymized_model_pipeline"
    ]
)


# 1. DỰ ĐOÁN ORIGINAL TEST


# Dùng mô hình Original dự đoán nhãn
# trên 6.121 bản ghi Test
y_pred_original_test_final = (
    selected_original_model.predict(
        X_original_test_final
    )
)


# Lấy danh sách các lớp
# mà mô hình Original đã học
original_test_classes = (
    selected_original_model
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
# để lấy đúng xác suất cho ROC-AUC
original_test_positive_index = (
    list(
        original_test_classes
    )
    .index(
        ">50K"
    )
)


# Lấy xác suất dự đoán lớp >50K
# của từng bản ghi Original Test
y_prob_original_test_final = (
    selected_original_model.predict_proba(
        X_original_test_final
    )[
        :,
        original_test_positive_index
    ]
)


# 2. DỰ ĐOÁN ANONYMIZED TEST


# Dùng mô hình Anonymized dự đoán nhãn
# trên chính 6.121 bản ghi Test tương ứng
y_pred_anonymized_test_final = (
    selected_anonymized_model.predict(
        X_anonymized_test_final
    )
)


# Lấy danh sách các lớp
# mà mô hình Anonymized đã học
anonymized_test_classes = (
    selected_anonymized_model
    .named_steps["model"]
    .classes_
)


# Tìm vị trí của lớp dương >50K
# trong mô hình Anonymized
anonymized_test_positive_index = (
    list(
        anonymized_test_classes
    )
    .index(
        ">50K"
    )
)


# Lấy xác suất dự đoán lớp >50K
# của từng bản ghi Anonymized Test
y_prob_anonymized_test_final = (
    selected_anonymized_model.predict_proba(
        X_anonymized_test_final
    )[
        :,
        anonymized_test_positive_index
    ]
)


# 3. KIỂM TRA SỐ LƯỢNG KẾT QUẢ DỰ ĐOÁN


# Kiểm tra số nhãn dự đoán Original
print(
    "Số dự đoán Original Test:",
    len(
        y_pred_original_test_final
    )
)


# Kiểm tra số xác suất Original
print(
    "Số xác suất Original Test:",
    len(
        y_prob_original_test_final
    )
)


# Kiểm tra số nhãn dự đoán Anonymized
print(
    "Số dự đoán Anonymized Test:",
    len(
        y_pred_anonymized_test_final
    )
)


# Kiểm tra số xác suất Anonymized
print(
    "Số xác suất Anonymized Test:",
    len(
        y_prob_anonymized_test_final
    )
)

In [ ]:
# LƯU DATASET ẨN DANH CUỐI CÙNG


# Import Path để tạo đường dẫn file
# rõ ràng và dễ sử dụng trên Windows
from pathlib import Path


# Xác định thư mục dùng để lưu dữ liệu
# Notebook hiện đang nằm trong thư mục notebooks
output_data_folder = Path(
    "../data/processed_da_xu_li"
)


# Đảm bảo thư mục lưu dữ liệu tồn tại
# exist_ok=True nghĩa là nếu thư mục đã có thì không báo lỗi
output_data_folder.mkdir(
    parents=True,
    exist_ok=True
)


# Tạo đường dẫn đầy đủ cho file đầu ra cuối cùng
final_anonymized_file = (
    output_data_folder
    / "du_lieu_an_danh_cuoi_cung.csv"
)


# Lưu dataset của Strategy được hệ thống chọn
# index=False để không lưu index gốc vào file phát hành
selected_release_data.to_csv(
    final_anonymized_file,
    index=False,
    encoding="utf-8-sig"
)


# KIỂM TRA FILE SAU KHI LƯU


# Kiểm tra file có thực sự được tạo hay chưa
print(
    "File tồn tại?:",
    final_anonymized_file.exists()
)


# Hiển thị đường dẫn file
print(
    "Đường dẫn:",
    final_anonymized_file.resolve()
)


# Hiển thị Strategy tạo ra file này
print(
    "Strategy:",
    selected_strategy_name
)


# Hiển thị kích thước dữ liệu đã lưu
print(
    "Kích thước:",
    selected_release_data.shape
)

Strategy 1 được chọn vì vừa đạt yêu cầu Privacy, vừa giữ lại 93.99% dữ liệu, vừa duy trì 97.41% Utility cho Machine Learning, nên được xếp hạng 1 với Selection Score 95.7.

In [ ]:
# ============================================================
# KIỂM TRA LẠI FILE DỮ LIỆU ẨN DANH CUỐI CÙNG SAU KHI LƯU
# ============================================================


# Đọc lại chính file CSV vừa được hệ thống tạo ra
# Việc đọc lại giúp kiểm tra file thực tế trên ổ đĩa có sử dụng được hay không
final_release_check = pd.read_csv(
    final_anonymized_file
)


# Hiển thị kích thước dữ liệu sau khi đọc lại
# Kỳ vọng vẫn là 30.604 dòng và 8 cột
print(
    "Kích thước sau khi đọc lại:",
    final_release_check.shape
)


# Hiển thị danh sách các cột thực tế trong file
# để kiểm tra không có cột index gốc bị lưu nhầm
print(
    "Các cột trong file:"
)

print(
    final_release_check.columns.tolist()
)


# Kiểm tra xem pandas có tạo ra cột kiểu "Unnamed: 0"
# thường xuất hiện khi index bị lưu nhầm vào CSV hay không
has_unwanted_index_column = any(
    str(column).startswith("Unnamed:")
    for column in final_release_check.columns
)


# False là kết quả mong muốn
print(
    "Có cột index thừa?:",
    has_unwanted_index_column
)


# Kiểm tra dữ liệu vừa đọc lại
# có đúng số dòng và số cột với dữ liệu trước khi lưu hay không
same_shape_after_save = (
    final_release_check.shape
    ==
    selected_release_data.shape
)


# True nghĩa là quá trình lưu và đọc lại không làm thay đổi kích thước dữ liệu
print(
    "Kích thước khớp dữ liệu trước khi lưu?:",
    same_shape_after_save
)

kiểm tra toàn bộ nội dung file

In [ ]:
# KIỂM TRA NỘI DUNG FILE SAU KHI LƯU


# Tạo biến mặc định là True
# Nếu phát hiện dữ liệu khác nhau thì sẽ đổi thành False
final_file_content_match = True


try:

    # So sánh toàn bộ dữ liệu trước khi lưu
    # với dữ liệu vừa đọc lại từ file CSV
    #
    # reset_index(drop=True):
    # bỏ index nội bộ của DataFrame để chỉ so sánh dữ liệu thực
    #
    # check_dtype=False:
    # không bắt buộc kiểu dữ liệu pandas phải giống tuyệt đối,
    # vì khi đọc lại CSV một số dtype có thể được pandas tự suy luận lại
    pd.testing.assert_frame_equal(

        selected_release_data
        .reset_index(drop=True),

        final_release_check
        .reset_index(drop=True),

        check_dtype=False
    )


except AssertionError as error:

    # Nếu có bất kỳ dữ liệu nào khác nhau
    # thì đánh dấu kết quả kiểm tra là False
    final_file_content_match = False

    # Hiển thị lỗi để biết vị trí dữ liệu không khớp
    print(
        "Chi tiết dữ liệu không khớp:"
    )

    print(
        error
    )



# HIỂN THỊ KẾT QUẢ


# True nghĩa là 30.604 dòng × 8 cột trong file CSV
# giống dữ liệu trước khi lưu
print(
    "Toàn bộ nội dung file khớp dữ liệu trước khi lưu?:",
    final_file_content_match
)

In [ ]:
# TẠO BẢN TÓM TẮT KẾT QUẢ CUỐI CÙNG CỦA HỆ THỐNG


# Lấy kết quả của Strategy đã được hệ thống lựa chọn
selected_strategy_result = (
    strategy_results[
        selected_strategy_name
    ]
)


# Tạo dictionary tổng hợp các thông tin quan trọng
# của toàn bộ quá trình ẩn danh hóa và đánh giá
final_system_summary = {

    # Strategy được hệ thống tự động lựa chọn
    "selected_strategy": selected_strategy_name,

    # Số bản ghi của dữ liệu gốc ban đầu
    "original_records": len(
        data_check
    ),

    # Số bản ghi còn lại trong dữ liệu phát hành
    "released_records": len(
        selected_release_data
    ),

    # Số bản ghi đã bị suppression
    "suppressed_records": (
        len(data_check)
        -
        len(selected_release_data)
    ),

    # Tỷ lệ suppression của Strategy được chọn
    "suppression_percent": (
        selected_strategy_result[
            "suppression_percent"
        ]
    ),

    # Tỷ lệ dữ liệu được giữ lại
    "data_retention_percent": (
        best_strategy[
            "data_retention_%"
        ]
    ),

    # Strategy có đạt điều kiện Privacy
    # theo tiêu chí k và l của đồ án hay không
    "privacy_valid": (
        best_strategy[
            "privacy_valid"
        ]
    ),

    # Utility Score trên Validation
    # được dùng trong quá trình lựa chọn Strategy
    "validation_utility_score_percent": (
        selected_strategy_result[
            "utility_score_percent"
        ]
    ),

    # Selection Score dùng để xếp hạng Strategy
    "selection_score": (
        best_strategy[
            "selection_score"
        ]
    ),

    # Số bản ghi của tập Test cuối cùng
    "test_size": (
        selected_strategy_result[
            "final_test"
        ][
            "test_size"
        ]
    ),

    # Utility Score cuối cùng trên tập Test
    "final_test_utility_score_percent": (
        selected_strategy_result[
            "final_test"
        ][
            "utility_score_percent"
        ]
    )
}



# HIỂN THỊ BẢN TÓM TẮT

# Duyệt từng thông tin để kiểm tra kết quả
for key, value in final_system_summary.items():

    # Hiển thị tên thông tin và giá trị tương ứng
    print(
        key,
        ":",
        value
    )

In [ ]:
# KIỂM TRA CẤU TRÚC KẾT QUẢ PRIVACY
# CỦA STRATEGY ĐƯỢC CHỌN


# Lấy kết quả Privacy đã được tính tự động
# của Strategy mà hệ thống lựa chọn
selected_privacy_result = (
    strategy_results[
        selected_strategy_name
    ][
        "privacy"
    ]
)


# Hiển thị toàn bộ dictionary Privacy
# để biết chính xác tên các key đang được lưu
print(
    "===== PRIVACY RESULT ====="
)


# Duyệt từng key và giá trị
# để xem rõ cấu trúc kết quả
for key, value in selected_privacy_result.items():

    # Hiển thị từng thông tin Privacy
    print(
        key,
        ":",
        value
    )

In [ ]:
# BỔ SUNG KẾT QUẢ PRIVACY VÀO BẢN TÓM TẮT CUỐI CÙNG



# Cập nhật thêm các chỉ số Privacy
# vào dictionary final_system_summary đã tạo ở bước trước
final_system_summary.update({

    # Giá trị k nhỏ nhất thực tế
    # sau khi hệ thống ẩn danh hóa dữ liệu
    "k_min": (
        selected_privacy_result[
            "k_min"
        ]
    ),

    # Ngưỡng k mà đồ án yêu cầu
    "k_required": (
        selected_privacy_result[
            "k_required"
        ]
    ),

    # True nghĩa là dữ liệu đạt điều kiện k-anonymity
    # theo ngưỡng k = 5 của đồ án
    "k_valid": (
        selected_privacy_result[
            "k_valid"
        ]
    ),

    # Số bản ghi còn vi phạm k-anonymity
    # Kỳ vọng bằng 0
    "records_violating_k": (
        selected_privacy_result[
            "so_ban_ghi_vi_pham_k"
        ]
    ),

    # Giá trị l nhỏ nhất thực tế
    # sau khi áp dụng l-diversity
    "l_min": (
        selected_privacy_result[
            "l_min"
        ]
    ),

    # Ngưỡng l mà đồ án yêu cầu
    "l_required": (
        selected_privacy_result[
            "l_required"
        ]
    ),

    # True nghĩa là dữ liệu đạt điều kiện l-diversity
    # theo ngưỡng l = 2 của đồ án
    "l_valid": (
        selected_privacy_result[
            "l_valid"
        ]
    ),

    # Số nhóm còn vi phạm l-diversity
    # Kỳ vọng bằng 0
    "groups_violating_l": (
        selected_privacy_result[
            "so_nhom_vi_pham_l"
        ]
    ),

    # Số bản ghi còn nằm trong các nhóm vi phạm l-diversity
    # Kỳ vọng bằng 0
    "records_violating_l": (
        selected_privacy_result[
            "so_ban_ghi_vi_pham_l"
        ]
    )
})


# HIỂN THỊ PHẦN PRIVACY TRONG BẢN TÓM TẮT

print(
    "k_min:",
    final_system_summary[
        "k_min"
    ]
)

print(
    "k_required:",
    final_system_summary[
        "k_required"
    ]
)

print(
    "k_valid:",
    final_system_summary[
        "k_valid"
    ]
)

print(
    "records_violating_k:",
    final_system_summary[
        "records_violating_k"
    ]
)

print(
    "l_min:",
    final_system_summary[
        "l_min"
    ]
)

print(
    "l_required:",
    final_system_summary[
        "l_required"
    ]
)

print(
    "l_valid:",
    final_system_summary[
        "l_valid"
    ]
)

print(
    "groups_violating_l:",
    final_system_summary[
        "groups_violating_l"
    ]
)

print(
    "records_violating_l:",
    final_system_summary[
        "records_violating_l"
    ]
)

In [ ]:
# BỔ SUNG CHI TIẾT MACHINE LEARNING TEST


# Cập nhật các metric của Original và Anonymized
# vào final_system_summary để sau này lưu báo cáo
final_system_summary.update({

    # --------------------------------------------------------
    # METRIC CỦA DỮ LIỆU GỐC - ORIGINAL TEST
    # --------------------------------------------------------

    # Accuracy của mô hình trên dữ liệu gốc
    "original_test_accuracy_percent": (
        original_test_metrics["accuracy"] * 100
    ),

    # Precision của mô hình trên dữ liệu gốc
    "original_test_precision_percent": (
        original_test_metrics["precision"] * 100
    ),

    # Recall của mô hình trên dữ liệu gốc
    "original_test_recall_percent": (
        original_test_metrics["recall"] * 100
    ),

    # F1 Score của mô hình trên dữ liệu gốc
    "original_test_f1_percent": (
        original_test_metrics["f1_score"] * 100
    ),

    # Balanced Accuracy của mô hình trên dữ liệu gốc
    "original_test_balanced_accuracy_percent": (
        original_test_metrics["balanced_accuracy"] * 100
    ),

    # ROC-AUC của mô hình trên dữ liệu gốc
    "original_test_roc_auc_percent": (
        original_test_metrics["roc_auc"] * 100
    ),


    # METRIC CỦA DỮ LIỆU ĐÃ ẨN DANH - ANONYMIZED TEST

    # Accuracy sau ẩn danh hóa
    "anonymized_test_accuracy_percent": (
        anonymized_test_metrics["accuracy"] * 100
    ),

    # Precision sau ẩn danh hóa
    "anonymized_test_precision_percent": (
        anonymized_test_metrics["precision"] * 100
    ),

    # Recall sau ẩn danh hóa
    "anonymized_test_recall_percent": (
        anonymized_test_metrics["recall"] * 100
    ),

    # F1 Score sau ẩn danh hóa
    "anonymized_test_f1_percent": (
        anonymized_test_metrics["f1_score"] * 100
    ),

    # Balanced Accuracy sau ẩn danh hóa
    "anonymized_test_balanced_accuracy_percent": (
        anonymized_test_metrics["balanced_accuracy"] * 100
    ),

    # ROC-AUC sau ẩn danh hóa
    "anonymized_test_roc_auc_percent": (
        anonymized_test_metrics["roc_auc"] * 100
    ),


    # UTILITY RETENTION TRÊN TEST


    # Mức giữ lại Accuracy
    "test_accuracy_retention_percent": (
        final_test_utility["accuracy_retention_%"]
    ),

    # Mức giữ lại F1 Score
    "test_f1_retention_percent": (
        final_test_utility["f1_retention_%"]
    ),

    # Mức giữ lại Balanced Accuracy
    "test_balanced_accuracy_retention_percent": (
        final_test_utility[
            "balanced_accuracy_retention_%"
        ]
    ),

    # Mức giữ lại ROC-AUC
    "test_roc_auc_retention_percent": (
        final_test_utility["roc_auc_retention_%"]
    )
})


# KIỂM TRA CÁC GIÁ TRỊ VỪA BỔ SUNG

print(
    "Original Accuracy (%):",
    round(
        final_system_summary[
            "original_test_accuracy_percent"
        ],
        2
    )
)

print(
    "Original F1 (%):",
    round(
        final_system_summary[
            "original_test_f1_percent"
        ],
        2
    )
)

print(
    "Anonymized Accuracy (%):",
    round(
        final_system_summary[
            "anonymized_test_accuracy_percent"
        ],
        2
    )
)

print(
    "Anonymized F1 (%):",
    round(
        final_system_summary[
            "anonymized_test_f1_percent"
        ],
        2
    )
)

print(
    "Final Test Utility Score (%):",
    final_system_summary[
        "final_test_utility_score_percent"
    ]
)

In [ ]:
# LƯU BẢN TỔNG KẾT KẾT QUẢ CUỐI CÙNG RA FILE CSV


# Import Path để xử lý đường dẫn file
from pathlib import Path


# 1. XÁC ĐỊNH THƯ MỤC LƯU KẾT QUẢ


# Notebook đang nằm trong thư mục notebooks
# nên ".." dùng để quay về thư mục gốc của project
summary_output_folder = Path(
    "../outputs_bieu_do_ket_qua"
)


# Đảm bảo thư mục tồn tại
# Nếu đã tồn tại thì không tạo lại và không báo lỗi
summary_output_folder.mkdir(
    parents=True,
    exist_ok=True
)


# Tạo đường dẫn đầy đủ cho file tổng kết
summary_output_file = (
    summary_output_folder
    / "ket_qua_tong_hop_he_thong.csv"
)


# 2. CHUYỂN DICTIONARY THÀNH DATAFRAME



# final_system_summary hiện là một dictionary
# Ta chuyển thành DataFrame gồm 1 dòng
# để có thể lưu dưới dạng CSV
final_summary_dataframe = pd.DataFrame(
    [
        final_system_summary
    ]
)


# 3. LƯU FILE CSV


# Lưu toàn bộ kết quả tổng hợp ra file
# index=False để không tạo thêm cột index thừa
# utf-8-sig giúp file dễ mở bằng Excel trên Windows
final_summary_dataframe.to_csv(
    summary_output_file,
    index=False,
    encoding="utf-8-sig"
)

# 4. KIỂM TRA FILE SAU KHI LƯU


# Kiểm tra file có được tạo thành công hay không
print(
    "File tồn tại?:",
    summary_output_file.exists()
)


# Hiển thị đường dẫn tuyệt đối của file
print(
    "Đường dẫn:",
    summary_output_file.resolve()
)


# Hiển thị kích thước bảng tổng kết
# 1 dòng nghĩa là 1 kết quả tổng hợp của hệ thống
print(
    "Kích thước bảng tổng kết:",
    final_summary_dataframe.shape
)


# Hiển thị số lượng chỉ số đã được lưu
print(
    "Số chỉ số đã lưu:",
    len(
        final_summary_dataframe.columns
    )
)

In [ ]:
# KIỂM TRA CẤU TRÚC HIỆN TẠI CỦA strategy_results


# Duyệt qua từng Strategy đang có trong hệ thống
for strategy_name in strategy_names:

    # Hiển thị tên Strategy
    print(
        "Strategy:",
        strategy_name
    )


    # Hiển thị toàn bộ tên key
    # đang được lưu trong Strategy hiện tại
    print(
        "Các key:",
        list(
            strategy_results[
                strategy_name
            ].keys()
        )
    )


    # In dòng phân cách để dễ theo dõi
    print(
        "----------------------------------------"
    )

In [ ]:
# TỰ ĐỘNG ĐÁNH GIÁ ML VALIDATION CHO TẤT CẢ STRATEGY


# Duyệt qua toàn bộ Strategy đang có trong hệ thống
# Ví dụ hiện tại gồm strategy_1 và strategy_2
for strategy_name in strategy_names:

    # 1. LẤY DỮ LIỆU CỦA STRATEGY HIỆN TẠI

    # Lấy dataset đã được ẩn danh hóa
    strategy_release_data = (
        strategy_results[
            strategy_name
        ][
            "release_data"
        ]
    )


    # Lấy index các bản ghi còn được giữ lại
    # sau Generalization + Suppression
    strategy_retained_indices = (
        strategy_results[
            strategy_name
        ][
            "retained_indices"
        ]
    )


    # 2. TỰ ĐỘNG CHẠY MACHINE LEARNING VALIDATION

    # Hàm evaluate_strategy_validation() sẽ:
    # - căn chỉnh dữ liệu Original và Anonymized
    # - chia Train / Validation / Test
    # - huấn luyện Logistic Regression
    # - đánh giá trên Validation
    # - tính Utility Retention
    ml_validation_result = (
        ml_evaluator.evaluate_strategy_validation(

            # Dataset gốc ban đầu
            original_dataframe=data_check,

            # Dataset ẩn danh của Strategy hiện tại
            anonymized_dataframe=strategy_release_data,

            # Index còn được giữ lại
            retained_indices=strategy_retained_indices,

            # Cột cần dự đoán
            target_column="thu_nhap",

            # Giữ cố định random state
            # để kết quả có thể tái lập
            random_state=42
        )
    )


    # 3. LƯU TOÀN BỘ KẾT QUẢ ML VÀO STRATEGY

    # Lưu cả model, metric, split index,
    # Utility Result,... vào chính Strategy đó
    strategy_results[
        strategy_name
    ][
        "ml_validation"
    ] = ml_validation_result


    # Lấy riêng Utility Score
    # để Strategy Selector sử dụng trực tiếp
    strategy_results[
        strategy_name
    ][
        "utility_score_percent"
    ] = (
        ml_validation_result[
            "utility_score_percent"
        ]
    )


    # 4. HIỂN THỊ KẾT QUẢ

    print(
        "Strategy:",
        strategy_name
    )

    print(
        "Validation Utility Score (%):",
        round(
            strategy_results[
                strategy_name
            ][
                "utility_score_percent"
            ],
            2
        )
    )

    print(
        "Đã lưu ml_validation?:",
        "ml_validation"
        in strategy_results[
            strategy_name
        ]
    )

    print(
        "----------------------------------------"
    )

In [ ]:
# KIỂM TRA HÀM FINAL TEST TỰ ĐỘNG



# Import importlib để nạp lại
# phiên bản mới nhất của ml_evaluator.py
import importlib


# Nạp lại module sau khi vừa thêm hàm mới
ml_evaluator = importlib.reload(
    ml_evaluator
)


# GỌI HÀM ĐÁNH GIÁ TEST TỰ ĐỘNG

# Đánh giá Test cuối cùng của Strategy
# mà hệ thống đã tự động lựa chọn
final_test_auto_result = (
    ml_evaluator.evaluate_selected_strategy_test(

        # Dataset gốc ban đầu
        original_dataframe=data_check,

        # Dataset ẩn danh của Strategy được chọn
        anonymized_dataframe=selected_release_data,

        # Các index còn giữ lại sau Suppression
        retained_indices=selected_retained_indices,

        # Kết quả Validation đã lưu của Strategy được chọn
        validation_result=selected_ml_result,

        # Cột target
        target_column="thu_nhap"
    )
)


# KIỂM TRA KẾT QUẢ


# Hiển thị số bản ghi Test
print(
    "Test size:",
    final_test_auto_result[
        "test_size"
    ]
)


# Kiểm tra hai tập Test có cùng index
print(
    "Index Test giống nhau?:",
    final_test_auto_result[
        "same_test_indices"
    ]
)


# Kiểm tra hai tập Test có cùng target
print(
    "Target Test giống nhau?:",
    final_test_auto_result[
        "same_test_target"
    ]
)


# Hiển thị Accuracy của Original Test
print(
    "Original Accuracy (%):",
    round(
        final_test_auto_result[
            "original_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Accuracy của Anonymized Test
print(
    "Anonymized Accuracy (%):",
    round(
        final_test_auto_result[
            "anonymized_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Utility Score cuối cùng
print(
    "Final Test Utility Score (%):",
    final_test_auto_result[
        "utility_score_percent"
    ]
)

In [ ]:
# LƯU FINAL TEST TỰ ĐỘNG VÀO STRATEGY ĐƯỢC CHỌN


# Lưu toàn bộ kết quả Final Test tự động
# vào đúng Strategy mà hệ thống đã lựa chọn
strategy_results[
    selected_strategy_name
][
    "final_test"
] = final_test_auto_result


# KIỂM TRA KẾT QUẢ ĐÃ ĐƯỢC LƯU


# Lấy lại kết quả Final Test
# từ chính strategy_results để kiểm tra
selected_final_test_result = (
    strategy_results[
        selected_strategy_name
    ][
        "final_test"
    ]
)


# Hiển thị Strategy được chọn
print(
    "Strategy:",
    selected_strategy_name
)


# Hiển thị số bản ghi Test
print(
    "Test size:",
    selected_final_test_result[
        "test_size"
    ]
)


# Hiển thị Accuracy của dữ liệu gốc
print(
    "Original Accuracy (%):",
    round(
        selected_final_test_result[
            "original_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Accuracy của dữ liệu ẩn danh
print(
    "Anonymized Accuracy (%):",
    round(
        selected_final_test_result[
            "anonymized_metrics"
        ][
            "accuracy"
        ] * 100,
        2
    )
)


# Hiển thị Final Utility Score
print(
    "Final Test Utility Score (%):",
    selected_final_test_result[
        "utility_score_percent"
    ]
)


# Kiểm tra final_test đã tồn tại
# trong Strategy được chọn hay chưa
print(
    "Đã lưu final_test tự động?:",
    "final_test"
    in strategy_results[
        selected_strategy_name
    ]
)

In [ ]:
# ĐỒNG BỘ KẾT QUẢ FINAL TEST TỰ ĐỘNG
# CHO CÁC PHẦN TỔNG HỢP KẾT QUẢ PHÍA SAU


# Lấy kết quả Final Test đã được lưu tự động
# của Strategy mà hệ thống lựa chọn
selected_final_test_result = (
    strategy_results[
        selected_strategy_name
    ][
        "final_test"
    ]
)


# Lấy metric của dữ liệu Original
# từ kết quả Final Test tự động
original_test_metrics = (
    selected_final_test_result[
        "original_metrics"
    ]
)


# Lấy metric của dữ liệu Anonymized
# từ kết quả Final Test tự động
anonymized_test_metrics = (
    selected_final_test_result[
        "anonymized_metrics"
    ]
)


# Lấy kết quả Utility Retention
# từ Final Test tự động
final_test_utility = (
    selected_final_test_result[
        "utility_result"
    ]
)


# KIỂM TRA

print(
    "Original Accuracy (%):",
    round(
        original_test_metrics[
            "accuracy"
        ] * 100,
        2
    )
)


print(
    "Anonymized Accuracy (%):",
    round(
        anonymized_test_metrics[
            "accuracy"
        ] * 100,
        2
    )
)


print(
    "Final Test Utility Score (%):",
    final_test_utility[
        "utility_score_%"
    ]
)


print(
    "Nguồn kết quả:",
    "strategy_results -> final_test tự động"
)

In [ ]:
# KIỂM TRA BẢN TỔNG KẾT
# CÓ KHỚP VỚI FINAL TEST TỰ ĐỘNG HAY KHÔNG

# Lấy Utility Score trực tiếp
# từ Final Test tự động
auto_final_utility = (
    strategy_results[
        selected_strategy_name
    ][
        "final_test"
    ][
        "utility_score_percent"
    ]
)


# Lấy Utility Score đang được lưu
# trong bản tổng kết cuối cùng
summary_final_utility = (
    final_system_summary[
        "final_test_utility_score_percent"
    ]
)


# Kiểm tra hai giá trị có giống nhau không
utility_summary_match = (
    auto_final_utility
    ==
    summary_final_utility
)


# Lấy Accuracy Anonymized trực tiếp
# từ Final Test tự động
auto_anonymized_accuracy = (
    strategy_results[
        selected_strategy_name
    ][
        "final_test"
    ][
        "anonymized_metrics"
    ][
        "accuracy"
    ] * 100
)


# Lấy Accuracy Anonymized
# đang lưu trong bản tổng kết
summary_anonymized_accuracy = (
    final_system_summary[
        "anonymized_test_accuracy_percent"
    ]
)


# Kiểm tra hai Accuracy có khớp nhau không
accuracy_summary_match = (
    abs(
        auto_anonymized_accuracy
        -
        summary_anonymized_accuracy
    )
    < 0.000001
)




print(
    "Final Utility tự động (%):",
    auto_final_utility
)

print(
    "Final Utility trong Summary (%):",
    summary_final_utility
)

print(
    "Utility Summary khớp?:",
    utility_summary_match
)

print(
    "Anonymized Accuracy Summary khớp?:",
    accuracy_summary_match
)